---
permalink: switch-cisco-3232c/concept-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3232c-cluster-switches.html
sidebar: sidebar
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c
summary: "You must be aware of certain configuration information, port connections, and cabling requirements when you migrate a two-node switchless cluster to a cluster with Cisco Nexus 3232C cluster switches."
---
= Migrate from a two-node switchless cluster to a cluster with Cisco Nexus 3232C cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain configuration information, port connections, and cabling requirements when you migrate a two-node switchless cluster to a cluster with Cisco Nexus 3232C cluster switches.

The link:http://mysupport.netapp.com/NOW/download/software/cm_switches/.html[Cisco Ethernet Switches page^] has information about the ONTAP and NX-OS versions supported in this procedure.

You must have the following before you begin the migration process:

* Available ports for node connections
+
The cluster switches use the Inter-Switch Link (ISL) ports e1/31-32.
-
* Appropriate cables for cluster connections:
 ** The nodes with 10 GbE cluster connections require QSFP optical modules with breakout fiber cables or QSFP to SFP+ copper breakout cables.
 ** The nodes with 40/100 GbE cluster connections require supportedQSFP/ QSFP28 optical modules with fiber cables or QSFP/QSFP28 copper direct-attach cables.
 ** The cluster switches require the appropriate ISL cabling: 2x QSFP28 fiber or copper direct-attach cables.

+
[NOTE]
====
See the link:https://hwu.netapp.com/[_Hardware Universe_^] for further information on cabling systems with Nexus 3232C switches.
====
