---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html
sidebar: sidebar
keywords: install, cisco nexus 3232c switch,
summary: 'Before configuring Cisco Nexus 3232c switches, review an overview of the process and the nomenclature.'
---
= Migration requirements
:imagesdir: ../media/

[.lead]
Cisco Nexus 3232C switches can be used as cluster switches in your AFF or FAS cluster. Cluster switches allow you to build ONTAP clusters with more than two nodes. 

NOTE: The procedure requires the use of both ONTAP commands and Cisco Nexus 3000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

If necessary, refer to the following for more information:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab[NetApp CN1601 and CN1610^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches^]
* link:http://hwu.netapp.com[Hardware Universe^]


== CN1610 migrate requirements
The cluster switches support the following node connections:

* NetApp CN1610: ports 0/1 through 0/12 (10 GbE)
* Cisco Nexus 3232C: ports e1/1-30 (40 or 100 or 4x10GbE)

The cluster switches use the following inter-switch link (ISL) ports.

* NetApp CN1610: ports 0/13 through 0/16 (10 GbE)
* Cisco Nexus 3232C: ports 1/31-32 (100GbE)

[NOTE]
====
You must use 4x10G breakout cables on the Cisco Nexus 3232C cluster switch.
====

The following table shows the cabling connections that are required at each stage as you make the transition from NetApp CN1610 switches to Cisco Nexus 3232C cluster switches:
[options="header"]
|===
| Stage| Description| Required cables
a|
Initial
a|
CN1610 to CN1610 (SFP+ to SFP+)
a|
4 SFP+ optical fiber or copper direct-attach cables
a|
Transition
a|
CN1610 to 3232C (QSFP to SFP+)
a|
1 QSFP and 4 SFP+ optical fiber or copper breakout cables
a|
Final
a|
3232C to 3232C (QSFP to QSFP)
a|
2 QSFP optical fiber or copper direct-attach cables
|===
You must have downloaded the applicable reference configuration files (RCFs). The number of 10 GbE and 40/100 GbE ports are defined in the RCFs available at link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab[Cisco® Cluster Network Switch Reference Configuration File Download^].

The ONTAP and NX-OS versions that are supported in this procedure are listed at link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches^].

The ONTAP and FASTPATH versions that are supported in this procedure are listed at link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab[NetApp CN1601 and CN1610 Switches^].

.About the examples used

The examples in the migration procedure use four nodes: 

* Two nodes use four 10 GbE cluster interconnect ports: *e0a*, *e0b*, *e0c*, and *e0d*. 
* The other two nodes use two 40 GbE cluster interconnect fiber cables: *e4a* and *e4e*. 
+
The link:https://hwu.netapp.com/[_Hardware Universe_^] has information about the cluster fiber cables for your platforms.

The examples in this procedure use the following switch and node nomenclature:

* The nodes are *n1*, *n2*, *n3*, and *n4*.
* The command outputs might vary depending on different releases of ONTAP software.
* The CN1610 switches to be replaced are *CL1* and *CL2*.
* The Nexus 3232C switches to replace the CN1610 switches are *C1* and *C2*.
* *n1_clus1* is the first cluster logical interface (LIF) that is connected to cluster switch 1 (CL1 or C1) for node *n1*.
* *n1_clus2* is the first cluster LIF that is connected to cluster switch 2 (CL2 or C2) for node *n1*.
* *n1_clus3* is the second LIF that is connected to cluster switch 2 (CL2 or C2) for node *n1*.
* *n1_clus4* is the second LIF that is connected to cluster switch 1 (CL1 or C1) for node *n1*.
* The number of 10 GbE and 40/100 GbE ports are defined in the reference configuration files (RCFs) available at link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab[Cisco® Cluster Network Switch Reference Configuration File Download^].

.What's next?
After you've reviewed the migration requirements, you can link:cn1610-prepare-to-migrate.html[prepare to migrate your switches].

//Updates for internal GH issue #262, 2024-11-14