---
permalink: switch-cisco-3232c/concept_replacing_a_cisco_nexus_3232c_cluster_switch.html
sidebar: sidebar
keywords: 
summary: 'You must be aware of certain configuration information, port connections and cabling requirements when you replace Cisco Nexus 3232C cluster switches.'
---
= Replacing a Cisco Nexus 3232C cluster switch
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain configuration information, port connections and cabling requirements when you replace Cisco Nexus 3232C cluster switches.

You must verify the following conditions exist before installing the NX-OS software and RCFs on a Cisco Nexus cluster switch:

* Your system can support Cisco Nexus 3232C switches.
* The cluster must be fully functioning.
* You must have consulted the switch compatibility table on the Cisco Ethernet Switch page for the supported ONTAP, NX-OS, and RCF versions.
+
[NOTE]
====
You should be aware there can be dependencies between command syntax in the RCF and NX-OS versions.
====

* You must have referred to the appropriate software and upgrade guides available on the Cisco web site for complete documentation on the Cisco switch upgrade and downgrade procedures.
* You must have downloaded the applicable RCFs.
