---
permalink: switch-cisco-3232c/concept_migrate_from_a_two_node_switchless_cluster_to_a_cluster_with_cisco_nexus_3232c_cluster_switches.html
sidebar: sidebar
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c
summary: "You must be aware of certain configuration information, port connections, and cabling requirements when you migrate a two-node switchless cluster to a cluster with Cisco Nexus 3232C cluster switches."
---
= Migrate from a two-node switchless cluster to a cluster with Cisco Nexus 3232C cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain configuration information, port connections, and cabling requirements when you migrate a two-node switchless cluster to a cluster with Cisco Nexus 3232C cluster switches.

The _Cisco Ethernet Switches_ page has information about the ONTAP and NX-OS versions supported in this procedure.

http://mysupport.netapp.com/NOW/download/software/cm_switches/[Cisco Ethernet Switches^]

You must have the following before you begin the migration process:

* Available ports for node connections
+
The cluster switches use the Inter-Switch Link (ISL) ports e1/31-32.

* Appropriate cables for cluster connections:
 ** The nodes with 10 GbE cluster connections require QSFP optical modules with breakout fiber cables or QSFP to SFP+ copper breakout cables.
 ** The nodes with 40/100 GbE cluster connections require supportedQSFP/ QSFP28 optical modules with fiber cables or QSFP/QSFP28 copper direct-attach cables.
 ** The cluster switches require the appropriate ISL cabling: 2x QSFP28 fiber or copper direct-attach cables.

+
[NOTE]
====
See the _Hardware Universe_ for further information on cabling systems with Nexus 3232C switches.
====
