---
permalink: switch-cisco-3232c/concept-replace-a-cisco-nexus-3232c-storage-switch.html
sidebar: sidebar
keywords: replace, cisco nexus 3232c, storage switches
summary: "You must be aware of certain configuration information, port connections and cabling requirements when you replace Cisco Nexus 3232C storage switches."
---
= Replace a Cisco Nexus 3232C storage switch
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain configuration information, port connections and cabling requirements when you replace Cisco Nexus 3232C storage switches.

You must verify the following conditions exist before installing the NX-OS software and RCFs on a Cisco Nexus storage switch:

* Your system can support Cisco Nexus 3232C storage switches.
* You must have consulted the switch compatibility table on the Cisco Ethernet Switch page for the supported ONTAP, NX-OS, and RCF versions.
+
[NOTE]
====
You should be aware there can be dependencies between command syntax in the RCF and NX-OS versions.
====

* You must have referred to the appropriate software and upgrade guides available on the Cisco web site for complete documentation on the Cisco switch upgrade and downgrade procedures at link:http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html[Cisco Nexus 3000 Series Switches^].
* You must have downloaded the applicable RCFs.
