---
permalink: switch-cisco-3232c/configure-reqs-3232c.html
sidebar: sidebar
keywords: cisco 3232c, cluster switches
summary: "You can use Cisco Nexus 3232C switches as cluster switches in your AFF or FAS cluster."
---
= Configuration requirements for Cisco Nexus 3232C switches
:icons: font
:imagesdir: ../media/

[.lead]
For Cisco Nexus 3232C switch installation and maintenance, be sure to review configuration and network requirements. 

== Configuration requirements

To configure your cluster, you need the appropriate number and type of cables and cable connectors for your switches. Depending on the type of switch you are initially configuring, you need to connect to the switch console port with the included console cable; you also need to provide specific network information.

== Network requirements

You need the following network information for all switch configurations:

* IP subnet for management network traffic
* Host names and IP addresses for each of the storage system controllers and all applicable switches
* Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon). On AFF A800 and AFF A700 systems, the e0M interface uses a dedicated Ethernet port.

Refer to the https://hwu.netapp.com[Hardware Universe^] for latest information.

.What's next

After you've confirmed your configuration requirements, you review the link:required-documentation-3232c.html[required documentation].

// Updates for AFFFASDOC-370, 2025-JUL-29
// AFFFASDOC-411, 2025-OCT-29