---
permalink: switch-cisco-3232c/index.html
sidebar: sidebar
keywords: cisco 3232c, cluster switches
summary: "You can use Cisco Nexus 3232C switches as cluster switches in your AFF or FAS cluster."
---
= Cisco Nexus 3232C switches
:icons: font
:imagesdir: ../media/

[.lead]
You can use Cisco Nexus 3232C switches as cluster switches in your AFF or FAS cluster.

.Overview
* You can install the switch, migrate from an existing switch, replace a switch, and update the RCF files on the switch.
* You can install NX-OS and reference configuration files (RCF's) on the Cisco Nexus 3232C cluster switch.
* You can migrate from a two-node switchless cluster to a cluster with Cisco Nexus 3232C cluster switches.
* You can replace a Cisco Nexus 3232C cluster or storage switch.
* You can install the Cisco Nexus 3232C switch (X190100) NetApp system cabinet with the
custom brackets that come with the switch, or you can install it in a rack with the standard
brackets that are also included with the switch.

.Available documentation
The following table lists the documentation available for the Cisco Nexus 3232C switches.
["options="header"]
|===
| Title| Description
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/task-install-a-cisco-nexus-3232c-cluster-switch-and-pass-through-panel-in-a-netapp-cabinet.html[_Install a Cisco® Nexus 3232C cluster switch and pass-through panel in a NetApp® cabinet_^]
a|
Describes how to install the pass-through panel in system cabinets where power connectors are at the front of the chassis and power distribution units are located in the rear of the chassis.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/setup-switches.html[_Setup the Cisco® Nexus 3232C cluster switches_^]
a| Describes how to setup and configure your Cisco Nexus 3232C cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/task-install-nx-os-software-and-rcfs-on-cisco-nexus-3232-cluster-switches-running-ontap-9-4-and-later.html[_Install NX-OS and Reference Configuration Files (RCFs)_^]
a|
Describes how to install NX-OS and reference configuration files (RCFs) on Nexus 3232C cluster switch.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-migrate-from-a-cisco-5596-switch-to-a-cisco-nexus-3232c.html[_Migrate from a Cisco Nexus 5596 Switch to a Cisco Nexus 3232C Switch_^]
a|
Describes how to migrate from environments that use older Cisco switches to environments that use Cisco 3232C switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html[_Migrate from a CN1610 Switch to a Cisco Nexus 3232C Switch_^]
a|
Describes the procedure to replace a CN1610 switch with a Cisco Nexus 3232C cluster switch.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3232c-cluster-switches.html[_Migrate from a two-node Switchless Cluster_^]
a|
Describes how to migrate from a two-node switchless cluster environment to a two-node switched environment using Cisco Nexus 3232C cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-replace-a-cisco-nexus-3232c-cluster-switch.html[_Replace a Cisco Nexus 3232C Cluster Switch_^]
a|
Describes the procedure to replace a defective Cisco Nexus 3232C switch in a cluster and download the switch operating system and reference configuration file.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-replace-a-cisco-nexus-3232c-storage-switch.html[_Replace a Cisco Nexus 3232C Storage Switch_^]
a|
Describes the procedure to replace a defective Cisco Nexus 3232C storage switch and download the switch operating system and reference configuration file.
|===
