---
permalink: switch-cisco-3132q-v/install-overview-cisco-3232c.html
sidebar: sidebar
keywords: install, cisco nexus 3232c switch,
summary: 'Before configuring Cisco Nexus 3232c switches, review an overview of the process and the nomenclature.'
---
= Overview of configuration process for Cisco Nexus 3232c switches
:icons: font
:imagesdir: ../media/

[.lead]
Before configuring Cisco Nexus 3232c switches, review the requirements and the procedure overview.

== Requirements
Be sure to review the link:index.html[Overview and requirements].

== Procedure overview

To initially configure a Cisco Nexus 3232c switch on systems running ONTAP, follow these steps:

. link:/switch-cisco-3232c/setup_worksheet_3232c[Complete cabling worksheet].
. link:/switch-cisco-3232c/install-cisco-nexus-3232c.html"[Install the switch in a NetApp cabinet]
. link:/switch-cisco-3232c/setup-switch.html[Configure the 3232C cluster switch]
. link:/switch-cisco-3232c/prepare-install-cisco-nexus-3232c.html"[Prepare to install NX-OS software and Reference Configuration file].
. link:/switch-cisco-3232c/install-nx-os-software-3232c.html[Install the NX-OS software].
. link:/switch-cisco-3232c/install-rcf-3232c.html[Install the Reference Configuration File (RCF)].


