---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html
sidebar: sidebar
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster
summary: "You must be aware of certain configuration information, port connections, and cabling requirements when you replace CN1610 cluster switches with Cisco Nexus 3232C cluster switches."
---
= Migration requirements for Cisco Nexus 3232C cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
Before you migrate to Cisco Nexus 3232C cluster switches. review the configuration information, port connections, and cabling requirements.

== CN1610 migrate requirements
The cluster switches support the following node connections:

* NetApp CN1610: ports 0/1 through 0/12 (10 GbE)
* Cisco Nexus 3232C: ports e1/1-30 (40 or 100 or 4x10GbE)

The cluster switches use the following inter-switch link (ISL) ports.

* NetApp CN1610: ports 0/13 through 0/16 (10 GbE)
* Cisco Nexus 3232C: ports 1/31-32 (100GbE)

[NOTE]
====
You must use 4x10G breakout cables on the Cisco Nexus 3232C cluster switch.
====

The following table shows the cabling connections that are required at each stage as you make the transition from NetApp CN1610 switches to Cisco Nexus 3232C cluster switches:
[options="header"]
|===
| Stage| Description| Required cables
a|
Initial
a|
CN1610 to CN1610 (SFP+ to SFP+)
a|
4 SFP+ optical fiber or copper direct-attach cables
a|
Transition
a|
CN1610 to 3232C (QSFP to SFP+)
a|
1 QSFP and 4 SFP+ optical fiber or copper breakout cables
a|
Final
a|
3232C to 3232C (QSFP to QSFP)
a|
2 QSFP optical fiber or copper direct-attach cables
|===
You must have downloaded the applicable reference configuration files (RCFs). The number of 10 GbE and 40/100 GbE ports are defined in the RCFs available on the https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml[Cisco® Cluster Network Switch Reference Configuration File Download^] page.

The ONTAP and NX-OS versions that are supported in this procedure are listed on the link:https://mysupport.netapp.com/NOW/download/software/cm_switches/.html[Cisco Ethernet Switches page^].

The ONTAP and FASTPATH versions that are supported in this procedure are listed on the link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/.html[NetApp CN1601 and CN1610 Switches page^].

== CN5596 requirements
The cluster switches use the following ports for connections to nodes:

 ** Ports e1/1-40 (10 GbE): Nexus 5596
 ** Ports e1/1-30 (10/40/100 GbE): Nexus 3232C
* The cluster switches use the following Inter-Switch Link (ISL) ports:
 ** Ports e1/41-48 (10 GbE): Nexus 5596
 ** Ports e1/31-32 (40/100 GbE): Nexus 3232C
* The link:https://hwu.netapp.com/[_Hardware Universe_^] contains information about supported cabling to Nexus 3232C switches:
 ** Nodes with 10 GbE cluster connections require QSFP to SFP+ optical fiber breakout cables or QSFP to SFP+ copper breakout cables.
 ** Nodes with 40/100 GbE cluster connections require supported QSFP/QSFP28 optical modules with fiber cables or QSFP/QSFP28 copper direct-attach cables.
* The cluster switches use the appropriate ISL cabling:
 ** Beginning: Nexus 5596 (SFP+ to SFP+)
  *** 8x SFP+ fiber or copper direct-attach cables
 ** Interim: Nexus 5596 to Nexus 3232C (QSFP to 4xSFP+ break-out)
  *** 1x QSFP to SFP+ fiber break-out or copper break-out cables
 ** Final: Nexus 3232C to Nexus 3232C (QSFP28 to QSFP28)
  *** 2x QSFP28 fiber or copper direct-attach cables
* On Nexus 3232C switches, you can operate QSFP/QSFP28 ports in either 40/100 Gigabit Ethernet or 4 x10 Gigabit Ethernet modes.
+
By default, there are 32 ports in the 40/100 Gigabit Ethernet mode. These 40 Gigabit Ethernet ports are numbered in a 2-tuple naming convention. For example, the second 40 Gigabit Ethernet port is numbered as 1/2. The process of changing the configuration from 40 Gigabit Ethernet to 10 Gigabit Ethernet is called _breakout_ and the process of changing the configuration from 10 Gigabit Ethernet to 40 Gigabit Ethernet is called _breakin_. When you break out a 40/100 Gigabit Ethernet port into 10 Gigabit Ethernet ports, the resulting ports are numbered using a 3-tuple naming convention. For example, the break-out ports of the second 40/100 Gigabit Ethernet port are numbered as 1/2/1, 1/2/2, 1/2/3, and 1/2/4.

* On the left side of Nexus 3232C switches are 2 SFP+ ports, called 1/33 and 1/34.
* You have configured some of the ports on Nexus 3232C switches to run at 10 GbE or 40/100 GbE.
+
[NOTE]
====
You can break out the first six ports into 4x10 GbE mode by using the `interface breakout module 1 port 1-6 map 10g-4x` command. Similarly, you can regroup the first six QSFP+ ports from breakout configuration by using the `no interface breakout module 1 port 1-6 map 10g-4x` command.
====

* You have done the planning, migration, and read the required documentation on 10 GbE and 40/100 GbE connectivity from nodes to Nexus 3232C cluster switches.
* The ONTAP and NX-OS versions supported in this procedure are on the link:http://support.netapp.com/NOW/download/software/cm_switches/.html[Cisco Ethernet Switches page^].

// end tabbed area
