---
permalink: switch-cisco-3232c/replace-storage-switch.html
sidebar: sidebar
keywords: replace, cisco nexus, 3232c storage switch
summary: "You can nondisruptively replace a defective Cisco Nexus 3232C storage switch by performing a specific sequence of tasks."
---
= Replace a Cisco Nexus 3232C storage switch
:icons: font
:imagesdir: ../media/

[.lead]
Follow these steps to replace a defective Cisco Nexus 3232C storage switch. This is a non-disruptive procedure.

== Review requirements

The existing network configuration must have the following characteristics:

* The Cisco Ethernet Switches page has the latest RCF and NX-OS versions on your switches.
* Management connectivity must exist on both switches.
+
[NOTE]
====
Make sure that all troubleshooting steps have been completed to confirm that your switch needs replacing.
====

The replacement Cisco Nexus 3232C switch must have the following characteristics:

* Management network connectivity must be functional.
* Console access to the replacement switch must be in place.
* The appropriate RCF and NX-OS operating system image must be loaded onto the switch.
* Initial customization of the switch must be complete.

== Replace the switch
This procedure replaces the second Nexus 3232C storage switch S2 with the new 3232C switch NS2. The two nodes are node1 and node2.

=== Step 1: Confirm the switch to be replaced is S2 

. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ is the duration of the maintenance window in hours.
+
[NOTE]
====
The AutoSupport message notifies technical support of this maintenance task so that automatic case creation is suppressed during the maintenance window.
====

. Check on the health status of the storage node ports to make sure that there is connection to storage switch S1:
+
`storage port show -port-type ENET`
+
.Show example
[%collapsible]
====
----
storage::*> storage port show -port-type ENET
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====

. Verify that storage switch S1 is available:
+
`network device-discovery show`
+
.Show example
[%collapsible]
====
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
====

. Run the `show lldp neighbors` command on the working switch to confirm that you can see both nodes and all shelves:
+
`show lldp neighbors`
+
.Show example
[%collapsible]
====
----
S1# show lldp neighbors
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====

=== Step 2: Configure cabling

. [[five]]Verify the shelf ports in the storage system:
+
`storage shelf port show -fields remote-device,remote-port`
+
.Show example
[%collapsible]
====
----
storage::*> storage shelf port show -fields remote-device,remote-port

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
====

. Remove all cables attached to storage switch S2.
. Reconnect all cables to the replacement switch NS2.

=== Step 3: Verify all device configurations on switch NS2

. Recheck the health status of the storage node ports:
+
`storage port show -port-type ENET`
+
.Show example
[%collapsible]
====
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====

. Verify that both switches are available:
+
`network device-discovery show`
+
.Show example
[%collapsible]
====
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
====

. Verify the shelf ports in the storage system:
+
`storage shelf port show -fields remote-device,remote-port`
+
.Show example
[%collapsible]
====
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
====

. If you suppressed automatic case creation, re-enable it by invoking an AutoSupport message:
+
`system node autosupport invoke -node * -type all -message MAINT=END`
