---
permalink: switch-bes-53248/replace-install-licenses.html
sidebar: sidebar
keywords: bes, cluster, switch, base, model, license, install license for bes-53428 cluster switches - bes-53428 switches
summary: The BES-53248 cluster switch base model is licensed for 16 10GbE or 25GbE ports and two 100GbE ports. New ports can be added by purchasing more licenses.
---
= Install licenses for BES-53248 cluster switches - BES-53248 switches
:icons: font
:imagesdir: ../media/

[.lead]
The BES-53248 cluster switch base model is licensed for 16 10GbE or 25GbE ports and two 100GbE ports. New ports can be added by purchasing more licenses.

The following licenses are available for use on the BES-53248 cluster switch:

[options="header" cols="1,2"]
|===
| License type| License details| Supported firmware version
a|
SW-BES-53248A1-G1-8P-LIC
a|
Broadcom 8P 10-25,2P40-100 License Key, X190005/R
a|
EFOS 3.4.3.3 and later
a|
SW-BES-53248A1-G1-16P-LIC
a|
Broadcom 16P 10-25,4P40-100 License Key, X190005/R
a|
EFOS 3.4.3.3 and later
a|
SW-BES-53248A1-G1-24P-LIC
a|
Broadcom 24P 10-25,6P40-100 License Key, X190005/R
a|
EFOS 3.4.3.3 and later
a|
SW-BES54248-40-100G-LIC
a|
Broadcom 6Port 40G100G License Key, X190005/R
a|
EFOS 3.4.4.6 and later
a|
SW-BES53248-8P-10G25G-LIC
a|
Broadcom 8Port 10G25G License Key, X190005/R
a|
EFOS 3.4.4.6 and later
a|
SW-BES53248-16P-1025G-LIC
a|
Broadcom 16Port 10G25G License Key, X190005/R
a|
EFOS 3.4.4.6 and later
a|
SW-BES53248-24P-1025G-LIC
a|
Broadcom 24Port 10G25G License Key, X190005/R
a|
EFOS 3.4.4.6 and later
|===

.Steps
. Connect the cluster switch to the management network.
. Use the `ping` command to verify connectivity to the server hosting EFOS, licenses, and the RCF file.
+
This example verifies that the switch is connected to the server at IP address 172.19.2.1:
+
----
(cs2) # **ping 172.19.2.1**
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----

. Check the current license usage on switch cs2:
+
`show license`
+
----
(cs2) # **show license**
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----

. Install the license file. The following example uses HTTP to copy a license file to a key index 1.
+
Repeat this step to load more licenses and to use different key index numbers.
+
----
(cs2) # **copy http://172.19.2.1/tmp/efos/license1.dat nvram:license-key 1**

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... tmp/efos/
Filename....................................... license1.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) **y**

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

License Key transfer operation completed successfully. System reboot is required.
----

. Display all current license information and note the license status before switch cs2 is rebooted:
+
`show license`
+
----
(cs2) # **show license**

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----

. Display all licensed ports:
+
`show port all | exclude Detach`
+
The ports from the additional license files are not displayed until after the switch is rebooted.
+
----
(cs2) # **show port all \| exclude Detach**

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----

. Reboot the switch:
+
`reload`
+
----
(cs2) # **reload**

The system has unsaved changes.
Would you like to save them now? (y/n) **y**

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) **y**
----

. Check that the new license is active and note that the license has been applied:
+
`show license`
+
----
(cs2) # **show license**

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
(cs2) #
----

. Check that all new ports are available:
+
`show port all | exclude Detach`
+
----
(cs2) # **show port all \| exclude Detach**

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long

(cs2) #
----
