---
permalink: switch-bes-53248/replace-required-documentation.html
sidebar: sidebar
keywords: documentation requirements,BES-53248 switches,cluster switches
summary: 'You need specific switch and controller documentation to set up your Cluster-Mode configuration.'
---
= Required documentation for BES-53248 cluster switches - BES-53248 switches
:icons: font
:imagesdir: ../media/

[.lead]
You need specific switch and controller documentation to set up your Cluster-Mode configuration.

== Required documentation for BES-53248 cluster switches

To set up the BES-53248 cluster switch, you need the following documents available from the Broadcom Support Site: https://www.broadcom.com/support/bes-switch[Broadcom Ethernet Switch Product Line]

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_EFOS Administrator's Guide v3.4.3_
a|
Provides examples of how to use the BES-53248 switch in a typical network.
a|
_EFOS CLI Command Reference v3.4.3_
a|
Describes the command-line interface (CLI) commands you use to view and configure the BES-53248 software.
a|
_EFOS Getting Started Guide v3.4.3_
a|
Provides detailed information about for the BES-53248 switch.
a|
_EFOS SNMP Reference Guide v3.4.3_
a|
Provides examples of how to use the BES-53248 switch in a typical network.
a|
_EFOS Scaling Parameters and Values v3.4.3_
a|
Describes the default scaling parameters with which EFOS software is delivered and validated on the supported platforms.
a|
_EFOS Functional Specifications v3.4.3_
a|
Describes the specifications for the EFOS software on the supported platforms.
a|
_EFOS Release Notes v3.4.3_
a|
Provides release-specific information about BES-53248 software.
|===

== Required documentation for supported ONTAP systems

To set up an ONTAP system, you need the following documents from the NetApp Support Site at http://mysupport.netapp.com/[mysupport.netapp.com]

[options="header" cols="1,2"]
|===
| Name| Description
a|
_Hardware Universe_
a|
Describes the power and site requirements for all NetApp hardware, including system cabinets.
a|
Controller-specific _Installation and Setup Instructions_
a|
Describes how to install NetApp hardware.
a|
ONTAP 9
a|
Provides detailed information about all aspects of the ONTAP 9 release.
|===
