---
permalink: switch-bes-53248/replace-prepare-controller.html
sidebar: sidebar
keywords: BES-53248 switches,preparing for upgrade,upgrade bes-53248 switch
summary: 'You can use this procedure to prepare the controller for a BES-53248 cluster switch upgrade.'
---
= Prepare the controller for a cluster switch upgrade
:icons: font
:imagesdir: ../media/

[.lead]
You can use this procedure to prepare the controller for a BES-53248 cluster switch upgrade.

.Steps
. Connect the cluster switch to the management network.
. Use the ping command to verify connectivity to the server hosting EFOS, licenses, and the RCF.
+
If this is an issue, use a nonrouted network and configure the service port using IP address 192.168.x or 172.19.x. You can reconfigure the service port to the production management IP address later.
+
This example verifies that the switch is connected to the server at IP address 172.19.2.1:
+
----
(cs2) # **ping 172.19.2.1**
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----

. Verify that the cluster ports are healthy and have a link using the command:
+
`network port show -ipspace Cluster`
+
The following example shows the type of output with all ports having a `Link` value of up and a `Health Status` of healthy:
+
----
cluster1::> **network port show -ipspace Cluster**

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

	4 entries were displayed.
----

. Verify that the cluster LIFs are administratively and operationally up and reside on their home ports, using the command:
+
`network interface show -vserver Cluster`
+
In this example, the `-vserver` parameter displays information about the LIFs that are associated with cluster ports. `Status Admin/Oper` must be up and `Is Home` must be true:
+
----
cluster1::>**network interface show -vserver Cluster**

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true

	4 entries were displayed.
----
