---
permalink: switch-bes-53248/replace-install.html
sidebar: sidebar
keywords: procedure, perform, initial, installation, bes, cluster, switch, initial installation of the bes-53428 cluster switch - bes-53428 switches
summary: You can use this procedure to perform the initial installation of the BES-53248 cluster switch.
---
= Initial installation of the BES-53248 cluster switch - BES-53248 switches
:icons: font
:imagesdir: ../media/

[.lead]
You can use this procedure to perform the initial installation of the BES-53248 cluster switch.

You can download the applicable Broadcom EFOS software for your cluster switches from the https://www.broadcom.com/support/bes-switch[Broadcom Ethernet Switch Support] site.

EFOS is a wide-ranging software set of advanced networking features and protocols necessary to develop a variety of Ethernet and IP infrastructure systems for data center applications. EFOS software is an architecture suitable for any network organizational device using leading-edge applications that require thorough packet inspection or separation.

This procedure provides a summary of the process to install your switches and get them running:

.Steps
. Connect the serial port to the host or serial port of your choice.
. Connect the management port (the RJ-45 wrench port on the left side of the switch) to the same network where your TFTP server is located.
. At the console, set the host side serial settings:
 ** 115200 baud
 ** 8 data bits
 ** 1 stop bit
 ** parity: none
 ** flow control: none
. Log in to the switch as admin and press enter when prompted for a password. The default switch name is routing. At the prompt, `enable`. This gives you access to Privileged EXEC mode for switch configuration.
+
----
User:**admin**
Password:
(Routing)> **enable**
Password:
(Routing) #
----

. Change the switch name to cs2:
+
----
(Routing) # **hostname cs2**
(cs2) #
----

. To set a static IP address, use the serviceport protocol, network protocol, and serviceport ip commands as shown in the example.
+
The serviceport is set to use DHCP by default. The IP address, subnet mask, and default gateway address are assigned automatically.
+
----
(cs2) # **serviceport protocol none**
(cs2) # **network protocol none**
(cs2) # **serviceport ip ipaddr netmask gateway**
----

. Verify the results using the command:
+
`show serviceport`
+
The following example shows IP information provided by DHCP server.
+
----
(cs2) # **show serviceport**
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----

. Configure the domain and name server:
+
`configure`
+
----
(cs2) # configure
(cs2) (Config)#ip domain name company.com
(cs2) (Config)#ip name server 10.10.99.1 10.10.99.2
(cs2) (Config)#exit
(cs2) (Config)#
----

. Configure the NTP server.
 .. Configure the time zone and time synchronization (SNTP):
+
`sntp`
+
----
(cs2) #
(cs2) (Config)#sntp client mode unicast
(cs2) (Config)#sntp server 10.99.99.5
(cs2) (Config)#clock timezone -7
(cs2) (Config)#exit
(cs2) (Config)#
----

 .. Configure the time manually:
+
`clock`
+
----
(cs2) #config
(cs2) (Config)#no sntp client mode
(cs2) (Config)#clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST
(cs2) (Config)#clock timezone -5 zone EST
(cs2) (Config)#clock set 07:00:00
(cs2) (Config)#clock set 10/20/2020

(cs2) (Config)#show clock

07:00:11 EST(UTC-5:00) Oct 20 2020
No time source

(cs2) (Config)#exit

(cs2) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) **y**

Config file 'startup-config' created successfully .

Configuration Saved!
----
