---
permalink: switch-cisco-9336/migrate-to-9336-overview.html
sidebar: sidebar
keywords: Cisco Nexus cluster switches,replacing older Cisco switches,9336C-FX2 cluster switches,migrate to newer cisco cluster switch
summary: 'You must be aware of certain configuration information, port connections and cabling requirements when you are replacing some older Cisco Nexus cluster switches with Cisco Nexus 9336C-FX2 cluster switches.'
---
= Migrate from a Cisco switch to a Cisco Nexus 9336C-FX2 cluster switch
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain configuration information, port connections and cabling requirements when you are replacing some older Cisco Nexus cluster switches with Cisco Nexus 9336C-FX2 cluster switches.

* The following cluster switches are supported:
 ** Nexus 9336C-FX2
 ** Nexus 92300YC
 ** Nexus 5596UP
 ** Nexus 5020
 ** Nexus 5010
* The cluster switches use the following ports for connections to nodes:
 ** Nexus 9336C-FX2:
  *** Ports 1- 3: Breakout mode (4x10G) Intra-Cluster Ports, int e1/1/1-4, e1/2/1-4, e1/3/1-4
  *** Ports 4- 6: Breakout mode (4x25G) Intra-Cluster/HA Ports, int e1/4/1-4, e1/5/1-4, e1/6/1-4
  *** Ports 7-34: 40/100GbE Intra-Cluster/HA Ports, int e1/7-34
 ** Nexus 92300YC:
  *** Ports e1/1-48 (10/25 GbE) e1/49-64 (40/100 GbE)
 ** Nexus 5596UP:
  *** Ports e1/1-40 (10 GbE)
 ** Nexus 5020:
  *** Ports e1/1-32 (10 GbE)
 ** Nexus 5010 with expansion:
  *** Ports e1/1-12, e2/1-6 (10 GbE)
* The cluster switches use the following Inter-Switch Link (ISL) ports:
 ** Ports int e1/35-36: Nexus 9336C-FX2
 ** Ports e1/65-66 (100 GbE): Nexus 92300YC
 ** Ports e1/41-48 (10 GbE): Nexus 5596UP
 ** Ports e1/33-40 (10 GbE): Nexus 5020
 ** Ports e1/13-20 (10 GbE): Nexus 5010
* The _Hardware Universe_ contains information about supported cabling for all cluster switches.
* You have configured some of the ports on Nexus 9336C-FX2 switches to run at 10 GbE or 40 GbE.
* You have planned, migrated, and documented 10 GbE and 40 GbE connectivity from nodes to Nexus 9336C-FX2 cluster switches.
* The ONTAP and NX-OS versions supported in this procedure are on the _Cisco Ethernet Switches_ page.
+
https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches]
