---
permalink: switch-cisco-9336/setup-required-documentation.html
sidebar: sidebar
keywords: controller, documentation, ontap, cluster, required documentation - cisco nexus 9336c-fx2
summary: You need specific switch and controller documentation to set up your ONTAP cluster.
---
= Required documentation
:icons: font
:imagesdir: ../media/

[.lead]
You need specific switch and controller documentation to set up your ONTAP cluster.

== Required documentation for cluster network switches

To set up the Cisco Nexus 9336C-FX2 and 92300YC switches, you need the following documentation from the https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches Support] page:

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_Nexus 9000 Series Hardware Installation Guide_
a|
Provides detailed information about site requirements, switch hardware details, and installation options.
a|
_Cisco Nexus 9000 Series Switch Software Configuration Guides_ (choose the guide for the NX-OS release installed on your switches)
a|
Provides initial switch configuration information that you need before you can configure the switch for ONTAP operation.
a|
_Cisco Nexus 9000 Series NX-OS Software Upgrade and Downgrade Guide_ (choose the guide for the NX-OS release installed on your switches)
a|
Provides information on how to downgrade the switch to ONTAP supported switch software, if necessary.
a|
_Cisco Nexus 9000 Series NX-OS Command Reference Master Index_
a|
Provides links to the various command references provided by Cisco.
a|
_Cisco Nexus 9000 MIBs Reference_
a|
Describes the Management Information Base (MIB) files for the Nexus 9000 switches.
a|
_Nexus 9000 Series NX-OS System Message Reference_
a|
Describes the system messages for Cisco Nexus 9000 series switches, those that are informational, and others that might help diagnose problems with links, internal hardware, or the system software.
a|
_Cisco Nexus 9000 Series NX-OS Release Notes (choose the notes for the NX-OS release installed on your switches)_
a|
Describes the features, bugs, and limitations for the Cisco Nexus 9000 Series.
a|
Regulatory Compliance and Safety Information for Cisco Nexus 9000 Series
a|
Provides international agency compliance, safety, and statutory information for the Nexus 9000 series switches.
|===
To set up the Cisco Nexus 3232C and 3132Q-V switches, you need the following documentation from the https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html[Cisco Nexus 3000 Series Switches Support] page:

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_Nexus 3000 Series Hardware Installation Guide_
a|
Provides detailed information about site requirements, switch hardware details, and installation options.
a|
_Cisco Nexus 3000 Series Switch Software Configuration Guides_ (choose the guide for the NX-OS release installed on your switches)
a|
Provides initial switch configuration information that you need before you can configure the switch for ONTAP operation.
a|
_Cisco Nexus 3000 Series NX-OS Software Upgrade and Downgrade Guide_ (choose the guide for the NX-OS release installed on your switches)
a|
Provides information on how to downgrade the switch to ONTAP supported switch software, if necessary.
a|
_Cisco Nexus 3000 Series NX-OS Command Reference Master Index_
a|
Provides links to the various command references provided by Cisco.
a|
_Cisco Nexus 3000 MIBs Reference_
a|
Describes the Management Information Base (MIB) files for the Nexus 3000 switches.
a|
_Nexus 3000 Series NX-OS System Message Reference_
a|
Describes the system messages for Cisco Nexus 3000 series switches, those that are informational, and others that might help diagnose problems with links, internal hardware, or the system software.
a|
_Cisco Nexus 3000 Series NX-OS Release Notes (choose the notes for the NX-OS release installed on your switches)_
a|
Describes the features, bugs, and limitations for the Cisco Nexus 3000 Series.
a|
Regulatory, Compliance, and Safety Information for the Cisco Nexus 6000, Cisco Nexus 5000 Series, Cisco Nexus 3000 Series, and Cisco Nexus 2000 Series
a|
Provides international agency compliance, safety, and statutory information for the Nexus 3000 series switches.
|===
To set up the Cisco Nexus 5596 switch, you need the following documents from https://www.cisco.com/c/en/us/support/switches/nexus-5000-series-switches/series.html[Cisco Nexus 5000 Series Switches Support] page:

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_Nexus 5000 Series Hardware Installation Guide_
a|
Provides detailed information about site requirements, switch hardware details, and installation options.
a|
_Cisco Nexus 5000 Series Switch Software Configuration Guide_ (choose the guide for the software you are using)
a|
Provides initial switch configuration information that you need before you can configure the switch for ONTAP operation.
a|
_Cisco Nexus 5000 Series NX-OS Software Upgrade and Downgrade Guide_
a|
Provides information about how to downgrade the switch to the supported ONTAP switch software, if necessary.
a|
_Cisco Nexus 5000 Series NX-OS Command Reference Master Index_
a|
Provides an alphabetical list of all the commands supported for a specific NX-OS release.
a|
_Cisco Nexus 5000 and Nexus 2000 MIBs Reference_
a|
Describes the Management Information Base (MIB) files for the Nexus 5000 switches.
a|
_Nexus 5000 Series NX-OS System Message Reference_
a|
Describes troubleshooting information.
a|
_Regulatory, Compliance, and Safety Information for the Cisco Nexus 6000 Series, Cisco Nexus 5000 Series, Cisco Nexus 3000 Series, and Cisco Nexus 2000 Series_
a|
Provides international agency compliance, safety, and statutory information for the Nexus 5000 series switches.
|===

== Required documentation for supported ONTAP systems

To set up an ONTAP system, you need the following documents for your version of the operating system from the https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center].

[options="header" cols="1,2"]
|===
| Name| Description
a|
Controller-specific _Installation and Setup Instructions_
a|
Describes how to install NetApp hardware.
a|
ONTAP documentation
a|
Provides detailed information about all aspects of the ONTAP releases.
a|
https://hwu.netapp.com[Hardware Universe]
a|
Provides NetApp hardware configuration and compatibility information.
|===

== Rail kit and cabinet documentation

To install a Cisco switch in a NetApp cabinet, see the following hardware documentation:

[options="header" cols="1,2"]
|===
| Name| Description
a|
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394[42U System Cabinet, Deep Guide]
a|
Describes the FRUs associated with the 42U system cabinet, and provides maintenance and FRU replacement instructions.
a|
https://library.netapp.com/ecm/ecm_get_file/ECMLP2843148[Installing a Cisco Nexus 3232C cluster switch and pass-through panel in a NetApp cabinet]
a|
Describes how to install a Cisco Nexus 3232C switch in a four-post NetApp cabinet.
a|
https://library.netapp.com/ecm/ecm_download_file/ECMLP2518305[Installing a Cisco Nexus 3132Q-V switch and pass-through panel in a NetApp Cabinet]
a|
Describes how to install a Cisco Nexus 3132Q-V switch in a four-post NetApp cabinet.
a|
https://library.netapp.com/ecm/ecm_download_file/ECMP1141864[Installing a Cisco Nexus 5596 switch and pass-through panel in a NetApp Cabinet]
a|
Describes how to install a Cisco Nexus 5596 switch in a NetApp cabinet.
|===
