settings:
  search: ontap-systems-switches
sidebar:
  entries:
    - title: AFF and FAS switch docs
      url: "/index.html"
    - section: switch-bes-53248
    - section: switch-cisco-3132q-v
    - section: switch-cisco-3232c
    - section: switch-cisco-9336c-fx2
    - section: switch-cisco-9336c-fx2-shared
    - section: switch-cisco-92300
    - section: switch-netapp-cn1610
    - section: switch-nvidia-msn2100
    - section: other
    - title: Legal notices
      url: "/legal-notices.html"
