settings:
  name: Install and maintain
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  pdf:
    zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
sidebar:
  entries:
    - title: Switch docs for ONTAP hardware systems
      url: "/index.html"
    - title: Get started
      entries:
        - title: What's new
          url: "/whats-new.html"
        - title: Learn about ONTAP systems switches
          url: "/get-started/learn-switch-concept.html"
        - title: Get up and running
          url: "/get-started/get-up-and-running.html"
    - title: AFX systems switches
      url: /afx/index.html
      entries:
        - section: switch-cisco-9332d-gx2b
        - section: switch-cisco-9364d-gx2a
    - title: Cluster switches
      url: /cluster/index.html
      entries:
        - section: switch-bes-53248
        - section: switch-cisco-9336c-fx2
        - section: switch-nvidia-sn2100
    - title: Storage switches
      url: /storage/index.html
      entries:
        - section: switch-cisco-9336c-fx2-storage
        - section: switch-nvidia-sn2100-storage
    - title: Shared switches
      url: /shared/index.html
      entries:
        - section: switch-cisco-9336c-fx2-shared
          pdf-filename: switch-cisco-9336c-fx2-storage
    - section: switch-cshm
    - title: End-of-availability switches
      entries:
        - title: Overview
          url: "/overview-eod.html"
        - section: switch-cisco-3232c
        - section: switch-cisco-3132q-v
        - section: switch-cisco-92300
        - section: switch-netapp-cn1610
    - title: Legal notices
      url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
