settings:
  name: "ONTAP Systems Switches"
  search: "ontap-systems, ontap-systems-upgrade"
  internal:
    pdf_enabled: true
  prod: 
    pdf_enabled: true
    harmony_enabled: true
    langs: "us-en,ja-jp,zh-cn"
sidebar:
  entries:
    - title: Home
      url: "/index.html"
    - section: switch-bes-532480
    - section: switch-cisco-9336
    - section: switch-cisco-9336c-shared
    - section: switch-cisco-92300
    - section: other
    - title: Legal notices
      url: "/legal-notices.html"
