settings:
  name: Cluster and storage switches
  search: ontap-systems-switches
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  pdf:
    gen-type: named only
    #zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
sidebar:
  entries:
    - title: AFF and FAS switch docs
      url: "/index.html"
    - title: Get started
      entries:
        - title: What's new
          url: "/whats-new.html"
        - title: Learn about ONTAP systems switches
          url: "/get-started/learn-switch-concept.html"
        - title: Get up and running
          url: "/get-started/get-up-and-running.html"
    - title: Cluster switches
      entries:
        - section: switch-bes-53248
        - section: switch-cisco-9336c-fx2
        - section: switch-nvidia-sn2100
    - title: Storage switches
      entries:
        - section: switch-cisco-9336c-fx2-storage
        - section: switch-nvidia-sn2100-storage
    - title: Shared switches
      entries:
        - section: switch-cisco-9336c-fx2-shared
    - title: End-of-availability switches
      entries:
        - title: Overview
          url: "/overview-eod.html"
        - section: switch-cisco-3232c
        - section: switch-cisco-3132q-v
        - section: switch-cisco-92300
        - section: switch-netapp-cn1610
    - title: Legal notices
      url: "/legal-notices.html"
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
