settings:
  name: Install and maintain
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  pdf:
    zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
sidebar:
  entries:
    - title: Switch docs for ONTAP storage systems
      url: "/index.html"
    - title: Release notes
      entries:
        - title: What's new for switches
          url: "/whats-new.html"
        - title: End-of-support
          url: "/eoa-switches.html"
    - title: Get started
      entries: 
       - title: Learn about ONTAP systems switches
         url: "/get-started/learn-switch-concept.html" 
       - title: Quick start
         url: "/get-started/get-up-and-running.html"
      url: "/get-started/get-up-and-running.html"
    - title: AFX systems switches
      url: /afx/index.html
      entries:
        - section: switch-cisco-9808
        - section: switch-cisco-9332d-gx2b
        - section: switch-cisco-9364d-gx2a
    - title: Cluster switches
      url: /cluster/index.html
      entries:
        - section: switch-bes-53248
        - section: switch-cisco-9336c-fx2
    - title: Storage switches
      url: /storage/index.html
      entries:
        - section: switch-cisco-9336c-fx2-storage
    - title: Shared switches
      url: /shared/index.html
      entries:
        - section: switch-cisco-9336c-fx2-shared
          pdf-filename: switch-cisco-9336c-fx2-storage
    - title: Monitor switch health
      url: /cshm/index.html
      entries:
        - section: switch-cshm
    - title: End-of-availability switches
#      url: "/overview-eod.html"
      entries:
        - section: switch-nvidia-sn2100
        - section: switch-nvidia-sn2100-storage
    - title: Legal notices
      url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
