settings:
  search: ontap-systems-switches
sidebar:
  entries:
    - title: Home
      url: "/index.html"
    - section: switch-bes-53248
    - section: switch-netapp-cn1610
    - section: switch-cisco-3132q-v
    - section: switch-cisco-3232c
    - section: switch-cisco-9336
    - section: switch-cisco-9336c-shared
    - section: switch-cisco-92300
    - section: other
    - title: Legal notices
      url: "/legal-notices.html"
