---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html
sidebar: sidebar
keywords: nvidia SN2100 switches
summary: For NVIDIA SN2100 switch installation and maintenance, be sure to review all requirements and recommended documentation. 
---
= Configuration requirements for NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
For NVIDIA SN2100 switch installation and maintenance, be sure to review all configuration requirements. 

== Installation requirements

If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.

You install the NVIDIA SN2100 switch (X190006) in the NVIDIA dual/single switch cabinet with the standard brackets that are included with the switch. 

For cabling guidelines, see link:cabling-considerations-sn2100-cluster.html[Review cabling and configuration considerations].

== ONTAP and Linux support

The NVIDIA SN2100 switch is a 10/25/40/100GbE switch running Cumulus Linux. The switch supports the following:

* ONTAP 9.10.1P3 and later.
+
The SN2100 switch serves Cluster and Storage applications in ONTAP 9.10.1P3 and later over different switch-pairs. 

* Cumulus Linux (CL) OS versions. 
** Specific CL versions are qualified and supported by NetApp. For current compatibility information, see the link:https://mysupport.netapp.com/site/info/nvidia-cluster-switch[NVIDIA Ethernet Switches information^] page or link:https://hwu.netapp.com[NetApp Hardware Universe^].

** In order to download the SN2100 Cumulus software from NVIDIA, you must have login credentials to access NVIDIA's Enterprise Support Portal. See the Knowledge Base article https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access[How to register with NVIDIA for Enterprise Support Portal Access^]. 

//For current compatibility information, see the https://mysupport.netapp.com/site/info/nvidia-cluster-switch[NVIDIA Ethernet Switches^] information page.

* You can install Cumulus Linux when the switch is running Cumulus Linux or ONIE.

// Updated content as part of the LH release of CL 5.4, 2023-APR-17
// Updates for AFFFASDOC-167, 2023-NOV-14
// Updates for GH issues #230 & 231, 2024-DEC-10