---
permalink: switch-nvidia-sn2100/configure-log-collection.html
sidebar: sidebar
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation
summary: 'The cluster switch health monitor log collection feature is used to collect switch-related log files in ONTAP. You must make sure that you have set up your environment using the NVIDIA SN2100 cluster switch CLI as detailed here.'
---
= Enable the log collection feature
:icons: font
:imagesdir: ../media/

[.lead]
You can use the log collection feature to collect switch-related log files in ONTAP. 

//IMPORTANT: To enable the log collection feature, you must be running ONTAP version 9.12.1 and later and EFOS 3.8.0.2 and later.

NOTE: You must specify a user in the RCF (in addition to the admin user) to be used specifically for log collection. Additionally, you must enable switch health monitoring on the switch in order to run the log collection feature. 

Verify that you have set up your environment using the SN2100 cluster switch *CLI*.

.Steps

. Create a password for the Ethernet switch health monitor log collection feature:
`system switch ethernet log setup-password`

+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====

. Enable the Ethernet switch health monitor log collection feature.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Wait for 10 minutes and then check that the log collection completes using the command:
+
`system switch ethernet log show`
+
CAUTION: If any of these commands return an error or if the log collection does not complete, contact NetApp support.


//.What's next?
//If you are upgrading the switch, go to link:replace-verify.html[Verify upgrade configuration].

// Updates for AFFFASDOC-142, 2023-OCT-18
