---
permalink: switch-nvidia-sn2100/install-cumulus-mode-sn2100-cluster.html
sidebar: sidebar
keywords: install cumulus mode, sn2100 SN2100 switches setup, cumulus linux, cumulus mode
summary: 'Cumulus Linux (CL) OS can be installed either when the switch is running Cumulus Linux or ONIE.'
---
= Install Cumulus Linux in Cumulus mode
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to install Cumulus Linux (CL) OS when the switch is running in Cumulus mode. 

NOTE: Cumulus Linux (CL) OS can be installed either when the switch is running Cumulus Linux or ONIE (see link:install-onie-mode-sn2100-cluster.html[Install in ONIE mode]).

.What you'll need

* Intermediate-level Linux knowledge.
* Familiarity with basic text editing, UNIX file permissions, and process monitoring. A variety of text editors are pre-installed, including `vi` and `nano`.
* Access to a Linux or UNIX shell. If you are running Windows, use a Linux environment as your command line tool for interacting with Cumulus Linux.

* The baud rate requirement is set to 115200 on the serial console switch for NVIDIA SN2100 switch console access, as follows:

** 115200 baud
** 8 data bits
** 1 stop bit
** parity: none
** flow control: none

//NOTE: Example command output uses switch management IP address 10.233.204.71, netmask 255.255.254.0 and default gateway 10.233.204.1.

.About this task
Be aware of the following:

NOTE: Each time Cumulus Linux is installed, the entire file system structure is erased and rebuilt.

CAUTION: The default password for the cumulus user account is *cumulus*. The first time you log into Cumulus Linux, you must change this default password. Be sure to update any automation scripts before installing a new image. Cumulus Linux provides command line options to change the default password automatically during the installation process.

.Steps

// start of tabbed content 

[role="tabbed-block"] 

==== 

.For Cumulus Linux version 4.4.3
--
. Log in to the switch. 
+
First time log in to the switch requires username/password of *cumulus*/*cumulus* with `sudo` privileges.
+
[subs=+quotes]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----

. Check the Cumulus Linux version: `net show system`
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox
----
//====

. Configure the hostname, IP address, subnet mask, and default gateway. The new hostname only becomes effective after restarting the console/SSH session.
+
NOTE: A Cumulus Linux switch provides at least one dedicated Ethernet management port called `eth0`. This interface is specifically for out-of-band management use. By default, the management interface uses DHCPv4 for addressing.
+
CAUTION: Do not use an underscore (_), apostrophe ('), or non-ASCII characters in the hostname.
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *net add hostname sw1*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip address 10.233.204.71*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *net pending*
cumulus@cumulus:mgmt:~$ *net commit*
----
+
This command modifies both the `/etc/hostname` and `/etc/hosts` files.

. Confirm that the hostname, IP address, subnet mask, and default gateway have been updated.
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----

. Configure the time zone using NTP interactive mode.

.. On a terminal, run the following command:
+
[subs=+quotes]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Follow the on-screen menu options to select the geographic area and region.
.. To set the time zone for all services and daemons, reboot the switch.
.. Verify that the date and time on the switch are correct and update if necessary.

. Install Cumulus Linux 4.4.3:
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*
----
The installer starts the download.  Type *y* when prompted.
. Reboot the NVIDIA SN2100 switch:
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. The installation starts automatically, and the following GRUB screen choices appear.  Do *not* make any selections.
* Cumulus-Linux GNU/Linux
* ONIE: Install OS
* CUMULUS-INSTALL
* Cumulus-Linux GNU/Linux
. Repeat steps 1 to 4 to log in.
. Verify that the Cumulus Linux version is 4.4.3: `net show version`
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u0
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3"*
----

. Create a new user and add this user to the `sudo` group.  This user only becomes effective after the console/SSH session is restarted.
+
`sudo adduser --ingroup netedit admin`
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user `admin’ ...
Adding new user `admin’ (1001) with group `netedit' ...
Creating home directory `/home/admin’ ...
Copying files from `/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ exit
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----

--
.For Cumulus Linux 5.x and later
--
. Log in to the switch. 
+
First time log in to the switch requires username/password of *cumulus*/*cumulus* with `sudo` privileges.
+
[subs=+quotes]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----

. Check the Cumulus Linux version: `nv show system`
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
Static hostname for the switch
build               Cumulus Linux 5.3.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----

. Configure the hostname, IP address, subnet mask, and default gateway. The new hostname only becomes effective after restarting the console/SSH session.
+
NOTE: A Cumulus Linux switch provides at least one dedicated Ethernet management port called `eth0`. This interface is specifically for out-of-band management use. By default, the management interface uses DHCPv4 for addressing.
+
CAUTION: Do not use an underscore (_), apostrophe ('), or non-ASCII characters in the hostname.
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *nv add hostname sw1*
cumulus@cumulus:mgmt:~$ *nv add interface eth0 ip address 10.233.204.71*
cumulus@cumulus:mgmt:~$ *nv add interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv pending*
cumulus@cumulus:mgmt:~$ *nv commit*
----
+
This command modifies both the `/etc/hostname` and `/etc/hosts` files.

. Confirm that the hostname, IP address, subnet mask, and default gateway have been updated.
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----

. Configure the time zone using NTP interactive mode.

.. On a terminal, run the following command:
+
[subs=+quotes]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Follow the on-screen menu options to select the geographic area and region.
.. To set the time zone for all services and daemons, reboot the switch.
.. Verify that the date and time on the switch are correct and update if necessary.

. Install Cumulus Linux 5.4:
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*
----
The installer starts the download.  Type *y* when prompted.
. Reboot the NVIDIA SN2100 switch:
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. The installation starts automatically, and the following GRUB screen choices appear.  Do *not* make any selections.
* Cumulus-Linux GNU/Linux
* ONIE: Install OS
* CUMULUS-INSTALL
* Cumulus-Linux GNU/Linux
. Repeat steps 1 to 4 to log in.
. Verify that the Cumulus Linux version is 5.4: `nv show version`
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *nv show version*
NCLU_VERSION=1.0-cl5.4u0
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*5.4*
DISTRIB_DESCRIPTION=*"Cumulus Linux 5.4"*
----

. Create a new user and add this user to the `sudo` group.  This user only becomes effective after the console/SSH session is restarted.
+
`sudo adduser --ingroup netedit admin`
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user `admin’ ...
Adding new user `admin’ (1001) with group `netedit' ...
Creating home directory `/home/admin’ ...
Copying files from `/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ exit
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
--
==== 

// end of tabbed content

NOTE: To upgrade from Cumulus Linux 5.3.0 to 5.4.0, see link:upgrade-cl-version.html[Upgrade from Cumulus Linux 5.3.0 to 5.4.0]. 

.What's next?
link:install-rcf-sn2100-cluster.html[Install the Reference Configuration File (RCF) script].

// GH issue #77 replacing 4.4.2 with 4.4.3, 2023-FEB-22
// Updated password examples, 2023-MAR-07
// Added in content for LH - CLI version 5.x, 2023-MAY-08