---
permalink: switch-nvidia-sn2100/install_setup_sn2100_switches_overview.html
sidebar: sidebar
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux
summary: 'The NVIDIA SN2100 switch is a 10/25/40/100 GbE Ethernet switch running Cumulus Linux. The SN2100 switch serves Cluster and Storage applications in ONTAP 9.10.1 over different switch-pairs.'
---
= Set up and configure the NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
The NVIDIA SN2100 switch is a 10/25/40/100 Gb Ethernet switch running Cumulus Linux. The SN2100 switch serves Cluster and Storage applications in ONTAP 9.10.1P3 over different switch-pairs.

Cumulus Linux (CL) OS can be installed either when the switch is running Cumulus Linux or ONIE.
For this release, Cumulus Linux version 4.4.2 is supported.

NOTE: The procedures here use Network Command Line Utility (NCLU) which is a command line interface that ensures Cumulus Linux is fully accessible to all. The net command is the wrapper utility you use to execute actions from a terminal.

IMPORTANT: When using breakout cables for 10G and 25G, make sure that auto-negotiation is off and hard set the port speed on the switch. See link:install_cabling_config_considerations_sn2100.html[Cabling and configuration considerations^] for further details.
