---
permalink: switch-nvidia-sn2100/install-onie-mode-sn2100-cluster.html
sidebar: sidebar
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode
summary: 'Cumulus Linux (CL) OS can be installed either when the switch is running Cumulus Linux or ONIE.'
---
= Install Cumulus Linux in ONIE mode
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to install Cumulus Linux (CL) OS when the switch is running in ONIE mode.  

NOTE: Cumulus Linux (CL) OS can be installed either when the switch is running ONIE or Cumulus Linux (see link:install-cumulus-mode-sn2100-cluster.html[Install in Cumulus mode]).

.About this task
You can install Cumulus Linux using Open Network Install Environment (ONIE) that allows for automatic discovery of a network installer image. This facilitates the system model of securing switches with an operating system choice, such as Cumulus Linux. The easiest way to install Cumulus Linux with ONIE is with local HTTP discovery.

NOTE: If your host is IPv6-enabled, make sure it is running a web server. If your host is IPv4-enabled, make sure it is running DHCP in addition to a web server.

This procedure demonstrates how to upgrade Cumulus Linux after the admin has booted in ONIE.

//NOTE: Example command output uses switch management IP address 10.233.204.71, netmask 255.255.254.0 and default gateway 10.233.204.1.

.Steps

// start of tabbed content 

[role="tabbed-block"] 

==== 

.On Cumulus Linux version 4.4.3

--
. Download the Cumulus Linux installation file to the root directory of the web server. Rename this file to: `onie-installer`.
. Connect your host to the management Ethernet port of the switch using an Ethernet cable.
. Power on the switch. 
+
The switch downloads the ONIE image installer and boots. After the installation completes, the Cumulus Linux login prompt appears in the terminal window.
+
NOTE: Each time Cumulus Linux is installed, the entire file system structure is erased and rebuilt.

. Reboot the SN2100 switch:
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Press the *Esc* key at the GNU GRUB screen to interrupt the normal boot process, select *ONIE*, and press *Enter*.
. On the next screen, select *ONIE: Install OS*.
. The ONIE installer discovery process runs searching for the automatic installation.  Press *Enter* to temporarily stop the process.
. When the discovery process has stopped:
+
[subs=+quotes]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. If the DHCP service is running on your network, verify that the IP address, subnet mask, and the default gateway are correctly assigned:
+
`ifconfig eth0`
+
[subs=+quotes]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----

. If the IP addressing scheme is manually defined, do the following:
+
[subs=+quotes]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. Repeat step 9 to verify that the static information is correctly entered.
. Install Cumulus Linux:
+
----
# onie-nos-install http://<web-server>/<path>/cumulus-linux-4.4.3-mlx-amd64.bin
----
+
[subs=+quotes]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----

. Once the installation has completed, log in to the switch.
+
[subs=+quotes]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----

. Verify the Cumulus Linux version: `net show version`
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
--

.On Cumulus Linux 5.x and later

--
. Download the Cumulus Linux installation file to the root directory of the web server. Rename this file to: `onie-installer`.
. Connect your host to the management Ethernet port of the switch using an Ethernet cable.
. Power on the switch. 
+
The switch downloads the ONIE image installer and boots. After the installation completes, the Cumulus Linux login prompt appears in the terminal window.
+
NOTE: Each time Cumulus Linux is installed, the entire file system structure is erased and rebuilt.

. Reboot the SN2100 switch:
+
----
cumulus@cumulus:mgmt:~$ sudo reboot
.
.
GNU GRUB version 2.06-3
+-------------------------------------------------------------------------+
| Cumulus-Linux GNU/Linux                                                 |
| Advanced options for Cumulus-Linux GNU/Linux                            |
| ONIE                                                                    |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
+
Press the Esc key at the GNU GRUB screen to interrupt the normal boot process, select ONIE, and press Enter
.
.
Loading ONIE ...

GNU GRUB version 2.02

+-------------------------------------------------------------------------+
| ONIE: Install OS                                                        |
| ONIE: Rescue                                                            |
| ONIE: Uninstall OS                                                      |
| ONIE: Update ONIE                                                       |
| ONIE: Embed ONIE                                                        |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
Select ONIE: Install OS.
----

. The ONIE installer discovery process runs searching for the automatic installation.  Press *Enter* to temporarily stop the process.
. When the discovery process has stopped:
+
[subs=+quotes]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----

. Configure the IP address, subnet mask, and the default gateway:
+
`ifconfig eth0`
+
[subs=+quotes]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff
ONIE:/ #       
ONIE:/ # *ifconfig eth0 10.228.140.27 netmask 255.255.248.0*
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet HWaddr B8:CE:F6:5E:05:E6
       inet addr:10.228.140.27 Bcast:10.228.143.255 Mask:255.255.248.0
       inet6 addr: fd20:8b1e:b255:822b:bace:f6ff:fe5e:5e6/64 Scope:Global
       inet6 addr: fe80::bace:f6ff:fe5e:5e6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
       RX packets:18813 errors:0 dropped:1418 overruns:0 frame:0
       TX packets:491 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:1339596 (1.2 MiB) TX bytes:49379 (48.2 KiB)
       Memory:dfc00000-dfc1ffff
ONIE:/ # *route add default gw 10.228.136.1*
ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.228.136.1    0.0.0.0         UG    0      0      0   eth0
10.228.136.1    *               255.255.248.0   U     0      0      0   eth0
----

. Install Cumulus Linux 5.4:
+
`# onie-nos-install http://<web-server>/<path>/cumulus-linux-5.4-mlx-amd64.bin`
+
[subs=+quotes]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-5.4-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----

. Once the installation has completed, log in to the switch.
+
[subs=+quotes]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----

. Verify the Cumulus Linux version: `nv show version`
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *nv show version*
NCLU_VERSION=1.0-cl5.4u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*5.4*
DISTRIB_DESCRIPTION=*"Cumulus Linux 5.4”*
----

. Create additional user groups for the cumulus user:
+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
--
==== 

// end of tabbed content 

NOTE: See https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/[NVIDIA User Accounts] for more information.

//NOTE: To upgrade from Cumulus Linux 5.3.0 to 5.4.0, see link:upgrade-cl-version.html[Upgrade from Cumulus Linux 5.3.0 to 5.4.0]. 

.What's next?
link:install-rcf-sn2100-cluster.html[Install the Reference Configuration File (RCF) script].

// GH issue #77 replacing 4.4.2 with 4.4.3, 2023-FEB-22
// Updated password examples, 2023-MAR-07
// Added in content for LH - CLI version 5.x, 2023-APR-08