---
permalink: switch-nvidia-sn2100/install_cabling_config_considerations_sn2100.html
sidebar: sidebar
keywords: sn2100 SN2100 cabling setup, sn2100 switches configuration, cumulus linux os
summary: 'Before configuring your NVIDIA SN2100 switch, review the following information:'
---
= Cabling and configuration considerations
:icons: font
:imagesdir: ../media/

[.lead]
Before configuring your NVIDIA SN2100 switch, review the following information:

. Only optical connections are supported on SN2100 switches with X1151A NIC, X1146A NIC, or onboard 100GbE ports. For example:
.. AFF A800 on ports e0a and e0b
.. AFF A320 on ports e0g and e0h
. When a QSA adapter is used to connect to the onboard Intel cluster ports on a platform, not all links come up.
+
Example platforms are: FAS2750, AFF A300, and FAS8200 (all 10G) and AFF A250 (25G).
+
To resolve this issue, do the following:

.. For Intel 10G, manually set the swp1s0-3 link speed to 10000 and set auto-negotiation to off
.. For Chelsio 25G, manually set the swp2s0-3 link speed to 25000 and set auto-negotiation to off
+

NOTE: Using 10G/25G QSA, use the non-breakout 40/100G ports. Do not insert the QSA adapter on ports that are configured for breakout.


. Depending on the transceiver in the switchport, you might need to set the speed on the switchport to fixed speed. If using 10G and 25G breakout ports, make sure that auto-negotiation is off and hard set the port speed on the switch. For example:
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ net add int swp1s3 link autoneg off && net com
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----

== Support for DAC cables
Cumulus Linux version 4.4.3 supports DAC cabling. You enable the reduce link up time algorithm on a per port basis for this feature.

.Steps
. Add the following lines to the `/etc/cumulus/switchd.conf` file.
.. `interface.swp1.enable_media_depended_linkup_flow=TRUE`
.. `interface.swp1.enable_short_tuning=TRUE`
. Run either of these commands:
.. `systemctl reload switchd`
.. `systemctl restart switchd`

NOTE: This procedure applies only to ports that are using DAC.

.Example
The following example shows output for port 1. The port format is swp[_n_], where _n_ is the applicable port number.

Enter the commands as shown:

[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *cat /etc/cumulus/switchd.conf | grep swp3*
interface.swp3.enable_media_depended_linkup_flow=TRUE
interface.swp3.enable_short_tuning=TRUE
cumulus@cumulus:mgmt:~$ *cat /etc/cumulus/switchd.conf | grep swp6*
interface.swp6.enable_media_depended_linkup_flow=TRUE
interface.swp6.enable_short_tuning=TRUE
cumulus@cumulus:mgmt:~$
----
