---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-cluster.html
sidebar: sidebar
keywords: nvidia SN2100 switches
summary: For NVIDIA SN2100 switch installation and maintenance, be sure to review all the recommended documentation. 
---
= Documentation requirements for NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
For NVIDIA SN2100 switch installation, be sure to review all the recommended documentation. 

[options="header" cols="1,2"]
|===
| Title | Description
a|
link:https://docs.nvidia.com/networking/display/sn2000pub/Installation[NVIDIA Switch Installation Guide^]
a|
Describes how to install your NVIDIA SN2100 switches.
a|
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580[NS224 NVMe Drive Shelf Cabling Guide^]
a|
Overview and illustrations showing how to configure cabling for drive shelves.
|===

== ONTAP systems documentation

To set up an ONTAP system, you need the following documents for your version of the operating system.

[options="header" cols="1,2"]
|===
| Name| Description
a|
Controller-specific _Installation and Setup Instructions_
a|
Describes how to install NetApp hardware.
a|
link:https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9^]
a|
Provides detailed information about all aspects of the ONTAP releases.
a|
link:https://hwu.netapp.com/[Hardware Universe^]
a|
Allows you to confirm supported hardware, such as cluster switches and cables, for your platform model.
|===

// AFFFASDOC-473, 2026-MAR-18