---
permalink: switch-nvidia-sn2100/reset-switch-sn2100.html
sidebar: sidebar
keywords: SN2100 reset switch to factory defaults, SN2100 switches configuration, efos
summary: 'Before configuring your Cisco Nexus SN2100 switch, review the following information.'
---
= Reset the SN2100 cluster switch to factory defaults

:icons: font
:imagesdir: ../media/

[.lead]
To reset the SN2100 cluster switch to factory defaults:

* For Cumulus Linux 5.10 and earlier, you can apply the Cumulus image.
* For Cumulus Linux 5.10 and later, you can use the `sudo systemctl restart factory-reset.service` command. 

.About this task

* You must be connected to the switch using the serial console.
* You must have the root password for sudo access to the commands.
* You must have system admin, root, or sudo privileges to run factory reset commands.
* The switch does not support factory reset if you upgrade to Cumulus Linux 5.11 from Cumulus Linux 5.9.x or 5.10.x with package upgrade.

NOTE: For more information about installing Cumulus Linux, see link:configure-software-overview-sn2100-cluster.html[Software install workflow for NVIDIA SN2100 switches].

.About the factory reset command

Factory reset provides options to:

* Remove all configuration, system files, and log files.
* Remove system files and log files but keep certain configuration, such as password policy rules, management interface configuration (such as eth0), local user accounts and roles, and SSH configuration.
* Remove system files and log files but keep all configuration.
* Remove configuration but keep system files and log files.

.Steps

// start of tabbed content 

[role="tabbed-block"] 

==== 

.Cumulus Linux 5.10 and earlier

--
. From the Cumulus console, download and queue the switch software installation with the command `onie-install -a -i` followed by the file path to the switch software, for example:
+

[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://<web-server>/<path>/cumulus-linux-4.4.3-mlx-amd64.bin*
----

. The installer starts the download. Type *y* when prompted to confirm the installation when the image is downloaded and verified.

. Reboot the switch to install the new software.
+
`sudo reboot`

+
[subs=+quotes]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
+

NOTE: The switch reboots and enters the switch software installation which takes some time. When the installation is complete, the switch reboots and remains at the `log-in` prompt.
--

.Cumulus Linux 5.11 and later
--
. To reset the switch to the factory defaults and remove all configuration, system files, and log files (the default option) run:
+
`systemctl restart factory-reset.service`

. To keep  certain configuration, keep all configuration but not system and log files, or keep system and log files but no configuration, create the `/tmp/factory-reset.conf` file, add one of the reset options to the file, then run `systemctl restart factory-reset.service`.
+
* `TYPE=keep-basic` resets the switch to the factory defaults but keeps password policy rules, management interface configuration (such as eth0), local user accounts and roles, and SSH configuration.
* `TYPE=keep-all-config` resets the switch to the factory defaults but keeps all configuration.
* `TYPE=keep-all-files` resets the switch to the factory defaults but keeps all system files and log files. 

+
For example, to reset the switch to the factory defaults but keep password policy rules, management interface configuration (such as eth0), local user accounts and roles, and SSH configuration.

+
[subs=+quotes]
----
cumulus@switch:~$ *sudo nano /tmp/factory-reset.conf
TYPE=keep-basic*
----

NOTE: When you use the `keep-basic` option, you must create a `/tmp/startup-new.yaml` file with the configuration you want after factory reset, then start `factory-reset.service`. This is not necessary for the other options. 

See NVIDIA'S https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/Installation-Management/Factory-Reset/[Factory Reset^] page for further details.

--
====

// end of tabbed content 

// New content for AFFFASDOC-373, 2025-AUG-05
