---
permalink: switch-nvidia-sn2100/setup-install-cshm-file.html
sidebar: sidebar
keywords: install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for SN2100 switches
summary: You can use this procedure to install the applicable configuration file for cluster switch health monitoring of NVIDIA SN2100 cluster switches.
---
= Install the Ethernet Switch Health Monitor configuration file
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to install the applicable configuration file for Ethernet switch health monitoring of NVIDIA cluster switches. 
Supported models are:

//* MSN2100-CB2FC
//* MSN2100-CB2RC
* X190006-PE
* X190006-PI

NOTE: The following installation procedure applies to ONTAP version 9.10.1 and later.

//In future patch releases the configuration file will be bundled with ONTAP. 

.Before you begin

* Verify that you need to download the configuration file by running `system switch ethernet show` and check if *OTHER* is shown for your model. 
+
If your model is still showing *OTHER*  after applying the configuration file, contact NetApp support. 
//* Make sure that the Ethernet switch health monitor process is running using `spm show -name cshmd`
* Make sure that the ONTAP cluster is up and running.
* Enable SSH to use all of the features available in CSHM.

.Steps

. Download the Ethernet switch health monitor configuration zip file based on the corresponding ONTAP release version. This file is available from the https://mysupport.netapp.com/site/info/nvidia-cluster-switch[NVIDIA Ethernet switches^] page.
 .. On the Software download page, select *Switch Health Monitor Configuration Files*
 .. Select Platform = *ONTAP* and click *Go!*
 .. On the Switch Health Monitor Configuration Files for ONTAP page, click *View & Download*
 .. On the Switch Health Monitor Configuration Files for ONTAP - Description page, click *Download* for the applicable cluster switch model, for example: *NVIDIA SN2100*
 .. On the End User License Agreement page, click *Accept*
 .. On the Switch Health Monitor Configuration Files for ONTAP - Download page, select the applicable configuration file, for example, *NVIDIA_SN2100.zip*

. Upload the applicable zip file to your internal web server.
+
For an internal web server IP address of 192.168.2.20 and assuming a /usr/download directory exists, you can upload your zip file to your web server using scp. For example: 
+
[subs=+quotes]
----
*% scp NVIDIA_SN2100C.zip admin@192.168.2.20:/usr/download/NVIDIA_SN2100.zip*
----

. Access the advanced mode setting from one of the ONTAP systems in the cluster.
+
`set -privilege advanced`
//+
//[subs=+quotes]
//----
//cluster1::> *set -privilege advanced*
//----

. Run the switch health monitor configure command.
+
[subs=+quotes]
----
cluster1::> *system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/NVIDIA_SN2100.zip*
----

. Verify the command output text as follows:

// start of tabbed content 

[role="tabbed-block"] 

==== 

.ONTAP 9.15.1 and later
--
Ethernet switch health monitoring installed the configuration file.
--

.ONTAP 9.11.1 through 9.14.1
--
SHM installed the configuration file.
--

.ONTAP 9.10.1
--
CSHM downloaded package processed successfully.
--
====

// end of tabbed content 

If an error occurs, contact NetApp support.

[start=6]
. [[step6]]Wait up to twice the Ethernet switch health monitor polling interval, found by running `system switch ethernet polling-interval show` before completing the next step.

. Run the command `system switch ethernet show` on the ONTAP system and make sure that the cluster switches are discovered with the monitored field set to *True* and the serial number field is not showing *Unknown*.
+
[subs=+quotes]
----
cluster1::> *system switch ethernet show*
----

//NOTE: If at any time you revert to an earlier version of ONTAP, you will need to install the CSHM configuration file again to enable switch health monitoring of NVIDIA cluster switches.


// Updates for AFFFASDOC-237, 2024-JUL-02