---
permalink: switch-nvidia-sn2100/setup-install-cshm-file.html
sidebar: sidebar
keywords: install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for SN2100 switches
summary: You can use this procedure to install the applicable configuration file for cluster switch health monitoring of NVIDIA SN2100 cluster switches.
---
= Install the Cluster Switch Health Monitor (CSHM) configuration file
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to install the applicable configuration file for cluster switch health monitoring of NVIDIA SN2100 cluster switches. 

NOTE: In ONTAP releases 9.5P7 and earlier and 9.6P2 and earlier, you must download the cluster switch health monitor configuration file separately. In ONTAP releases 9.5P8 and later, 9.6P3 and later, and 9.7 and later, the cluster switch health monitor configuration file is bundled with ONTAP.

.What you'll need

* Make sure that the ONTAP cluster is up and running.
* Enable SSH to use all the features available in CSHM.

.Steps

. Download the cluster switch health monitor configuration zip file based on the corresponding ONTAP release version. This file is available from the https://mysupport.netapp.com/site/info/nvidia-cluster-switch[NVIDIA SN2100 Software Download^] page.
 .. On the Software download page, select *Switch Health Monitor Configuration Files*
 .. Select Platform = *ONTAP* and click *Go!*
 .. On the Switch Health Monitor Configuration Files for ONTAP page, click *View & Download*
 .. On the Switch Health Monitor Configuration Files for ONTAP - Description page, click *Download* for the applicable cluster switch model, for example: *NVIDIA SN2100*
 .. On the End User License Agreement page, click *Accept*
 .. On the Switch Health Monitor Configuration Files for ONTAP - Download page, select the applicable configuration file, for example, *NVIDIA_SN2100.zip*

. Upload the applicable zip file to your internal web server where the IP address is X.X.X.X.
+
For an internal web server IP address of 192.168.2.20 and assuming a /usr/download directory exists, you can upload your zip file to your web server using scp:
+
[subs=+quotes]
----
*% scp NVIDIA_SN2100C.zip admin@192.168.2.20:/usr/download/NVIDIA_SN2100.zip*
----

. Access the advanced mode setting from one of the ONTAP systems in the cluster, using the command set-privilege advanced:
+
[subs=+quotes]
----
cluster1::> *set -privilege advanced*
----

. Run the switch health monitor configure command system cluster-switch configure-health-monitor -node * -package-url X.X.X.X/location_to_download_zip_file:
+
[subs=+quotes]
----
cluster1::> *system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/NVIDIA_SN2100.zip*
----

. Verify that the command output contains the text string *downloaded package processed successfully*. If an error occurs, contact NetApp support.
. Run the command `system switch ethernet show` on the ONTAP system and make sure that the cluster switches are discovered with the monitored field set to *True*.
+
[subs=+quotes]
----
cluster1::> *system switch ethernet show*
----

NOTE: If at any time you revert to an earlier version of ONTAP, you will need to install the CSHM configuration file again to enable switch health monitoring of SN2100 cluster switches.


// Updates for AFFFASDOC-237, 2024-JUL-02