---
permalink: switch-nvidia-sn2100/sn2100-overview.html
sidebar: sidebar
keywords: nvidia SN2100 switches
summary: If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.
---
= Overview and requirements: NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
For NVIDIA SN2100 switch installation and maintenance, be sure to review all requirements and recommended documentation. 

If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.

== ONTAP and Linux support

The NVIDIA SN2100 switch is a 10/25/40/100GbE switch running Cumulus Linux. The switch supports the following:

* ONTAP 9.10.1P3. The SN2100 switch serves Cluster and Storage applications in ONTAP 9.10.1P3 over different switch-pairs. From ONTAP 9.10.1P3, you can use NVIDIA SN2100 switches to combine storage and cluster functionality into a shared switch configuration.

* Cumulus Linux (CL) OS version 4.4.3. For current compatibility information, see the https://mysupport.netapp.com/site/info/nvidia-cluster-switch[NVIDIA Ethernet Switches^] information page.

* You can install Cumulus Linux when the switch is running Cumulus Linux or ONIE.


== Cabinet and rail kit details
You install the NVIDIA SN2100 switch (X190006/X190106) in the NVIDIA dual/single switch cabinet with the standard brackets that are included with the switch.

The following table lists the part number and description for the MSN2100 switches and rail kits:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
X190006-PE
a|
Cluster Switch, NVIDIA SN2100, 16PT 100GbE, PTSX
a|
X190006-PI
a|
Cluster Switch, NVIDIA SN2100, 16PT 100GbE, PSIN
a|
X190106-FE-PE
a|
Switch, NVIDIA SN2100, 16PT 100GbE, PTSX, Front End
a|
X190106-FE-PI
a|
Switch, NVIDIA SN2100, 16PT 100GbE, PSIN, Front End
a|
X-MTEF-KIT-D
a|
Rail Kit, NVIDIA Dual switch side by side
a|
X-MTEF-KIT-E
a|
Rail Kit, NVIDIA Single switch short depth
|===

NOTE: See NVIDIA documentation for details on https://docs.nvidia.com/networking/display/sn2000pub/Installation[installing your SN2100 switch and rail kit^].

== Available documentation
The following table lists the documentation available for the NVIDIA SN2100 switches.

[options="header" cols="1,2"]
|===
| Title | Description
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html[_Setup and configure your NVIDIA SN2100 switches_^]
a|
Describes how to setup and configure your NVIDIA SN2100 switches, including installing Cumulus Linux and applicable RCFs.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-sn2100-cluster-switch.html[_Migrate from a Cisco cluster switch to a NVIDIA SN2100 cluster switch_^]
a|
Describes how to migrate from environments that use Cisco cluster switches to environments that use NVIDIA SN2100 cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-storage-switch-sn2100-storage.html[_Migrate from a Cisco storage switch to a NVIDIA storage switch_^]
a|
Describes how to migrate from environments that use Cisco storage switches to environments that use NVIDIA SN2100 storage switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html[_Migrate to a two-node switched cluster with NVIDIA SN2100 cluster switches_^]
a|
Describes how to migrate to a two-node switched environment using NVIDIA SN2100 cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-cluster.html[_Replace a NVIDIA SN2100 cluster switch_^]
a|
Describes the procedure to replace a defective NVIDIA SN2100 switch in a cluster and download Cumulus Linux and reference configuration file.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-storage.html[_Replace a NVIDIA SN2100 storage switch_^]
a|
Describes the procedure to replace a defective NVIDIA SN2100 storage switch and download Cumulus Linux and reference configuration file.
|===

// GH issue #77 replacing 4.4.2 with 4.4.3, 2023-FEB-22
// Updated content as part of the LH release of CL 5.4, 2023-APR-17