---
permalink: switch-cisco-9336c-fx2-storage/configure-switch-overview-9336c-storage.html
sidebar: sidebar
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch
summary: 'Overview of installation and configuration for Cisco Nexus 9336C-FX2 storage switches'
---
= Overview of installation and configuration for Cisco Nexus 9336C-FX2 storage switches
:icons: font
:imagesdir: ../media/

[.lead]
The Cisco Nexus 9336C-FX2 switch is part of the Cisco Nexus 9000 platform and can be installed in a NetApp system cabinet. The Nexus 9336C-FX2 is an Ethernet switch that allows you to switch data between controllers and disk shelves.

== Initial configuration overview

To initially configure a Cisco Nexus 9336C-FX2 switch on systems running ONTAP, follow these steps:

. link:setup-worksheet-9336c-storage.html[Complete cabling worksheet]. 
+
The sample cabling worksheet provides examples of recommended port assignments from the switches to the controllers. The blank worksheet provides a template that you can use in setting up your cluster.
. link:install-9336c-storage.html[Install the switch].
+
Set up the switch hardware.
. link:setup-switch-9336c-storage.html[Configure the switch].
+
Set up the Cisco Nexus 9336C-FX2 storage switch.
. link:install-switch-and-passthrough-panel-9336c-storage.html[Install the switch in a NetApp cabinet]. 
+
Depending on your configuration, you can install the Cisco Nexus 9336C-FX2 switch and pass-through panel in a NetApp cabinet with the standard brackets that are included with the switch.
. link:install-nxos-overview-9336c-storage.html[Prepare to install or upgrade NX-OS and RCF]. 
+
Follow preliminary procedures in preparation for installing the Cisco NX-OS software and reference configuration files (RCFs).
. link:install-nxos-software-9336c-storage.html[Install or upgrade the NX-OS software]. 
+ 
Install or upgrade the NX-OS software on the Nexus 9336C-FX2 storage switch.
. link:install-rcf-software-9336c-storage.html[Install or upgrade the RCF config file]. 
+
Install or upgrade the RCF after setting up the Nexus 9336C-FX2 switch for the first time. You can also use this procedure to upgrade your RCF version.

== Additional information

Before you begin installation or maintenance, be sure to review the following:

* link:configure-reqs-9336c-storage.html[Configuration requirements]
* link:components-9336c-storage.html[Components and part numbers]
* link:required-documentation-9336c-storage.html[Required documentation]
* link:smart-call-9336c-storage.html[Smart Call Home requirements]

// Updated as part of Jackie's review for AFFFASDOC-216/217, 2024-JUL-25
// Updates for AFFFASDOC-115, 2024-SEP-18
// Updates for AFFFASDOC-283, 2025-JAN-28
// Updates for AFFFASDOC-315, 2025-MAR-26