---
permalink: switch-cisco-9336c-fx2-storage/configure-software-overview-9336c-storage.html
sidebar: sidebar
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch
summary: 'Overview of software configuration for Cisco Nexus 9336C-FX2 storage switches'
---
= Software install workflow for Cisco Nexus 9336C-FX2 storage switches
:icons: font
:imagesdir: ../media/

[.lead]

To install and configure software for a Cisco Nexus 9336C-FX2 storage switch, follow these steps:

. link:install-nxos-overview-9336c-storage.html[Prepare to install or upgrade NX-OS and RCF]. 
+
The Cisco NX-OS software and reference configuration files (RCFs) must be installed on Cisco Nexus 9336C-FX2 storage switches.
. link:install-nxos-software-9336c-storage.html[Install or upgrade the NX-OS software]. 
+
Download and install or upgrade the NX-OS software on the Cisco Nexus 9336C-FX2 storage switch.
. link:install-rcf-software-9336c-storage.html[Install or upgrade the RCF config file].
+
Install or upgrade the RCF after setting up the Cisco Nexus 9336C-FX2 storage switch for the first time. You can also use this procedure to upgrade your RCF version.

// Updated as part of Jackie's review for AFFFASDOC-216/217, 2024-JUL-25
// Updates for GH issue #187, 2025-JAN-08
// Updates for AFFFASDOC-283, 2025-JAN-28
// Updates for AFFFASDOC-315, 2025-MAR-26