---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2
summary: 'You can install the RCF after setting up the Nexus 9336C-FX2 switch for the first time. You can also use this procedure to upgrade your RCF version.'
---
= Install or upgrade the Reference Configuration File (RCF) overview
:icons: font
:imagesdir: ../media/

[.lead]
You install the Reference Configuration File (RCF) after setting up the Nexus 9336C-FX2 storage switch for the first time. You upgrade your RCF version when you have an existing version of the RCF file installed on your switch. 

See the Knowledge Base article link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity[How to clear configuration on a Cisco interconnect switch while retaining remote connectivity^] for further information when installing or upgrading your RCF.

Storage (Storage RCF 1._xx_) is the available RCF configuration where all ports are configured for 100GbE NVMe storage connections.


.Suggested documentation
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches^]
+
Consult the switch compatibility table for the supported ONTAP and RCF versions on the NetApp Support Site. Note that there can be command dependencies between the command syntax in the RCF and the syntax found in specific versions of NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches^]
+
Refer to the appropriate software and upgrade guides available on the Cisco website for complete documentation on the Cisco switch upgrade and downgrade procedures.

.About the examples
The examples in this procedure use the following switch and node nomenclature:

* The names of the two Cisco switches are s1 and s2.
* The node names are cluster1-01 and cluster1-02.

See the https://hwu.netapp.com/SWITCH/INDEX[Hardware Universe^] to verify the correct ports on your platform.

NOTE: The command outputs might vary depending on different releases of ONTAP.

.Commands used
The procedure requires the use of both ONTAP commands and Cisco Nexus 9000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

.What's next?

After you've reviewed the install RCF or upgrade RCF procedure, you can link:install-rcf-software-9336c-storage.html[install the RCF] or link:upgrade-rcf-software-9336c-storage.html[upgrade your RCF] as needed.

// AFFFASDOC-289, 2025-NOV-05
// AFFFASDOC-458, 2026-FEB-03