---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-overview-9336c-storage.html
sidebar: sidebar
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2
summary: The Cisco NX-OS software and reference configuration files \(RCFs\) must be installed on Cisco Nexus 9336C-FX2 cluster switches.
---
= Prepare to install or upgrade NX-OS software and RCF

:icons: font
:imagesdir: ../media/

[.lead]
Before you install the NX-OS software and the Reference Configuration File (RCF), follow this procedure.

.About the examples
The examples in this procedure use the following switch and node nomenclature:

* The names of the two Cisco switches are s1 and s2.
* The node names are cluster1-01 and cluster1-02.
//* The cluster LIF names are cluster1-01_clus1 and cluster1-01_clus2 for cluster1-01 and cluster1-02_clus1 and cluster1-02_clus2 for cluster1-02.
//* The `cluster1::*>` prompt indicates the name of the cluster.

.About this task
The procedure requires the use of both ONTAP commands and Cisco Nexus 9000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

.Steps

. If AutoSupport is enabled, suppress automatic case creation by invoking an AutoSupport message: `system node autosupport invoke -node * -type all -message MAINT=x h`
+
where x is the duration of the maintenance window in hours.
+
NOTE: The AutoSupport message notifies technical support of this maintenance task so that automatic case creation is suppressed during the maintenance window.

. Change the privilege level to advanced, entering *y* when prompted to continue:
+
[source,cli]
----
set -privilege advanced
----
+
The advanced prompt (`*>`) appears.

. Display how many cluster interconnect interfaces are configured in each node for each cluster interconnect switch: 
+
[source,cli]
----
network device-discovery show -protocol lldp
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/lldp
            e0a    s1                        Eth1/2            N9K-C9336C
            e0b    s2                        Eth1/2            N9K-C9336C
cluster1-01/lldp
            e0a    s1                        Eth1/1            N9K-C9336C
            e0b    s2                        Eth1/1            N9K-C9336C
4 entries were displayed.
----
====

. Check the administrative or operational status of each node storage port and storage shelf port.

.. Display the node storage port attributes: 
+
[source,cli]
----
storage port show
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e0a  ENET  storage    100 enabled  online      -
               e0b  ENET  storage    100 enabled  online      -
cluster1-02

               e0a  ENET  storage    100 enabled  online      -
               e0b  ENET  storage    100 enabled  online      -
4 entries were displayed.
----
====

.. Display the storage shelf port attributes:
+
[source,cli]
----
storage shelf port show
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
4 entries were displayed.
----
====

.. Verify that switch health monitoring (CSHM) is enabled for the switch so that the switches are monitored:
+
[source,cli]
----
system switch ethernet show 
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----

----
====

.What's next?
After you've prepared to install the NX-OS software and RCF, you can link:install-nxos-software-9336c-storage.html[install or upgrade the NX-OS software].


// Updated for AFFFASDOC-216, 217, 2024-JUL-30
// Updates for AFFFASDOC-207, 2024-MAY-21
// Updates for GH issue #212. 20204-OCT-17
// Updates for GH issue #86, 2025-JAN-09
// Updates for AFFFASDOC-315, 2025-MAR-26
// AFFFASDOC-380, 2025-SEPT-03
// AFFFFASDOC-458, 2026-FEB-03