---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html
sidebar: sidebar
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2
summary: Replacing a defective Nexus 9336C-FX2 switch in a cluster network is a nondisruptive procedure \(NDU\).
---
= Replace Cisco Nexus 9336C-FX2 and 9336C-FX2-T storage switches
:icons: font
:imagesdir: ../media/

[.lead]
You can replace defective Nexus 9336C-FX2 and 9336C-FX2-T switches in a cluster network. This is a nondisruptive procedure.

.Before you begin
Before installing the NX-OS software and RCFs on Cisco Nexus 9336C-FX2 and 9336C-FX2-T storage switches, ensure that:

* Your system can support Cisco Nexus 9336C-FX2 and 9336C-FX2-T storage switches.
* You have consulted the switch compatibility table on the Cisco Ethernet Switch page for the supported ONTAP, NX-OS, and RCF versions.
* You have referred to the appropriate software and upgrade guides available on the Cisco web site.

* You have downloaded the applicable RCFs.
* The existing network configuration has the following characteristics:

** The Cisco Ethernet Switches page has the latest RCF and NX-OS versions on your switches.
** Management connectivity must exist on both switches.
* The replacement Cisco Nexus 9336C-FX2 switch has the following characteristics:
** Management network connectivity is functional.
** Console access to the replacement switch is in place.
** The appropriate RCF and NX-OS operating system image is loaded onto the switch.
** Initial configuration of the switch is complete.

.About this task
This procedure replaces the second Nexus 9336C-FX2 storage switch s2 with the new 9336C-FX switch ns2. The two nodes are cluster1-01 and cluster1-02.

Steps to complete:

* Confirm the switch to be replaced is s2.
* Disconnect the cables from switch s2.
* Reconnect the cables to switch ns2.
* Verify all device configurations on switch ns2.

+
NOTE: There can be dependencies between command syntax in the RCF and NX-OS versions.

.Steps
. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`
+
_x_ is the duration of the maintenance window in hours.
+
. Check on the health status of the storage node ports to make sure that there is connection to storage switch s1:
+
`storage port show -port-type ENET`
+
.Show example 
[%collapsible]
====
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====

. Verify that storage switch s1 is available:
+
`network device-discovery show`
+
.Show example 
[%collapsible]
====
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====

. Run the show `lldp neighbors` command on the working switch to confirm that you can see both nodes and all shelves:
+
`show lldp neighbors`
+
.Show example 
[%collapsible]
====
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====

. Verify the storage shelf ports in the storage system:
+
`storage shelf port show -fields remote-device,remote-port`
+
.Show example 
[%collapsible]
====
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====

. Remove all cables attached to storage switch s2.
. Reconnect all cables to the replacement switch ns2.
. Recheck the health status of the storage node ports:
+
`storage port show -port-type ENET`
+
.Show example 
[%collapsible]
====
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
+
. Verify that both switches are available:
+
`network device-discovery show`
+
.Show example 
[%collapsible]
====
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====

. Verify the shelf ports in the storage system:
+
`storage shelf port show -fields remote-device,remote-port`
+
.Show example 
[%collapsible]
====
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. If you suppressed automatic case creation, re-enable it by invoking an AutoSupport message:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

.What's next?
After you've replaced your switches, you can link:../switch-cshm/config-overview.html[configure switch health monitoring].

// Updated as part of AFFFASDOC-216, 217, 2024-JUL-30
// AFFFASDOC-380, 2025-SEPT-03
// AFFFASDOC-458, 2026-FEB-17