---
permalink: switch-cisco-9808/configure-install-rcf-9808.html
sidebar: sidebar
keywords: install rcf, cisco switches
summary: You install the RCF on new Cisco Nexus 9808 switch(es) as part of a new AFX 2K system installation and setup, replacing a faulty switch, or resetting a switch to factory default settings.
---
= Install the RCF - Cisco Nexus 9808
:icons: font
:imagesdir: ../media/

[.lead]
You install the RCF on new Cisco Nexus 9808 switch(es) as part of a new AFX 2K system installation, replacing a switch, or a switch reset to factory default settings.

.Before you begin

* The switch(es) must be powered on and you must have completed the link:configure-complete-initial-setup-9808.html[Complete initial switch setup] procedure.

* You must have installed the desired NX-OS version using the link:configure-install-nxos-9808.html[Install the NX-OS] procedure.

* You must have read the link:configure-install-upgrade-rcf-overview-9808.html[Install or upgrade RCF overview] page.

* If you are installing the RCF on a switch as part of a switch replacement or a switch reset to factory default settings, verify that your cluster is fully functional, meaning that there are no errors in the logs or similar issues.
+
If you are installing the RCF as part of a new AFX system installation, you can skip this requirement because the controllers in your AFX system are not powered on at this point in your AFX system installation and setup.


.About this task

* If you have installed switches as part of a new AFX 2K system installation, this procedure has you install the RCF on the first switch (cs1) and then has you repeat the steps for the second switch (cs2).

* This procedure only requires the use of Cisco Nexus 9000 Series Switches commands.

* The examples in this procedure refer to the first switch as cs1 and the second switch as cs2.

* The examples shown in this procedure are for AFX 1K systems with switches running RCF 10.0. If you have an AFX 2K system, the input and output can vary.


== Step 1: Prepare to install the RCF

Prepare to install the RCF on the switch(es) by making sure you have the necessary connections to download the RCF, and then download the RCF.

.Steps

. You must have access to an HTTP, FTP, or TFTP server. Access to one of these servers allows you to download a supported version of the RCF.

. Download the RCF supported for your type of AFX system from the NetApp Support Site at link:http://mysupport.netapp.com/[mysupport.netapp.com^]. 
+
NOTE: New switches do not ship with the RCF installed. You must install the RCF on the switches.

. Each switch must be connected to a console or you must have remote access to each switch.

. You must be connected to the switches using the serial console or have preserved basic configuration information. This is because the RCF upgrade procedure requires you to erase the switch settings and perform basic configuration.
//+
// Hey, this step 4 above is from Upgrade RCF, but does it apply here too because the `write erase` command is also used to Install RCF (step 9)? It's similar to step 3 above.


== Step 2: Install the RCF
You install the RCF on the first switch (cs1) by copying and applying the RCF to the bootflash, examining the banner output, verifying the RCF version is correct, recording any custom additions, saving basic configuration details, verifying that the write_erase.cfg file is populated, erasing the current saved configuration, copying the previously saved basic configuration into the startup configuration, and then rebooting the switch. You repeat these steps on the second switch (cs2) if you are installing the RCF as part of a new AFX system installation.

. Login to switch cs1 using SSH or by using a serial console.

. Copy the RCF to the bootflash of switch cs1 using one of the following transfer protocols: FTP, TFTP, SFTP, or SCP. 
+
For more information on Cisco commands, refer to the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.
+
`copy <protocol>: bootflash: vrf management`
+
.Show example 
[%collapsible]
====
This example shows TFTP being used to copy an RCF to the bootflash on switch cs1:

[subs=+quotes]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9808-RCF-v10.1 1-Cluster 1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====

. Apply the RCF previously copied to the bootflash.
//This steps is where installation of the RCF happens.
+
For more information on Cisco commands, refer to the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.
+
This example shows the RCF file `NX9808-RCF-v10.1 1-Cluster 1-Storage.txt` being installed on switch cs1:
+
[subs=+quotes]
----
cs1# *copy NX9808-RCF-v10.1 1-Cluster 1-Storage.txt running-config echo-commands*
----
+
//NOTE: For RCF 10.1 and later, the file name format is different: `RCF-v10.1-NX9332D-GX2B-CL1.txt`.

. Examine the banner output from the `show banner motd` command. You must read and follow these instructions to ensure the proper configuration and operation of the switch.
+
.Show example 
[%collapsible]

[subs=+quotes]
====
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9808
* Filename : NX9808-RCF-v10.1 1-Cluster 1-Storage.txt
* Date     : 04-11-2026
* Version  : v10.1
* Port Usage:
* Ports   1-18 (LC1-LC8) : 400GbE Cluster/Storage/HA ports.
* Ports   19-35 (LC1-LC8): 4 * 100 GbE Storage shelf ports, int e1-e8/{19-35}/1-4
* Port    36 (LC1-LC8)   : Intra-Cluster ISL Ports, int e1-e8/36
* IMPORTANT NOTES
* Interface port-channel998/9 is reserved to identify the version of this file.

******************************************************************************
----
====

. Verify that the RCF file is the correct version: 
+
`show running-config`
+
When you check the output to verify you have the correct RCF, make sure that the following information is correct:

 ** The RCF banner
 ** The node and port settings
 ** Customizations
+
The output varies according to your site configuration. Check the port settings and refer to the release notes for any changes specific to the RCF that you have installed.

. If your switches have RCF 10.1 or later installed, complete the following substeps if needed:

.. Record any custom additions between the current `running-config` file and the RCF file in use.
+
You can link:configure-install-upgrade-rcf-overview-9332d.html#change-port-speed-configuration[change the port speed configuration] for RCF 10.1 as needed.

.. After you verify that the RCF versions, custom additions, and switch settings are correct, copy the `running-config` file to the `startup-config` file.
+
----
cs1# copy running-config startup-config [########################################] 100% Copy complete
----

. Save basic configuration details to the `write_erase.cfg` file on the bootflash.
+
[NOTE]
====================================
Make sure to configure the following:

* Username and password
* Management IP address
* Default gateway
* Switch name
====================================
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`
+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`
+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`
+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`
+
Refer to the Knowledge Base article link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity[How to clear configuration on a Cisco interconnect switch while retaining remote connectivity^] for further details.

. Verify that the `write_erase.cfg` file is populated as expected:
+
`*show file bootflash:write_erase.cfg*`

. Issue the `write erase` command to erase the current saved configuration:
+
`cs1# *write erase*`
+
`Warning: This command will erase the startup-configuration.`
+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copy the previously saved basic configuration into the startup configuration.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Reboot the switch:
+
`cs1# *reload*`
+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repeat these steps on switch cs2.


.What's next?

After you've installed the RCF in your switch(es), you link:configure-verify-ssh-9808.html[verify SSH for log collection].

// New content for Organza (9808) project, 2026-JUN-08