---
permalink: switch-cisco-9808/configure-verify-ssh-9808.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9808
summary: If you are configuring your switches as part of a new AFX 2K system installation, a switch replacement, or a reset to factory default settings, and you want to use the Cluster Switch Health Monitor (CSHM) and log collection features, you must verify that SSH and SSH keys are enabled on the switches.
---
= Verify SSH for log collection - Cisco Nexus 9808
:icons: font
:imagesdir: ../media/

[.lead]
If you are configuring your switches as part of a new AFX 2K system installation, a switch replacement, or a reset to factory default settings, to use the Ethernet switch health monitor(CSHM) log collection feature, you must verify that SSH is enabled on the switches.


.Before you begin
You must be connected to the switch using the serial console.


.Steps

. Verify that SSH is enabled:
+ 

[subs=+quotes]
----
(switch) *show ssh server*
ssh version 2 is enabled
----

. Verify that the SSH keys are enabled:
+
`show ssh key`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(switch)# *show ssh key*

**************************************
rsa Keys generated:Wed May 14 18:49:37 2025

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCndfdJesautdCwk5Mk/7pKOFl0IeShc9uBtj74F52vbjyf1FHOCXX7Xf3Vopxs6L1hbzgCpFLo9E7pZBd3I+1AoLyQULtR3svzNieGY8mlWZGLtpKf/P2fDCd8JVJaejrwQhm49WUPiC6ziEqBDMOGhJpD2e9++umyDdr6
NbmK8Q==


bitcount:1024
fingerprint:
SHA256:QtNU+Qq2I4ZfYwEfMEB1+z8w7xaKTlantTdsjLBx+OU
**************************************
could not retrieve dsa key information
**************************************
ecdsa Keys generated:Wed May 14 18:50:56 2025


ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAYnv17T+JlGmH8rg81xiOow0mPmkbkIG0o7h9EchixO3i3KjgQr8AwqkRHNTcQC3lRnizhJFUeMGCwuQTurziRCwE6fAOkWa2MRyXA1DYRKKXjVEOnW9+MvinMipHQ0cCc
YSExhh7j4HvWHIuYv8RmD7e3rmDQFlyyiLwdmpGfas2yaw==


bitcount:521
fingerprint:
SHA256:7cpZ5NGnIq5Iamw67ke+9o4qG9D3xxmGPauVl4X5934
**************************************

(switch)# *show feature | include scpServer*
scpServer              1          enabled
(switch)# *show feature | include ssh*
sshServer              1          enabled
(switch)#
----
====

.What's next?

* After you've verified SSH is enabled for log collection, you link:../switch-cshm/cshm-overview.html[configure Ethernet switch health monitoring].

** After you've configured Ethernet switch health monitoring, if you want to take advantage of Cisco's Smart Call Home support feature, you link:configure-smart-call-9332d.html[configure Smart Call Home].

* If you configured your switch as part of a new AFX 2K system installation, you must link:install-complete-afx-setup-9808.html[complete the AFX system setup].


// New content for Organza (9808) project, 2026-JUN-08