---
permalink: switch-cisco-9808/configure-install-upgrade-rcf-overview-9808.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9808
summary: You can install or upgrade the reference configuration file (RCF) on your Nexus 9808 switches. You install a supported version of the RCF on the switches as part of a new AFX 2K system installation, a supervisor module replacement, or a switch reset to factory default settings. You upgrade to a supported version of the RCF on the switches to support new hardware, a new ONTAP version, or to align with a new NX-OS version in your AFX 2K system configuration.
---
= Install or upgrade the RCF overview - Cisco Nexus 9808
:icons: font
:imagesdir: ../media/

[.lead]
You can install or upgrade the reference configuration file (RCF) on your Nexus 9808 switches. You install a supported version of the RCF on the switches as part of a new AFX 2K system installation, a supervisor module replacement, or a switch reset to factory default settings. You upgrade to a supported version of the RCF on the switches to support new hardware, a new ONTAP version, or to align with a new NX-OS version in your AFX system configuration.

NOTE: RCF installation or upgrade is independent of NX-OS installation or upgrade. If you are installing or upgrading both the NX-OS and RCF, it is recommended you install or upgrade NX-OS first. 


=== Understand the supported RCF versions
The version of ONTAP running on your AFX system and version of NX-OS on your switches determines the supported versions of RCF for your switches. RCF versions have preset port speed configurations that determine how many switch ports are in breakout mode (4x100GbE) and non-breakout mode.

[NOTE]
====
For the current list of supported RCF versions, refer to link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^].

Switch port information can also be found in the link:https://hwu.netapp.com[NetApp Hardware Universe^].
====

NOTE: For specific port and VLAN usage details, refer to the banner and important notes section in your RCF. Refer to link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^] for more information.

For example, the following table shows the preset groups of the switch ports, their port speeds, and usage based on RCF version 10.1.

//Filename : RCF-v10.1-NX9808-CL1-ST1.txt

[options="header" cols="1,2"]
|===
| Switch port groups | Port speeds and usage
a|
Ethernet1/1 to Ethernet1/18
a|
400GbE mode for Intra-cluster, HA, and storage shelf connections 
//The term "shelf" can only be listed when this table is applicable to 2K only. Does not apply to 1K.
a|
Ethernet1/19 to Ethernet1/35
a|
4x100GbE mode for Intra-cluster, HA, and storage connections 
a|
Ethernet1/36
a|
400GbE Intra-cluster ISL connections
|===

=== Change port speed configuration

For switches with RCF 10.1 and later, you can change the port speed configuration to adjust the number of switch ports in breakout mode (4x100GbE) and non-breakout mode (400GbE) when you need to accommodate a different port speed configuration for your AFX system. Any port modifications made are made per line card(s) currently in use. 

You perform this change as part of the RCF installation or RCF upgrade procedure. The procedures have steps that link you to this page.

You enter the commands on both switches.

[options="header" cols="1,2"]
|===
| Change port speeds | Steps
a|
Change non-breakout ports to breakout ports
a|
. Enter config mode in the CLI.
. Modify port speeds and breakout modes on the switches:
+
To designate breakout ports, use the `interface breakout module` command. 
+
For example, to designate 400GbE mode ports 19-22 as breakout (4x100GbE) ports, use the following: 
+
`interface breakout module 1 port 19-22 map 100g-4x`

. Modify the port list with the new ports that need to use the port profile for the desired port speed.
+ 
For example, to modify the port list with the new ports,  19-22, for the 100G speed port profile, use the following: 
+
`interface e1/19/1-4, e1/20/1-4, e1/21/1-4, e1/22/1-4`

. Hard-code the switch breakout (4x100GbE) ports for 100GbE. If you do not hard-code the speed, the ports will not come up and will be in an error-disabled state.
+
`speed 100000`
+
`no negotiate auto`

a|
Return breakout ports to non-breakout ports
a|
. Enter config mode in the CLI.

. To return breakout ports to non-breakout ports, use the `no interface breakout` command in config mode. 
+
For example, to return ports 19-22 to 400GbE mode, use the following: 
+
`no interface breakout module 1 port 19-22` 
|===

=== Suggested documentation
Before you install or upgrade the RCF on your switches, it is recommended you review the following documentation:

* Refer to the NetApp Knowledge Base article link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity[How to clear configuration on a Cisco interconnect switch while retaining remote connectivity^] for further information when installing or upgrading your RCF.

* Refer to the https://hwu.netapp.com/SWITCH/INDEX[Hardware Universe^] to verify the correct ports on your platform.

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches (NSS)^]
+
Consult the switch compatibility table for the supported ONTAP and RCF versions on the NetApp Support Site. Note that there can be command dependencies between the command syntax in the RCF and the syntax found in specific versions of NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches^]
+
Refer to the appropriate software and upgrade guides available on the Cisco website for complete documentation on the Cisco switch upgrade and downgrade procedures.


.What's next?

After you've reviewed the install or upgrade RCF overview, you link:configure-install-rcf-9808.html[install the RCF] or link:configure-upgrade-rcf-9808.html[upgrade the RCF] as needed.


// New content for Organza (9808) project, 2026-JUN-08


