---
permalink: switch-cisco-9808/install-complete-afx-setup-9808.html
sidebar: sidebar
keywords: switches, complete system setup, Cisco Nexus, 9808 switches, AFX
summary: "Complete the AFX 2K system setup after finishing Cisco Nexus 9808 switch configuration."
---
= Complete the AFX system setup for the Cisco Nexus 9808 switch
:icons: font
:imagesdir: ../media/

[.lead]
After completing Cisco Nexus 9808 switch configuration, power on the storage shelves and controllers, verify switch connectivity, and complete the AFX 2K system setup.

.Before you begin
* You must have completed the switch configuration procedures in the link:configure-switch-workflow-9808.html[configure switch workflow]. 

* Each switch must be connected to a console or you must have remote access to each switch.


.Step

. Complete the power on and setup steps for your AFX 2K system by using the link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/power-on-hardware.html[Power on your AFX 2K storage system^] procedure.



.What's next?

After you've powered on the storage shelves and controllers and completed the AFX 2K system setup, you are ready to use your AFX system.


// New content for Organza (9808) project, 2026-JUN-08