---
permalink: switch-cisco-9808/maintain-replace-supervisor-module-9808.html
sidebar: sidebar
keywords: replacing, replace, defective, Cisco Nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a Cisco Nexus 9808 supervisor module - Cisco Nexus 9808
summary: "Replacing a defective Cisco Nexus 9808 supervisor module is a nondisruptive procedure."
---
= Replace a supervisor module - Cisco Nexus 9808
:icons: font
:imagesdir: ../media/

[.lead]
Follow these steps to replace a defective supervisor module in a cluster network. This is a nondisruptive procedure (NDU)

== Review requirements

Before performing the supervisor module replacement, make sure that: 

* You have verified the supervisor module serial number to ensure that the correct module is replaced. 
* You have executed the command for migrating a cluster LIF from the node where the cluster LIF is hosted.

* If you are replacing a module that is currently in the chassis, verify that the new Supervisor module is running the same version of NX-OS as the other Supervisor module. If the new Supervisor module is not running the same version of NX-OS, upgrade the new Supervisor module to the same version of NX-OS as the other Supervisor module. Refer to link:configure-install-nxos-9808.html[Install NX-OS] for instructions on how to upgrade NX-OS on your switch.

* If you are replacing a module that is currently in the chassis, verify that the new Supervisor module is running the same version of RCF as the other Supervisor module. If the new Supervisor module is not running the same version of RCF, install the same version of RCF on the new Supervisor module as the other Supervisor module. Refer to link:configure-install-rcf-9808.html[Install the RCF] for instructions on how to install the RCF on your switch.


== Enable console logging
NetApp strongly recommends that you enable console logging on the devices that you are using and take the following actions when replacing your supervisor module:

* Leave AutoSupport enabled during maintenance.
* Trigger a maintenance AutoSupport before and after maintenance to disable case creation for the duration of the maintenance. Refer to this Knowledge Base article https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92[SU92: How to suppress automatic case creation during scheduled maintenance windows^] for further details.
* Enable session logging for any CLI sessions. For instructions on how to enable session logging, review the "Logging Session Output" section in this Knowledge Base article https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems[How to configure PuTTY for optimal connectivity to ONTAP systems^].

== Replace the supervisor module

.About the examples
The examples in this procedure use the following switch and node nomenclature:

* The names of the existing Nexus 9808 switches are cs1 and cs2.
* The name of the new Nexus 9808 switch is nsm-cs1.
* The node names are node1-01, node1-02, node1-03, and node1-04.
* The cluster LIF names are node1-01_clus1 and node1-01_clus2 for node1-01, node1-02_clus1 and node1-02_clus2 for node1-02, node1-03_clus1 and node1-03_clus2 for node1-03, and node1-04_clus1 and node1-04_clus2 for node1-04.
* The prompt for changes to all cluster nodes is cluster1::*>

=== Step 1: Prepare for replacement

. Open the packaging for the new Supervisor module, inspect the module for damage, and verify that the module is the same type as the other Supervisor module installed in the chassis.

. Remove the existing module from the chassis as detailed in the link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide/m-8000-replace-chassis-components.html#task_dqf_spp_13b[Replace a Supervisor module^] section of the Cisco Nexus 9808 NX-OS Mode Switch Hardware Installation Guide.

. Using the switch CLI, in EXEC mode, verify that the status of the module is `shut down` using the `show module` command.
+
.Show example 
[%collapsible]
====
[subs=+quotes]

----
cs1# *show module*  
Mod Ports       Module-Type                    Model                   Status
--- ----- ------------------------------------ ----------------------- ------       
27   0       Supervisor Module                 N9K-C9800-SUP-A         shut down *  
-    -       Supervisor Module                 -                       -

Mod  Sw                       Hw    Slot
---  ----------------------- ------ ----
27   10.6(3)                  1.0    SUP1
-    -                        -      -


Mod  MAC-Address(es)                         Serial-Num
---  --------------------------------------  ----------
27   14-bc-68-e7-93-f0 to 14-bc-68-e7-93-f7  FVH1XXXXXXX
28   --                                      -


Mod  Online Diag Status
---  ------------------
27   Pass
-    -

 
27   0    Supervisor Module                N9K-C9800-SUP-A       shut down*  
28   -        -                                 -                -
----
====

. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message: 
+
`system node autosupport invoke -node * -type all -message MAINT=xh`
+
where x is the duration of the maintenance window in hours.
+
NOTE: The AutoSupport message notifies technical support of this maintenance task so that automatic case creation is suppressed during the maintenance window.
. Install the appropriate RCF and image on the new supervisor module, and make any necessary site preparations.
+
If necessary, verify, download, and install the appropriate versions of the RCF and NX-OS software for the new supervisor module. If you have verified that the new supervisor module is correctly set up and does not need updates to the RCF and NX-OS software, continue to step 2.

 .. Go to the _NetApp Cluster and Management Network Switches Reference Configuration File Description Page_ on the NetApp Support Site.
 .. Click the link for the _Cluster Network and Management Network Compatibility Matrix_, and then note the required switch software version.
 .. Click your browser's back arrow to return to the Description page, click *CONTINUE*, accept the license agreement, and then go to the Download page.
 .. Follow the steps on the Download page to download the correct RCF and NX-OS files for the version of ONTAP software you are installing.

. On the new supervisor module, log in as admin and shut down all of the ports that will be connected to the node cluster interfaces:
+
.Show example 
[%collapsible]
====
[subs=+quotes]

----
cs1# *config terminal*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-18*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4,e1/33/1-4,e1/34/1-4,e1/35/1-4*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
====
+
If the supervisor module that you are replacing is not functional and is powered down, go to 7. The LIFs on the cluster nodes should have already failed over to the other cluster port for each node.

. Verify that all cluster LIFs have auto-revert enabled: 
+
[source,cli]
----
network interface show -vserver Cluster -fields auto-revert
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

             Logical
Vserver      Interface        Auto-revert
------------ ---------------- -------------
Cluster      node1-01_clus1   true
Cluster      node1-01_clus2   true
Cluster      node1-02_clus1   true
Cluster      node1-02_clus2   true
Cluster      node1-03_clus1   true
Cluster      node1-03_clus2   true
Cluster      node1-04_clus1   true
Cluster      node1-04_clus2   true
----
====

. Verify the connectivity of the remote cluster interfaces: 

.. You can use the `network interface check cluster-connectivity show` command to display the details of an accessibility check for cluster connectivity:
+
[source,cli]
----
network interface check cluster-connectivity show
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01  
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02  
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====

.. Alternatively, you can also use the `cluster ping-cluster -node <node-name>` command to check the connectivity:
+
`cluster ping-cluster -node <node-name>`
+

.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====

=== Step 2: Configure cables and ports
. Shut down the ISL port 1/36 on cs1.
+

[subs=+quotes]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/36*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----

. Remove all of the cables from the old supervisor module, and then connect them to the same ports on the new supervisor module.
. Bring up the ISLs port 1/36 and then verify the port channel operation status.
+
Port-Channel should indicate Po1(SU) and Member Port should indicate Eth1/36(P).
+
.Show example 
[%collapsible]
====
This example enables ISL port 1/36 and displays the port channel summary on switch cs1:

[subs=+quotes]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/36*
cs1(config-if-range)# *no shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
cs1#
cs1(config-if-range)# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
11     Po1(SU)     Eth      LACP      Eth1/36(P)
999    Po999(SD)   Eth      NONE      --
----
====

. Bring up all of the ports on the new supervisor module, nsm-cs1.
+
.Show example 
[%collapsible]
====
[subs=+quotes]

----
nsm-cs1# *config terminal*
Enter configuration commands, one per line. End with CNTL/Z.
nsm-cs1(config)# *interface e1/1-18*
nsm-cs1(config-if-range)# *no shutdown*
nsm-cs1(config)# *interface e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4,e1/33/1-4,e1/34/1-4,e1/35/1-4*
nsm-cs1(config-if-range)# *no shutdown*
nsm-cs1(config-if-range)# *exit*
nsm-cs1(config)# *exit*
----
====

. Verify that port `e2b` is up on all nodes: 
+
[source,cli]
----
network port show ipspace Cluster
----
+
.Show example 
[%collapsible]
====
The output should be similar to the following:

----
cluster1::*> network port show -ipspace Cluster

Node: node1-01
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false


Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false


Node: node1-03
                                                                        Ignore
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false


Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====

. On the same node you used in the previous step, revert the cluster LIF associated with the port in the previous step by using the network interface revert command.
+
.Show example 
[%collapsible]
====
In this example, LIF node1-01_clus2 on node1-01 is successfully reverted if the Home value is true and the port is e2b.

The following commands return LIF `node1-01_clus2` on `node1-01` to home port `e2a` and displays information about the LIFs on both nodes. Bringing up the first node is successful if the Is Home column is true for both cluster interfaces and they show the correct port assignments, in this example `e2a` and `e2b` on node1-01.

[subs=+quotes]
----
cluster1::*> *network interface show -vserver Cluster* | grep e2

            Logical         Status     Network            Current    Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node       Port    Home
----------- --------------- ---------- ------------------ ---------- ------- -----
Cluster
            node1-01_clus1  up/up      169.254.209.69/16  node1-01   e2a     true
            node1-01_clus2  up/up      169.254.49.125/16  node1-01   e2b     true
            node1-02_clus1  up/up      169.254.47.194/16  node1-02   e2b     true
            node1-02_clus2  up/up      169.254.19.183/16  node1-02   e2a     false
            .
            .
            .
----
====

. Display information about the nodes in a cluster: 
+
`cluster show`
+
.Show example 
[%collapsible]
====
This example shows that the node health for node1 and node2 in this cluster is true:

[subs=+quotes]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1-01      false   true
node1-02      true    true
node1-03      true    true
node1-04      true    true
----
====

. Verify that all physical cluster ports are up: 
+
[source,cli]
----
network port show ipspace Cluster
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy false
.
.
.
----
====

. Verify the connectivity of the remote cluster interfaces: 

.. You can use the `network interface check cluster-connectivity show` command to display the details of an accessibility check for cluster connectivity:
+
[source,cli]
----
network interface check cluster-connectivity show
----

+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01  
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02  
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====

.. Alternatively, you can also use the `cluster ping-cluster -node <node-name>` command to check the connectivity:
+
`cluster ping-cluster -node <node-name>`
+

.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====

=== Step 3: Verify the configuration

. Using the switch CLI, in EXEC mode, verify that the status of the module is `active` using the `show module` command.
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
nsm-cs1# *show module*
Mod Ports             Module-Type                 Model             Status
--- ----- ----------------------------------- --------------------- --------       
27   0    Supervisor Module                     N9K-C9800-SUP-A     active *  
28   0    Supervisor Module                     N9K-C9800-SUP-A     ha-standby

Mod  Sw                       Hw    Slot
---  ----------------------- ------ ----
27   10.6(3)                  1.0    SUP1
28   10.6(3)                  1.0    SUP2


Mod  MAC-Address(es)                         Serial-Num
---  --------------------------------------  ----------
27   14-bc-68-e7-93-f0 to 14-bc-68-e7-93-f7  FVH1XXXXXXX
28   c8-78-f7-2f-98-30 to c8-78-f7-2f-98-37  FVH2XXXXXXX


Mod  Online Diag Status
---  ------------------
27   Pass
28   Pass

LFM Ports                  Module-Type                            Model           Status
--- ----- ------------------------------------------------ --------------------- --------
19   0    8-slot Fabric Module                             N9K-C9808-FM-A        ok        
20   0    8-slot Fabric Module                             N9K-C9808-FM-A        ok        
21   0    8-slot Fabric Module                                                   pwr-denied
22   0    8-slot Fabric Module                             N9K-C9808-FM-A        ok        
23   0    8-slot Fabric Module                             N9K-C9808-FM-A        ok        
24   0    8-slot Fabric Module                             N9K-C9808-FM-A        ok        
25   0    8-slot Fabric Module                             N9K-C9808-FM-A        ok        
26   0    8-slot Fabric Module                             N9K-C9808-FM-A        ok        


Mod  Power-Status  Reason
---  ------------  ---------------------------
21   pwr-denied     Issue show environment power ...


Mod  Sw                       Hw    Slot
---  ----------------------- ------ ----
19   NA                       1.0    FM1
20   NA                       1.0    FM2
22   NA                       1.0    FM4
23   NA                       1.0    FM5
24   NA                       1.0    FM6
25   NA                       1.0    FM7
26   NA                       1.0    FM8


LFM MAC-Address(es)                          Serial-Num
---  --------------------------------------  ----------
19   NA                                      FOCXXXXXXXX
20   NA                                      FOCXXXXXXXX
22   NA                                      FOCXXXXXXXX
23   NA                                      FOCXXXXXXXX
24   NA                                      FOCXXXXXXXX
25   NA                                      FOCXXXXXXXX
26   NA                                      FOCXXXXXXXX


LFM  Online Diag Status
---  ------------------
19   Pass
20   Pass
22   Pass
23   Pass
24   Pass
25   Pass
26   Pass
 
27   0    Supervisor Module                        N9K-C9800-SUP-A       active *  
28   0    Supervisor Module                        N9K-C9800-SUP-A       ha-standby
----
====

. Using the switch CLI, in EXEC mode, verify the high-availability and redundancy state of the supervisor modules.
+
`show system redundancy status`
+
.Show example 
[%collapsible]

====
[subs=+quotes]

----
nsm-cs1# *show system redundancy status*
Redundancy mode
---------------
      administrative:   HA
         operational:   HA


This supervisor (sup-1)
-----------------------
    Redundancy state:   Active
    Supervisor state:   Active
      Internal state:   Active with HA standby


Other supervisor (sup-2)
------------------------
    Redundancy state:   Standby
    Supervisor state:   HA standby
      Internal state:   HA standby

----
====

. Verify the health of all the ports on the cluster.
.. *Cluster ports*
... Verify that cluster ports are up and healthy across all nodes in the cluster:
+
[source,cli]
----
network port show ipspace Cluster
----
+
[source,cli]
----
network interface show -vserver cluster
----
+
[source,cli]
----
network device-discovery show -protocol cdp
----
+
[source,cli]
----
show cdp neighbors
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network port show -ipspace Cluster*
Node: node1-01
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false


Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false


Node: node1-03
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false


Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false


cluster1::*> *network interface show -vserver cluster*

          Logical         Status     Network            Current       Current Is
Vserver   Interface       Admin/Oper Address/Mask       Node          Port    Home
--------- --------------- ---------- ------------------ ------------- ------- ----
Cluster
          node1-01_clus1  up/up      169.254.209.69/16  node1-01      e2a     true
          node1-01_clus2  up/up      169.254.49.125/16  node1-01      e2b     true
          node1-02_clus1  up/up      169.254.47.194/16  node1-02      e2b     true
          node1-02_clus2  up/up      169.254.19.183/16  node1-02      e2a     false
          .
          .
          .

cluster1::> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
            .
            .
            .
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXXX)         Ethernet1/2       N9K-C9808
            e2b    cs2(FOX3005Q66Q)          Ethernet1/13      N9K-C9808
.
.
.

nsm-cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID            Local Intrfce  Hldtme Capability  Platform      Port ID
nsm-cs1              Eth1/3         179    H         AFX-2K          e2a
cs2                  Eth1/4         123    H         AFX-2K          e2a
nsm-cs1              Eth1/5         179    H         AFX-2K          e10a
cs2                  Eth1/6         123    H         AFX-2K          e10a
nsm-cs1              Eth1/7         179    H         AFX-2K          e11a
cs2                  Eth1/8         123    H         AFX-2K          e11a
nsm-cs1              Eth1/12        179    H         AFX-2K          e2b
cs2                  Eth1/13        123    H         AFX-2K          e2b
nsm-cs1              Eth1/14        179    H         AFX-2K          e10b
cs2                  Eth1/15        123    H         AFX-2K          e10b
nsm-cs1              Eth1/16        179    H         AFX-2K          e11b
cs2                  Eth1/17        123    H         AFX-2K          e11b


cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
nsm-cs1              Eth1/3         179    H         AFX-2K          e2a
cs2                  Eth1/4         123    H         AFX-2K          e2a
nsm-cs1              Eth1/5         179    H         AFX-2K          e10a
cs2                  Eth1/6         123    H         AFX-2K          e10a
nsm-cs1              Eth1/7         179    H         AFX-2K          e11a
cs2                  Eth1/8         123    H         AFX-2K          e11a
nsm-cs1              Eth1/12        179    H         AFX-2K          e2b
cs2                  Eth1/13        123    H         AFX-2K          e2b
nsm-cs1              Eth1/14        179    H         AFX-2K          e10b
cs2                  Eth1/15        123    H         AFX-2K          e10b
nsm-cs1              Eth1/16        179    H         AFX-2K          e11b
cs2                  Eth1/17        123    H         AFX-2K          e11b
----
====

.. *HA ports*

... Verify that all the HA ports are up with a healthy status: 
+
`ha interconnect status show -node <node-name>`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1a-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====

.. *Storage ports*

... Verify that all the storage ports are up with a healthy status: 
+
[source,cli]
----
storage port show -port-type ENET
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====

.. *Storage shelf ports*

... Verify that all the storage shelf ports are up with a healthy status: 
+
[source,cli]
----
storage shelf port show
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.0
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false
----
====

... Verify the connection status of all the storage shelf ports: 
+
[source,cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device                 
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)   
----
====

. If you suppressed automatic case creation, re-enable it by invoking an AutoSupport message: 
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.What's next?

After you've replaced your supervisor module, you link:../switch-cshm/config-overview.html[configure switch health monitoring].

