---
permalink: switch-cisco-9808/maintain-replace-frus-9808.html
sidebar: sidebar
keywords: switches, hardware installation, Cisco Nexus, 9808 switches
summary: Your Cisco Nexus 9808 switch has field replaceable units (FRUs) that you can replace when they are faulty.
---
= Replace FRUs - Cisco Nexus 9808
:icons: font
:imagesdir: ../media/

[.lead]
Your Cisco Nexus 9808 switch has field replaceable units (FRUs) that you can replace when they are faulty.


.About this task
The Cisco Nexus 9808 switch has the following FRUs:

* *Chassis door foam air filters* (2 total): Doors come with pre-installed air filters. You should inspect the air filter every 3 months and replace as necessary.
* *Supervisor module* (1 or 2 total, depending on how you ordered your switch): When two Supervisor modules are installed in the switch, one acts as an active module and the other as the standby module. When the active Supervisor module is removed, the switch automatically makes the standby Supervisor module active. If the switch has only one installed Supervisor module, a new Supervisor module can be installed in the empty Supervisor slot during operation.
* *Line card* (8 total, each with 16 fixed 400GbE ports): The switch operates with one or more line cards that are installed in the chassis.
* *Fan tray* (2 total) 
* *Fabric module* (2 total)
* *Power supply components* (2 total)
* *Fan module* (6 total)
* *OSFP/QSFP transceiver modules* (32 fixed 400GbE ports)

.Steps

. Go to the Cisco site for the link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide.html[Cisco Nexus 9808 NX-OS Mode Switch Hardware Installation Guide^].

. Navigate to the link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide/m-8000-replace-chassis-components.html[Replace chassis components^] section to see the FRU procedures.

. Follow the applicable procedure to replace your faulty FRU.
+
Refer to the link:https://hwu.netapp.com[NetApp Hardware Universe^] for NetApp hardware configuration and compatibility information.

.What's next?

After you've completed the applicable FRU procedure on the Cisco site, you can resume normal operations.

// New content for Organza (9808) project, 2026-JUN-08