---
permalink: switch-cisco-3232c-storage/task-upgrade-nx-os-software-and-rcfs-on-cisco-nexus-3232c-storage-switches.html
sidebar: sidebar
keywords: upgrade, cisco nexus, 3232c storage switch
summary: "The Cisco NX-OS software and reference configuration files (RCFs) can be upgraded on Cisco Nexus 3232C storage switches."
---
= Upgrade a Cisco Nexus 3232C storage switch
:icons: font
:imagesdir: ../media/

[.lead]
The Cisco NX-OS software and reference configuration files (RCFs) can be upgraded on Cisco Nexus 3232C storage switches.

.Before you begin

The following conditions must exist before you upgrade the NX-OS software and RCFs on the storage switch:

* The switch must be fully functioning (there should be no errors in the logs or similar issues).
* You must have checked or set your desired boot variables in the RCF to reflect the desired boot images if you are installing only NX-OS and keeping your current RCF version.
+
If you need to change the boot variables to reflect the current boot images, you must do so before reapplying the RCF so that the correct version is instantiated on future reboots.

* You must have referred to the appropriate software and upgrade guides available on the http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html[Cisco Nexus 3000 Series Switches^] page for complete documentation on the Cisco storage upgrade and downgrade procedures.

* The number of 10 GbE and 40/100 GbE ports are defined in the reference configuration files (RCFs) available on the https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco® Ethernet Switches^] page.

*Procedure summary:*

* **I. Check the health status of switches and ports (<<step1_upgrade_3232c, Steps 1>>- <<step4_upgrade_3232c, 4>>)**
* **II. Copy the RCF to Cisco switch S2 (<<step5_upgrade_3232c, Steps 5>> - <<step8_upgrade_3232c, 8>>)**
* **III. Download the NX-OS image to Cisco switch S2 and reboot  (<<step9_upgrade_3232c, Steps 9>> - <<step12_upgrade_3232c, 12>>)**
* **IV. Recheck the health status of switches and ports (<<step13_upgrade_3232c, Steps 13>> - <<step15_upgrade_3232c, 15>>)**
* **V. Repeat <<step1_upgrade_3232c, Steps 1>>- <<step17_upgrade_3232c, 17>> for Cisco switch S1.**

The examples in this procedure use two nodes; node1 with two storage ports and node2 with two storage ports. See the link:https://hwu.netapp.com/SWITCH/INDEX[Hardware Universe^] to verify the correct storage ports on your platforms.

NOTE: The command outputs might vary depending on different releases of ONTAP.

The examples in this procedure use the following switch and node nomenclature:

* The names of the two storage switches are S1 and S2.
* The nodes are node1 and node2.

NOTE: The procedure requires the use of both ONTAP commands and Cisco Nexus 3000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

.Steps

. [[step1_upgrade_3232c]]If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ is the duration of the maintenance window in hours.
+
NOTE: The AutoSupport message notifies technical support of this maintenance task so that automatic case creation is suppressed during the maintenance window.

. Check that the storage switches are available:
`system switch ethernet show`
+
----
storage::*> system switch ethernet show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

2 entries were displayed.
storage::*>
----

. Verify that the node ports are healthy and operational:
`storage port show -port-type ENET`
+
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----

. [[step4_upgrade_3232c]]Check that there are no storage switch or cabling issues with the cluster:
`system health alert show -instance`
+
----
storage::*> system health alert show -instance
There are no entries matching your query.
----

. [[step5_upgrade_3232c]]Copy the RCF on switch S2 to the switch bootflash using one of the following transfer protocols: FTP, HTTP, TFTP, SFTP, or SCP.
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html[Cisco Nexus 3000 Series NX-OS Command References^].
+
The following example shows HTTP being used to copy an RCF to the bootflash on switch S2:
+
----
S2# copy http://172.16.10.1//cfg/Nexus_3232C_RCF_v1.6-Storage.txt bootflash: vrf management
% Total    % Received % Xferd  Average  Speed   Time    Time     Time                          Current
                               Dload    Upload  Total   Spent    Left                          Speed
  100        3254       100    3254     0       0       8175     0 --:--:-- --:--:-- --:--:–   8301
Copy complete, now saving to disk (please wait)...
Copy complete.
S2#
----

. Apply the RCF previously downloaded to the bootflash:
`copy bootflash:`
+
The following example shows the RCF file `Nexus_3232C_RCF_v1.6-Storage.txt` being installed on switch S2:
+
----
S2# copy Nexus_3232C_RCF_v1.6-Storage.txt running-config echo-commands
----

. Verify that the RCF file is the correct newer version:
`show running-config`
+
When you check the output to verify you have the correct RCF, make sure that the following information is correct:
+
 * The RCF banner
 * The node and port settings
 * Customizations
The output varies according to your site configuration. Check the port settings and refer to the release notes for any changes specific to the RCF that you have installed.
+
[NOTE]
====
In the banner output from the `show banner motd` command, you must read and follow the instructions in the *IMPORTANT NOTES* section to ensure the proper configuration and operation of the switch.
====
+
----
S2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3232C
* Filename : Nexus_3232C_RCF_v1.6-Storage.txt
* Date     : Oct-20-2020
* Version  : v1.6
*
* Port Usage : Storage configuration
* Ports  1-32: Controller and Shelf Storage Ports
* Ports 33-34: Disabled
*
* IMPORTANT NOTES*
* - This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*   to be loaded twice with the Storage Switch rebooted in between.
*
* - Perform the following 4 steps to ensure proper RCF installation:
*
*   (1) Apply RCF first time, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4 ingress...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*       - Syntax error while parsing...
*
*   (4) Save running-configuration again
******************************************************************************
S2#
----
NOTE: When applying the RCF for the first time, the *ERROR: Failed to write VSH commands* message is expected and can be ignored.

. [[step8_upgrade_3232c]] After you verify that the software versions and switch settings are correct, copy the `running-config` file to the `startup-config` file on switch S2.
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html[Cisco Nexus 3000 Series NX-OS Command References^].
+
The following example shows the `running-config` file successfully copied to the `startup-config` file:
+
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
----

. [[step9_upgrade_3232c]]Download the NX-OS image to switch S2.
. Install the system image so that the new version will be loaded the next time switch S2 is rebooted.
+
The switch will be reboot in 10 seconds with the new image as shown in the following output:
+
----
S2# install all nxos bootflash:nxos.9.3.4.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image                  Running-Version(pri:alt)           New-Version  Upg-Required
------  ----------  ----------------------------------------  --------------------  ------------
     1        nxos                                    9.3(3)                9.3(4)           yes
     1        bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)            no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n]  y
input string too long
Do you want to continue with the installation (y/n)?  [n] y

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
S2#
----

. Save the configuration.
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html[Cisco Nexus 3000 Series NX-OS Command References^].
+
You are prompted to reboot the system as shown in the following example:
+
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
S2# reload
This command will reboot the system. (y/n)?  [n] y
----

. [[step12_upgrade_3232c]]Confirm that the new NX-OS version number is on the switch:
+
----
S2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
 NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: S2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

S2#
----

. [[step13_upgrade_3232c]]Recheck that the storage switches are available after the reboot:
`system switch ethernet show`
+
----
storage::*> system switch ethernet show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

2 entries were displayed.
storage::*>
----

. Verify that the switch ports are healthy and operational after the reboot:
`storage port show -port-type ENET`
+
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----

. [[step15_upgrade_3232c]]Recheck that there are no storage switch or cabling issues with the cluster:
`system health alert show -instance`
+
----
storage::*> system health alert show -instance
There are no entries matching your query.
----

. Repeat the procedure to upgrade the NX-OS software and RCF on switch S1.
. [[step17_upgrade_3232c]]If you suppressed automatic case creation, re-enable it by invoking an AutoSupport message:
`system node autosupport invoke -node * -type all -message MAINT=END`

// QA clean-up, 2022-03-04
