---
permalink: switch-cisco-1610/task_install_an_rcf_on_a_cn1610_switch.html
sidebar: sidebar
keywords: reference configuration, file ,install, cn1610, switch
summary: "When you are installing a reference configuration file (RCF), you must first migrate the cluster LIFs away from switch cs2. After the RCF is installed and validated, the LIFs can be migrated back."
---
= Installing a Reference Configuration File on a CN1610 switch
:icons: font
:imagesdir: ../media/

[.lead]
When you are installing a reference configuration file (RCF), you must first migrate the cluster LIFs away from switch cs2. After the RCF is installed and validated, the LIFs can be migrated back.

== What you'll need

You must have saved the configuration that is currently running on your switch.

== Steps

. Save your current switch configuration information: `write memory`
+
The following example shows the current switch configuration being saved to the startup configuration (`startup-config`) file on switch cs2:
+
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----

. On the console of each node, migrate clus2 to port e1a:`network interface migrate`
+
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----

. On the console of each node, verify that the migration occurred: `network interface show -role cluster`
+
The following example shows that clus2 has migrated to port e1a on both nodes:
+
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----

. Shut down port e2a on both nodes: `network port modify`
+
The following example shows port e2a being shut down on both nodes:
+
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----

. Verify that port e2a is shut down on both nodes: `network port show`
+
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----

. Shut down the ISL ports on cs1, the active NetApp switch.
+
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----

. Copy the RCF to the switch.
+
[NOTE]
====
You must set the `.scr` extension as part of the file name before invoking the script. This extension is the extension for the FASTPATH operating system.
====
+
The switch will validate the script automatically as it is downloaded to the switch, and the output will go to the console.
+
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----

. Verify that the script was downloaded and saved with the file name that you gave it.
+
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----

. Validate the script.
+
[NOTE]
====
The script is validated during the download to verify that each line is a valid switch command line.
====
+
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----

. Apply the script to the switch.
+
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----

. Verify that your changes have been implemented on the switch.
+
----
(cs2) # show running-config
----
+
The example displays the `running-config` file on the switch. You must compare the file to the RCF to verify that the parameters that you set are as you expect.

. Save the changes.
. Set the `running-config` file to be the standard one.
+
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----

. Reboot the switch and verify that the `running-config` file is correct.
+
After the reboot completes, you must log in, view the `running-config` file, and then look for the description on interface 3/64, which is the version label for the RCF.
+
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----

. Bring up the ISL ports on cs1, the active switch.
+
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----

. Verify that the ISLs are operational: `show port-channel 3/1`
+
The Link State field should indicate `Up`.
+
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----

. Bring up cluster port e2a on both nodes: `network port modify`
+
The following example shows port e2a being brought up on node1 and node2:
+
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----

. Verify that port e2a is up on both nodes: `network port show -_role cluster_`
+
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----

. On both nodes, revert clus2 that is associated with port e2a: `network interface revert`
+
The LIF might revert automatically, depending on your version of ONTAP.
+
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----

. Verify that the LIF is now home (`true`) on both nodes: `network interface show -_role cluster_`
+
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----

. View the status of the node members: `cluster show`
+
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----

. Copy the `running-config` file to the `startup-config` file when you are satisfied with the software versions and switch settings.
+
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----

. Repeat step 1 through step 22 to upgrade the RCF on the other switch, cs1.

*Related information*

https://support.netapp.com/[NetApp Support]
