---
sidebar: sidebar
permalink: switch-cisco-9336c-fx2-shared/9336c_install_nxos_rcf_share.html
keywords: rcfs, nx-os, install
summary:
---
= Install NX-OS software and RCFs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
From ONTAP 9.9.1, you can use Cisco Nexus 9336C-FX2 switches to combine storage and cluster functionality into a shared switch scenario.

.Before you begin
The cluster and storage switches must be fully functioning (there should be no errors in the logs or similar issues).

.About this task
* The names of the two storage switches are _sh1_ and _sh2_.
* The example used here loads the shared RCF on to the new switch.

.Steps

. Copy the RCF on switch sh2 to the switch bootflash using one of the following transfer protocols: FTP, HTTP, TFTP, SFTP, or SCP.
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html[Cisco Nexus 9000 Series NX-OS Command Reference guides].
+
The following example shows HTTP being used to copy an RCF to the bootflash on switch sh2:
+
[subs=+quotes]
----
sh2# *copy http://172.16.10.1//cfg/Nexus_9336C_RCF_v1.7-Cluster-Ha-Storage.txt bootflash: vrf management*
% Total % Received % Xferd   Average   Speed  Time   Time   Time
Current
   Dload     Upload  Total Spent   Left
Speed
 100    5143          100     5143      0       0     11300    0 --:--:-- --:--:-- --:--:–
11300
Copy complete, now saving to disk (please wait)...
Copy complete.
sh2#
----
[start=2]
. [[step2]]Apply the RCF previously downloaded to the bootflash:
`copy bootflash`.
+
The following example shows the RCF file `Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt `   being installed on switch sh2:
+
[subs=+quotes]
----
sh2# *copy Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt running-config echo-commands*
----
[start=3]
. [[step3]]Verify that the RCF file is the correct newer version:  `show running-config`
+
When you check the output to verify you have the correct RCF, make sure that the following information is correct:

** The RCF banner
** The node and port settings
** Customizations
+
The output varies according to your site configuration. Check the port settings and refer to the release notes for any changes specific to the RCF that you have installed.
+
*Important:* In the banner output from the `show banner motd` command, you must read and follow the instructions in the *IMPORTANT NOTES *section to ensure the proper configuration and operation of the switch.
+
----
sh2# show banner motd
******************************************************************************
*NetApp Reference Configuration File (RCF)
*
*Switch : Nexus N9K-C9336C-FX2
*Filename : Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt
* Date :  Jan-08-2021
*Version  : v1.7
*
*Port Usage:
*Ports  1-8: 40/100GbE Intra-Cluster/HA Ports, int e1/1-8
*Port     9: 10GbE breakout Intra-Cluster Ports, int e1/9/1-4
*Port    10: 25GbE breakout Intra-Cluster/HA Ports, int e1/10/1-4
*Ports 11-22: First HA-pair Controller and Shelf Storage Ports, int e1/11-22
*Ports 23-34: Second HA-pair Controller and Shelf Storage Ports, int e1/23-34
*Ports 35-36: Intra-Cluster ISL Ports, int e1/35-36
*
* Undo breakout commands and return interfaces to 40/100G configuration in
* config mode:
* no interface breakout module 1 port 9 map 10g-4x
* no interface breakout module 1 port 10 map 25g-4x
* interface Ethernet 1/9-10
* inherit port-profile CLUSTER_HA
* priority-flow-control mode auto
* service-policy type qos input HA_POLICY
* exit
*
*IMPORTANT NOTES*
* In certain conditions, N9K-C9336C-FX2 may not be able to auto-negotiate port
* speed correctly, and port speed must be manually set, in config mode, e.g.
* int e1/1
* speed 40000
* int e1/3
* speed 100000
*
******************************************************************************
sh2#
----
[start=4]
. [[step4]]After you verify that the software versions and switch settings are correct, copy the `running-config` file to the startup-config file on switch sh2.
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html[Cisco Nexus 9000 Series NX-OS Command Reference guides].
+
The following example shows the `running-config` file successfully copied to the `startup-config` file:
+
[subs=+quotes]
----
sh2# *copy running-config startup-config*
[########################################] 100% Copy complete.
----
[start=5]
. [[step5]]Repeat this procedure for the RCF on switch sh1.
