---
sidebar: sidebar
permalink: switch-cisco-9336c-fx2-shared/components-9336c-shared.html
keywords: shared storage cluster switch
summary: "Identify the components and part numbers for Cisco Nexus 9336C-FX2 shared switches to support hardware installation and ongoing maintenance."
---
= Review components and part numbers for Cisco Nexus 9336C-FX2 shared switches
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Identify the components and part numbers for Cisco Nexus 9336C-FX2 shared switches to support hardware installation and ongoing maintenance.

The following table lists the part number and description for the 9336C-FX2 switch, fans, and power supplies:

|===
|Part number |Description

|X190200-CS-PE
|N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28
|X190200-CS-PI
|N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28
|X190002
|Accessory Kit X190001/X190003
|X-NXA-PAC-1100W-PE2
|N9K-9336C AC 1100W PSU - Port side exhaust airflow
|X-NXA-PAC-1100W-PI2
|N9K-9336C AC 1100W PSU - Port side Intake airflow
|X-NXA-FAN-65CFM-PE
|N9K-9336C 65CFM, Port side exhaust airflow
|X-NXA-FAN-65CFM-PI
|N9K-9336C 65CFM, Port side intake airflow
|===

.What's next

After you've confirmed your components and part numbers, you can review the link:required-documentation-9336c-shared.html[required documentation].

// Updates for AFFFASDOC-370, 2025-JUL-29
// GH issue #340 internal repo, 2025-SEPT-18
// AFFFASDOC-411, 2025-OCT-30