---
permalink: switch-cisco-9336c-fx2-shared/configure-switch-overview-9336c-shared.html
sidebar: sidebar
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch
summary: 'Overview of installation and configuration for Cisco Nexus 9336C-FX2 shared switches'
---
= Overview of installation and configuration for Cisco Nexus 9336C-FX2 shared switches
:icons: font
:imagesdir: ../media/

[.lead]
The Cisco Nexus 9336C-FX2 shared switch is part of the Cisco Nexus 9000 platform and can be installed in a NetApp system cabinet. Shared switches allow you to combine cluster and storage functionality into a shared switch configuration, by supporting the use of shared cluster and storage Reference Configuration Files. 

== Initial configuration overview

To initially configure a Cisco Nexus 9336C-FX2 switch on systems running ONTAP, follow these steps:

. link:cable-9336c-shared.html[Complete cabling worksheet]. 

. link:install-9336c-shared.html[Install the switch]. 

. link:setup-and-configure-9336c-shared.html[Configure the switch]. 

. link:install-switch-and-passthrough-panel-9336c-shared.html[Install the switch in NetApp cabinet]. 

. link:prepare-nxos-rcf-9336c-shared.html[Prepare to install the NX-OS and RCF]. 

. link:install-nxos-software-9336c-shared.html[Install the NX-OS software]. 

. link:install-nxos-rcf-9336c-shared.html[Install the RCF config file]. 

. link:../switch-cisco-9336c-fx2/configure-ssh.html[Enable SSH].

== Additional information

Before you begin installation or maintenance, be sure to review the following:

* link:configure-reqs-9336c-shared.html[Configuration requirements]
* link:components-9336c-shared.html[Components and part numbers]
* link:required-documentation-9336c-shared.html[Required documentation]

// Updated after Jackie's review for AFFFASDOC-216, 217, 2024-JUL-25