---
permalink: switch-cisco-9336c-fx2-shared/CSHM_log_collection.html
sidebar: sidebar
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation
summary: 'The cluster switch health monitor log collection feature is used to collect switch-related log files in ONTAP. You must make sure that you have set up your environment using the 9336c-FX2 cluster switch CLI as detailed here.'
---
= Ethernet Switch Health Monitoring log collection
:icons: font
:imagesdir: ../media/

[.lead]
You can use the log collection feature to collect switch-related log files in ONTAP. 
The Ethernet switch health monitor (CSHM) is responsible for ensuring the operational health of Cluster and Storage network switches and collecting switch logs for debugging purposes. This procedure guides you through the process of setting up and starting the collection of detailed *Support* logs from the switch and starts an hourly collection of *Periodic* data that is collected by AutoSupport.

//IMPORTANT: To enable the log collection feature, you must be running ONTAP version 9.12.1 and later and EFOS 3.8.0.2 and later.

//Verify that you have set up your environment using the 9336C-FX2 cluster switch *CLI*.

// start of tabbed content 

.Before you begin

* Verify that you have set up your environment using the 9336C-FX2 cluster switch *CLI*.
* Switch health monitoring must be enabled for the switch. Verify this by ensuring the `Is Monitored:` field is set to *true* in the output of the `system switch ethernet show` command.

.Steps

. Create a password for the Ethernet switch health monitor log collection feature:
+
`system switch ethernet log setup-password`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====

. To start log collection, run the following command, replacing DEVICE with the switch used in the previous command. This starts both types of log collection: the detailed *Support* logs and an hourly collection of *Periodic* data.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Wait for 10 minutes and then check that the log collection completes:
+
`system switch ethernet log show`
+
CAUTION: If any of these commands return an error or if the log collection does not complete, contact NetApp support.

.Troubleshooting
If you encounter any of the following error statuses reported by the log collection feature (visible in the output of `system switch ethernet log show`), try the corresponding debug steps:

|===

h| *Log collection error status* h| *Resolution* 
a| *RSA keys not present*
a| Regenerate ONTAP SSH keys. Contact NetApp support.
a| *switch password error*
a| Verify credentials, test SSH connectivity, and regenerate ONTAP SSH keys. Review the switch documentation or contact NetApp support for instructions.
a| *ECDSA keys not present for FIPS*
a| If FIPS mode is enabled, ECDSA keys need to be generated on the switch before retrying.
a| *pre-existing log found*
a| Remove the previous log collection file on the switch.
a| *switch dump log error*
a| Ensure the switch user has log collection permissions. Refer to the prerequisites above.

|===

// New content for the CSHM log collection feature, 2024-FEB-21
