---
sidebar: sidebar
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html
keywords:
summary:
---
= Configure Cisco Nexus 9336C-FX2 shared switches
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Follow these instructions to configure Cisco Nexus 9336C-FX2 shared switches.

.Before you begin
Make sure you have the following:

* Required shared switch documentation, controller documentation and ONTAP documentation. See link:required-documentation-9336c-shared.html[Documentation requirements for Cisco Nexus 9336C-FX2 shared switches] and https://docs.netapp.com/us-en/ontap/index.html[NetApp ONTAP documentation^].

* Applicable licenses, network and configuration information, and cables.

* Completed cabling worksheets. See link:cable-9336c-shared.html[Complete the Cisco Nexus 9336C-FX2 cabling worksheet]. For more information on cabling, refer to the https://hwu.netapp.com[Hardware Universe].

.Steps
. [[step3]]Perform an initial configuration of the switches.
+
For configuration, you need the appropriate number and type of cables and cable connectors for your switches.
+
Depending on the type of switch you are initially configuring, you need to connect to the switch console port with the included console cable; you also need to provide specific network information.
+
. Boot the switch.
+
Provide the applicable responses to the following initial setup questions when you first boot the switch.
+
Your site's security policy defines the responses and services to enable.

.. Abort Auto Provisioning and continue with normal setup? (yes/no)
+
Respond with *yes*. The default is no.

.. Do you want to enforce secure password standard? (yes/no)
+
Respond with *yes*. The default is yes.

.. Enter the password for admin.
+
The default password is admin; you must create a new, strong password.
+
A weak password can be rejected.

.. Would you like to enter the basic configuration dialog? (yes/no)
+
Respond with *yes* at the initial configuration of the switch.

.. Create another login account? (yes/no)
+
Your answer depends on your site's policies on alternate administrators. The default is no.

.. Configure read-only SNMP community string? (yes/no)
+
Respond with *no*. The default is no.

.. Configure read-write SNMP community string? (yes/no)
+
Respond with *no*. The default is no.

.. Enter the switch name.
+
The switch name is limited to 63 alphanumeric characters.

.. Continue with out-of-band (mgmt0) management configuration? (yes/no)
+
Respond with *yes* (the default) at that prompt. At the mgmt0 IPv4 address: prompt, enter your IP address: ip_address

.. Configure the default-gateway? (yes/no)
+
Respond with *yes*. At the IPv4 address of the default-gateway: prompt, enter your default_gateway.

.. Configure advanced IP options? (yes/no)
+
Respond with *no*. The default is no.

.. Enable the telnet service? (yes/no)
+
Respond with *no*. The default is no.

.. Enable SSH service? (yes/no)
+
Respond with *yes*. The default is yes.
+
NOTE: SSH is recommended when using Ethernet Switch Health Monitor (CSHM) for its log collection features. SSHv2 is also recommended for enhanced security.
+
[start=14]
.. [[step14]]Enter the type of SSH key you want to generate (dsa/rsa/rsa1). The default is rsa.
.. Enter the number of key bits (1024- 2048).
.. Configure the NTP server? (yes/no)
+
Respond with *no*. The default is no.

.. Configure default interface layer (L3/L2):
+
Respond with *L2*. The default is L2.

.. Configure default switch port interface state (shut/noshut):
+
Respond with *noshut*. The default is noshut.

.. Configure CoPP system profile (strict/moderate/lenient/dense):
+
Respond with *strict*. The default is strict.

.. Would you like to edit the configuration? (yes/no)
+
You should see the new configuration at this point. Review and make any necessary changes to the configuration you just entered. Respond with no at the prompt if you are satisfied with the configuration. Respond with *yes* if you want to edit your configuration settings.

.. Use this configuration and save it? (yes/no)
+
Respond with *yes* to save the configuration. This automatically updates the kickstart and system images.

. Verify the configuration choices you made in the display that appears at the end of the setup, and make sure that you save the configuration.
+
NOTE: If you do not save the configuration at this stage, none of the changes will be in effect the next time you reboot the switch.
. Check the version on the cluster network switches, and if necessary, download the 
NetApp-supported version of the software to the switches from the https://software.cisco.com/download/home[Cisco software download^] page.

.What's next?

After you've configured your switches, you can link:prepare-nxos-rcf-9336c-shared.html[prepare to install NX-OS and RCF].

// Updates for AFFFASDOC-370, 2025-JUL-29
// GH issue #340 internal repo, 2025-SEPT-18
// AFFFASDOC-411, 2025-OCT-30