---
permalink: switch-cisco-9364d-gx2a/install-switches-9364d.html
sidebar: sidebar
keywords: switches, hardware installation, Cisco Nexus, 9364D-GX2A switches
summary: Installing the Cisco Nexus 9364D-GX2A switches as part of a new AFX 1K or AFX 2K system installation includes installing the switches into a rack or cabinet, cabling them to the system controllers and shelves, and then powering them on.
---
= Install the switches - Cisco Nexus 9364D-GX2A
:icons: font
:imagesdir: ../media/

[.lead]
Installing the Cisco Nexus 9364D-GX2A switches as part of a new AFX 1K or AFX 2K system installation includes installing the switches into a rack or cabinet, cabling them to the system controllers and shelves, and then powering them on.

.Before you begin
You must have completed the switch preparation steps in link:install-prepare-9364d.html[Prepare to install the switches].


.About this task

You use the applicable AFX 1K or AFX 2K system install and setup workflow on the AFX system documentation site to install and cable the system hardware, and then power on the switches. 

The system install and setup workflow includes instructions such as:

* Instructions for getting the site ready, unpacking the boxes and comparing the contents of the boxes to the packing slip, and registering the system to access support benefits.

* Instructions for installing the switches, controllers, and storage shelves in a NetApp cabinet or telco rack.

* Instructions for cabling your system, including cabling the controllers to switch connections and cabling the storage shelves to switch connections.

.Steps

. Install the switches as part of your AFX 1K or AFX 2K system installation and setup workflow:


* For an AFX 1K system, go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html[AFX 1K install and setup workflow^].

* For an AFX 2K system, go to the link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/install-setup-workflow.html[AFX 2K install and setup workflow^].

NOTE: After you have installed the switches, the AFX install and setup workflow instructions redirect you back to this switch documentation to configure the switches.


.What's next?

After you've installed, cabled, and powered on your switches as part of your AFX 1K or AFX 2K system installation, you link:https://review.docs.netapp.com/us-en/ontap-systems-switches_hotfix-refactor-phase1/switch-cisco-9364d-gx2a/install-configure-switches-in-afx-workflow-9364d.html#configure-switches[configure your switches] and then link:https://review.docs.netapp.com/us-en/ontap-systems-switches_hotfix-refactor-phase1/switch-cisco-9364d-gx2a/install-configure-switches-in-afx-workflow-9364d.html#complete-afx-system-setup[complete the AFX system setup].


// New content for OAM project, AFFFASDOC-331, 2025-MAY-06
// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN