---
permalink: switch-cisco-9364d-gx2a/install-complete-afx-setup-9364d.html
sidebar: sidebar
keywords: switches, complete system setup, Cisco Nexus, 9364D-GX2A switches, AFX
summary: After you complete the Cisco Nexus 9364D-GX2A switch configuration procedures, you go to the AFX system documentation site to power on the storage shelves and controllers in your AFX 1K or AFX 2K system, verify switch connectivity, and complete the AFX system setup.
---
= Complete the AFX system setup - Cisco Nexus 9364D-GX2A
:icons: font
:imagesdir: ../media/

[.lead]
After you complete the Cisco Nexus 9364D-GX2A switch configuration procedures, you go to the AFX system documentation site to power on the storage shelves and controllers in your AFX 1K or AFX 2K system, verify switch connectivity, and complete the AFX system setup.

.Before you begin
* You must have completed the switch configuration procedures in the link:configure-switch-workflow-9364d.html[configure switch workflow]. 

* Each switch must be connected to a console or you must have remote access to each switch.


.Steps

. Complete the power on and setup steps for your AFX 1K or AFX 2K system:

* For an AFX 1K system, go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/power-on-hardware.html[Power on your AFX 1K storage system^] procedure.

* For an AFX 2K system, go to the link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/power-on-hardware.html[Power on your AFX 2K storage system^] procedure.



.What's next?

After you've powered on the storage shelves and controllers and completed the AFX 1K or AFX 2K system setup, you are ready to use your AFX system.

// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN