---
permalink: switch-cisco-9364d-gx2a/install-nxos-software-9364d-cluster.html
sidebar: sidebar
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9364d-gx2a
summary: You can use this procedure to install the NX-OS software on the Nexus 9364d-gx2a cluster switch.
---
= Install or upgrade the NX-OS software
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to install or upgrade the NX-OS software on the Nexus 9364D-GX2A switch.

Before you begin, complete the procedure in link:install-nxos-overview-9364d-cluster.html[Prepare to install NX-OS and RCF].

== Review requirements

.What you'll need

* A current backup of the switch configuration.
* A fully functioning cluster (no errors in the logs or similar issues).

.Suggested documentation

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet switch page^] 
+
Consult the switch compatibility table for the supported ONTAP and NX-OS versions.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html[Software Upgrade and downgrade guides^] 
+
Refer to the appropriate software and upgrade guides available on the Cisco website for complete documentation on the Cisco switch upgrade and downgrade procedures.

* link:https://www.cisco.com/c/dam/en/us/td/docs/dcn/tools/nexus-9k3k-issu-matrix/index.html[Cisco Nexus 9000 and 3000 Upgrade and ISSU Matrix^]
+
Provides information on Disruptive Upgrade/Downgrade for Cisco NX-OS software on Nexus 9000 Series Switches 
based on your current and target releases.
+
On the page, select *Disruptive Upgrade* and select your current release and target release from the dropdown list. 


.About the examples
The examples in this procedure use the following switch and node nomenclature:

* The names of the two Cisco switches are cs1 and cs2.
* The node names are node1-01, node1-02, node1-03, and node1-04.
* The cluster LIF names are node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1, and node1-04_clus2.
* The `cluster1::*>` prompt indicates the name of the cluster.

== Install the software

The procedure requires the use of both ONTAP commands and Cisco Nexus 9000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

.Steps

. Connect the switch to the management network.

. Use the ping command to verify connectivity to the server hosting the NX-OS software and the RCF.
+
.Show example
[%collapsible]
====

This example verifies that the switch can reach the server at IP address 172.19.2.1:

[subs=+quotes]
----
cs2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====

. Display the cluster ports on each node that are connected to the cluster switches: 
+
`network device-discovery show`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network device-discovery show*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface         Platform
----------- ------ ------------------------ ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLM284504N6)         Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs1(FDO2846056X)         Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs1(FLM284504N6)         Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs1(FDO2846056X)         Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs1(FLM284504N6)         Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs1(FDO2846056X)         Ethernet1/13/1    N9K-C9364D-GX2A
            e2a    cs2(FLM284504R2)         Ethernet1/8       N9K-C9364D-GX2A
            e2b    cs2(FDO28390Q24)         Ethernet1/7       N9K-C9364D-GX2A
            e3a    cs2(FLM284504R2)         Ethernet1/7       N9K-C9364D-GX2A
            e3b    cs2(FDO28390Q24)         Ethernet1/8       N9K-C9364D-GX2A
            e7a    cs1(FLM284504N6)         Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs1(FDO2846056X)         Ethernet1/13/2    N9K-C9364D-GX2A

node1-01/lldp
            e0M    RTP-eng.netapp.com (34:6f:90:b0:5e:3b) 
                                            Eth123/1/26       -
            e10a   cs1 (c8:60:8f:34:78:d4)  Ethernet1/16/3    -
            e10b   cs1 (04:e3:87:19:a2:5a)  Ethernet1/13/3    -
            e11a   cs1 (c8:60:8f:34:78:d5)  Ethernet1/16/4    -
            e11b   cs1 (04:e3:87:19:a2:5b)  Ethernet1/13/4    -
            e1a    cs1 (c8:60:8f:34:78:d2)  Ethernet1/16/1    -
            e1b    cs1 (04:e3:87:19:a2:58)  Ethernet1/13/1    -
            e2a    cs2 (c8:60:8f:34:a7:4a)  Ethernet1/8       -
            e2b    cs2 (28:b5:91:09:38:d8)  Ethernet1/7       -
            e3a    cs2 (c8:60:8f:34:a7:46)  Ethernet1/7       -
            e3b    cs2 (28:b5:91:09:38:dc)  Ethernet1/8       -
            e7a    cs1 (c8:60:8f:34:78:d3)  Ethernet1/16/2    -
            e7b    cs1 (04:e3:87:19:a2:59)  Ethernet1/13/2    -
----
====

. Check the administrative and operational status of each port.

.. *Cluster ports*

... Verify that all the cluster ports are up with a healthy status: 
+
`network port show -role cluster`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network port show -role cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-03

                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====

... Verify that all the cluster interfaces (LIFs) are on the home port: 
+
`network interface show -role cluster`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current   Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node      Port    Home
----------- --------------- ---------- ------------------ --------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01  e7a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01  e7b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02  e7a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02  e7b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03  e7a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03  e7b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04  e7a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04  e7b     true

8 entries were displayed.
----
====

... Verify that the cluster displays information for both cluster switches: 
+
`system cluster-switch show -is-monitoring-enabled-operational true`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1(FDO2846056X)            cluster-network    10.228.137.233   N9K-C9364D-GX2A
     Serial Number: FDO2846056X
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP


cs2(FLM284504N6)             cluster-network   10.228.137.253   N9K-C9364D-GX2A
     Serial Number: FLM284504N6
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP

2 entries were displayed.
----
====

.. *Storage ports*

... Verify that all the storage ports are up with a healthy status: 

+
`storage port show -port-type ENET`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====

.. *HA ports*

... Verify that all the HA ports are up with a healthy status: 


. Disable auto-revert on the cluster LIFs. The cluster LIFs fail over to the partner cluster switch and remain there as you perform the upgrade procedure on the targeted switch:
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

. Copy the NX-OS software to the Nexus 9364D-GX2A switch.
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.10.4.2.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *root*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
root@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.10.4.2.bin  /bootflash/nxos.10.4.2.bin
/code/nxos.10.4.2.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====

. Install the NX-OS software on the Nexus 9364D-GX2A switch.
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cs2# *install all nxos bootflash:nxos.10.4.2.bin*

Module       Image  Running-Version(pri:alt)       New-Version           Upg-Required

------   ---------  -----------------------------  --------------------  ------------

     1        nxos  10.4(2)                        10.4.2                No

     1        bios  x.x.x:x.x.x                    x.x.x                 No
----
====

. Verify the running version of the NX-OS software:
+
`show version`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cs2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.4(2) [Feature Release]
  Host NXOS: version 10.4(2)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-cs.10.4.2.F.bin
  NXOS compile time:  11/30/2023 12:00:00 [12/14/2023 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9332D-GX2B Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLM284504N6
  Device name: cs2
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(2)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs2#
----
====

. Install the NX-OS image.
+
Installing the image file causes it to be loaded every time the switch is rebooted.
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cs2# *install all nxos bootflash:nxos.9.3.5.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.5.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.5.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.5.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     9.3(4)                                   9.3(5)                  yes
  1      bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)      yes


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====

. Verify the new version of NX-OS software after the switch has rebooted: 
+
`show version`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cs2# *show version*

Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 05.33
  NXOS: version 9.3(5)
  BIOS compile time:  09/08/2018
  NXOS image file is: bootflash:///nxos.9.3.5.bin
  NXOS compile time:  11/4/2018 21:00:00 [11/05/2018 06:11:06]


Hardware
  cisco Nexus9000 C9336C-FX2 Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: cs2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 277524 usecs after Mon Nov  2 22:45:12 2020
  Reason: Reset due to upgrade
  System version: 9.3(4)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====

. Verify the health of cluster ports on the cluster.

.. Verify that cluster ports are up and healthy across all nodes in the cluster: 
+
`network port show -role cluster`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network port show -role cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false
----
====

.. Verify the switch health from the cluster:
+
`network device-discovery show -protocol cdp` and
`system cluster-switch show -is-monitoring-enabled-operational true`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network device-discovery show -protocol cdp*

node1-02/cdp
            e10a   cs1(FLM284504N6)         Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs1(FDO2846056X)         Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs1(FLM284504N6)         Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs1(FDO2846056X)         Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs1(FLM284504N6)         Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs1(FDO2846056X)         Ethernet1/13/1    N9K-C9364D-GX2A
            e2a    cs2(FLM284504R2)         Ethernet1/8       N9K-C9364D-GX2A
            e2b    cs2(FDO28390Q24)         Ethernet1/7       N9K-C9364D-GX2A
            e3a    cs2(FLM284504R2)         Ethernet1/7       N9K-C9364D-GX2A
            e3b    cs2(FDO28390Q24)         Ethernet1/8       N9K-C9364D-GX2A
            e7a    cs1(FLM284504N6)         Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs1(FDO2846056X)         Ethernet1/13/2    N9K-C9364D-GX2A

node1-01/cdp
            e10a   cs1(FLM284504N6)         Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs1(FDO2846056X)         Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs1(FLM284504N6)         Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs1(FDO2846056X)         Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs1(FLM284504N6)         Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs1(FDO2846056X)         Ethernet1/13/1    N9K-C9364D-GX2A
            e2a    cs2(FLM284504R2)         Ethernet1/8       N9K-C9364D-GX2A
            e2b    cs2(FDO28390Q24)         Ethernet1/7       N9K-C9364D-GX2A
            e3a    cs2(FLM284504R2)         Ethernet1/7       N9K-C9364D-GX2A
            e3b    cs2(FDO28390Q24)         Ethernet1/8       N9K-C9364D-GX2A
            e7a    cs1(FLM284504N6)         Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs1(FDO2846056X)         Ethernet1/13/2    N9K-C9364D-GX2A
.
.
.

cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1(FDO2846056X)            cluster-network    10.228.137.233   N9K-C9364D-GX2A
     Serial Number: FDO2846056X
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP


cs2(FLM284504N6)             cluster-network   10.228.137.253   N9K-C9364D-GX2A
     Serial Number: FLM284504N6
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Versi9K-C9332D-Gon
                    10.4(2)
    Version Source: CDP/ISDP
----
//You might observe the following output on the cs1 switch console depending on the RCF version previously loaded on the switch:

//----
//2020 Nov 17 16:07:18 cs1 %$ VDC-1 %$ %STP-2-UNBLOCK_CONSIST_PORT: Unblocking port port-channel1 on VLAN0092. Port consistency restored.
//2020 Nov 17 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_PEER: Blocking port-channel1 on VLAN0001. Inconsistent peer vlan.
//2020 Nov 17 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_LOCAL: Blocking port-channel1 on VLAN0092. Inconsistent local vlan.
//----
====

. Verify that the cluster is healthy: 
+
`cluster show`
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *cluster show*


Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1-01             true    true          false
node1-02             true    true          false
node1-03             true    true          false
node1-04             true    true          true

4 entries were displayed.
----
====

. Repeat steps 6 to 13 to install the NX-OS software on switch cs1.

. Enable auto-revert on the cluster LIFs.
+
`network interface modify -vserver Cluster -lif * -auto-revert true` 

. Verify that the cluster LIFs have reverted to their home port: 
+
`network interface show -role cluster` 
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e7a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e7b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e7a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e7b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e7a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e7b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e7a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e7b     true
----
====
+
If any cluster LIFs have not returned to their home ports, revert them manually from the local node: 
+
`network interface revert -vserver Cluster -lif <lif_name>`


.What's next?

link:install-upgrade-rcf-overview-cluster.html[Install or upgrade the Reference Configuration File (RCF)]

// New content for OAM project, AFFFASDOC-331, 2025-MAY-06
