---
permalink: switch-cisco-9364d-gx2a/maintain-replace-frus-9364d.html
sidebar: sidebar
keywords: switches, hardware installation, Cisco Nexus, 9364D-GX2A switches
summary: Your Cisco Nexus 9364D-GX2A switch has field replaceable units (FRUs) that you can replace when they are faulty.
---
= Replace FRUs - Cisco Nexus 9364D-GX2A
:icons: font
:imagesdir: ../media/

[.lead]
Your Cisco Nexus 9364D-GX2A switch has field replaceable units (FRUs) that you can replace when they are faulty.


.About this task
The Cisco Nexus 9364D-GX2A switch has the following FRUs:

* Fan module (4 total)
* Power supply module (2 total)
* OSFP/QSFP transceiver modules (64 fixed 400GbE ports)


.Steps

. Go to the Cisco site for the https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9364d-gx2a/cisco-nexus-9364d-gx2a-nx-os-mode-switch-hardware-installation-guide.html?dtid=osscdc000283&linkclickid=srch&scid=srch-9364d-gx2a-hw-guide#id_111902[Cisco Nexus 9364D-GX2A NX-OS Mode Switch Hardware Installation Guide^].

. Navigate to the Replacing components section to see the FRU procedures.

. Follow the applicable procedure to replace your faulty FRU.


.What's next?

After you've completed the applicable FRU procedure on the Cisco site, you can resume normal operations.


// New topic for 2K project, AFFFASDOC-xxx, 2026-July
// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN