---
permalink: switch-nvidia-msn2100/install_setup_msn2100_switches_overview.html
sidebar: sidebar
keywords: msn2100 switches setup, msn2100 switches install, cumulus linux
summary: 'The NVIDIA MSN2100 switch is a 10/25/40/100 GbE Ethernet switch running Cumulus Linux. The MSN2100 switch serves Cluster and Storage applications in ONTAP 9.10.1 over different switch-pairs.'
---
= Setup and configure the NVIDIA MSN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
The NVIDIA MSN2100 switch is a 10/25/40/100 Gb Ethernet switch running Cumulus Linux. The MSN2100 switch serves Cluster and Storage applications in ONTAP 9.10.1 over different switch-pairs.

Cumulus Linux (CL) OS can be installed either when the switch is running Cumulus Linux or ONIE.
For this release, the minimal version of Cumulus Linux supported is 4.4.2.


NOTE: The procedures here use Network Command Line Utility (NCLU) which is a command line interface that ensures Cumulus Linux is fully accessible to all. The net command is the wrapper utility you use to execute actions from a terminal.

IMPORTANT: When using breakout cables for 10G and 25G, make sure that auto-negotiation is off and hard set the port speed on the switch. See https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-msn2100/install_msn2100_rcf.html[Install the RCF script] for further details.
