---
permalink: switch-nvidia-msn2100/install_msn2100_rcf.html
sidebar: sidebar
keywords: install rcf script, python script, msn2100 switches, cumulus
summary: 'Ensure that the following are available on the switch before installing the RCF script'
---
= Install the RCF script
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the RCF script, ensure that the following are available on the switch:

* Cumulus Linux 4.4.2 is installed.
* IP address, subnet mask, and default gateway defined via DHCP or manually configured.

== Current RCF script Versions
There are two RCF scripts available for Clustering and Storage applications.  The procedure for each is the same.

* Clustering:  *MSN2100-RCF-v1.8X3-Cluster*
* Storage: *MSN2100-RCF-v1.8X2-Storage*


NOTE: The following example procedure shows how to download and apply the RCF script for Clusters.

.Steps
. Display the availabe interfaces on the  MSN2100 switch:
+
----
cumulus@cumulus:mgmt:~$ net show interface all

State  Name   Spd  MTU    Mode         LLDP                          Summary
-----  -----  ---  -----  -----------  -----------------------------  --------------
UP     lo     N/A  65536  Loopback                                    IP: 127.0.0.1/8

       lo                                                             IP: ::1/128

UP     eth0   1G   1500   Mgmt         RTP-LF02-41MM20 (Eth100/1/12)  Master: mgmt(UP)

       eth0                                                           IP: 10.233.204.71/23(DHCP)

ADMDN  swp1   N/A  9216   NotConfigured

ADMDN  swp2   N/A  9216   NotConfigured

ADMDN  swp3   N/A  9216   NotConfigured

ADMDN  swp4   N/A  9216   NotConfigured

ADMDN  swp5   N/A  9216   NotConfigured

ADMDN  swp6   N/A  9216   NotConfigured

ADMDN  swp7   N/A  9216   NotConfigured

ADMDN  swp8   N/A  9216   NotConfigured

ADMDN  swp9   N/A  9216   NotConfigured

ADMDN  swp10  N/A  9216   NotConfigured

ADMDN  swp11  N/A  9216   NotConfigured

ADMDN  swp12  N/A  9216   NotConfigured

ADMDN  swp13  N/A  9216   NotConfigured

ADMDN  swp14  N/A  9216   NotConfigured

ADMDN  swp15  N/A  9216   NotConfigured

ADMDN  swp16  N/A  9216   NotConfigured

UP     mgmt   N/A  65536  VRF                                           IP: 127.0.0.1/8

       mgmt                                                             IP: ::1/128
----
. Copy the RCF script to the switch:
+
----
cumulus@cumulus:mgmt:~$ pwd
/home/cumulus
cumulus@cumulus:mgmt:/tmp$ scp ssologin@10.60.132.97:/x/eng/testbedN,svl/nic/files/ MSN2100-RCF-v1.8X3-Cluster
ssologin@10.60.132.97's password:
MSN2100-RCF-v1.8X3-Cluster                 100% 8607   111.2KB/s         00:00
----
. Apply the RCF script *MSN2100-RCF-v1.8X3-Cluster*:
+
----
cumulus@cumulus:mgmt:/tmp$ sudo python3 MSN2100-RCF-v1.8X3-Cluster
[sudo] password for cumulus:
...
...
----
+
The RCF script completes the following steps:
+
.. Updates the banner MOTD
.. Disables the apt-get for OS updates
.. Defines breakout and non-breakout interfaces
.. Configures interfaces and SNMP
.. Disables CDP
.. Changes the LLDP configuration
.. Adds a RoCE configuration
.. Modifies the RoCE configuration for HA and Cluster RDMA
.. Reboots the switch

. Verify the configuration after the reboot:
+
----
cumulus@cumulus:mgmt:~$ net show interface all

State  Name      Spd   MTU    Mode       LLDP                          Summary

-----  --------- ----  -----  ---------- ----------------------------- --------

UP     lo        N/A   65536  Loopback                                 IP: 127.0.0.1/8

      lo                                                               IP: ::1/128

UP    eth0       100M  1500   Mgmt       RTP-LF02-41MM20 (Eth100/1/12) Master: mgmt(UP)

      eth0                                                             IP: 10.233.204.71/23(DHCP)

DN    swp1s0     N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN    swp1s1     N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN    swp1s2     N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp1s3    N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp2s0    N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp2s1    N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp2s2    N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp2s3    N/A   9216   Trunk/L2                                 Master: bridge(UP)

UP     swp3      100G  9216   Trunk/L2    rtpnpi-a320-1a (e0d)         Master: bridge(UP)

UP     swp4      100G  9216   Trunk/L2    rtpnpi-a320-1b (e0d)         Master: bridge(UP)

DN     swp5      N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp6      N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp7      N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp8      N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp9      N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp10     N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp11     N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp12     N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp13     N/A   9216   Trunk/L2                                 Master: bridge(UP)

DN     swp14     N/A   9216   Trunk/L2                                 Master: bridge(UP)

UP     swp15     N/A   9216   BondMember  ossg-intergrity-rcf1 (swp15) Master: bond_15_16(UP)

UP     swp16     N/A   9216   BondMember  ossg-intergrity-rcf1 (swp16) Master: bond_15_16(UP)

UP     bond_15_16 N/A  9216   802.3ad                                  Master: bridge(UP)

      bond_15_16                                                       Bond Members: swp15(UP)

      bond_15_16                                                       Bond Members: swp16(UP)

UP    bridge     N/A   9216   Bridge/L2

UP     mgmt      N/A   65536  VRF                                      IP: 127.0.0.1/8

       mgmt                                                            IP: ::1/128

cumulus@cumulus:mgmt:~$ net show roce config

RoCE mode.......... lossless

Congestion Control:

  Enabled SPs.... 0 2 5

  Mode........... ECN

  Min Threshold.. 150 KB

  Max Threshold.. 1500 KB

PFC:

  Status......... enabled

  Enabled SPs.... 2 5

  Interfaces......... swp10-16,swp1s0-3,swp2s0-3,swp3-9



DSCP                     802.1p  switch-priority
-----------------------  ------  ---------------
0 1 2 3 4 5 6 7               0                0

8 9 10 11 12 13 14 15         1                1

16 17 18 19 20 21 22 23       2                2

24 25 26 27 28 29 30 31       3                3

32 33 34 35 36 37 38 39       4                4

40 41 42 43 44 45 46 47       5                5

48 49 50 51 52 53 54 55       6                6

56 57 58 59 60 61 62 63       7                7


switch-priority  TC  ETS
---------------  --  --------
0 1 3 4 6 7       0  DWRR 28%

2                 2  DWRR 28%

5                 5  DWRR 43%
----
