---
permalink: switch-nvidia-msn2100/migrate_cisco_msn2100_storage_switch.html
sidebar: sidebar
keywords: migrating to a storage switch with NVIDIA MSN2100 storage switches, how to migrate
summary: 'You can migrate nondisruptively older Cisco switches for an ONTAP cluster to NVIDIA MSN2100 storage switches.'
---
= Migrate from a Cisco storage switch to a NVIDIA MSN2100 storage switch
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain configuration information, port connections and cabling requirements when you are replacing some older Cisco switches with NVIDIA MSN2100 storage switches.

* The following storage switches are supported:
** Nexus 9336C-FX2
** Nexus 3232C

* See the https://hwu.netapp.com/[Hardware Universe^] for full details of supported ports and their configurations.

.Before you begin
You can migrate nondisruptively older Cisco storage switches for an ONTAP cluster to NVIDIA MSN2100 storage switches.

* The existing cluster must be properly set up and functioning.
* All storage ports must be in the up state to ensure nondisruptive operations.
* The NVIDIA MSN2100  storage switches must be configured and operating under the proper version of Cumulus Linux installed with the reference configuration file (RCF) applied.
* The existing storage network configuration must have the following:
** A redundant and fully functional NetApp cluster using both older Cisco switches.
** Management connectivity and console access to both the older Cisco switches and the new switches.
** All cluster LIFs in the up state with the cluster LIfs are on their home ports.
** ISL ports enabled and cabled between the older Cisco switches and between the new switches.
* See the https://hwu.netapp.com/[Hardware Universe^] for full details of supported ports and their configurations.
* You have configured some of the ports on NVIDIA MSN2100 switches to run at 40 GbE or 100 GbE.
* You have planned, migrated, and documented 40 GbE and 100 GbE connectivity from nodes to NVIDIA MSN2100 storage switches.
+
NOTE: In this procedure, Cisco Nexus 9336C-FX2 storage switches are used for example commands and outputs.

.About this task
The examples in this procedure use the following switch and node nomenclature:

* The existing Cisco Nexus 9336C-FX2 storage switches are _S1_ and _S2_.
* The new NVIDIA MSN2100 storage switches are _sw1_ and _sw2_.
* The nodes are _node1_ and _node2_.
* The cluster LIFs are node1_clus1 and node1_clus2 on node 1, and node2_clus1 and node2_clus2 on node 2 respectively.
//* The `cluster1::*>` prompt indicates the name of the cluster.
* The network ports used in this procedure are e5a and e5b.
* Breakout ports take the format: swp1s0-3. For example four breakout ports on swp1 are _swp1s0_, _swp1s1_, _swp1s2_, and _swp1s3_.
* Switch S2 is replaced by switch sw2 first and then switch S1 is replaced by switch sw1.
** Cabling between the nodes and S2 are then disconnected from S2 and reconnected to sw2.
** Cabling between the nodes and S1 are then disconnected from S1 and reconnected to sw1.

.Steps
. If AutoSupport is enabled, suppress automatic case creation by invoking an AutoSupport message: `system node autosupport invoke -node * -type all -message MAINT=xh`
+
where _x_ is the duration of the maintenance window in hours.

. Change the privilege level to advanced, entering *y* when prompted to continue: `set -privilege advanced`
+
The advanced prompt (*>) appears.
+
//. Disable auto-revert on the cluster LIFs: `net interface modify -vserver Cluster -lif * -auto-revert false`

. Determine the administrative or operational status for each storage interface:
+
Each port should display enabled for  `Status`.
+
Display the network port attributes: `storage port show`
+
[subs=+quotes]
----
storage::*> *st port show*
(storage port show)

storage::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET   storage   0   enabled  offline     30
               e0d  ENET  storage  100   enabled  online      30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage    0   enabled  offline     30
               e0d  ENET  storage  100   enabled  online      30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
storage::*>
----

. The storage ports on each node are connected to existing storage switches in the following way (from the nodes' perspective) using the command: `net device-discovery show -protocol lldp`
+
[subs=+quotes]
----
storage::*> *net device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0d    S1                        Eth1/1          N9K-C9336C-FX2
            e5b    S2                        Eth1/1          N9K-C9336C-FX2
node2      /lldp
            e0d    S1                        Eth1/2          N9K-C9336C-FX2
            e5b    S2                        Eth1/2          N9K-C9336C-FX2

----

. The storage ports and switches are connected in the following way (from the switches' perspective) using the command: `show lldp neighbors`
+
[subs=+quotes]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/11        121         S                    e0d
node2                 Eth1/12        121         S                    e0d
S2                    Eth1/33        121         S                    e0c
S2                    Eth1/34        121         S                    e0c

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/11         121         S                    e5b
node2                 Eth1/12         121         S                    e5b
S1                    Eth1/33         121         S                    e5a
S1                    Eth1/34         121         S                    e5a
----

. Ensure that the network has full connectivity using the command: `cluster ping-cluster -node node-name`
+
[subs=+quotes]
----
storage::*> *cluster ping-cluster -node node2*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----

. On switch sw2, shut down the ports connected to the storage ports and nodes of the disk shelves.
+
[subs=+quotes]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----

. Move the node storage ports of the controller and disk shelves from the old switch S2 to the new switch sw2, using appropriate cabling supported by NVIDIA MSN2100.
. The storage ports on each node are now connected to the switches in the following way, from  the nodes' perspective:
+
[subs=+quotes]
----
storage::*> *net device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0d    S1                        Eth1/11        N9K-C9336C-FX2
            e5b    sw2                       swp1           MSN2100-CB2RC

node2      /lldp
            e0d    S1                        Eth1/12        N9K-C9336C-FX2
            e5b    sw2                       swp2           MSNN2100-CB2RC
----
. Verify that all node storage ports are up:
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP                    Summary
-----  -----------  ----  -----  ----------  ----------------------  -----------------------
UP     lo           N/A   65536  Loopback                            IP: 127.0.0.1/8
       lo                                                            IP: ::1/128
UP     eth0         100M  1500   Mgmt        RTP-LF01(Eth104/1/35)   Master: mgmt(UP)
       eth0                                                          IP: 10.231.80.190/22
...
...
...
UP     swp13        N/A   9216   Trunk/L2                            Master: bridge(UP)
UP     swp14        N/A   9216   Trunk/L2                            Master: bridge(UP)
UP     swp15        100G  9216   BondMember  cs05 (swp15)            Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  cs06 (swp16)            Master: cluster_isl(UP)
----

. On switch sw2, bring up the ports connected to the storage ports of the nodes and the disk shelves.
+
[subs=+quotes]
----
cumulus@sw2:~$ net del interface swp1-16 link down
cumulus@sw2:~$ net pending
cumulus@sw2:~$ net commit
----
. On switch sw1, shut down the ports connected to the storage ports of the nodes and the disk shelves.
+
[subs=+quotes]
----
cumulus@sw1:~$ net add interface swp1-16 link down
cumulus@sw1:~$ net pending
cumulus@sw1:~$ net commit
----

. Move the node storage ports of the controller and the disk shelves from the old switch S1 to the new switch sw1, using appropriate cabling supported by NVIDIA MSN2100.

. On switch sw1, bring up the ports connected to the storage ports of the nodes and the disk shelves.
+
[subs=+quotes]
----
cumulus@sw1:~$ net del interface swp1-16 link down
cumulus@sw1:~$ net pending
cumulus@sw1:~$ net commit
----

. The storage ports on each node are now connected to the switches in the following way, from the nodes' perspective:
+
[subs=+quotes]
----
storage::*> *net device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e0d    sw1                       swp1             MSN2100-CB2RC
            e5b    sw2                       swp1             MSN2100-CB2RC

node2      /lldp
            e0d    sw1                       swp2             MSN2100-CB2RC
            e5b    sw2                       swp2             MSNN2100-CB2RC

----

. Verify the final configuration: `storage port show`
+
Each port should display enabled for `State` and enbled for `Status`.
+
[subs=+quotes]
----
storage::*> *storage port show*
  (storage port show)

                               Speed                     VLAN
Node        Port Type  Mode    (Gb/s) State    Status      ID
----------- ---- ----- ------- ------ -------- --------- ----
node1       e0c  ENET  storage     0  enabled  offline     30
            e0d  ENET  storage   100  enabled  online      30
            e5a  ENET  storage     0  enabled  offline     30
            e5b  ENET  storage   100  enabled  online      30
node2
            e0c  ENET  storage     0  enabled  offline     30
            e0d  ENET  storage   100  enabled  online      30
            e5a  ENET  storage     0  enabled  offline     30
            e5b  ENET  storage   100  enabled  online      30
----

. Verify that both nodes each have one connection to each switch: `net show lldp`
+
The following example shows the appropriate results for both switches:
+
[subs=+quotes]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/11         121         S                    e5b
node2                 Eth1/12         121         S                    e5b
S2                    Eth1/33         121         S                    e5a
S2                    Eth1/34         121         S                    e5a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/11         121         S                    e5b
node2                 Eth1/12         121         S                    e5b
S1                    Eth1/33         121         S                    e5a
S1                    Eth1/34         121         S                    e5a
----
*Do we need to do a 'net show interface' here too?*
//. Enable auto-revert on the cluster LIFs: `cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert True`


*Does health monitoring apply to storage switches too?*
. Enable the Ethernet switch health monitor log collection feature for collecting switch-related log files, using the two commands: `system switch ethernet log setup-password` and `system switch ethernet log enable-collection`
+
Enter: `system switch ethernet log setup-password`
+
[subs=+quotes]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
sw1
sw2

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
Followed by: `system  switch ethernet log enable-collection`
[subs=+quotes]
----
cluster1::*> *system  switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
+
NOTE: If any of these commands return an error, contact NetApp support.

. If you suppressed automatic case creation, reenable it by invoking an AutoSupport message: `system node autosupport invoke -node * -type all -message MAINT=END`
