---
permalink: switch-nvidia-msn2100/msn2100-overview.html
sidebar: sidebar
keywords: nvidia msn2100 switches
summary: If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.
---
= NVIDIA MSN2100 switch overview
:icons: font
:imagesdir: ../media/

[.lead]
If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.

You can install the NVIDIA MSN2100 switch (X190200/X190210) in a NetApp system cabinet or third-party cabinet with the standard brackets that are included with the switch.

The following table lists the part number and description for the MSN2100 switch, fans, and power supplies:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
X190200-CS-PE
a|
N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28
a|
X190200-CS-PI
a|
N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28
a|
X190210-FE-PE
a|
N9K-9336C, FTE, PTSX, 36PT10/25/40/100GQSFP28
a|
X190210-FE-PI
a|
N9K-9336C, FTE, PSIN, 36PT10/25/40/100GQSFP28
a|
X190002
a|
Accessory Kit X190001/X190003
a|
X-NXA-PAC-1100W-PE2
a|
N9K-9336C AC 1100W PSU - Port side exhaust airflow
a|
X-NXA-PAC-1100W-PI2
a|
N9K-9336C AC 1100W PSU - Port side Intake airflow
a|
X-NXA-FAN-65CFM-PE
a|
N9K-9336C 65CFM, Port side exhaust airflow
a|
X-NXA-FAN-65CFM-PI
a|
N9K-9336C 65CFM, Port side intake airflow
|===
