---
permalink: switch-nvidia-msn2100/msn2100-overview.html
sidebar: sidebar
keywords: nvidia msn2100 switches
summary: If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.
---
= NVIDIA MSN2100 switch overview
:icons: font
:imagesdir: ../media/

[.lead]
If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.

You install the NVIDIA MSN2100 switch (X190006/X190106) in the NVIDIA dual/single switch cabinet with the standard brackets that are included with the switch.

The following table lists the part number and description for the MSN2100 switches and rail kits:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
X190006-PE
a|
Cluster Switch, NVIDIA SN2100, 16PT 100G, PTSX
a|
X190006-PI
a|
Cluster Switch, NVIDIA SN2100, 16PT 100G, PSIN
a|
X190106-FE-PE
a|
Switch, NVIDIA SN2100, 16PT 100G, PTSX, Front End
a|
X190106-FE-PI
a|
Switch, NVIDIA SN2100, 16PT 100G, PSIN, Front End
a|
X-MTEF-KIT-D
a|
Rail Kit, NVIDIA Dual switch side by side
a|
X-MTEF-KIT-E
a|
Rail Kit, NVIDIA Single switch short depth
|===

See NVIDIA documentation for details on https://docs.nvidia.com/networking/display/sn2000pub/Installation[installing your MSN2100 switch and rail kit^].
