---
permalink: switch-nvidia-msn2100/replace_msn2100_switch_storage.html
sidebar: sidebar
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia msn2100 cluster switch - nvidia msn2100
summary: Replacing a defective NVIDIA MSN2100 switch in a cluster network is a nondisruptive procedure \(NDU\).
---
= Replace a NVIDIA MSN2100 storage switch
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain configuration information, port connections and cabling requirements when you replace NVIDIA MSN2100 storage switches.

.Before you begin
You must verify that the following conditions exist before installing the Cumulus software and RCFs on a NVIDIA MSN2100 storage switch:

* Your system can support NVIDIA MSN2100 storage switches.
* You must have downloaded the applicable RCFs.
* The http://hwu.netapp.com[Hardware Universe^] provides full details of supported ports and their configurations.

.About this task
The existing network configuration must have the following characteristics:

* Ensure that all troubleshooting steps have been completed to confirm that your switch needs replacing.
* Management connectivity must exist on both switches.
+
NOTE: Make sure that all troubleshooting steps have been completed to confirm that your switch
needs replacing.

+
The replacement NVIDIA MSN2100 switch must have the following characteristics:
+
* Management network connectivity must be functional.
* Console access to the replacement switch must be in place.
* The appropriate RCF and Cumulus operating system image must be loaded onto the switch.
* Initial customization of the switch must be complete.

.Procedure summary
This procedure replaces the second NVIDIA MSN2100 storage switch sw2 with the new NVIDIA MSN2100 switch nsw2. The two nodes are node1 and node2.

Steps to complete:

* Confirm the switch to be replaced is sw2.
* Disconnect the cables from switch sw2.
* Reconnect the cables to switch nsw2.
* Verify all device configurations on switch nsw2.

.Steps
. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ is the duration of the maintenance window in hours.
. Check on the health status of the storage node ports to make sure that there is connection to storage switch S1:
+
`storage port show -port-type ENET`
+
[subs=+quotes]
----
storage::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
. Verify that storage switch sw1 is available:
`network device-discovery show`
+
[subs=+quotes]
----
storage::*> *network device-discovery show protocol lldp*
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface   Platform
--------   ----  -----------------------   ---------   ---------
node1/lldp
           e3a   sw1                       swp3        -
           e3a   node1                     e3a         -
           e3b   node1                     e3b         -
node2/lldp
           e3a   sw1                       swp4        -
           e3a   node2                     e3a         -
           e3b   node2                     e3b         -
storage::*>
----
. Run the `net show lldp` command on the working switch to confirm that you can see both nodes and all shelves:
`net show lldp`
+
[subs=+quotes]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost        RemotePort
---------  -----  ----------  ----------------  -----------
swp3       100G   Trunk/L2    sw2               e3a
swp4       100G   Trunk/L2    sw2               e3b
swp15      100G   BondMember  sw2               swp15
swp16      100G   BondMember  sw2               swp16
----
. Verify the shelf ports in the storage system:
`storage shelf port show -fields remote-device, remote-port`
+
[subs=+quotes]
----
storage::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   sw1
3.20    1   -             -
3.20    2   Ethernet1/6   sw1
3.20    3   -             -
3.30    0   Ethernet1/7   sw1
3.20    1   -             -
3.30    2   Ethernet1/8   sw1
3.20    3   -             -
storage::*>
----
. Remove all cables attached to storage switch sw2.
. Reconnect all cables to the replacement switch ns2.
. Recheck the health status of the storage node ports:
`storage port show -port-type ENET`
+
[subs=+quotes]
----
storage::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
+
. Verify that both switches are available:
`net device-discovery show`
+
[subs=+quotes]
----
storage::*> *net device-discovery show protocol lldp*
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/lldp
          e3a  sw1                        swp3        NVIDIA MSN2100
          e3a  node2                      Ethernet1/1 AFF-A400
          e3b  node2                      Ethernet1/2 AFF-A400
          e3b  nsw1                       swp4        NVIDIA MSN2100
node2/lldp
          e3a  sw1                        swp3        -
          e3a  node2                      swp4        -
          e3b  node2                      swp4        -
          e3b  nsw2                       swp3        -
storage::*>
----
. Verify the shelf ports in the storage system:
`storage shelf port show -fields remote-device, remote-port`
+
[subs=+quotes]
----
storage::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     Ethernet1/7     sw1
3.20    1     Ethernet1/7     nsw2
3.30    2     Ethernet1/8     sw1
3.20    3     Ethernet1/8     nsw2
storage::*>
----
. If you suppressed automatic case creation, re-enable it by invoking an AutoSupport message:
`system node autosupport invoke -node * -type all -message MAINT=END`
