---
permalink: switch-nvidia-msn2100/replace_msn2100_switch_cluster.html
sidebar: sidebar
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia msn2100 cluster switch - nvidia msn2100
summary: Replacing a defective NVIDIA MSN2100 switch in a cluster network is a nondisruptive procedure \(NDU\).
---
= Replace a NVIDIA MSN2100 cluster switch
:icons: font
:imagesdir: ../media/

[.lead]
Replacing a defective NVIDIA MSN2100 switch in a cluster network is a nondisruptive procedure (NDU).

.Before you begin
The following conditions must exist before performing the switch replacement in the current environment and on the replacement switch.

* Existing cluster and network infrastructure:
 ** The existing cluster must be verified as completely functional, with at least one fully connected cluster switch.
 ** All cluster ports must be up.
 ** All cluster logical interfaces (LIFs) must be up and on their home ports.
 ** The ONTAP `cluster ping-cluster -node node1` command must indicate that basic connectivity and larger than PMTU communication are successful on all paths.
* NVIDIA MSN2100 replacement switch:
 ** Management network connectivity on the replacement switch must be functional.
 ** Console access to the replacement switch must be in place.
 ** The node connections are ports swp1 through swp14.
 ** All Inter-Switch Link (ISL) ports must be disabled on ports swp15 and swp16.
 ** The desired reference configuration file (RCF) and Cumulus operating system image switch must be loaded onto the switch.
 ** Initial customization of the switch must be complete, as detailed in:
+
//xref:replace-configure-new-switch.adoc[Configuring a new Cisco Nexus 9336C-FX2 switch]
+
Any previous site customizations, such as STP, SNMP, and SSH, should be copied to the new switch.

You must execute the command for migrating a cluster LIF from the node where the cluster LIF is hosted.

.About this task
The examples in this procedure use the following switch and node nomenclature:

* The names of the existing NVIDIA MSN2100 switches are _sw1_ and _sw2_.
* The name of the new NVIDIA MSN2100 switch is _nsw2_.
* The node names are node1 and node2.
* The cluster ports on each node are named e3a and e3b.
* The cluster LIF names are node1_clus1 and _node1_clus2 for node1, and node2_clus1 and node2_clus2 for node2.
* The prompt for changes to all cluster nodes is `cluster1::*>`
* Breakout ports take the format: swp1s0-3. For example four breakout ports on swp1 are _swp1s0_, _swp1s1_, _swp1s2_, and _swp1s3_.
+
NOTE: The following procedure is based on the following cluster network topology:
+

----
cluster1::*> net port show -ipspace Cluster

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false
4 entries were displayed.


cluster1::*> net interface show -vserver Cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.


cluster1::*> net device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    sw1                       Eth1/swp1         MSN2100-CB2RC
            e3b    sw2                       Eth1/swp2         MSN2100-CB2RC
node2      /lldp
            e3a    sw1                       Eth1/swp1         MSN2100-CB2RC
            e3b    sw2                       Eth1/swp2         MSN2100-CB2RC

4 entries were displayed.
----
+
----
cumulus@sw1:~$ show lldp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
S - Switch, H - Host, I - IGMP, r - Repeater,
V - VoIP-Phone, D - Remotely-Managed-Device,
s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform       Port ID
node1              Eth1/1         144    H           AFF400         e3a
node2              Eth1/2         145    H           AFF400         e3a
sw2                Eth1/swp15     176    R S I s     MSN2100-CB2RC  Eth1/swp15
sw2                Eth1/swp16     176    R S I s     MSN2100-CB2RC  Eth1/swp16

Total entries displayed: 4


cumulus@sw2:~$ show lldp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
S - Switch, H - Host, I - IGMP, r - Repeater,
V - VoIP-Phone, D - Remotely-Managed-Device,
s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform       Port ID
node1              Eth1/swp1      139    H           AFF400         e3b
node2              Eth1/swp2      124    H           AFF400         e3b
sw1                Eth1/swp15     178    R S I s     MSN2100-CB2RC  Eth1/swp15
sw1                Eth1/swp16     178    R S I s     MSN2100-CB2RC  Eth1/swp16

Total entries displayed: 4
----

.Steps
. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message: `system node autosupport invoke -node * -type all -message MAINT=xh`
+
where _x_ is the duration of the maintenance window in hours.

. Install the appropriate RCF and image on the switch, nsw2, and make any necessary site preparations.
+
If necessary, verify, download, and install the appropriate versions of the RCF and Cumulus software for the new switch. If you have verified that the new switch is correctly set up and does not need updates to the RCF and Cumulus software, continue to step 3. See https://review.docs.netapp.com/us-en/ontap-systems-switches_yos_integrity_docs/switch-nvidia-msn2100/install_setup_msn2100_switches_overview.html[Setup and configure NVIDIA MSN2100 switches].
+
 .. You can download the applicable Cumulus software for your cluster switches from the _NVIDIA Support_ site. Follow the steps on the Download page to download the Cumulus Linux for the version of ONTAP software you are installing.
 .. The appropriate RCF is available from the _NVIDIA Cluster and Storage Switches_ page (*add link when available*). Follow the steps on the Download page to download the correct RCF for the version of ONTAP software you are installing.
+
. On the new switch, log in as admin and shut down all of the ports that will be connected to the node cluster interfaces (ports swp1 to swp14).
+
If the switch that you are replacing is not functional and is powered down, go to Step 4. The LIFs on the cluster nodes should have already failed over to the other cluster port for each node.
+
----
cumulus@nsw2:~$ net add interface swp1-14 link down
cumulus@nsw2:~$ net pending
cumulus@nsw2:~$ net commit
----
+
. Verify that all cluster LIFs have auto-revert enabled: `net interface show -vserver Cluster -fields auto-revert`
. Verify that all the cluster LIFs can communicate: `cluster ping-cluster`
+
----
cluster1::*> cluster ping-cluster node1

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----

. Shut down the ISL ports swp15 and swp16 on the MSN2100 switch sw1:
+
----
cumulus@sw1:~$ net add interface swp15-16 link down
cumulus@sw1:~$ net pending
cumulus@sw1:~$ net commit
----
. Remove all the cables from the MSN2100 sw2 switch, and then connect them to the same ports on the MSN2100 nsw2 switch.

. Bring up the ISL ports swp15 and swp16 between the sw1 and nsw2 switches, and then verify the port channel operation status.
+
This example enables ISL ports swp15 and swp16 and displays the port channel summary on switch sw1:
+
----
cumulus@sw1:~$ net del interface swp15-16 link down
cumulus@sw1:~$ net pending
cumulus@sw1:~$ net commit
----
The following example shows that the ISL ports are up on switch sw1:
+
----
cumulus@sw1:~$ net show interface

State  Name         Spd   MTU    Mode        LLDP                  Summary
-----  -----------  ----  -----  ----------  --------------------  -----------------------
UP     lo           N/A   65536  Loopback                          IP: 127.0.0.1/8
       lo                                                          IP: ::1/128
...
...
...
UP     swp15        100G  9216   BondMember  sn2100c-cs06 (swp15)  Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sn2100c-cs06 (swp16)  Master: cluster_isl(UP)
----
+
The following example shows that the ISL ports are up on switch nsw2:
+
----
cumulus@nsw2:~$ net show interface

State  Name         Spd   MTU    Mode        LLDP                    Summary
-----  -----------  ----  -----  ----------  ----------------------  -----------------------
UP     lo           N/A   65536  Loopback                            IP: 127.0.0.1/8
       lo                                                            IP: ::1/128
...
...
...
UP     swp15        100G  9216   BondMember  sn2100c-cs06 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sn2100c-cs06 (swp16)    Master: cluster_isl(UP)
----

. Verify that port `e3b` is up on all nodes: `network port show ipspace Cluster`
+
The output should be similar to the following:
+
----
cluster1::*> net port show -ipspace Cluster

Node: node1
                                                                                                                                                                     Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e3a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000  healthy  false


Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e3a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/auto   -        false

4 entries were displayed.
----

. On the same node you used in the previous step, revert the cluster LIF associated with the port in the previous step by using the network interface revert command.
+
In this example, LIF `node1_clus2` on `node1` is successfully reverted if the `Home` value is `true` and the port is `e3b`.
+
The following commands return LIF `node1_clus2` on `node1` to home port `e3a` and displays information about the LIFs on both nodes. Bringing up the first node is successful if the `Is Home` column is true for both cluster interfaces and they show the correct port assignments, in this example `e3a` and `e3b` on `node1`.
+
----
cluster1::*> net interface show -vserver Cluster

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e3a     false

4 entries were displayed.
----

. Display information about the nodes in a cluster: `cluster show`
+
This example shows that the node health for node1 and node2 in this cluster is true:
+
----
cluster1::*> cluster show

Node          Health  Eligibility
------------- ------- ------------
node1         false   true
node2         true    true
----

. Verify that all physical cluster ports are up: `network port show ipspace Cluster`
+
----
cluster1::*> net port show -ipspace Cluster

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false

4 entries were displayed.
----

. Verify that all the cluster LIFs can communicate: `cluster ping-cluster`
+
----
cluster1::*> cluster ping-cluster -node node2
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----

. Verify that the cluster network is healthy:
+
----
cumulus@sw1:~$ show lldp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID            Local Intrfce  Hldtme Capability  Platform       Port ID
node1                Eth1/swp1      144    H           AFF400         e3a
node2                Eth1/swp2      145    H           AFF400         e3a
nsw2                 Eth1/swp15     176    R S I s     MSN2100-CB2RC  Eth1/swp15
nsw2                 Eth1/swp16     176    R S I s     MSN2100-CB2RC  Eth1/swp16

Total entries displayed: 4


cumulus@sw2:~$ show lldp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform       Port ID
node1              Eth1/swp1      139    H           AFF400         e3b
node2              Eth1/swp2      124    H           AFF400         e3b
sw1                Eth1/swp15     178    R S I s     MSN2100-CB2RC  Eth1/swp15
sw1                Eth1/swp16     178    R S I s     MSN2100-CB2RC  Eth1/swp16

Total entries displayed: 4
----

. Enable the Ethernet switch health monitor log collection feature for collecting switch-related log files, using the commands: `system switch ethernet log setup-password` and `system switch ethernet log enable-collection`
+
Enter: `system switch ethernet log setup-password`
+
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
sw1
sw2

cluster1::*> system switch ethernet log setup-password

Enter the switch name: sw1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log setup-password

Enter the switch name: sw2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
Followed by: `system switch ethernet log enable-collection`
+
----
cluster1::*> system switch ethernet log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
+
NOTE: If any of these commands return an error, contact NetApp support.

. If you suppressed automatic case creation, re-enable it by invoking an AutoSupport message: `system node autosupport invoke -node * -type all -message MAINT=END`
