.Before you begin

* If you use FIPS mode, complete the following before setting up log collection:
.. Regenerate SSH keys on the switch using the vendor instructions.
.. Regenerate SSH keys in ONTAP using `debug system regenerate-systemshell-key-pair`.
.. Re-run log collection setup using the `system switch ethernet log setup-password` command.
* You must have access to the switch `show` commands. If you do not, create a new switch user and grant the necessary privileges.
* Switch health monitoring must be enabled for the switch. Verify by checking that the `Is Monitored:` field is set to *true* in the output of `system switch ethernet show`.
//* For NVIDIA switches, the user for log collection must be specified when the Reference Configuration File (RCF) is applied. By default, this user is set to 'admin'. If you wish to use a different user, you must specify this in the *# SHM User's* section of the RCF.
* For log collection with Broadcom and Cisco switches: 
** The local user must have network admin privileges.
** Create a new switch user for each cluster with log collection enabled. These switches do not support multiple SSH keys for the same user, running setup again overwrites the existing SSH key.
* For support log collection with NVIDIA switches, the log collection user must be able to run the `cl-support` command without a password. To allow this, run:
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`

.Steps

Follow the steps for your version of ONTAP to set up log collection, enable periodic data collection, and optionally request on-demand support logs.

// start of tabbed content 

[role="tabbed-block"] 

==== 

.ONTAP 9.15.1 and later
--
. To set up log collection, run the following command for each switch. You are prompted to enter the switch name, username, and password for log collection.
+
*NOTE:* If answering *y* to the user specification prompt, make sure that the user has the necessary permissions as outlined in <<Before you begin>>.
+
[source,cli]
----
system switch ethernet log setup-password
----
+
[subs=+quotes]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----

NOTE: For CL 5.11.1, create the user *cumulus* and respond *y* to the following prompt: Would you like to specify a user other than admin for log collection? {y|n}: *y*

[start=2]
. [[step2]]Enable periodic log collection:
+
[source,cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[subs=+quotes]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----

. Request support log collection:
+
[source,cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[subs=+quotes]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection. 

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection. 

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----

. To view all details of log collection, including the enablement, status message, previous timestamp and filename of periodic collection, the request status, status message, and previous timestamp and filename of support collection, use the following:
+
[source,cli]
----
system switch ethernet log show -instance
----
+
[subs=+quotes]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----
--

.ONTAP 9.14.1 and earlier
--

. To set up log collection, run the following command for each switch. You are prompted to enter the switch name, username, and password for log collection.
+
*NOTE:* If answering `y` to the user specification prompt, make sure that the user has the necessary permissions as outlined in <<Before you begin>>. 
+
[source,cli]
----
system switch ethernet log setup-password
----
+

[subs=+quotes]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----

NOTE: For CL 5.11.1, create the user *cumulus* and respond *y* to the following prompt: Would you like to specify a user other than admin for log collection? {y|n}: *y*

[start=2]
. [[step2]] To request support log collection and enable periodic collection, run the following command. This starts both types of log collection: the detailed `Support` logs and an hourly collection of `Periodic` data.
+
[source,cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[subs=+quotes]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
Wait for 10 minutes and then check that the log collection completes:
+
[source,cli]
----
system switch ethernet log show
----
--
====

// end of tabbed content 

// This include is used in ontap-metrocluster. See ONTAPDOC-2755.

// AFFFASDOC-476, 2026-MAR-30