
== July 2026

=== New Cisco Nexus 9808 switch for AFX 2K
The new Cisco 9808 switches connect to the AFX 2K controller nodes with the storage shelves. This new switch allows you to build ONTAP clusters with more than two nodes. Advanced protocols are used to optimize performance. The design is based on VLAN tagging with multiple network paths, as well as tech‑refresh configurations, to ensure continuous operation and ease of upgrade.

They are 36-port 400GbE Cisco switches with 1 Supervisor module, 7 Fabric modules, and 4 Power Supply Units (PSU) (X-N9K-C9808-B1-A) supporting ONTAP 9.19.1 and later.

== 2025 releases

[%collapsible]
.October 2025
====

.Cisco Nexus 9332D-GX2B and 9364D-GX2A switches for AFX 1K
The Cisco 9364D-GX2A and the Cisco 9332D-GX2B switches, allow you to build ONTAP clusters with more than two nodes. Advanced protocols are used to optimize performance. The design is based on VLAN tagging with multiple network paths, as well as tech‑refresh configurations, to ensure continuous operation and ease of upgrade.

They are 32-port and 64-port 400GbE Cisco switches (X190300-CS-PI, X190300-PE and X190310-CS-PI) supporting ONTAP 9.17.1 and later.
The new NetApp AFX storage system provides a disaggregated solution engineered to meet the rigorous requirements of high-performance NAS and S3 workloads, including AI/ML applications. AFX systems deliver specialized capabilities for customers requiring scalable, high-throughput file and object storage.

====

[%collapsible]
.May 2025
====

.Cisco Nexus 9336C-FX2-T storage switch
These are 12-port 10/25/40/100GbE Cisco storage switches (X190212-CS-PE and X190212-CS-PI) supporting ONTAP 9.10.1 and later. They support 100GbE storage (switch-attached storage) configurations.
====

== 2023 release

[%collapsible]
.May 2023
====

.Cisco Nexus 9336C-FX2-T cluster switch
These are 12-port 10/25/40/100GbE Cisco cluster switches (X190212-CS-PE and X190212-CS-PI) supporting ONTAP 9.10.1 and later. They support 10/25/40/100GbE cluster configurations.
====

== 2022 release

[%collapsible]
.October 2022
====
.NVIDIA SN2100 switch
The NVIDIA SN2100 is a 16-port 100GbE NVIDIA switch (X190006-PE and X190006-PI) that allows you to build ONTAP clusters with more than two nodes, supporting ONTAP 9.10.1 and later. It is an NVIDIA SN2100 cluster interconnect switch and storage switch, including support for MetroCluster IP configurations.
====

== 2021 release

[%collapsible]
.May 2021
====
.Cisco Nexus 9336C-FX2 switch
The Cisco Nexus 9336C-FX2 is a 36-port 100GbE Cisco switch (X190200-CS-PE and X190200-CS-PI). It supports a shared Infrastructure (Cluster, HA, and switch-attached storage) on the same pair of Cisco Nexus 9336C-FX2 switches, including support for MetroCluster IP configurations, supporting ONTAP 9.9.1 and later.
====

== 2019 release

[%collapsible]
.May 2019
====
.Broadcom BES-53248 switch
The Broadcom BES-53248 switch (X190005 and X190005R) supports AFF/FAS controllers with 10/25GbE and 40/100GbE ports, supporting ONTAP 9.8 and later.
====

[%collapsible]
.March 2019
====
.Cisco Nexus 3232C cluster and storage switches
The Cisco Nexus 3232C switch is a 36-port 100GbE Cisco switch (X190200) and a 32-port 100GbE Cisco switch (X190100 and X190100R). Cisco Nexus 3232C storage switch supports connections to the following NS224 NVMe drive shelves AFF and ASA storage systems:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400

They support ONTAP 9.8 and later.
====

// Updates for internal GH issue #450, 2026-JUL-15