
== New switch support

[cols="25h,~,~",options="header"]
|===
| Switches| Description| Available beginning
a|
64-port 400GbE ports Cisco switch (X190310-CS-PI)
a|
Cisco 9364D-GX2BA Intra-Cluster/HA/Storage switch support.
a|
ONTAP 9.17.1
a|
32-port 400GbE ports Cisco switch (X190300-CS-PI and X190300-PE)
a|
Cisco 9332D-GX2B Intra-Cluster/HA/Storage switch support.
a|
ONTAP 9.17.1
a|
12-port 10/25/40/100GbE Cisco Nexus 9336C-FX2-T cluster and storage switch (X190212-CS-PE and X190212-CS-PI)
a|
Supports 10/25/40/100GbE cluster configurations and 100GbE storage (switch-attached storage) configurations.
a|
ONTAP 9.10.1
a|
16-port 100GbE NVIDIA switch (X190006-PE and X190006-PI)
a|
NVIDIA SN2100 cluster interconnect switch and storage switch support, including support for MetroCluster IP configurations.
a|
ONTAP 9.10.1
a|
36-port 100GbE Cisco switch (X190200-CS-PE and X190200-CS-PI)
a|
Supports a shared Infrastructure (Cluster, HA, and switch-attached storage) on the same pair of Cisco Nexus 9336C-FX2 switches, including support for MetroCluster IP configurations.
a|
ONTAP 9.9.1
a|
36-port 100GbE Cisco switch (X190200-CS-PE and X190200-CS-PI), (X190210-FE-PE and X190210-FE-PI)
a|
Cisco Nexus 9336C-FX2 cluster interconnect switch and storage switch support for AFF and ASA storage systems, as well as for front-end data connectivity.
a|
ONTAP 9.8
a|
Broadcom BES-53248 switch (X190005 and X190005R)
a|
Broadcom BES-53248 cluster interconnect switch support for AFF/FAS controllers with 10/25GbE and 40/100GbE ports.
a|
ONTAP 9.8
a|
36-port 100GbE Cisco switch (X190200) and 32-port 100GbE Cisco switch (X190100 and X190100R)
a|
Cisco Nexus 3232C storage switch support to connect NS224 NVMe drive shelves AFF and ASA storage systems:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320
a|
ONTAP 9.8
|===


// Updates for JS, 2024-OCT-29