To configure Ethernet switch health monitoring on NVIDIA Ethernet switches, follow this procedure.
 
These instructions apply if NVIDIA X190006-PE and X190006-PI switches are not detected properly, which can be confirmed by running `system switch ethernet show` and checking if *OTHER* is shown for your model. To identify your NVIDIA switch model, find the part-number with the command `nv show platform hardware` for NVIDIA CL 5.8 and earlier or `nv show platform` for later versions.

[NOTE]
================
These steps are also recommended if you want health monitoring and log collection to work as intended when using NVIDIA CL 5.11.x with the following ONTAP releases. While health monitoring and log collection might still function without these steps, following them ensures everything operates correctly.

* 9.10.1P20, 9.11.1P18, 9.12.1P16, 9.13.1P8, 9.14.1, 9.15.1 and later patch releases
================


.Before you begin

* Make sure that the ONTAP cluster is up and running.
* Enable SSH on the switch to use all of the features available in CSHM.
* Clear the `/mroot/etc/cshm_nod/nod_sign/` directory on all nodes: 
.. Enter the nodeshell:
+
`system node run -node <name>`
.. Change to advanced privilege:
+
`priv set advanced`
.. List the configuration files in the `/etc/cshm_nod/nod_sign` directory. If the directory exists and contains configuration files, it lists the file names.
+
`ls /etc/cshm_nod/nod_sign`
.. Delete all configuration files corresponding to your connected switch models. 
+
If you are unsure, remove all configuration files for the supported models listed above, then download and install the latest configuration files for those same models.
+
`rm /etc/cshm_nod/nod_sign/<filename>`
.. Confirm that the deleted configuration files are no longer in the directory:
+
`ls /etc/cshm_nod/nod_sign`

.Steps

. Download the Ethernet switch health monitor configuration zip file based on the corresponding ONTAP release version. This file is available from the https://mysupport.netapp.com/site/info/nvidia-cluster-switch[NVIDIA Ethernet switches^] page.
 .. On the NVIDIA SN2100 Software download page, select *Nvidia CSHM File*.
 .. On the Caution/Must read page, select the check box to agree.
 .. On the End User License Agreement page, select the check box to agree and click *Accept & Continue*.
 .. On the Nvidia CSHM File - Download page, select the applicable configuration file. The following files are available:
 
// start of tabbed content 

[role="tabbed-block"] 

==== 

.ONTAP 9.15.1 and later
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip
--

.ONTAP 9.11.1 through 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip
--
====

// end of tabbed content 

[start=2]
. [[step2]]Upload the applicable zip file to your internal web server.

. Access the advanced mode setting from one of the ONTAP systems in the cluster.
+
`set -privilege advanced`

. Run the switch health monitor configure command.
+
[subs=+quotes]
----
cluster1::> *system switch ethernet*
----

. Verify that the command output ends with the following text for your ONTAP version:

// start of tabbed content 

[role="tabbed-block"] 

==== 

.ONTAP 9.15.1 and later
--
Ethernet switch health monitoring installed the configuration file.
--

.ONTAP 9.11.1 through 9.14.1
--
SHM installed the configuration file.
--

.ONTAP 9.10.1
--
CSHM downloaded package processed successfully.
--
====

// end of tabbed content 

If an error occurs, contact NetApp support.

[start=6]
. [[step6]]Wait up to twice the Ethernet switch health monitor polling interval, found by running `system switch ethernet polling-interval show`, before completing the next step.

. Run the command `system switch ethernet show` on the ONTAP system and make sure that the cluster switches are discovered with the monitored field set to *True* and the serial number field not showing *Unknown*.
+
[subs=+quotes]
----
cluster1::> *system switch ethernet show*
----

NOTE: If your model is still showing *OTHER* after applying the configuration file, contact NetApp support.

// Updates for AFFFASDOC-341, 2025-MAY-28
// This include is used in ontap-metrocluster. See ONTAPDOC-2755.