Cisco's Smart Call Home monitors the hardware and software components on your network. When a critical system configuration occurs, it generates an email-based notification and raises an alert to all the recipients that are configured in your destination profile.

[NOTE]
====
ONTAP supports Ethernet switch health monitoring (CSHM) to monitor the AFX cluster switches, as well as the ability to collect switch diagnostic logs.

Cisco's Smart Call Home is an option to provide proactive support and help you resolve any issues that might arise with the switches.
====

Before you can use Smart Call Home, be aware of the following requirements:

* An email server must be in place.
* The switch must have IP connectivity to the email server.
* The contact name (SNMP server contact), phone number, and street address information must be configured. This is required to determine the origin of messages received.
* A CCO ID must be associated with an appropriate Cisco SMARTnet Service contract for your company.
* Cisco SMARTnet Service must be in place for the device to be registered.

The http://www.cisco.com/c/en/us/products/switches/index.html[Cisco support site^] contains information about the commands to configure Smart Call Home.

Smart Call Home can be configured during a new system installation and setup or afterwards.

// AFFFASDOC-380, 2025-SEPT-03
// AFFFASDOC-473, 2026-MAR-16