---
permalink: switch-cisco-9332d-gx2b/cabling-considerations-9332d.html
sidebar: sidebar
keywords: 9332d-gx2b cabling setup, 9332d-gx2b switches configuration, nx-os
summary: 'Before configuring your Cisco 9332D-GX2B switch, review the following information.'
---
= Review cabling and configuration considerations
:icons: font
:imagesdir: ../media/

[.lead]
Before configuring your Cisco Nexus 9332D-GX2B switches, review the following considerations.


== Hard-code the speed on breakout ports

You must hard-code the speed on all breakout (4x100GbE) ports on the switches because the switches do not support auto-negotiation on breakout ports. If you do not hard-code the speed, the ports will not come up and will be in an error-disabled state.

For example, to hard-code breakout ports 1-14 on switches running RCF 10.1 and later, do the following:

[subs=+quotes]
----
(cs1)(config)# interface Ethernet1/1-14
*For 100GbE speed:*
(cs1)(config-if)# *speed 100000*
*For 40GbE speed:*
(cs1)(config-if)# *speed 40000*
(cs1)(config-if)# no negotiate auto
(cs1)(config-if)# exit
(cs1)(config)# exit
*Save the changes:*
(cs1)# *copy running-config startup-config*
----

//== Support for NVIDIA CX6, CX6-DX, and CX7 Ethernet ports
//If connecting a switch port to an ONTAP controller using NVIDIA ConnectX-6 (CX6), ConnectX-6 Dx (CX6-DX), or ConnectX-7 (CX7) NIC ports, you must hard-code the switch port speed.

//[subs=+quotes]
//----
//(cs1)(config)# interface Ethernet1/19
//*For 100GbE speed:*
//(cs1)(config-if)# *speed 100000*
//*For 40GbE speed:*
//(cs1)(config-if)# *speed 40000*
//(cs1)(config-if)# no negotiate auto
//(cs1)(config-if)# exit
//(cs1)(config)# exit
//*Save the changes:*
//(cs1)# *copy running-config startup-config*
//----

//Refer to the link:https://hwu.netapp.com/Switch/Index[Hardware Universe^] for more information on switch ports. Refer to link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU[What additional information do I need to install my equipment that is not in HWU?^] for more information about switch installation requirements.

== Use of mixed connection types is not supported for NVIDIA CX6-DX and CX7 (100G) NICs
The mixed usage of copper and optical breakout connections is not supported by NVIDIA C6X-DX and CX7 (100G)  NIC adapters. You should use either copper or optical connections exclusively and avoid combining different connection types. Mixing types can lead to link saturation after extended use.

 

// New topic and refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN