---
permalink: switch-cisco-9332d-gx2b/change-port-speed-9332d-cluster.html
sidebar: sidebar
keywords: install rcf, cisco switches
summary: For Cisco Nexus 9332D-GX2B switches running RCF version 10.1 in an AFX A2K system, you can change the number of switch ports in breakout mode (4x100GbE) and 400GbE mode when you need to accommodate different network configurations for your system.
---
= Change port speed (breakout) configuration - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
For Cisco Nexus 9332D-GX2B switches running RCF version 10.1 in an AFX A2K system, you can change the number of switch ports in breakout mode (4x100GbE) and 400GbE mode when you need to accommodate a different port speed configuration for your AFX A2K system.

To change the RCF 10.1 port speed configuration, you save a backup of the current switch configuration, change your port configuration, apply the modified RCF 10.1 copy to the switches and verify the configuration.

//The use case is using the older AFX switches with 2K so can change port speeds from breakout to 400g. However, the KB says it only applies to 9336 (not 9364). That's because 9336 had breakout and non that could be changed, so just reuse it:
https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_modify_RCF_1.X_Breakout_on_Cisco_9336C-FX2_cluster_switch_for_specific_customer_needs[How to modify RCF 1.X Breakout on Cisco 9336C-FX2 cluster switch for specific customer needs^]

.Before you begin

* You must have an AFX A2K system running ONTAP 9.19.1GA or later.

* Your switches must be running NX-OS 10.6 or later. If you are running an older version of NX-OS, you must upgrade to the required version using the link:upgrade-nxos-software-9332d-cluster-test.html[upgrade NX-OS] procedure (or should point to the overview topic).

* Your switches must be running RCF version 10.1 or later. If you are running RCF version 10.0, you must upgrade to RCF version 10.1 using the link:upgrade-rcf-software-9332d-cluster.html[upgrade the RCF] procedure. (or should point to the overview topic)
+
The version of RCF you have on your switches determines the port speed options available to you. For example, if you have RCF version 10.0, the ports are preset for breakout mode (4x100GbE) and cannot be changed. If you have RCF version 10.1, you can change the number of preset ports that are in breakout mode (4x100GbE) and 400GbE mode.
//per AnD, changing port speeds can only happen after installing RCF or updating RCF. So this topic needs to address both the install and upgrade use cases.

* Determine the port speed configuration you need for your AFX A2K system connectivity. RCF 10.1 has the following preset port speed configuration:
+
[options="header" cols="1,2"]
|===
| Switch port groups | Port speeds and usage
a|
Ethernet1/1/1-4 to Ethernet1/14/1-4
a|
4x100GbE mode for Intra-cluster, HA, and storage connections 
a|
Ethernet1/15 to Ethernet1/30
a|
400GbE mode for Intra-cluster, HA, and storage connections 
a|
Ethernet1/31, Ethernet1/32
a|
400GbE Intra-cluster ISL connections
a|
|===


.About this task
Is this procedure being done on one switch at a time - do the procedure then repeat?

.Steps
Google had these steps, which I think mimic the KB. If these steps are correct, it's a great structure for sequence. 

Steps for Modifying RCFs:

. Save a backup of the current switch configuration. This is highly recommended in case you need to revert to the previous configuration.
+
You can use the `copy running-config startup-config` command to save the running configuration to the startup configuration, and then use a secure copy method to back up the configuration file to a safe location.
(here or keep in Before you begin? I think here is better.)
+
. Modify the RCF file to meet your specific port speed needs, following NetApp KB guidelines.

. Transfer the modified RCF to the switch.

. Apply the new RCF using the copy <rcf_file> running-config command.

. Verify the configuration, specifically checking port-channel summaries and VLANs.



.What's next?

After you've changed the RCF 10.1 port speed configuration, and if this procedure was done as part of a new AFX A2K system installation and setup, you link:configure-ssh-keys.html[verify the SSH configuration]. Otherwise, if you were changing the port speed configuration for an existing AFX A2K system, you are done; no additional action is needed.

// New topic for 2k project, AFFFASDOC-xxx, 2026-JULY-xx
// Refactored content project, GH#423 2026-APR-MAY