---
permalink: switch-cisco-9332d-gx2b/change-port-speed-9332d-cluster.html
sidebar: sidebar
keywords: install rcf, cisco switches
summary: For Cisco Nexus 9332D-GX2B switches running RCF version 10.1 in an AFX A2K system, you can change the number of switch ports in breakout mode (4x100GbE) and 400GbE mode when you need to accommodate different network configurations for your system.
---
= Change port speed configuration - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
For Cisco Nexus 9332D-GX2B switches running RCF version 10.1 in an AFX A2K system, you can change the number of switch ports in breakout mode (4x100GbE) and 400GbE mode when you need to accommodate a different port speed configuration for your system.

You can modify the RCF file before or after installation of the RCF file on a switch: 

* If you are installing switches as part of a new AFX system installation and setup or switch replacement (the switches are not yet operational in the system), you download and modify the RCF file, and then install it on each switch.

* If you have switches already installed and setup (operational) in your AFX system, you have to reset each switch back to factory default settings, download and modify the RCF file, and then install it on each switch.
+
Because these switches are operational in your system, you perform this procedure one switch at a time, which requires you to offload LIFs from the target switch, reset the switch to factory default settings, modify the RCF file, apply the modified RCF file to the target switch, and then verify the configuration before moving on to the next switch.

//per AnD, changing port speeds can only happen after installing RCF or updating RCF. So this topic needs to address both the install and upgrade use cases. May 7: okay this is opposite of KB, which makes it sound like you can modify RCF before or after it's installed.

Hey, this was a sub-lead, but maybe not totally correct since there are 2 use cases!. To change the RCF 10.1 port speed configuration, you save a backup of the current switch configuration, change your port configuration, apply the modified RCF 10.1 copy to one of the switches, repeat for the second switch, and then verify the configuration. 

Hey: this below is a 2 paragraph note in prepare to install topic:

You can change the preset groups to adjust the number of switch ports in breakout mode (4x100GbE) and 400GbE mode when you need to accommodate a different port speed configuration for your AFX A2K system.
//This above text came from change port speed topic.

You can do this later as part of your switch setup process, after you install the RCF on your switches by using the link: change-port-speed-9332d-cluster.html[Change port speed configuration] procedure.

Hey, this last paragraph of note -based on sequence Andris said - isn't what KB says. It says can modify RCF file before it's installed on a switch. IF KB is correct, then reword to: You can do this later as part of your switch setup process, BEFORE you install the RCF on your switches by using the link: change-port-speed-9332d-cluster.html[Change port speed configuration] procedure." Ohh, then if RCF modification can be done before installing RCF, then this topic can't be under the RCF section.Needs to be outside of it.

.Before you begin

* You must have an AFX A2K system running ONTAP 9.19.1GA or later.

* Your switches must be running NX-OS 10.6 or later. If you are running an older version of NX-OS, you must upgrade to the required version using the link:upgrade-nxos-software-9332d-cluster-test.html[upgrade NX-OS] procedure (or should point to the overview topic).

* Your switches must be running RCF version 10.1 or later. If you are running RCF version 10.0, you must upgrade to RCF version 10.1 using the link:upgrade-rcf-software-9332d-cluster.html[upgrade the RCF] procedure. (or should point to the overview topic)
+
The version of RCF you have on your switches determines the port speed options available to you. For example, if you have RCF version 10.0, the ports are preset for breakout mode (4x100GbE) and cannot be changed. If you have RCF version 10.1, you can change the number of preset ports that are in breakout mode (4x100GbE) and 400GbE mode.

* Determine the port speed configuration you need for your AFX A2K system connectivity. RCF 10.1 has the following preset port speed configuration:
+
For the current list of supported RCF versions, see the link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^] page.
+
//NOTE: Do not upgrade or downgrade your RCF version to an unsupported version.
+
[options="header" cols="1,2"]
|===
| Switch port groups | Port speeds and usage
a|
Ethernet1/1/1-4 to Ethernet1/14/1-4
a|
4x100GbE mode for Intra-cluster, HA, and storage connections 
a|
Ethernet1/15 to Ethernet1/30
a|
400GbE mode for Intra-cluster, HA, and storage connections 
a|
Ethernet1/31, Ethernet1/32
a|
400GbE Intra-cluster ISL connections
a|
|===


.About this task
Is this procedure being done on one switch at a time - do the procedure then repeat?

.Steps
Google had these steps, which I think mimic the KB. If these steps are correct, it's a great structure for sequence. 

Steps for Modifying RCFs:

. Save a backup of the current switch configuration. This is highly recommended in case you need to revert to the previous configuration.
+
You can use the `copy running-config startup-config` command to save the running configuration to the startup configuration, and then use a secure copy method to back up the configuration file to a safe location.
(here or keep in Before you begin? I think here is better.)
+
Hey
NOTE: Save your changes by copying the running configuration to the startup configuration. A backup of the config is highly recommended, as well.
+
Hey, does the note above from KB mean that you can modify the RCF file then save it (your changes) by copying the running config (your modified file/where your modified file is) to the startup config? Then you install/apply the modified file to the switches?

. Modify the RCF file to meet your specific port speed needs, following NetApp KB guidelines.

. Transfer the modified RCF to the switch.

. Apply the new RCF using the copy <rcf_file> running-config command.

. Verify the configuration, specifically checking port-channel summaries and VLANs.

.Steps
KB has these steps:
//https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_modify_RCF_1.X_Breakout_on_Cisco_9336C-FX2_cluster_switch_for_specific_customer_needs[How to modify RCF 1.X Breakout on Cisco 9336C-FX2 cluster switch for specific customer needs^]

. Modify port speeds and breakout modes, as needed by the cluster:
+
interface breakout module 1 port 1-3 map 10g-4x
interface breakout module 1 port 4-6 map 25g-4x
+
For example, to configure ports 1-6 for 4 x 10GbE breakout mode, change to the following:
+
interface breakout module 1 port 1-6 map 10g-4x 
+
(1-6 is bold)
+
Previously: 
+
interface breakout module 1 port 4-6 map 25g-4x
+
. Modify the port list with the new ports that need to use the port profile for the desired port speed:
+
interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/33-34
inherit port-profile 10G
exit
+
interface e1/4/1-4, e1/5/1-4, e1/6/1-4
inherit port-profile 25G
priority-flow-control mode auto
service-policy input HA
exit
+
For example, to modify configure ports 1-6 for the 10G speed port profile, change to the following:
+
interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/33-34
inherit port-profile 10G
+
(e1/4/1-4, e1/5/1-4, e1/6/1-4 are bold)
exit
+
Previously:
+
interface e1/4/1-4, e1/5/1-4, e1/6/1-4
inherit port-profile 25G
priority-flow-control mode auto
service-policy input HA
exit

.What's next?

After you've changed the RCF 10.1 port speed configuration, and if this procedure was done as part of a new AFX A2K system installation and setup, you link:configure-ssh-keys.html[verify the SSH configuration]. Otherwise, if you were changing the port speed configuration for an existing AFX A2K system, you are done; no additional action is needed.

// New topic for 2k project, AFFFASDOC-xxx, 2026-JULY-xx
// Refactored content project, GH#423 2026-APR-MAY