---
permalink: switch-cisco-9332d-gx2b/change-port-personality-upgrade-rcf-9332d-cluster.html
sidebar: sidebar
keywords: install rcf, cisco switches
summary: 'You can install the RCF after setting up the Nexus 9332D-GX2B switch for the first time.'
---
= Change port speed (breakout) configuration - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
For Cisco Nexus 9332D-GX2B switches running RCF version 10.1 in an AFX A2K system, you can change the number of switch ports in breakout mode (4x100GbE) and 400GbE mode when you need to accommodate different network configurations for your system.

NOTE Lisa: per APr 23 mtg with S & A: A suggested a new topic to move the following KB content into for changing port speed. It has to do with updating the RCF too.

I think the use case is using the older AFX switches with 2K so have to change port speeds from breakout to 400g.However, the KB says it only applies to 9336 (not 9364):
https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_modify_RCF_1.X_Breakout_on_Cisco_9336C-FX2_cluster_switch_for_specific_customer_needs[How to modify RCF 1.X Breakout on Cisco 9336C-FX2 cluster switch for specific customer needs^]

NOTE: Lisa, because of the KB to change port speed from breakout to 400g when installing RCF or upgrading it to 10.1 (in that larger use case I guess install is for new 2k system and upgrade is ???) I might need to bring RCF install or upgrade back together instead of separate topics and in separate sections of the sidebar.

.Before you begin
* Your switches must be running RCF version 10.1. If you are running RCF version 10.0, you must upgrade to RCF version 10.1 using the link:upgrade-rcf-software-9332d-cluster.html[upgrade the RCF] procedure.
+
The version of RCF you have on your switch determines the port speed options available to you. For example, if you have RCF version 10.0, the ports are pre-set for breakout mode (4x100GbE) and cannot be changed. If you have RCF version 10.1, you can change the number of ports that are in breakout mode (4x100GbE) and 400GbE mode.

* Any other items from the KB?

.About this task


.Steps
Google had these steps, which I think mimic the KB. If these steps are correct, it's a great structure for sequence. How's this tie into install sequence for new systems? And is new system install still the only use case?

Steps for Modifying RCFs:

. Backup the current switch configuration.
. Download the appropriate RCF file for your specific switch model.
+
NOTE: Lisa: If modifying the RCF has to happen after you already have the curent RDF on the switches, that means (as part of a new install) that you came back to the switch repo from the AFX repo , meaning that your switch is cabled and powered on. Now you are going through the switch setup: complete initial setup, install NX-OS, install RCF, but now you can modify RCF...before verify SSH, config CSHM, and complete AFX system setup. I think that's the correct sequence.
+
. Modify the RCF file to meet your specific port speed needs, following NetApp KB guidelines.
. Transfer the modified RCF to the switch.
. Apply the new RCF using the copy <rcf_file> running-config command.
. Verify the configuration, specifically checking port-channel summaries and VLANs.



.What's next?

After you've changed the port personalities, you update the RCF (to 10.1 to support 400GbE. (Or did that happen as part of this change personality procedure already. See what the KB says to do), you link:configure-ssh-keys.html[verify the SSH configuration].

// New topic for 2k project, AFFFASDOC-xxx, 2026-JULY-xx
// Refactored content project, GH#423 2026-APR-MAY