---
permalink: switch-cisco-9332d-gx2b/complete-cluster-setup.html
sidebar: sidebar
keywords: switches, complete system setup, Cisco Nexus, 9332D-GX2B switches
summary: After you complete the switch setup procedures, you need to power on the rest of your AFX system and complete the AFX system setup.
---
= Complete the AFX system setup - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
After you complete the switch setup procedures, you need to power on the rest of your AFX system and complete the AFX system setup.

Go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html[AFX install and setup workflow^] and complete the steps to install and setup the switch hardware and controller hardware for your system.

.Before you begin
You have completed the preparation steps for installing the Cisco Nexus 9332D-GX2B switches and are ready to install the hardware. If you have not completed the preparation steps, see:install-prepare-9332d-cluster.html[Prepare to install the Cisco Nexus 9332D-GX2B switches^].

.About this task
The AFX install and setup workflow includes instructions such as:

* Instructions for getting the site ready, unpacking the boxes and comparing the contents of the boxes to the packing slip, and registering the system to access support benefits.

* Instructions for installing the switches, controllers, and storage shelf in a NetApp cabinet or telco rack.

* Instructions for cabling your system, including cabling the controller storage to switch connections and cabling the shelf to switch connections.

.Steps

. Complete the power on and setup steps for your AFX system:

.. Go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/power-on-hardware.html[Power on your AFX 1K storage system^] procedure.

.. Follow the instructions to power on your storage shelves and controller nodes.

.. Follow the instructions to complete the system setup based on your deployment option.


.What's next?

After you've completed the AFX system setup, you are ready to use your system. (Add anything about maintenance?)



// Refactored content project, new topic, GH#423 2026-APR-MAY