---
permalink: switch-cisco-9332d-gx2b/complete-cluster-setup.html
sidebar: sidebar
keywords: switches, complete system setup, Cisco Nexus, 9332D-GX2B switches
summary: After you complete the switch setup procedures, you need to power on the controllers and shelves in your AFX system, and then complete the AFX system setup.
---
= Complete the AFX system setup - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
After you complete the switch setup procedures, you need to power on the controllers and shelves in your AFX system, and then complete the AFX system setup.

.Before you begin
You must have completed all of the procedures in the link:install-prepare-9332d-cluster.html[Switch setup workflow].

.Steps

. Complete the power on and setup steps for your AFX system:

.. Go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/power-on-hardware.html[Power on your AFX 1K storage system^] procedure.

.. Follow the instructions to power on your storage shelves and controller nodes.

.. Follow the instructions to complete the system setup based on your deployment option.


.What's next?

After you've completed the AFX system setup, you are ready to use your system. (Add anything about maintenance?)



// Refactored content project, new topic, GH#423 2026-APR-MAY