---
permalink: switch-cisco-9332d-gx2b/configure-software-overview-9332d-cluster.html
sidebar: sidebar
keywords: switches, initial installation, configure switch-cisco-9332d-gx2b switch
summary: 'Overview of software configuration for Cisco Nexus 9332D-GX2B cluster switches'
---
= Software install workflow for Cisco Nexus 9332D-GX2B cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
To install and configure the software for a Cisco Nexus 9332D-GX2B switch and to install or upgrade the Reference Configuration File (RCF), follow these steps:

. link:install-nxos-overview-9332d-cluster.html[Prepare to install the NX-OS software and RCF]. 
+
The Cisco NX-OS software and reference configuration files (RCFs) must be installed on Cisco Nexus 9332D-GX2B cluster switches.

. link:install-nxos-software-9332d-cluster.html[Install or upgrade the NX-OS software]. 
+
Download and install or upgrade the NX-OS software on the Cisco Nexus 9332D-GX2B cluster switch.

. link:install-upgrade-rcf-overview-cluster.html[Install or upgrade the RCF]. 
+
Install or upgrade the RCF after setting up the Cisco Nexus 9332D-GX2B switch for the first time. You can also use this procedure to upgrade your RCF version.

. link:configure-ssh-keys.html[Verify SSH configuration on the Nexus 9332D-GX2B cluster switches]. 
+
If you use the Ethernet Switch Health Monitor (CSHM) and log collection features, verify SSH is enabled on the switches.

// New content for OAM project, AFFFASDOC-331, 2025-MAY-06