---
permalink: switch-cisco-9332d-gx2b/configure-install-rcf-9332d.html
sidebar: sidebar
keywords: install rcf, cisco switches
summary: You install the RCF on new Cisco Nexus 9332D-GX2B switch(es) as part of a new AFX 1K or AFX 2K system installation and setup, replacing a faulty switch, or resetting a switch to factory default settings.
---
= Install the RCF - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
You install the RCF on new Cisco Nexus 9332D-GX2B switch(es) as part of a new AFX 1K or AFX 2K system installation, replacing a switch, or a switch reset to factory default settings.

.Before you begin

* The switch(es) must be powered on and you must have completed the link:configure-complete-initial-setup-9332d.html[Complete initial switch setup] procedure.

* You must have installed the desired NX-OS version using the link:configure-install-nxos-9332d.html[Install the NX-OS] procedure.

* You must have read the link:configure-install-upgrade-rcf-overview-9332d.html[Install or upgrade RCF overview] page.

* If you are installing the RCF on a switch as part of a switch replacement or a switch reset to factory default settings, verify that your cluster is fully functional, meaning that there are no errors in the logs or similar issues.
+
If you are installing the RCF as part of a new AFX system installation, you can skip this requirement because the controllers in your AFX system are not powered on at this point in your AFX system installation and setup.
//If you are installing the RCF as part of a new AFX system installation, you can skip this requirement because your AFX system is not yet up and running.


.About this task

* If you have installed switches as part of a new AFX 1K or AFX 2K system installation, you install the RCF on one switch at a time. This procedure has you install the RCF on the first switch (cs1) and then has you repeat the steps for the second switch (cs2).

* The examples shown in this procedure are for AFX 1K systems with switches running RCF 10.0. If you have an AFX 2K system, the input and output can vary.

//* Lisa: this step only belongs in install RCF...and Upgrade? Seems to be covered in steps 1 and 2. 
//Download the RCF supported for your type of AFX system from the NetApp Support Site at http://mysupport.netapp.com/[mysupport.netapp.com^]. 
//+
//NOTE: New switches do not ship with the RCF installed. You must install the RCF on the switches.

== Step 1: Prepare to install the RCF

Prepare to install the RCF on the switch(es) by making sure you have the necessary connections to download the RCF, and then download the RCF.

.Steps

. You must have access to an HTTP, FTP, or TFTP server. Access to one of these servers allows you to download a supported version of the RCF as instructed later in this procedure.
//Above bullet was in original/pre-refactored topic Configure the 9332 switch (config wizard topic) and so applicable to new installs...I think.

. Each switch must be connected to a console or you must have remote access to each switch.

. You must be connected to the switches using the serial console or have preserved basic configuration information. This is because the RCF upgrade procedure requires you to erase the switch settings and perform basic configuration.
+
Hey, this step 3 is from Upgrade RCF, but does it apply here too because the `write erase` command is also used to Install RCF (step 9)? It's similar to step 2 above.

+
//Hey, the following two steps below are from the current live topic: Install or upgrade NX-OS. Do these apply to installing and/or upgrading NX-OS?
+
. Connect the switch to the management network (for the file transfer).
+
//FYI: If you are installing or upgrading the NX-OS on switches as part of a new AFX system installation, the connection to the management network should have been done over on the AFX system doc side.
+
. Verify connectivity to the server hosting the RCF using the ping command.
//In a NetApp system, there is no proprietary NetApp server used for this purpose. The server hosting the NX-OS software and the RCF (Reference Configuration File) is simply an external SFTP, SCP, FTP, or TFTP server (e.g., a local admin workstation or a management server) running on your local network.
+
.Show example
[%collapsible]
====

This example verifies that the switch can reach the server at IP address 172.19.2.1:

[subs=+quotes]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====

. Download the RCF supported for your type of AFX system from the NetApp Support Site at http://mysupport.netapp.com/[mysupport.netapp.com^]. 
+
NOTE: New switches do not ship with the RCF installed. You must install the RCF on the switches.
+
//The download step is from the current public Configure switches (config wizard) topic that had download sw and rcf bullets in before you begin, so moved the dnld content to the respective install RCF and install NX-OS topics.

== Step 2: Install the RCF
You install the RCF on the first switches (cs1) and then you repeat these steps to install the RCF on the second switch (cs2).

. Login to switch cs1 using SSH or by using a serial console.

. Copy the RCF to the bootflash of switch cs1 using one of the following transfer protocols: FTP, TFTP, SFTP, or SCP. 
+
For more information on Cisco commands, refer to the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.
+
.Show example 
[%collapsible]
====
This example shows TFTP being used to copy an RCF to the bootflash on switch cs1:

[subs=+quotes]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9332D-GX2B-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====

. Apply the RCF previously copied to the bootflash.
//This steps is where installation of the RCF happens.
+
For more information on Cisco commands, refer to the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.
+
This example shows the RCF file `NX9332D-GX2B-RCF-v10.0-Shared.txt` being installed on switch cs1:
+
[subs=+quotes]
----
cs1# *copy NX9332D-GX2B-RCF-v10.0-Shared.txt running-config echo-commands*
----
+
NOTE: For RCF 10.1 and later, the file name format is different: `RCF-v10.1-NX9332D-GX2B-CL1.txt`.

+
. Examine the banner output from the `show banner motd` command. You must read and follow these instructions to ensure the proper configuration and operation of the switch.
+
.Show example 
[%collapsible]

[subs=+quotes]
====
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9332D-GX2B
* Filename : NX9332D-GX2B-RCF-v10.0-Shared.txt
* Date     : 05-09-2025
* Version  : v10.0
* Port Usage:
* Ports  1-30: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-30}/1-4
* Ports 31-32: Intra-Cluster ISL Ports, int e1/31-32
*
* IMPORTANT NOTES
* Interface port-channel999 is reserved to identify the version of this file.
******************************************************************************
----
====

. Verify that the RCF file is the correct version: 
+
`show running-config`
+
When you check the output to verify you have the correct RCF, make sure that the following information is correct:

 ** The RCF banner
 ** The node and port settings
 ** Customizations
+
The output varies according to your site configuration. Check the port settings and refer to the release notes for any changes specific to the RCF that you have installed.

. If your switches have RCF 10.1 or later installed, complete the following substeps if needed:

.. Record any custom additions between the current `running-config` file and the RCF file in use.
+
You can link:configure-install-upgrade-rcf-overview-9332d.html#change-port-speed-configuration[change the port speed configuration] for RCF 10.1 as needed.

.. After you verify that the RCF versions, custom additions, and switch settings are correct, copy the `running-config` file to the `startup-config` file.
+
----
cs1# copy running-config startup-config [########################################] 100% Copy complete
----

. Save basic configuration details to the `write_erase.cfg` file on the bootflash.
+
[NOTE]
====================================
Make sure to configure the following:

* Username and password
* Management IP address
* Default gateway
* Switch name
====================================
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`
+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`
+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`
+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`
+
Refer to the Knowledge Base article link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity[How to clear configuration on a Cisco interconnect switch while retaining remote connectivity^] for further details.

. Verify that the `write_erase.cfg` file is populated as expected:
+
`*show file bootflash:write_erase.cfg*`

. Issue the `write erase` command to erase the current saved configuration:
+
`cs1# *write erase*`
+
`Warning: This command will erase the startup-configuration.`
+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copy the previously saved basic configuration into the startup configuration.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Reboot the switch:
+
`cs1# *reload*`
+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repeat steps 1 through 11 on switch cs2.

//. Connect the ports of all nodes in the ONTAP cluster to switches cs1 and cs2.
//+ 
//The switches were already cabled as part of the install switches/hw topic that points to the AFX docs. Is it an issue for NX-OS and RCF if the switches were already cabled and powered on (in that order)????
//+
//This step only applies to installing switches as part of a new AFX system installation and setup and replacing a failed switch. It does not apply to resetting a switch since it's still cabled.


//I moved this section to a new topic in the sidebar under install and setup switches in a new AFX system. Because it  doesn't make sense here; the switch(es) were already cabled and powered as part of the AFX system hw install.
//== Step 2: Cable the switch(es) and verify the connections
//The following steps only apply if you installed switches as part of a new system installation and setup or replaced a failed switch. If you reset a switch to factory defaults, the switch is still cabled and powered on, so you can skip these steps.

//. Connect the ports of all nodes in the ONTAP cluster to switches cs1 and cs2.

//== Step 3: Set up your ONTAP cluster

//NetApp recommends that you use System Manager to set up new clusters. 

//System Manager provides a simple and easy workflow for cluster set up and configuration including assigning a node management IP address, initializing the cluster, creating a local tier, configuring protocols and provisioning initial storage.

//Go to https://docs.netapp.com/us-en/ontap/task_configure_ontap.html[Configure ONTAP on a new cluster with System Manager] for setup instructions.

.What's next?

After you've installed the RCF in your switch(es), you link:configure-verify-ssh-9332d.html[verify SSH for log collection].



// New content for OAM project, AFFFASDOC-331, 2025-MAY-06
// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN