---
permalink: switch-cisco-9332d-gx2b/configure-ssh-keys.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b
summary: If you are setting up switches as part of a new AFX A1K or AFX A2K system installation, a switch replacement, or a reset to factory default settings, and you want to use the Cluster Switch Health Monitor (CSHM) and log collection features, you must verify that SSH and SSH keys are enabled on the switches.
---
= Verify SSH and SSH keys are enabled - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
If you are setting up switches as part of a new AFX A1K or AFX A2K system installation, a switch replacement, or a reset to factory default settings, and you want to use the Cluster Switch Health Monitor (CSHM) and log collection features, you must verify that SSH and SSH keys are enabled on the switches.

//After you complete the initial Cisco Nexus 9332D-GX2B switch setup as part of a new AFX system installation, a switch replacement, or reset to its factory default settings, you are prompted to complete the initial setup for the switch(es) using configuration wizard. You can reference the following configuration wizard questions and recommended responses to help you complete the initial setup of the switch(es).

//After you power on Cisco Nexus 9332D-GX2B switch(es) as part of a new AFX system installation or a switch replacement, or after you reset a switch to its factory default settings, you are prompted to complete the initial setup for the switch(es) using configuration wizard. You can reference the following configuration wizard questions and recommended responses to help you complete the initial setup of the switch(es).

.Before you begin

* Hey, do you really need the following 3 bullets? If you're not doing the same for the other related topics, then don't do it here. Is What's next and Leads enough?

* If you are setting up switches as part of a new AFX A1K or AFX A2K system installation and setup, make sure you have completed the link:configure-software-overview-9332d-cluster.html[Install or upgrade NX-OS software and RCF] procedure for each switch in your system.

* If you are replacing a switch in an existing AFX A1K or AFX A2K system, make sure you have completed the link:replace-9332d-cluster-test.html[Replace a switch] procedure.

* If you are resetting a switch to its factory default settings, make sure you have completed the link:reset-switch-9332d.html[Reset a switch to factory default settings] procedure.

.About this task
When you completed the initial switch setup, you should have responded with `yes` to confirm SSH was enabled (the default) and entered the type of SSH keys you wanted to generate.

//SSH key default is rsa. You can add more keys for additional layers of security. For example, you can add ecdsa keys, which are more secure than rsa keys. If you want to add ecdsa keys, you can use the `ssh key generate ecdsa` command.

//Not needed because example seems generic: The examples shown in this procedure are for AFX A1K systems with switches running NX-OS 10.4.2 and RCF 10.0. If you have an AFX A2K system, the output will vary.

.Steps

. Verify that SSH is enabled:
+ 

[subs=+quotes]
----
(switch) *show ssh server*
ssh version 2 is enabled
----

. Verify that the SSH keys are enabled:
+
`show ssh key`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(switch)# *show ssh key*

**************************************
rsa Keys generated:Wed May 14 18:49:37 2025

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCndfdJesautdCwk5Mk/7pKOFl0IeShc9uBtj74F52vbjyf1FHOCXX7Xf3Vopxs6L1hbzgCpFLo9E7pZBd3I+1AoLyQULtR3svzNieGY8mlWZGLtpKf/P2fDCd8JVJaejrwQhm49WUPiC6ziEqBDMOGhJpD2e9++umyDdr6
NbmK8Q==


bitcount:1024
fingerprint:
SHA256:QtNU+Qq2I4ZfYwEfMEB1+z8w7xaKTlantTdsjLBx+OU
**************************************
could not retrieve dsa key information
**************************************
ecdsa Keys generated:Wed May 14 18:50:56 2025


ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAYnv17T+JlGmH8rg81xiOow0mPmkbkIG0o7h9EchixO3i3KjgQr8AwqkRHNTcQC3lRnizhJFUeMGCwuQTurziRCwE6fAOkWa2MRyXA1DYRKKXjVEOnW9+MvinMipHQ0cCc
YSExhh7j4HvWHIuYv8RmD7e3rmDQFlyyiLwdmpGfas2yaw==


bitcount:521
fingerprint:
SHA256:7cpZ5NGnIq5Iamw67ke+9o4qG9D3xxmGPauVl4X5934
**************************************

(switch)# *show feature | include scpServer*
scpServer              1          enabled
(switch)# *show feature | include ssh*
sshServer              1          enabled
(switch)#
----
====

.What's next?

After you've verified SSH and SSH keys are enabled, you link:../switch-cshm/config-overview.html[configure cluster switch health monitoring].

Additionally, if you configured your switch as part of a new AFX A1K or AFX A2K system installation, you must then link:complete-cluster-setup.html[complete the AFX system setup].


// New content for OAM project, AFFFASDOC-331, 2025-MAY-06
// Refactored content project, GH#423 2026-APR-MAY