---
permalink: switch-cisco-9332d-gx2b/configure-install-upgrade-nxos-overview-9332d.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b
summary: You can install or upgrade the NX-OS on the Nexus 9332D-GX2B switches for AFX 1K and AFX 2K systems.
---
= Install or upgrade the NX-OS overview - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
You can install or upgrade the NX-OS on the Nexus 9332D-GX2B switches for AFX 1K and AFX 2K systems. 

NOTE: NX-OS installation or upgrade is independent of RCF installation or upgrade. If you are installing or upgrading both the NX-OS and RCF, it is recommended you install or upgrade NX-OS first. 

NOTE: Do not upgrade or downgrade your NX-OS version to an unsupported version.


* link:configure-install-nxos-9332d.html[Install the NX-OS]
+
You install the NX-OS on the switches as part of a new AFX 1K or AFX 2K system installation, a switch replacement, or a switch reset to factory default settings.

* link:configure-upgrade-nxos-9332d.html[Upgrade the NX-OS]
+
You upgrade the NX-OS on the switches to support new hardware or a new ONTAP version on your AFX 1K or AFX 2K system.




// New topic and refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN


