---
permalink: switch-cisco-9332d-gx2b/install-nxos-overview-9332d-cluster.html
sidebar: sidebar
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2
summary: The Cisco NX-OS software and reference configuration files \(RCFs\) must be installed on Cisco Nexus 9332D-GX2B cluster switches.
---
= Prepare to install NX-OS software and RCF

:icons: font
:imagesdir: ../media/

[.lead]
Before you install the NX-OS software and the Reference Configuration File (RCF), follow this procedure.

.About the examples
The examples in this procedure use the following switch and node nomenclature:

* The names of the two Cisco switches are cs1 and cs2.
* The node names are node1-01, node1-02, node1-03, and node1-04.
* The cluster LIF names are node1-01_clus1 and node1-01_clus2 for node1-01, node1-02_clus1 and node1-02_clus2 for node1-02, node1-03_clus1 and node1-03_clus2 for node1-03, and node1-04_clus1 and node1-04_clus2 for node1-04.
* The `cluster1::*>` prompt indicates the name of the cluster.

.About this task
The procedure requires the use of both ONTAP commands and Cisco Nexus 9000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

.Steps

. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message: `system node autosupport invoke -node * -type all -message MAINT=x h`
+
where x is the duration of the maintenance window in hours.
+
NOTE: The AutoSupport message notifies technical support of this maintenance task so that automatic case creation is suppressed during the maintenance window.

. Change the privilege level to advanced, entering *y* when prompted to continue:
+
[source,cli]
----
set -privilege advanced
----
+
The advanced prompt (`*>`) appears.

. Display how many cluster interconnect interfaces are configured in each node for each cluster interconnect switch: 
+
[source,cli]
----
network device-discovery show -protocol cdp
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-02/cdp
            e10a   cs01(FLM284504N6)         Ethernet1/16/3    N9K-C9332D-GX2B
            e10b   cs01(FDO2846056X)         Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs01(FLM284504N6)         Ethernet1/16/4    N9K-C9332D-GX2B
            e11b   cs01(FDO2846056X)         Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs01(FLM284504N6)         Ethernet1/16/1    N9K-C9332D-GX2B
            e1b    cs01(FDO2846056X)         Ethernet1/13/1    N9K-C9364D-GX2A
            e2a    cs02(FLM284504R2)         Ethernet1/8       N9K-C9332D-GX2B
            e2b    cs02(FDO28390Q24)         Ethernet1/7       N9K-C9364D-GX2A
            e3a    cs02(FLM284504R2)         Ethernet1/7       N9K-C9332D-GX2B
            e3b    cs02(FDO28390Q24)         Ethernet1/8       N9K-C9364D-GX2A
            e7a    cs01(FLM284504N6)         Ethernet1/16/2    N9K-C9332D-GX2B
            e7b    cs01(FDO2846056X)         Ethernet1/13/2    N9K-C9364D-GX2A

node1-01/cdp
            e10a   cs01(FLM284504N6)         Ethernet1/16/3    N9K-C9332D-GX2B
            e10b   cs01(FDO2846056X)         Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs01(FLM284504N6)         Ethernet1/16/4    N9K-C9332D-GX2B
            e11b   cs01(FDO2846056X)         Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs01(FLM284504N6)         Ethernet1/16/1    N9K-C9332D-GX2B
            e1b    cs01(FDO2846056X)         Ethernet1/13/1    N9K-C9364D-GX2A
            e2a    cs02(FLM284504R2)         Ethernet1/8       N9K-C9332D-GX2B
            e2b    cs02(FDO28390Q24)         Ethernet1/7       N9K-C9364D-GX2A
            e3a    cs02(FLM284504R2)         Ethernet1/7       N9K-C9332D-GX2B
            e3b    cs02(FDO28390Q24)         Ethernet1/8       N9K-C9364D-GX2A
            e7a    cs01(FLM284504N6)         Ethernet1/16/2    N9K-C9332D-GX2B
            e7b    cs01(FDO2846056X)         Ethernet1/13/2    N9K-C9364D-GX2A

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e0a    cs1                       Eth1/2            N9K-C9336C
            e0b    cs2                       Eth1/2            N9K-C9336C
cluster1-01/cdp
            e0a    cs1                       Eth1/1            N9K-C9336C
            e0b    cs2                       Eth1/1            N9K-C9336C

4 entries were displayed.
----
====

. Check the administrative or operational status of each cluster interface.

.. Display the network port attributes: 
+
[source,cli]
----
network port show -ipspace Cluster
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.

Node: cluster1-02
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: cluster1-01
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====

.. Display information about the LIFs: 
+
[source,cli]
----
network interface show -vserver Cluster
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
cluster1::*> *network interface show -vserver Cluster*

----
            Logical       Status     Network            Current       Current Is
Vserver     Interface     Admin/Oper Address/Mask       Node          Port    Home
----------- ------------- ---------- ------------------ ------------- ------- ----
Cluster
            node1-01_clus1 up/up     169.254.36.44/16   node1-01      e7a     true
            node1-01_clus2 up/up     169.254.7.5/16     node1-01      e7b     true
            node1-02_clus1 up/up     169.254.197.206/16 node1-02      e7a     true
            node1-02_clus2 up/up     169.254.195.186/16 node1-02      e7b     true
            node1-03_clus1 up/up     169.254.192.49/16  node1-03      e7a     true
            node1-03_clus2 up/up     169.254.182.76/16  node1-03      e7b     true
            node1-04_clus1 up/up     169.254.59.49/16   node1-04      e7a     true
            node1-04_clus2 up/up     169.254.62.244/16  node1-04      e7b     true

8 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*

            Logical            Status     Network            Current       Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node       steswitch-vin   Port    Home
----------- ------------------ ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.209.69/16  cluster1-01   e0a     true
            cluster1-01_clus2  up/up      169.254.49.125/16  cluster1-01   e0b     true
            cluster1-02_clus1  up/up      169.254.47.194/16  cluster1-02   e0a     true
            cluster1-02_clus2  up/up      169.254.19.183/16  cluster1-02   e0b     true

4 entries were displayed.
----
====

. Verify the connectivity of the remote cluster interfaces: 
+
// start of tabbed content

[role="tabbed-block"]

====

.ONTAP 9.9.1 and later

--
You can use the `network interface check cluster-connectivity` command to start an accessibility check for cluster connectivity and then display the details: 

`network interface check cluster-connectivity start` and `network interface check cluster-connectivity show`

[subs=+quotes]
----
cluster1::*> *network interface check cluster-connectivity start*
----

*NOTE:* Wait for a number of seconds before running the `show` command to display the details.


[subs=+quotes]
----
cluster1::*> *network interface check cluster-connectivity show*

                                  Source           Destination     Packet
Node   Date                       LIF              LIF             Loss
------ -------------------------- ---------------- --------------- -----------
node1-01
       6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1   none
       6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus1   none 


node1-02
       6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1   none
       6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2   none 
.
.
.


                                  Source               Destination         Packet
Node   Date                       LIF                  LIF                 Loss
------ -------------------------- -------------------- ------------------- -----------
node1
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2    cluster1-02-clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2    cluster1-02_clus2   none
node2
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2    cluster1-01_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2    cluster1-01_clus2   none
----
--

.All ONTAP releases
--
For all ONTAP releases, you can also use the `cluster ping-cluster -node <name>` command to check the connectivity:

`cluster ping-cluster -node <name>`


[subs=+quotes]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e0a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e0b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e0a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====

// end of tabbed content

[start=6]
. [[step6]] Verify that the auto-revert command is enabled on all cluster LIFs: 
+
[source,cli]
----
network interface show -vserver Cluster -fields auto-revert
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
        Logical
Vserver Interface          Auto revert
------- ------------------ -----------
Cluster node1-01_clus1     true        
Cluster node1-01_clus2     true        
Cluster node1-02_clus1     true        
Cluster node1-02_clus2     true        
Cluster node1-03_clus1     true        
Cluster node1-03_clus2     true        
Cluster node1-04_clus1     true        
Cluster node1-04_clus2     true    

8 entries were displayed.

          Logical
Vserver   Interface           Auto-revert
--------- ------------------- ------------
Cluster
          cluster1-01_clus1   true
          cluster1-01_clus2   true
          cluster1-02_clus1   true
          cluster1-02_clus2   true
4 entries were displayed.
----
====


//include::../_include/prepare-install-software-9336c.adoc[]

//link:install-nxos-software-9332d-cluster.html[Install or upgrade the NX-OS software]

// New content for OAM project, AFFFASDOC-331, 2025-MAY-06