---
permalink: switch-cisco-9332d-gx2b/install-hardware.html
sidebar: sidebar
keywords: switches, hardware installation, Cisco Nexus, 9332D-GX2B switches
summary: Installing the Cisco Nexus 9332D-GX2B switches as part of a new AFX A1K or AFX A2K system installation includes installing the switches into a rack or cabinet, cabling them to the system controllers and shelves, and then powering them on.
---
= Install the switches - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
Installing the Cisco Nexus 9332D-GX2B switches as part of a new AFX A1K or AFX A2K system installation includes installing the switches into a rack or cabinet, cabling them to the system controllers and shelves, and then powering them on.

.Before you begin
You must have completed the switch preparation steps in link:install-prepare-9332d-cluster.html[Prepare to install the switches].

.About this task

You use the applicable AFX A1K or AFX A2K system install and setup workflow on the AFX system documentation site to install and cable the system hardware, and then power on the switches. 

The system install and setup workflow includes instructions such as:

* Instructions for getting the site ready, unpacking the boxes and comparing the contents of the boxes to the packing slip, and registering the system to access support benefits.

* Instructions for installing the switches, controllers, and storage shelves in a NetApp cabinet or telco rack.

* Instructions for cabling your system, including cabling the controller storage to switch connections and cabling the shelves to switch connections.

//* After you have installed the switches, the AFX install and setup workflow instructions redirect you back to this switch documentation to complete the switch setup, which includes completing the initial switch setup, installing the NX-OS software and RCF, verifying SSH is enabled, configuring health monitoring and optionally, configuring Smart Call Home.

.Steps

. Install the switches as part of your AFX A1K or AFX A2K system installation and setup procedure.
+
Follow the instructions in the applicable workflow to install the switches, controllers, and storage shelves in a NetApp cabinet or telco rack, cable the system (including the switches), and then power on the switches.

* For an AFX A1K system, go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html[AFX A1K install and setup workflow^].

* For an AFX A2K system, go to the link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/install-setup-workflow.html[AFX A2K install and setup workflow^]. 

Lisa: the above A2K link won't work until A2K site goes live. For now, can link to the AFX site preview draft of the topic: 

https://review.docs.netapp.com/us-en/ontap-afx_working-afx-emr-dr/install-afx-2k/install-setup-workflow.html


NOTE: After you have installed the switches, the AFX install and setup workflow instructions redirect you back to this switch documentation to configure the switches.

// which includes completing the initial switch setup, installing the NX-OS software and RCF, verifying SSH is enabled, configuring health monitoring and optionally, configuring Smart Call Home.

.What's next?

After you've installed, cabled, and powered on your switches as part of your AFX A1K or AFX A2K system installation, you link:https://review.docs.netapp.com/us-en/ontap-systems-switches_hotfix-refactor-phase1/switch-cisco-9332d-gx2b/install-configure-switches-in-afx-workflow-9332d.html#configure-switches[configure your switches] and then link:https://review.docs.netapp.com/us-en/ontap-systems-switches_hotfix-refactor-phase1/switch-cisco-9332d-gx2b/install-configure-switches-in-afx-workflow-9332d.html#complete-afx-system-setup[complete the AFX system setup].

//Not using: After you've installed, cabled, and powered on your switches as part of your AFX A1K or AFX A2K system installation and setup procedure, you link:setup-switch-9332d-cluster.html[complete the initial switch setup].


// New content for OAM project, AFFFASDOC-331, 2025-MAY-06
// Refactor content project phase 1 with A2K content, GH#423 2026-JUN