---
sidebar: sidebar
permalink: switch-cisco-9332d-gx2b/install-prepare-9332d-cluster.html
keywords: shared storage cluster switch
summary: For Cisco Nexus 9332D-GX2B switch installation and setup for a new AFX storage system, be sure to understand aspects of the switch and its installation by reviewing the applicable Cisco switch documentation and ONTAP systems documentation. Additionally, you should understand the switch port configuration and consider using Smart Call Home.
---
= Prepare to install the switches - Cisco Nexus 9332D-GX2B -TEST
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before installing Cisco Nexus 9332D-GX2B switches as part of a new AFX system installation, you need to understand aspects of the switch and its installation by reviewing the applicable Cisco switch documentation and ONTAP systems documentation, understanding the switch port configuration for your RCF version, and considering the use of Smart Call Home.

=== Step 1: Review the Cisco switch documentation
Review the following Cisco install and setup documents so you are familiar with the switch release notes, safety information, installation options, initial software configuration, and command references.

All of the Cisco documents are available on the link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches Support^] page.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html[Cisco Nexus 9000 Series NX-OS Release Notes^] (choose the notes for the NX-OS release installed on your switches)

* link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch[Regulatory Compliance and Safety Information for Cisco Nexus 9000 Series^]

* link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-nx-os-mode-switch-hardware-installation-guide/m_installing-the-switch-chassis-new-1ru-rack-mount.html[Cisco Nexus 9332D-GX2B NX-OS Mode Switch Hardware Installation Guide^]

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html[Cisco Nexus 9000 Series Switch Software Configuration Guides^] (choose the guide for the NX-OS release installed on your switches)

* link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html[Cisco Nexus 9000 Series NX-OS Command Reference^]
Provides links to the various command references provided by Cisco.

=== Step 2: Review the NetApp systems documentation
Review the following NetApp systems documentation so you are familiar with the AFX system installation, ONTAP release information, and hardware configuration and compatibility requirements.

* link:https://docs.netapp.com/us-en/ontap-afx/index.html[AFX systems documentation^] Describes how to install NetApp hardware.

* link:https://docs.netapp.com/us-en/ontap-family/[ONTAP documentation^] Provides detailed information about all aspects of the ONTAP releases.

* link:https://hwu.netapp.com[Hardware Universe^]
Provides NetApp hardware configuration and compatibility information.

* link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU[What additional information do I need to install my equipment that is not in HWU?^]
Provides more information about storage system installation requirements.

=== Step 3: Understand the switch port configuration
Understand the configuration of switch ports (breakout ports and non-breakout ports) so that you can determine connectivity for your AFX system.

//For ELMR (need to add ELMR):
//ELMR: Understand the preset configuration of switch port speeds (breakout ports 100GbE and non-breakout ports) so that you can determine if you need to change the port speed mix to accommodate a different port speed configuration for your ELMR system.

The following table shows the preset groupings of the switch's ports, their port speeds, and usage based on RCF version 10.0. (This is the only supported version of RCF.)

//ELMR: The following table shows the preset groupings of the switch's ports, their port speeds, and usage based on RCF version 10.1, which is only supported on switches in ELMR systems. (need to add a new table). Note, you can change the mix of breakout and non-breakout ports when your system configuration requires it. You can do this as part of your switch setup later in the installation and setup process (after installing RCF).

//Use for note text instead?: Note, You can change the number of switch ports in breakout mode (4x100GbE) and 400GbE mode when you need to accommodate a different port speed configuration for your system. (This text came form change port speed topic...which needs to be hidden when I PR my hotfix branch).

Switch port information can also be found in the https://hwu.netapp.com[NetApp Hardware Universe^].

[options="header" cols="1,2"]
|===
| Switch port groups | Port speeds and usage
a|
Ethernet1/1/1-4 to Ethernet1/30/1-4
a|
4x100GbE mode for cluster, HA, and storage connections 
a|
Ethernet1/31, Ethernet1/32
a|
400GbE ISL
a|
|===

=== Step 4: Consider using Smart Call Home
Cisco Smart Call Home is an option to provide proactive support and help you resolve any issues that might arise with the switches. However, the switch installation and setup instructions have you configure switch health monitoring (CSHM), which provides the same level of support. 

.Steps

. Familiarize yourself with Smart Call Home and the requirements for using it by reviewing the link:smart-call-9332d-cluster.html[configure Smart Call Home] documentation.

. If you decide to use Smart Call Home, you are instructed to configure it later in the link:configure-switch-overview-9332d-cluster.html[Install and setup workflow].

NOTE: Smart Call Home can be configured at any time after you have installed and setup your switches as part of the AFX storage system installation.

.What's next?

After you've prepared to install your switches, you link:install-hardware.html[install the switches and AFX storage system].

// New content for OAM project, AFFFASDOC-331, 2025-MAY-08
// AFFFASDOC-473, 2026-MAR-18
// Refactored content project, GH#423 2026-APR-MAY
