---
permalink: switch-cisco-9332d-gx2b/install-upgrade-rcf-overview-cluster.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b
summary: 'You can install the RCF after setting up the Nexus 9332D-GX2B switch for the first time. You can also use this procedure to upgrade your RCF version.'
---
= Install or upgrade the RCF overview - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
You can install or upgrade the reference configuration file (RCF) on your Nexus 9332D-GX2B switches depending on your situation. 

You install the RCF on the switches as part of a new AFX system installation, a switch replacement, or a reset to factory default settings.

You update the RCF on the switches to support a different RCF configuration, if available. For example, if you have RCF version 10.0, which only supports breakout mode (4x100GbE), and you want to change a number of port speeds to support 400GbE, you would need to update to RCF version 10.1. But you also need to have an AFX A2K system to use RCF version 10.1.

Lisa: You can't have any EMR content in here when your hotfix branch is published because it will be before EMR content goes live Jul. Maybe make a 2nd file with "EMR" so you can swap them out in folder and sidebar.yml for EMR July RTS? 

RCF installation or upgrade is independent of NS-OS installation or upgrade.

//You update the RCF on the switches to support new features or changes in the network environment.

//You update the RCF on the switches to support new hardware, a new ONTAP version, or to align with a new NX-OS version.

//Lisa: you need to make another version of this topic specific to 9364. Today they are exactly the same content - double check that - but just have diff file names and lead stated the specific switch model. Really should make include file for this topic content. 


.Available RCF configurations

Depending on your system type, AFX A2K or AFX A1K, you use the applicable RCF version:

* AFX A2K (with 9332 switches)

Switch   : NX9332D-GX2B
Filename : RCF-v10.1-NX9332D-GX2B-CL1-V1.txt
Date     : 04-21-2026
Version  : v10.1
Port Usage:
Ports    1-14: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-14}/1-4
Ports   15-30: 400GbE Intra-Cluster/HA/Storage Ports, int e1/{15-30}
Ports   31-32: Intra-Cluster ISL Ports, int e1/31-32

* AFX A2K (with 9364 switches)

Lisa: move this to the 9364 topic...maybe can't have include files?

Switch   : NX9364D-GX2A
Filename : RCF-v10.1-NX9364D-GX2A-CL1-V1.txt
Date     : 03-16-2026
Version  : v10.1
Port Usage:
Ports    1-13: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-13}/1-4
Ports   14-62: 400GbE Intra-Cluster/HA/Storage Ports, int e1/{14-62}
Ports   63-64: Intra-Cluster ISL Ports, int e1/63-64

* AFX A1K with 9332 switches

*Cluster-HA-Storage AFX* - All ports are configured in 4x100GbE breakout mode that universally supports AFX node clusters, HA, storage ports, and NX224 storage shelf ports. 400GbE ISL between switches. (_Cluster-HA-Storage AFX RCF_vxx.x_).

How come the RCF version isn't here? 10.0

For specific port and VLAN usage details, refer to the banner and important notes section in your RCF. Refer to link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches^] for more information.

//FYI:
//NetApp Reference Configuration File (RCF)

//* Switch   : NX9808
//* Filename : RCF-v10.1-NX9808-CL1-ST1.txt
//* Date     : 04-15-2026
//* Version  : v10.1
//* Port Usage:
//* Ports   1-18 (LC1-LC8) : 400GbE Cluster/Storage/HA ports.
//* Ports   19-35 (LC1-LC8): 4 * 100 GbE Storage shelf ports, int e1-e8/{19-35}/1-4
//* Port    36 (LC1-LC8)   : Intra-Cluster ISL Ports, int e1-e8/36

.Suggested documentation
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches (NSS)^]
+
Consult the switch compatibility table for the supported ONTAP and RCF versions on the NetApp Support Site. Note that there can be command dependencies between the command syntax in the RCF and the syntax found in specific versions of NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches^]
+
Refer to the appropriate software and upgrade guides available on the Cisco website for complete documentation on the Cisco switch upgrade and downgrade procedures.

.About the procedures
* The examples in this procedure use the following switch and node nomenclature:

** The names of the two Cisco switches are cs1 and cs2.
** The node names are node1-01, node1-02, node1-03, and node1-04.
** The cluster LIF names are node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1, and node1-04_clus2.
** The `cluster1::*>` prompt indicates the name of the cluster.

* The procedures require the use of both ONTAP commands and Cisco Nexus 9000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

.Prepare for the installation or upgrade
Before you begin the installation or upgrade, ensure that you do the following:

. Refer to the https://hwu.netapp.com/SWITCH/INDEX[Hardware Universe^] to verify the correct ports on your platform.
+
NOTE: The command outputs might vary depending on different releases of ONTAP.

. Refer to the Knowledge Base article link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity[How to clear configuration on a Cisco interconnect switch while retaining remote connectivity^] for further information when installing or upgrading your RCF.

.What's next?

After you've reviewed the install or upgrade RCF overview, you link:install-rcf-software-9332d-cluster.html[install the RCF] or link:upgrade-rcf-software-9332d-cluster.html[upgrade your RCF] as required.

// New content for OAM project, AFFFASDOC-331, 2025-MAY-06
// AFFFASDOC-372, 2025-NOV-25
// AFFFASDOC-473, 2026-MAR-16
// Refactored content project, GH#423 2026-APR-MAY