---
permalink: switch-cisco-9332d-gx2b/install-hardware.html
sidebar: sidebar
keywords: switches, hardware installation, Cisco Nexus, 9332D-GX2B switches
summary: 'Details on how to install and setup the switch hardware and controller hardware for your system.'
---
= Install hardware - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
Installing the Cisco Nexus 9332D-GX2B switches into a rack or cabinet is part of the overall installation and setup of a new AFX system. You use the AFX system install and setup workflow to install and cable the system hardware, then you power on the switches. You are directed back to this workflow to complete the switch setup, which includes performing the initial switch setup, installing the NX-OS software and RCF, verifying SSH is enabled, configuring health monitoring and optionally, configuring Smart Call Home.

//The workflow includes instructions for installing the switches, controllers, and storage shelf in a NetApp cabinet or telco rack, as well as instructions for cabling your system.

Go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html[AFX install and setup workflow^] and complete the steps to install and setup the switch hardware and controller hardware for your system.

.Before you begin
You have completed the preparation steps for installing the Cisco Nexus 9332D-GX2B switches and are ready to install the hardware. If you have not completed the preparation steps, see:install-prepare-9332d-cluster.html[Prepare to install the Cisco Nexus 9332D-GX2B switches^].

.About this task
The AFX install and setup workflow includes instructions such as:

* Instructions for getting the site ready, unpacking the boxes and comparing the contents of the boxes to the packing slip, and registering the system to access support benefits.

* Instructions for installing the switches, controllers, and storage shelf in a NetApp cabinet or telco rack.

* Instructions for cabling your system, including cabling the controller storage to switch connections and cabling the shelf to switch connections.

.Steps
. Install the switches in a rack or cabinet and power them on as part of the installation and setup for your AFX system.
+
Go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html[AFX install and setup workflow^]

.What's next?

After you've installed and cabled your switches and system hardware, and powered on the switches, the AFX system installation and setup documentation directs back to this switch documentation to complete the switch setup, which includes initial switch setup, installing the NX-OS software and RCF, verifying SSH is enabled, configuring health monitoring and optionally, configuring Smart Call Home. link:configure-software-overview-9332d-cluster.html[configure the switch software and RCF].(Lisa: this isn't the correct link/text. You want to link to configure switch or back to switch install workflow?)

// New content for OAM project, AFFFASDOC-331, 2025-MAY-06