---
permalink: switch-cisco-9332d-gx2b/install-hardware.html
sidebar: sidebar
keywords: switches, hardware installation, Cisco Nexus, 9332D-GX2B switches
summary: 'Details on how to install and setup the switch hardware and controller hardware for your system.'
---
= Install hardware - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
Installing and setting up the Cisco Nexus 9332D-GX2B switches is part of the overall installation and setup of the new AFX system. You use the AFX system install and setup workflow. The workflow includes instructions for installing the switches, controllers, and storage shelf in a NetApp cabinet or telco rack, as well as instructions for cabling your system.

Go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html[AFX install and setup workflow^] and complete the steps to install and setup the switch hardware and controller hardware for your system.

.Before you begin
You have completed the preparation steps for installing the Cisco Nexus 9332D-GX2B switches and are ready to install the hardware. If you have not completed the preparation steps, see:install-prepare-9332d-cluster.html[Prepare to install the Cisco Nexus 9332D-GX2B switches^].

.About this task
The AFX install and setup workflow includes instructions such as:

* Instructions for getting the site ready, unpacking the boxes and comparing the contents of the boxes to the packing slip, and registering the system to access support benefits.

* Instructions for installing the switches, controllers, and storage shelf in a NetApp cabinet or telco rack.

* Instructions for cabling your system, including cabling the controller storage to switch connections and cabling the shelf to switch connections.

.Steps
. Install and setup the switch hardware and controller hardware for your system.
+
Go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html[AFX install and setup workflow^]

.What's next?

After you've installed your switches and system hardware (and powered on and completed the initial setup?), you link:configure-software-overview-9332d-cluster.html[configure the switch software and RFC].

// New content for OAM project, AFFFASDOC-331, 2025-MAY-06