---
sidebar: sidebar
permalink: switch-cisco-9332d-gx2b/install-prepare-9332d-cluster.html
keywords: shared storage cluster switch
summary: Before installing Cisco Nexus 9332D-GX2B switches as part of a new AFX A1K or AFX A2K system installation, you should understand aspects of the switch and its installation by reviewing the applicable Cisco switch documentation and ONTAP systems documentation, understand the RCF versions supported for AFX systems, and consider using Smart Call Home.
---
= Prepare to install the switches - Cisco Nexus 9332D-GX2B
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before installing Cisco Nexus 9332D-GX2B switches as part of a new AFX A1K or AFX A2K system installation, you should understand aspects of the switch and its installation by reviewing the applicable Cisco switch documentation and ONTAP systems documentation, understand the RCF versions supported for AFX systems, and consider using Smart Call Home.

=== Step 1: Review the Cisco switch documentation
You should review the following Cisco install and setup documents so you are familiar with the switch release notes, safety information, installation options, initial software configuration, and command references.

All of the Cisco documents are available on the link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches Support^] page.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html[Cisco Nexus 9000 Series NX-OS Release Notes^] (choose the notes for the NX-OS release installed on your switches)

* link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch[Regulatory Compliance and Safety Information for Cisco Nexus 9000 Series^]

* link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-nx-os-mode-switch-hardware-installation-guide/m_installing-the-switch-chassis-new-1ru-rack-mount.html[Cisco Nexus 9332D-GX2B NX-OS Mode Switch Hardware Installation Guide^]

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html[Cisco Nexus 9000 Series Switch Software Configuration Guides^] (choose the guide for the NX-OS release installed on your switches)

* link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html[Cisco Nexus 9000 Series NX-OS Command Reference^]
Provides links to the various command references provided by Cisco.

=== Step 2: Review the NetApp systems documentation
You should review the following NetApp systems documentation so you are familiar with the AFX A1K or AFX A2K system installation, ONTAP release information, and hardware configuration and compatibility requirements.

* link:https://docs.netapp.com/us-en/ontap-afx/index.html[AFX systems documentation^] Describes how to install NetApp hardware.

* link:https://docs.netapp.com/us-en/ontap-family/[ONTAP documentation^] Provides detailed information about all aspects of the ONTAP releases.

* link:https://hwu.netapp.com[Hardware Universe^]
Provides NetApp hardware configuration and compatibility information.

* link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU[What additional information do I need to install my equipment that is not in HWU?^]
Provides more information about storage system installation requirements.

//=== Step 3: Determine your port speed configuration needs for AFX A2K systems

//If your switches are in an AFX A2K system, RCF 10.1 is supported, which has a mix of breakout (4x100GbE) mode ports and 400GbE mode ports. The following table shows the preset port speeds configuration.

//Determine the port speed configuration you need for your AFX A2K system connectivity based on RCF 10.1, the supported version of RCF on switches in AFX A2K systems at the initial release of ONTAP 9.19.1GA.

//RCF 10.1(supported at initial release of ONTAP 9.19.1GA on switches in AFX A2K systems) has the following preset port speed configuration.

//For the current list of supported RCF versions, see the link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^] page.

//[options="header" cols="1,2"]
//|===
//| Switch port groups | Port speeds and usage
//a|
//Ethernet1/1/1-4 to Ethernet1/14/1-4
//a|
//4x100GbE mode for Intra-cluster, HA, and storage connections 
//a|
//Ethernet1/15 to Ethernet1/30
//a|
//400GbE mode for Intra-cluster, HA, and storage connections 
//a|
//Ethernet1/31, Ethernet1/32
//a|
//400GbE Intra-cluster ISL connections
//a|
//|===


=== Step 3: Understand the RCF versions supported for AFX systems
The type of system (AFX A1K or AFX A2K) your switches are in determines the supported version of RCF. Understand the preset configuration of switch ports for the version of RCF supported by your AFX system.

* If you have an AFX A1K system, RCF 10.0 is supported:
+
The following table shows the preset groupings of the switch ports, their port speeds, and usage based on RCF version 10.0. (This is the only supported version of RCF.)
+
Switch port information can also be found in the https://hwu.netapp.com[NetApp Hardware Universe^].
+
[options="header" cols="1,2"]
|===
| Switch port groups | Port speeds and usage
a|
Ethernet1/1/1-4 to Ethernet1/30/1-4
a|
4x100GbE mode for cluster, HA, and storage connections 
a|
Ethernet1/31, Ethernet1/32
a|
400GbE ISL
|===
+
* If you have an AFX A2K system, RCF 10.1 is supported:
+
//Understand the preset configuration of switch port speeds (breakout ports 100GbE and non-breakout ports) so that you can determine if you need to change the port speed mix to accommodate a different port speed configuration for your AFX A2K system.
+
The following table shows the preset groups of the switch ports, their port speeds, and usage based on RCF version 10.1. (This is the only supported version of RCF at initial release of ONTAP 9.19.1GA.)
+
Current switch port information be found in the https://hwu.netapp.com[NetApp Hardware Universe^].
+
[options="header" cols="1,2"]
|===
| Switch port groups | Port speeds and usage
a|
Ethernet1/1/1-4 to Ethernet1/14/1-4
a|
4x100GbE mode for Intra-cluster, HA, and storage connections 
a|
Ethernet1/15 to Ethernet1/30
a|
400GbE mode for Intra-cluster, HA, and storage connections 
a|
Ethernet1/31, Ethernet1/32
a|
400GbE Intra-cluster ISL connections
|===
+
[NOTE]
====
You can change the preset groups to adjust the number of switch ports in breakout mode (4x100GbE) and 400GbE mode when you need to accommodate a different port speed configuration for your AFX A2K system.
//This above text came from change port speed topic.

You do this later, as part of the RCF installation procedure.

//You do this later as part of your switch setup process, after you install the RCF on your switches by using the link:change-port-speed-9332d-cluster.html[Change port speed configuration] procedure.
====

//NOTE: You can change the mix of breakout and non-breakout ports when your system configuration requires it. You can do this as part of your switch setup later in the installation and setup process (after installing RCF).

=== Step 4: Consider using Smart Call Home
Cisco Smart Call Home is an option to provide proactive support and help you resolve any issues that might arise with the switches. However, the switch installation and setup instructions have you configure switch health monitoring (CSHM), which provides the same level of support. 

.Steps

. Familiarize yourself with Smart Call Home and the requirements for using it by reviewing the link:smart-call-9332d-cluster.html[configure Smart Call Home] documentation.

. If you decide to use Smart Call Home, you are instructed to configure it later in the link:install-configure-switches-in-afx-workflow-9332d.html[Install and configure switches in an AFX system workflow]. 

NOTE: Smart Call Home can be configured at any time after you have installed and setup your switches as part of the AFX storage system installation.

.What's next?

After you've prepared to install your switches, you link:install-hardware.html[install the switches].

// New content for OAM project, AFFFASDOC-331, 2025-MAY-08
// AFFFASDOC-473, 2026-MAR-18
// Refactored content project, GH#423 2026-APR-MAY
