---
permalink: switch-cisco-9332d-gx2b/install-rcf-software-9332d-cluster.html
sidebar: sidebar
keywords: install rcf, cisco switches
summary: You install the RCF on new Cisco Nexus 9332D-GX2B switch(es) as part of a new AFX system installation and setup, replacing a failed switch, or resetting a switch to factory defaults.
---
= Install the RCF - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
You install the RCF on new Cisco Nexus 9332D-GX2B switch(es) as part of a new AFX system installation and setup, replacing a failed switch, or resetting a switch to factory defaults.

.Before you begin

* You must have read the     link:install-upgrade-rcf-overview-cluster.html[Install or upgrade RCF overview] page.
* The following must be completed for each switch:
** Each switch must be cabled to the system and each other (by ISL connections), and powered on using the link:install-hardware.html[Install Hardware] procedure. 
** The initial switch setup must be completed using the link:setup-switch-9332d-cluster.html[Setup Switches] procedure. 
** The desired NX-OS version must be installed using the link:install-nxos-software-9332d-cluster.html[Install NX-OS] procedure.
** You must have completed the link:install-nxos-overview-9332d-cluster.html[prepare to install NX-OS and RCF] procedure.
//** The RCF file must be obtained from NetApp. For more information, see the link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^] page. Hey: this is being handled in the prepare to install nxos and rcf topic...
* Each switch must be connected to a console or you must have remote access to each switch.

.About this task
* The type of AFX system your switches are in determines the supported versions of RCF for your switches.

** For switches in an AFX A1K system, running any supported version of ONTAP, RCF 10.0 is the only supported version.

** For switches in an AFX A2K system, running ONTAP 9.19.1GA or later, RCF 10.1 is the only supported version at the initial release of ONTAP 9.19.1GA.
+
For the current list of supported RCF versions, see the link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^] page.

NOTE: Do not upgrade or downgrade your RCF version to an unsupported version.

* If you have installed switches as part of a new AFX system installation, you install the RCF on one switch at a time. This procedure has you install the RCF on the first switch (cs1) and then has you repeat the steps for the second switch (cs2).

* The examples shown in this procedure are for AFX A1K systems with switches running NX-OS 10.4.2 and RCF 10.0. If you have an AFX A2K system, the output will vary.
 

.Steps

. Login to switch cs1 using SSH or by using a serial console.
+
//May 3: SSH was supposedly enabled in the initial switch setup (config wizard), but in this topics What's next, it pints to the Verify SSH is enable topic, which is the correct new sys install workflow). Seems like mentioning SSH here is a bit confusing. Just leave it.

. Copy the RCF to the bootflash of switch cs1 using one of the following transfer protocols: FTP, TFTP, SFTP, or SCP. 
+
For more information on Cisco commands, refer to the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.
+
.Show example 
[%collapsible]
====
This example shows TFTP being used to copy an RCF to the bootflash on switch cs1:

[subs=+quotes]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9332D-GX2B-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====

. Apply the RCF previously copied to the bootflash.
+
For more information on Cisco commands, refer to the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.
+

This example shows the RCF file `NX9332D-GX2B-RCF-v10.0-Shared.txt` being installed on switch cs1:
+
[subs=+quotes]
----
cs1# *copy NX9332D-GX2B-RCF-v10.0-Shared.txt running-config echo-commands*
----

+
. Examine the banner output from the `show banner motd` command. You must read and follow these instructions to ensure the proper configuration and operation of the switch.
+
.Show example 
[%collapsible]

[subs=+quotes]
====
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9332D-GX2B
* Filename : NX9332D-GX2B-RCF-v10.0-Shared.txt
* Date     : 05-09-2025
* Version  : v10.0
* Port Usage:
* Ports  1-30: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-30}/1-4
* Ports 31-32: Intra-Cluster ISL Ports, int e1/31-32
*
* IMPORTANT NOTES
* Interface port-channel999 is reserved to identify the version of this file.
******************************************************************************
----
====

. Verify that the RCF file is the correct version: 
+
`show running-config`
+
When you check the output to verify you have the correct RCF, make sure that the following information is correct:

 ** The RCF banner
 ** The node and port settings
 ** Customizations
+
The output varies according to your site configuration. Check the port settings and refer to the release notes for any changes specific to the RCF that you have installed.

. If you have an AFX A2K system (which supports RCF 10.1 and later), complete the following substeps as needed:

.. Record any custom additions between the current `running-config` file and the RCF file in use.
+
You can link:change-port-speed-9332d-cluster.html[change the port speed configuration] for RCF 10.1 as needed.

.. After you verify that the RCF versions, custom additions, and switch settings are correct, copy the `running-config` file to the `startup-config` file.
+
----
cs1# copy running-config startup-config [########################################] 100% Copy complete
----

. Save basic configuration details to the `write_erase.cfg` file on the bootflash.
+
[NOTE]
====================================
Make sure to configure the following:

* Username and password
* Management IP address
* Default gateway
* Switch name
====================================
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`
+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`
+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`
+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`
+
Refer to the Knowledge Base article link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity[How to clear configuration on a Cisco interconnect switch while retaining remote connectivity^] for further details.

. Verify that the `write_erase.cfg` file is populated as expected:
+
`*show file bootflash:write_erase.cfg*`

. Issue the `write erase` command to erase the current saved configuration:
+
`cs1# *write erase*`
+
`Warning: This command will erase the startup-configuration.`
+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copy the previously saved basic configuration into the startup configuration.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Reboot the switch:
+
`cs1# *reload*`
+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repeat steps 1 through 10 on switch cs2.

//. Connect the ports of all nodes in the ONTAP cluster to switches cs1 and cs2.
//+ 
//The switches were already cabled as part of the install switches/hw topic that points to the AFX docs. Is it an issue for NX-OS and RCF if the switches were already cabled and powered on (in that order)????
//+
//This step only applies to installing switches as part of a new AFX system installation and setup and replacing a failed switch. It does not apply to resetting a switch since it's still cabled.


//I moved this section to a new topic in the sidebar under install and setup switches in a new AFX system. Because it  doesn't make sense here; the switch(es) were already cabled and powered as part of the AFX system hw install.
//== Step 2: Cable the switch(es) and verify the connections
//The following steps only apply if you installed switches as part of a new system installation and setup or replaced a failed switch. If you reset a switch to factory defaults, the switch is still cabled and powered on, so you can skip these steps.

//. Connect the ports of all nodes in the ONTAP cluster to switches cs1 and cs2.

//== Step 3: Set up your ONTAP cluster

//NetApp recommends that you use System Manager to set up new clusters. 

//System Manager provides a simple and easy workflow for cluster set up and configuration including assigning a node management IP address, initializing the cluster, creating a local tier, configuring protocols and provisioning initial storage.

//Go to https://docs.netapp.com/us-en/ontap/task_configure_ontap.html[Configure ONTAP on a new cluster with System Manager] for setup instructions.

.What's next?

After you've installed the RCF, you link:configure-ssh-keys.html[Verify SSH and SSH keys are enabled].



// New content for OAM project, AFFFASDOC-331, 2025-MAY-06
// Refactored content project, GH#423 2026-APR-MAY