---
permalink: switch-cisco-9332d-gx2b/install-upgrade-rcf-overview-cluster.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b
summary: You can install or upgrade the reference configuration file (RCF) on your Nexus 9332D-GX2B switches. You install a supported version of the RCF on the switches as part of a new AFX 1K or AFX 2K system installation, a switch replacement, or a reset to factory default settings. You upgrade to a supported version of the RCF on the switches to support new hardware, a new ONTAP version, or to align with a new NX-OS version in your AFX 1K or AFX 2K system configuration.
---
= Install or upgrade the RCF overview - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
You can install or upgrade the reference configuration file (RCF) on your Nexus 9332D-GX2B switches. You install a supported version of the RCF on the switches as part of a new AFX 1K or AFX 2K system installation, a switch replacement, or a reset to factory default settings. You upgrade to a supported version of the RCF on the switches to support new hardware, a new ONTAP version, or to align with a new NX-OS version in your AFX 1K or AFX 2K system configuration.

NOTE: RCF installation or upgrade is independent of NS-OS installation or upgrade. If you are installing or upgrading both the NX-OS and RCF, it is recommended you install or upgrade NX-OS first. 

NOTE: Do not upgrade or downgrade your RCF version to an unsupported version.


=== Understand RCF versions supported for AFX systems
The version of ONTAP running on your AFX system and version of NX-OS on your switches determines the supported versions of RCF for your switches. RCF versions have preset port speed configurations that determine how many switch ports are in breakout mode (4x100GbE) and non-breakout mode.

//The type of system (AFX 1K or AFX 2K) your switches are in determines the supported RCF versions. Understand the preset configuration of switch ports for the RCF version you are installing or upgrading to.

[NOTE]
====
For the current list of supported RCF versions, see the link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^] page.

Switch port information can also be found in the https://hwu.netapp.com[NetApp Hardware Universe^].
====

NOTE: For specific port and VLAN usage details, refer to the banner and important notes section in your RCF. Refer to link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^] page for more information.

* If you have an AFX 1K system, RCF 10.0 and later is supported:
+
For example, the following table shows the preset groupings of the switch ports, their port speeds, and usage based on RCF version 10.0.
+
[options="header" cols="1,2"]
|===
| Switch port groups | Port speeds and usage
a|
Ethernet1/1/1-4 to Ethernet1/30/1-4
a|
4x100GbE mode for cluster, HA, and storage connections 
a|
Ethernet1/31, Ethernet1/32
a|
400GbE ISL
|===
+
* If you have an AFX 2K system, RCF 10.1 and later is supported:
+
For example, the following table shows the preset groups of the switch ports, their port speeds, and usage based on RCF version 10.1.
+
//Filename : RCF-v10.1-NX9332D-GX2B-CL1-V1.txt
+
[options="header" cols="1,2"]
|===
| Switch port groups | Port speeds and usage
a|
Ethernet1/1/1-4 to Ethernet1/14/1-4
a|
4x100GbE mode for Intra-cluster, HA, and storage shelf connections 
//The term "shelf" can only be listed when this table is applicable to 2K only. Does not apply to 1K.
a|
Ethernet1/15 to Ethernet1/30
a|
400GbE mode for Intra-cluster, HA, and storage connections 
a|
Ethernet1/31, Ethernet1/32
a|
400GbE Intra-cluster ISL connections
|===

=== Change port speed configuration

For switches with RCF 10.1 and later, you can change the port speed configuration to adjust the number of switch ports in breakout mode (4x100GbE) and non-breakout mode (400GbE) when you need to accommodate a different port speed configuration for your AFX system.

You perform this change as part of the RCF installation or RCF upgrade procedure. The procedures have steps that link you to this page.

[options="header" cols="1,2"]
|===
| Change port speeds | Steps
a|
Change non-breakout ports to breakout ports
a|
. Modify port speeds and breakout modes on the switches:
+
To designate breakout ports, use the `interface breakout module` command. 
+
For example, to designate 400GbE mode ports 15-19 as breakout (4x100GbE) ports, use the following: 
+
`interface breakout module 1 port 15-19 map 100g-4x`

. Modify the port list with the new ports that need to use the port profile for the desired port speed.
+ 
For example, to modify the port list with the new ports,  15-19, for the 100G speed port profile, use the following: 
+
`interface e1/15/1-4, e1/16/1-4, e1/17/1-4, e1/18/1-4, e1/19/1-4 inherit port-profile 100G`
a|
Return breakout ports to non-breakout ports
a|
. To return breakout ports to non-breakout ports, use the `no interface breakout` command in config mode. 
+
For example, to return ports 15-19 to 400GbE mode, use the following: 
+
`no interface breakout module 1 port 15-19`

. Modify the port list with the new ports that need to use the port profile for the desired port speed.
+ 
For example, to modify the port list with the new ports,  15-19, for the 400G speed port profile, use the following:
+
`interface e1/15-19 inherit port-profile 400G` 
|===

=== Suggested documentation
Before you install or upgrade the RCF on your switches, it is recommended you review the following documentation:

* Refer to the NetApp Knowledge Base article link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity[How to clear configuration on a Cisco interconnect switch while retaining remote connectivity^] for further information when installing or upgrading your RCF.

* Refer to the https://hwu.netapp.com/SWITCH/INDEX[Hardware Universe^] to verify the correct ports on your platform.

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches (NSS)^]
+
Consult the switch compatibility table for the supported ONTAP and RCF versions on the NetApp Support Site. Note that there can be command dependencies between the command syntax in the RCF and the syntax found in specific versions of NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches^]
+
Refer to the appropriate software and upgrade guides available on the Cisco website for complete documentation on the Cisco switch upgrade and downgrade procedures.

=== About the procedures
The following information applies to the procedures for installing or upgrading the RCF:

* The examples in these procedures use the following switch and node nomenclature:

** The names of the two Cisco switches are cs1 and cs2.
** The node names are node1-01, node1-02, node1-03, and node1-04.
** The cluster LIF names are node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1, and node1-04_clus2.
** The `cluster1::*>` prompt indicates the name of the cluster.

* The procedures require the use of both ONTAP commands and Cisco Nexus 9000 Series Switches commands; ONTAP commands are used unless otherwise indicated.
+
The command outputs might vary depending on different releases of ONTAP.



.What's next?

After you've reviewed the install or upgrade RCF overview, you link:install-rcf-software-9332d-cluster.html[install the RCF] or link:upgrade-rcf-software-9332d-cluster.html[upgrade the RCF] as needed.


// New content for OAM project, AFFFASDOC-331, 2025-MAY-06
// AFFFASDOC-372, 2025-NOV-25
// AFFFASDOC-473, 2026-MAR-16
// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN


