---
permalink: switch-cisco-9332d-gx2b/install-complete-afx-setup-9332d.html
sidebar: sidebar
keywords: switches, complete system setup, Cisco Nexus, 9332D-GX2B switches, AFX
summary: After you complete the Cisco Nexus 9332D-GX2B switch configuration procedures, you go to the AFX system documentation site to power on the storage shelves and controllers in your AFX 1K or AFX 2K system, verify switch connectivity, and complete the AFX system setup.
---
= Complete the AFX system setup - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
After you complete the Cisco Nexus 9332D-GX2B switch configuration procedures, you go to the AFX system documentation site to power on the storage shelves and controllers in your AFX 1K or AFX 2K system, verify switch connectivity, and complete the AFX system setup.

.Before you begin
* You must have completed the switch configuration procedures in the link:configure-switch-workflow-9332d.html[configure switch workflow]. 

* Each switch must be connected to a console or you must have remote access to each switch.


//Hey: Do these steps for verifying the switch connections need to be in the https://docs.netapp.com/us-en/ontap-afx/install-setup/power-on-configure-switch.html[AFX doc: Power on and configure switches^] after step 3 or step 4? I'd rather not have more dependencies between the two repos, so keep it here. May 18: They could be moved there if the example outputs can also have a 2k version; otherwise, to keep it as is (this example is specific to 1K) keep it in this topic. At some point, with more time, can change this. BT do want Don to add a link in his topic (Power on system) that links back to this topic for the switch cabling confirmation.
//May 18: AD says physical cabling confirmation for the switches is vital

.Steps

. Complete the power on and setup steps for your AFX 1K or AFX 2K system:

* For an AFX 1K system, go to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/power-on-hardware.html[Power on your AFX 1K storage system^] procedure.

* For an AFX 2K system, go to the link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/power-on-hardware.html[Power on your AFX 2K storage system^] procedure.
+
Lisa: The above 2K link won't work until 2K site goes live. For now, can link to the AFX site preview draft of the topic: 
+
https://review.docs.netapp.com/us-en/ontap-afx_working-afx-emr-dr/install-afx-2k/power-on-hardware.html
//+
//.. Follow the instructions to power on your storage shelves and controllers.

//.. Follow the instructions to verify the switch connections.

//.. Follow the instructions to complete the system setup based on your deployment options.


== Step 3: Verify the switch connections

From the switch CLI, verify that the switch ports connected to the cluster ports are up, that the cluster nodes are in their correct cluster VLANs, and that the ISL connection between the two switches is functional.

. Verify that the switch ports connected to the cluster ports are up:
+
`show interface brief`
+
You can use `| grep up` to filter the output to only show the ports that are up.
+
.Show example for Cisco Nexus 9332D-GX2B and 9364D-GX2A switches
[%collapsible]
====

[subs=+quotes]
----
cs1# *show interface brief | grep up*
.
.
Eth1/9/3        1       eth  trunk  up      none                     100G(D) --
Eth1/9/4        1       eth  trunk  up      none                     100G(D) --
Eth1/15/1       1       eth  trunk  up      none                     100G(D) --
Eth1/15/2       1       eth  trunk  up      none                     100G(D) --
Eth1/15/3       1       eth  trunk  up      none                     100G(D) --
Eth1/15/4       1       eth  trunk  up      none                     100G(D) --
Eth1/16/1       1       eth  trunk  up      none                     100G(D) --
Eth1/16/2       1       eth  trunk  up      none                     100G(D) --
Eth1/16/3       1       eth  trunk  up      none                     100G(D) --
Eth1/16/4       1       eth  trunk  up      none                     100G(D) --
Eth1/17/1       1       eth  trunk  up      none                     100G(D) --
Eth1/17/2       1       eth  trunk  up      none                     100G(D) --
Eth1/17/3       1       eth  trunk  up      none                     100G(D) --
Eth1/17/4       1       eth  trunk  up      none                     100G(D) --
.
.
----
====
+
.Show example for Cisco Nexus 9808 switches
[%collapsible]
====

[subs=+quotes]
----
cs1# *show interface brief*

--------------------------------------------------------------------------------
Port   VRF          Status IP Address                              Speed    MTU
--------------------------------------------------------------------------------
mgmt0  --           up     10.232.206.36                           1000    1500    
--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/1          1       eth  trunk  up      none                     400G(D) --
Eth1/2          1       eth  trunk  up      none                     400G(D) --
.
.
.
Eth1/17         1       eth  trunk  up      none                     400G(D) --
Eth1/18         1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/19/1       1       eth  trunk  up      none                     100G(D) --
Eth1/19/2       1       eth  trunk  up      none                     100G(D) --
.
.
.
Eth1/35/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/36         1       eth  trunk  down    XCVR not inserted        auto(D) 1

------------------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                              Speed   Protocol
Interface                                                                            
------------------------------------------------------------------------------------------
Po1          1       eth  trunk  down    No operational members                auto(D)  lacp
Po998        1       eth  access down    Administratively down                 auto(I)  none
Po999        1       eth  access down    Administratively down                 auto(I)  none
cs1#
----
====

. Verify that the cluster nodes are in their correct cluster VLANs using the following commands:
+
`show vlan brief`
+
`show interface trunk`
+
.Show example for Cisco Nexus 9332D-GX2B switches
[%collapsible]
====

[subs=+quotes]
----
cs1# *show vlan brief*
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po999, Eth1/31, Eth1/32
                                                Eth1/33, Eth1/34, Eth1/1/1
                                                Eth1/1/2, Eth1/1/3, Eth1/1/4
.
.
.
                                                Eth1/29/4, Eth1/30/1, Eth1/30/2
                                                Eth1/30/3, Eth1/30/4
17   VLAN0017                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
.
.
.
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
18   VLAN0018                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
.
.
.
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
30   VLAN0030                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
.
.
.
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
40   VLAN0040                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
.
.
.
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4

cs1# *show interface trunk*
--------------------------------------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
--------------------------------------------------------------------------------
Eth1/1/1      1       trunking      --
Eth1/1/2      1       trunking      --
Eth1/1/3      1       trunking      --
Eth1/1/4      1       trunking      --
Eth1/2/1      1       trunking      --
Eth1/2/2      1       trunking      --
Eth1/2/3      1       trunking      --
Eth1/2/4      1       trunking      --
.
.
. 
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31       none
Eth1/32       none
Po1           1
----
====
+
.Show example for Cisco Nexus 9364D-GX2A switches 
[%collapsible]
====

[subs=+quotes]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po999, Eth1/63, Eth1/64
                                                Eth1/65, Eth1/66, Eth1/1/1
                                                Eth1/1/2, Eth1/1/3, Eth1/1/4
.
.
.
                                                Eth1/62/1, Eth1/62/2, Eth1/62/3
                                                Eth1/62/4
17   VLAN0017                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
.
.
.
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
18   VLAN0018                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
.
.
.
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
30   VLAN0030                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
.
.
.
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
40   VLAN0040                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
.
.
.
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4

cs1# *show interface trunk*

-----------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
-----------------------------------------------------
Eth1/1/1      1       trunking      --
Eth1/1/2      1       trunking      --
Eth1/1/3      1       trunking      --
Eth1/1/4      1       trunking      --
Eth1/2/1      1       trunking      --
Eth1/2/2      1       trunking      --
Eth1/2/3      1       trunking      --
Eth1/2/4      1       trunking      --
.
.
.
Eth1/62/2     none
Eth1/62/3     none
Eth1/62/4     none
Eth1/63       none
Eth1/64       none
Po1           1
----
====
+
.Show example for Cisco Nexus 9808 switches
[%collapsible]
====
[subs=+quotes]
----
cs1# *show vlan brief*

VLAN Name                     Status    Ports
---- ----------------------- ---------- -------- -----------------------------
1    default                          active    Po1, Po998, Po999, Eth1/1
                                                Eth1/2, Eth1/3, Eth1/4, Eth1/5
                                                Eth1/6, Eth1/7, Eth1/8, Eth1/9
.
.
.
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
17   VLAN0017                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
.
.
.
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
18   VLAN0018                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
.
.
.
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
30   VLAN0030                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
.
.
.
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
40   VLAN0040                         active    Po1, Eth1/1, Eth1/2, Eth1/3
                                                Eth1/4, Eth1/5, Eth1/6, Eth1/7
                                                Eth1/8, Eth1/9, Eth1/10, Eth1/11
.
.
.
                                                Eth1/35/1, Eth1/35/2, Eth1/35/3
                                                Eth1/35/4

cs1# 

  
cs1# *show interface trunk*

--------------------------------------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
--------------------------------------------------------------------------------
Eth1/1        1       trunking      --
Eth1/2        1       trunking      --
.
.
.
Eth1/17       1       trunking      --
Eth1/18       1       trunking      --
Eth1/19/1     1       trunking      --
Eth1/19/2     1       trunking      --
.
.
.
Eth1/35/4     1       trunking      --
Eth1/36       1       trnk-bndl     Po1
Po1           1       trunking      --

--------------------------------------------------------------------------------
Port          Vlans Allowed on Trunk
--------------------------------------------------------------------------------
Eth1/1        1,17-18,30,40
Eth1/2        1,17-18,30,40
.
.
.
Eth1/17       1,17-18,30,40
Eth1/18       1,17-18,30,40
Eth1/19/1     1,17-18,30,40
Eth1/19/2     1,17-18,30,40
.
.
.
Eth1/35/3     1,17-18,30,40
Eth1/35/4     1,17-18,30,40
Eth1/36       1,40
Po1           1,40

--------------------------------------------------------------------------------
Port          Vlans Err-disabled on Trunk
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
.
.
.
Eth1/17       none
Eth1/18       none
Eth1/19/1     none
Eth1/19/2     none
.
.
.
Eth1/35/4     none
Eth1/36       none
Po1           none

--------------------------------------------------------------------------------
Port          STP Forwarding
--------------------------------------------------------------------------------
Eth1/1        1,17-18,30,40
Eth1/2        1,17-18,30,40
.
.
.
Eth1/17       1,17-18,30,40
Eth1/18       none
Eth1/19/1     1,17-18,30,40
Eth1/19/2     1,17-18,30,40
.
.
.
Eth1/35/4     none
Eth1/36       none
Po1           none

--------------------------------------------------------------------------------
Port          Vlans in spanning tree forwarding state and not pruned
--------------------------------------------------------------------------------
Eth1/1        Feature VTP is not enabled
1,17-18,30,40
Eth1/2        Feature VTP is not enabled
1,17-18,30,40
.
.
.
Eth1/23/3     Feature VTP is not enabled
1,17-18,30,40
Eth1/23/4     Feature VTP is not enabled
1,17-18,30,40
Eth1/24/1     Feature VTP is not enabled
none
Eth1/24/2     Feature VTP is not enabled
none
.
.
.
Eth1/35/4     Feature VTP is not enabled
none
Eth1/36       Feature VTP is not enabled
none
Po1           Feature VTP is not enabled
none
cs1#

----
====
+
NOTE: For specific port and VLAN usage details, refer to the banner and important notes section in your RCF.

. Verify that the ISL between the first switch (cs1) and the second switch (cs2) is functional:
+
`show port-channel summary`
+
.Show example for Cisco Nexus 9332D-GX2B switches
[%collapsible]
====

[subs=+quotes]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports      
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)      
999   Po999(SD)   Eth      NONE      --
cs1#
----
====
+
.Show example for Cisco Nexus 9364D-GX2A switches
[%collapsible]
====

[subs=+quotes]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports      
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/63(P)   Eth1/64(P) 
999   Po999(SD)   Eth      NONE      --
cs1#
----
====
+
.Show example for Cisco Nexus 9808 switches

[%collapsible]

====

NOTE: Because the Cisco Nexus 9808 switch is a single switch, ISL is disconnected; therefore, you won't see the peers in the command output.

[subs=+quotes]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SD)     Eth      LACP      Eth1/36(D)   
998   Po998(SD)   Eth      NONE      --
999   Po999(SD)   Eth      NONE      --
cs1#
----
====

.What's next?

After you've powered on the storage shelves and controllers and completed the AFX 1K or AFX 2K system setup, you are ready to use your AFX system.

// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN