---
permalink: switch-cisco-9332d-gx2b/maintain-overview-9332d.html
sidebar: sidebar
keywords: maintain overview, frus, replace switch, reset to factory defaults, cisco 9332d-gx2b
summary: "Review the maintenance tasks for Cisco Nexus 9332D-GX2B switches, including FRU replacement, switch replacement, and resetting to factory default settings."
---
= Learn about maintenance options for the Cisco Nexus 9332D-GX2B switch
:icons: font
:imagesdir: ../media/

[.lead]
Review the maintenance tasks available for Cisco Nexus 9332D-GX2B switches, including replacing faulty switch components (FRUs), replacing a faulty switch, and resetting a switch to factory default settings.

You can perform the following maintenance tasks on a switch:

* link:replace-9332d-cluster.html[Replace a switch]
* link:maintain-replace-frus-9332d.html[Replace FRUs]
* link:maintain-reset-switch-9332d.html[Reset a switch to factory default settings]

//Note that for 9808, you don't replace a switch, that procedure needs to be "Replace a supervisor module". And remember that NetApp ships with one supervisor module (not two) as a default, but customers can order a switch with two (maximum)...so title of that FRU topic should be "a", not "the"?


// New content for AFX project, AFFFASDOC-xxx, 2026-JUL-xx
// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN