---
sidebar: sidebar
permalink: switch-cisco-9332d-gx2b/maintain-reset-switch-9332d.html
keywords: reset switch factory defaults
summary: When a Cisco Nexus 9332D-GX2B switch fails and cannot be recovered, you reset the switch to its original factory default settings so that you can reconfigure it manually.
---
= Reset a switch to factory default settings - Cisco Nexus 9332D-GX2B
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
When a Cisco Nexus 9332D-GX2B switch fails and cannot be recovered, you reset the switch to its original factory default settings so that you can reconfigure it manually. 

You reset the switch to factory default settings by erasing the switch settings (startup configuration) and rebooting the switch, which brings up the configuration wizard so you can complete the initial switch setup, and then you complete the switch configuration.

.Before you begin
You must be connected to the switch using the serial console.

.About this task
* This task resets the configuration of the management network.
* The `reload` command used in this procedure reboots the switch, which interrupts all network traffic passing through it. (You should perform this procedure during a maintenance window when the switch is not in use.)
//* The switch will lose all configuration settings and return to factory defaults.

.Steps
. Erase the existing startup configuration:
+
`write erase`
+

[subs=+quotes]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----

. Reload the NX-OS:
+
`reload`
+

[subs=+quotes]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----

+
The system reboots and enters the configuration wizard. If needed, you can reference the configuration wizard questions and recommended responses in the link:configure-complete-initial-setup-9332d.html[Complete initial switch setup] procedure.
+
NOTE: During the reboot, if you receive the prompt “Abort Auto Provisioning and continue with normal setup? (yes/no)[n]”, respond *yes* to proceed.
+
. After you complete the initial switch setup, use the link:configure-switch-workflow-9332d.html[configure switch workflow] to complete the switch configuration.


.What's next?

* After you complete this procedure, your switch is returned to normal operation.

* If you had Smart Call Home configured on the switch before you reset it, you need to link:configure-smart-call-9332d.html[configure Smart Call Home] again. 

// New content for OAM project, AFFFASDOC-331, 2025-AUG-18
// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN