---
permalink: switch-cisco-9332d-gx2b/maintain-overview-9332d.html
sidebar: sidebar
keywords: maintain overview, frus, replace switch, reset to factory defaults, cisco 9332d-gx2b
summary: Maintain your Cisco Nexus 9332D-GX2B switch to ensure long-term reliability and optimal performance. You can perform maintenance tasks such as replacing failed switch components (FRUs), replacing a faulty switch, and resetting a switch to factory default settings.
---
= Maintain overview - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
Maintain your Cisco Nexus 9332D-GX2B switch to ensure long-term reliability and optimal performance. You can perform maintenance tasks such as replacing faulty switch components (FRUs), replacing a faulty switch, and resetting a switch to factory default settings.

You can perform the following maintenance tasks on a switch:

* link:replace-9332d-cluster-test.html[Replace a switch]
* link:replace-frus-9332d-cluster.html[Replace FRUs]
* link:reset-switch-9332d.html[Reset a switch to factory default settings]

//Note that for 9808, you don't replace a switch, that procedure needs to be "Replace a supervisor module". And remember that NetApp ships with one supervisor module (not two) as a default, but customers can order a switch with two (maximum)...so title of that FRU topic should be "a", not "the"?


// New content for AFX project, AFFFASDOC-xxx, 2026-JUL-xx
// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN