---
permalink: switch-cisco-9332d-gx2b/replace-9332d-cluster.html
sidebar: sidebar
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9332d-gx2b cluster switch - cisco nexus 9332d-gx2b
summary: Replacing a defective Nexus 9332D-GX2B switch in a cluster network is a nondisruptive procedure \(NDU\).
---
= Replace a Cisco Nexus 9332D-GX2B switch
:icons: font
:imagesdir: ../media/

[.lead]
Follow these steps to replace a defective Nexus 9332D-GX2B switch in a shared network. This is a nondisruptive procedure (NDU).

== Review requirements

Before performing the switch replacement, make sure that: 

* You have verified the switch serial number to ensure that the correct switch is replaced. 
* On the existing cluster and network infrastructure:
 ** The existing cluster is verified as completely functional, with at least one fully connected cluster switch.
 ** All cluster ports are *up*.
 ** All cluster logical interfaces (LIFs) are *up* and on their home ports.
 ** The ONTAP `cluster ping-cluster -node <node-name>` command must indicate that basic connectivity and larger than PMTU communication are successful on all paths.
* On the Nexus 9332D-GX2B replacement switch:
 ** Management network connectivity on the replacement switch is functional.
 ** Console access to the replacement switch is in place.
 ** The node connections are ports 1/1 through 1/30.
 ** All Inter-Switch Link (ISL) ports is disabled on ports 1/31 and 1/32.
 ** The desired reference configuration file (RCF) and NX-OS operating system image switch is loaded onto the switch.
// ** Initial customization of the switch is complete, as detailed in link:setup-switch-9332d-cluster.html[Configure the 9332D-GX2B cluster switch].
+
Any previous site customizations, such as STP, SNMP, and SSH, are copied to the new switch.

* You have executed the command for migrating a cluster LIF from the node where the cluster LIF is hosted.

== Enable console logging
NetApp strongly recommends that you enable console logging on the devices that you are using and take the following actions when replacing your switch:

* Leave AutoSupport enabled during maintenance.
* Trigger a maintenance AutoSupport before and after maintenance to disable case creation for the duration of the maintenance. See this Knowledge Base article https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92[SU92: How to suppress automatic case creation during scheduled maintenance windows^] for further details.
* Enable session logging for any CLI sessions. For instructions on how to enable session logging, review the "Logging Session Output" section in this Knowledge Base article https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems[How to configure PuTTY for optimal connectivity to ONTAP systems^].

== Replace the switch

.About the examples
The examples in this procedure use the following switch and node nomenclature:

* The names of the existing Nexus 9332D-GX2B switches are cs1 and cs2.
* The name of the new Nexus 9332D-GX2B switch is newcs2.
* The node names are node1-01, node1-02, node1-03, and node1-04.
//* The cluster ports on each node are named e0a and e0b.
* The cluster LIF names are node1-01_clus1 and node1-01_clus2 for node1-01, node1-02_clus1 and node1-02_clus2 for node1-02, node1-03_clus1 and node1-03_clus2 for node1-03, and node1-04_clus1 and node1-04_clus2 for node1-04.
* The prompt for changes to all cluster nodes is cluster1::*>

.About this task
The following procedure is based on the following cluster network topology:

.Show example 
[%collapsible]
====
----
cluster1::*> network port show -ipspace Cluster

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.


cluster1::*> network interface show -vserver Cluster
            Logical    Status     Network            Current     Current   Is
Vserver     Interface  Admin/Oper Address/Mask       Node        Port      Home
----------- ---------- ---------- ------------------ ----------- --------- ----
Cluster
            node1-01_clus1 up/up  169.254.36.44/16    node1-01    e7a      true
            node1-01_clus2 up/up  169.254.7.5/16      node1-01    e7b      true
            node1-02_clus1 up/up  169.254.197.206/16  node1-02    e7a      true
            node1-02_clus2 up/up  169.254.195.186/16  node1-02    e7b      true
            node1-03_clus1 up/up  169.254.192.49/16   node1-03    e7a      true
            node1-03_clus2 up/up  169.254.182.76/16   node1-03    e7b      true
            node1-04_clus1 up/up  169.254.59.49/16    node1-04    e7a      true
            node1-04_clus2 up/up  169.254.62.244/16   node1-04    e7b      true

8 entries were displayed.

cluster1::*> network device-discovery show -protocol cdp


Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLM284504N6)          Ethernet1/16/3    N9K-C9332D-GX2B
            e11a   cs1(FLM284504N6)          Ethernet1/16/4    N9K-C9332D-GX2B
            e1a    cs1(FLM284504N6)          Ethernet1/16/1    N9K-C9332D-GX2B
            e2a    cs2(FLM284504R2)          Ethernet1/8       N9K-C9332D-GX2B
            e3a    cs2(FLM284504R2)          Ethernet1/7       N9K-C9332D-GX2B
            e7a    cs1(FLM284504N6)          Ethernet1/16/2    N9K-C9332D-GX2B
.
.
.

cs1# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID   
cs2                Eth1/1/1       156    H           AFX-1K        e1a           
cs2                Eth1/1/2       156    H           AFX-1K        e7a           
cs2                Eth1/1/3       156    H           AFX-1K        e10a          
cs2                Eth1/1/4       156    H           AFX-1K        e11a          

Total entries displayed: 4

cs2# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID   
cs1                Eth1/9/1       175    H           AFX-1K        e1a           
cs1                Eth1/9/2       175    H           AFX-1K        e7a           
cs1                Eth1/9/3       175    H           AFX-1K        e10a          
cs1                Eth1/9/4       175    H           AFX-1K        e11a                

Total entries displayed: 4
----
====

=== Step 1: Prepare for replacement

. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message: 
+
`system node autosupport invoke -node * -type all -message MAINT=xh`
+
where x is the duration of the maintenance window in hours.
+
NOTE: The AutoSupport message notifies technical support of this maintenance task so that automatic case creation is suppressed during the maintenance window.

. Install the appropriate RCF and image on the switch, newcs2, and make any necessary site preparations.
+
If necessary, verify, download, and install the appropriate versions of the RCF and NX-OS software for the new switch. If you have verified that the new switch is correctly set up and does not need updates to the RCF and NX-OS software, continue to step 2.

 .. Go to the _NetApp Cluster and Management Network Switches Reference Configuration File Description Page_ on the NetApp Support Site.
 .. Click the link for the _Cluster Network and Management Network Compatibility Matrix_, and then note the required switch software version.
 .. Click your browser's back arrow to return to the Description page, click *CONTINUE*, accept the license agreement, and then go to the Download page.
 .. Follow the steps on the Download page to download the correct RCF and NX-OS files for the version of ONTAP software you are installing.

. On the new switch, log in as admin and shut down all of the ports that will be connected to the node cluster interfaces (ports 1/1 to 1/30).
+
If the switch that you are replacing is not functional and is powered down, go to Step 4. The LIFs on the cluster nodes should have already failed over to the other cluster port for each node.
+
.Show example 
[%collapsible]
====
----
newcs2# config
Enter configuration commands, one per line. End with CNTL/Z.
newcs2(config)# interface e1/1/1-30
newcs2(config-if-range)# shutdown
----
====

. Verify that all cluster LIFs have auto-revert enabled: 
+
`network interface show -vserver Cluster -fields auto-revert`
+
.Show example 
[%collapsible]
====
----
cluster1::> network interface show -vserver Cluster -fields auto-revert

             Logical
Vserver      Interface        Auto-revert
------------ -------   ------ -------------
Cluster      node1-01_clus1   true
Cluster      node1-02_clus2   true
Cluster      node1-03_clus1   true
Cluster      node1-04_clus2   true

4 entries were displayed.
----
====

. Verify the connectivity of the remote cluster interfaces: 
+
// start of tabbed content

[role="tabbed-block"]

====

.ONTAP 9.9.1 and later

--
You can use the `network interface check cluster-connectivity` command to start an accessibility check for cluster connectivity and then display the details: 

`network interface check cluster-connectivity start` and `network interface check cluster-connectivity show`

[subs=+quotes]
----
cluster1::*> *network interface check cluster-connectivity start*
----

*NOTE:* Wait for a number of seconds before running the `show` command to display the details.


[subs=+quotes]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01  
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02  
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
--

.All ONTAP releases
--
For all ONTAP releases, you can also use the `cluster ping-cluster -node <node-name>` command to check the connectivity:

`cluster ping-cluster -node <node-name>`


[subs=+quotes]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====

// end of tabbed content

=== Step 2: Configure cables and ports
. Shut down the ISL ports Eth1/31 and Eth1/32 on the Nexus 9332D-GX2B switch cs1.
+
.Show example 
[%collapsible]
====
----
cs1# configure
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/31-32
cs1(config-if-range)# shutdown
cs1(config-if-range)#
----
====

. Remove all of the cables from the Nexus 9332D-GX2B cs2 switch, and then connect them to the same ports on the 9332D-GX2B newcs2 switch.
. Bring up the ISLs ports 1/31 and 1/32 between the cs1 and newcs2 switches, and then verify the port channel operation status.
+
Port-Channel should indicate Po1(SU) and Member Ports should indicate Eth1/31(P) and Eth1/32(P).
+
.Show example 
[%collapsible]
====
This example enables ISL ports Eth1/31 and Eth1/32 and displays the port channel summary on switch cs1:

----
cs1# configure
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# int e1/31-32
cs1(config-if-range)# no shutdown

cs1(config-if-range)# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
999   Po999(SD)   Eth      NONE      --
----
====

. Verify that port e7b is up on all nodes: 
+
`network port show ipspace Cluster`
+
.Show example 
[%collapsible]
====
The output should be similar to the following:

----
cluster1::*> network port show -ipspace Cluster

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.
----
====

. On the same node you used in the previous step, revert the cluster LIF associated with the port in the previous step by using the network interface revert command.
+
.Show example 
[%collapsible]
====
In this example, LIF node1-01_clus2 on node1-01 is successfully reverted if the Home value is true and the port is e7b.

The following commands return LIF `node1-01_clus2` on `node1-01` to home port `e7a` and displays information about the LIFs on both nodes. Bringing up the first node is successful if the Is Home column is true for both cluster interfaces and they show the correct port assignments, in this example `e7a` and `e7b` on node1-01.

----
cluster1::*> network interface show -vserver Cluster

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- -------------- ---------- ------------------ ---------- ------- -----
Cluster
          node1-01_clus1  up/up     169.254.209.69/16  node1-01   e7a     true
          node1-01_clus2  up/up     169.254.49.125/16  node1-01   e7b     true
          node1-02_clus1  up/up     169.254.47.194/16  node1-02   e7b     true
          node1-02_clus2  up/up     169.254.19.183/16  node1-02   e7a     false

4 entries were displayed.
----
====

. Display information about the nodes in a cluster: 
+
`cluster show`
+
.Show example 
[%collapsible]
====
This example shows that the node health for node1 and node2 in this cluster is true:

----
cluster1::*> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1-01       false   true
node1-02       true    true
----
====

. Verify that all physical cluster ports are up: 
+
`network port show ipspace Cluster`
+
.Show example 
[%collapsible]
====
----
cluster1::*> network port show -ipspace Cluster

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

4 entries were displayed.
----
====

. Verify the connectivity of the remote cluster interfaces: 
+
// start of tabbed content

[role="tabbed-block"]

====

.ONTAP 9.9.1 and later

--
You can use the `network interface check cluster-connectivity` command to start an accessibility check for cluster connectivity and then display the details: 

`network interface check cluster-connectivity start` and `network interface check cluster-connectivity show`

[subs=+quotes]
----
cluster1::*> *network interface check cluster-connectivity start*
----

*NOTE:* Wait for a number of seconds before running the `show` command to display the details.


[subs=+quotes]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1-01  
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02  
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
--

.All ONTAP releases
--
For all ONTAP releases, you can also use the `cluster ping-cluster -node <name-name>` command to check the connectivity:

`cluster ping-cluster -node <name-name>`


[subs=+quotes]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====

// end of tabbed content
=== Step 3: Verify the configuration

. Confirm the following cluster network configuration: 
+
`network port show`
+
.Show example 
[%collapsible]
====
----
cluster1::*> network port show -ipspace Cluster
Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.

cluster1::*> network interface show -vserver Cluster

          Logical       Status     Network            Current    Current Is
Vserver   Interface     Admin/Oper Address/Mask       Node       Port    Home
--------- ------------- ---------- ------------------ ---------- ------- ----
Cluster
          node1-01_clus1  up/up    169.254.209.69/16  node1-01   e7a     true
          node1-01_clus2  up/up    169.254.49.125/16  node1-01   e7b     true
          node1-02_clus1  up/up    169.254.47.194/16  node1-02   e7b     true
          node1-02_clus2  up/up    169.254.19.183/16  node1-02   e7a     false

4 entries were displayed.

cluster1::> network device-discovery show -protocol cdp

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLM284504N6)          Ethernet1/16/3    N9K-C9332D-GX2B
            e11a   cs1(FLM284504N6)          Ethernet1/16/4    N9K-C9332D-GX2B
            e1a    cs1(FLM284504N6)          Ethernet1/16/1    N9K-C9332D-GX2B
            e2a    cs2(FLM284504R2)          Ethernet1/8       N9K-C9332D-GX2B
            e3a    cs2(FLM284504R2)          Ethernet1/7       N9K-C9332D-GX2B
            e7a    cs1(FLM284504N6)          Ethernet1/16/2    N9K-C9332D-GX2B
.
.
.

cs1# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
newcs2             Eth1/1/1       156    H           AFX-1K        e1a           
newcs2             Eth1/1/2       156    H           AFX-1K        e7a           
newcs2             Eth1/1/3       156    H           AFX-1K        e10a          
newcs2             Eth1/1/4       156    H           AFX-1K        e11a

Total entries displayed: 4


newcs2# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/9/1       175    H           AFX-1K        e1a           
cs1                Eth1/9/2       175    H           AFX-1K        e7a           
cs1                Eth1/9/3       175    H           AFX-1K        e10a          
cs1                Eth1/9/4       175    H           AFX-1K        e11a  

Total entries displayed: 4
----
====

. If you suppressed automatic case creation, re-enable it by invoking an AutoSupport message: 
+
`system node autosupport invoke -node * -type all -message MAINT=END`

.What's next?

link:../switch-cshm/config-overview.html[Configure switch health monitoring].

// New content for OAM project, AFFFASDOC-331, 2025-MAY-08
