---
sidebar: sidebar
permalink: switch-cisco-9332d-gx2b/required-documentation-9332d-cluster.html
keywords: shared storage cluster switch
summary: For Cisco Nexus 9332D-GX2B switch installation and configuration as part of a new AFX 1K or AFX 2K system or maintenance of existing switches, you can reference the applicable Cisco switch documentation and NetApp systems documentation.
---
= Reference documentation - Cisco Nexus 9332D-GX2B
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
For Cisco Nexus 9332D-GX2B switch installation and configuration as part of a new AFX 1K or AFX 2K system or maintenance of existing switches, you can reference the applicable Cisco switch documentation and NetApp systems documentation.

NOTE: For step-by-step instructions to install and configure your switches as part of a new AFX 1K or AFX 2K system, see the link:install-configure-switches-in-afx-workflow-9332d.html[Install and configure switches in an AFX system workflow].

== Cisco switch documentation
To install and configure your Cisco Nexus 9332D-GX2B switches as part of a new AFX 1K or AFX 2K system, you can reference the following Cisco documents so you are familiar with the switch release notes, safety information, installation options, initial software configuration, and command references.

After you install and configure your switches, you can reference the applicable Cisco documents to maintain your switches.

All of these documents are available on the link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches Support^] page. 

[options="header" cols="1,2,3"]
|===
| Task type| Cisco document title| Description
a|
Install and configure
a|
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html[Cisco Nexus 9000 Series NX-OS Release Notes^] (choose the notes for the NX-OS release installed on your switches)
a|
Describes the features, bugs, and limitations for the Cisco Nexus 9000 Series.
a|
Install and configure
a|
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch[Regulatory Compliance and Safety Information for Cisco Nexus 9000 Series^]
a|
Provides international agency compliance, safety, and statutory information for the Nexus 9000 series switches.
a|
Install and configure
a|
link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-nx-os-mode-switch-hardware-installation-guide/m_installing-the-switch-chassis-new-1ru-rack-mount.html[Cisco Nexus 9332D-GX2B NX-OS Mode Switch Hardware Installation Guide^]
a|
Provides detailed information about site requirements, switch hardware details, and installation options.
a|
Install and configure
a|
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html[Cisco Nexus 9000 Series Switch Software Configuration Guides^] (choose the guide for the NX-OS release installed on your switches)
a|
Provides initial switch configuration information that you need before you can configure the switch for ONTAP operation.
a|
Install and configure, and maintain
a|
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html[Cisco Nexus 9000 Series NX-OS Command Reference^]
a|
Provides links to the various command references provided by Cisco.
a|
Install and configure
a|
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html[Cisco Nexus 9000 Series NX-OS Software Upgrade and Downgrade Guide^] (choose the guide for the NX-OS release installed on your switches)
a|
Provides information on how to downgrade the switch to ONTAP supported switch software, if necessary.
a|
Maintain
a|
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html[Cisco Nexus 9000 Series NX-OS System Message Reference^]
a|
Describes the system messages for Cisco Nexus 9000 series switches, those that are informational, and others that might help diagnose problems with links, internal hardware, or the system software.
|===

== NetApp systems documentation

To install and configure your Cisco Nexus 9332D-GX2B switches as part of a new AFX 1K or AFX 2K system, you can reference the following NetApp systems documents and resources so you are familiar with the AFX systems, supported ONTAP releases, supported hardware configurations, and system installation requirements.

// Maybe also add row in NetApp systems table: For the current list of supported RCF versions, see the link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Cisco Ethernet Switches^] page.

[options="header" cols="1,2,3"]
|===
|Task type| ONTAP document title| Description
a|
Install and configure
a|
link:https://docs.netapp.com/us-en/ontap-afx/index.html[AFX systems documentation^]
a|
Describes how to install NetApp hardware.
a|
Install and configure
a|
link:https://docs.netapp.com/us-en/ontap-family/[ONTAP documentation^]
a|
Provides detailed information about all aspects of the ONTAP releases.
a|
Install and configure
a|
link:https://hwu.netapp.com[Hardware Universe^]
a|
Provides NetApp hardware configuration and compatibility information.
a|
Install and configure
a|
link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU[What additional information do I need to install my equipment that is not in HWU?^]
a|
Provides more information about storage system installation requirements.
|===

// New content for OAM project, AFFFASDOC-331, 2025-MAY-08
// AFFFASDOC-473, 2026-MAR-18
// Refactor content project phase 1 with 2K content, GH#423 2026-JUN
