---
sidebar: sidebar
permalink: switch-cisco-9332d-gx2b/maintain-reset-switch-9332d.html
keywords: reset switch factory defaults
summary: When a Cisco Nexus 9332D-GX2B switch fails and cannot be recovered, you reset the switch to its original factory default settings so that you can reconfigure it manually.
---
= Reset a switch to factory default settings - Cisco Nexus 9332D-GX2B
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
When a Cisco Nexus 9332D-GX2B switch fails and cannot be recovered, you reset the switch to its original factory default settings so that you can reconfigure it manually. 

You reset the switch to factory default settings by erasing the switch settings (startup configuration) and rebooting the switch, which brings up the configuration wizard so you can complete the initial switch setup, and then you complete the switch configuration.

.Before you begin
You must be connected to the switch using the serial console.

.About this task
* This task resets the configuration of the management network.
* The `reload` command used in this procedure reboots the switch, which interrupts all network traffic passing through it. (You should perform this procedure during a maintenance window when the switch is not in use.)
//* The switch will lose all configuration settings and return to factory defaults.

.Steps
. Erase the existing startup configuration:
+
`write erase`
+

[subs=+quotes]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
//Wipes Configuration: It removes the stored configuration file, allowing for a clean installation of a new Reference Configuration File (RCF) or to reconfigure the switch from scratch. Follow-up Action: A reload command is necessary to apply the empty configuration, as write erase does not affect the currently running configuration

. Reload the NX-OS:
+
`reload`
+
//The reload command restarts the switch operating system (NX-OS). It initiates a power-cycle of the hardware, which terminates all network traffic through the device and forces a system reboot. Does it actually reload the sw? 
+
//You only need to apply the RCF if you have explicitly performed a write erase (factory default). YES, you need to have users install the RCF.
+
[subs=+quotes]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----

+
The system reboots and enters the configuration wizard. 
+
NOTE: During the reboot, if you receive the prompt “Abort Auto Provisioning and continue with normal setup? (yes/no)[n]”, respond *yes* to proceed.
+
. Use the configuration wizard to complete the initial switch setup.
//assumed that it popped up.
+
If needed, you can reference the configuration wizard questions and recommended responses in the link:setup-switch-9332d-cluster.html[Complete initial switch setup] procedure.

. link:../switch-cisco-9332d-gx2b/configure-prepare-install-nxos-rcf-9332d.html[Prepare to install the NX-OS and RCF] on the switch.

. link:../switch-cisco-9332d-gx2b/configure-install-upgrade-nxos-9332d.html[Install or upgrade the NX-OS] on the switch.

. Install the RCF on the switch starting with the link:configure-install-upgrade-rcf-overview-9332d.html[Install or upgrade RCF overview].

. link:../switch-cisco-9332d-gx2b/configure-verify-ssh-9332d.html[Verify SSH for log collection] so that you can use the log collection feature.

. link:../switch-cshm/cshm-overview.html[Configure Ethernet switch health monitoring (CSHM)] to ensure the operational health of network switches and collect switch logs for debugging purposes.

.What's next?

* After you complete this procedure, your switch is returned to normal operation.

* If you had Smart Call Home configured on the switch before you reset it, you need to link:smart-call-9332d-cluster.html[configure Smart Call Home] again. 

// New content for OAM project, AFFFASDOC-331, 2025-AUG-18
// Refactor content project phase 1 with 2K/RCF 10.1 content, GH#423 2026-JUN