---
permalink: switch-cisco-9332d-gx2b/setup-worksheet-9332d-cluster.html
sidebar: sidebar
keywords: document, support, platform, complete, blank, cabling, worksheet, guide, cisco, nexus, cisco nexus 9332d-gx2b cabling worksheet
summary: If you want to document the supported platforms, you must complete the blank cabling worksheet by using the completed sample cabling worksheet as a guide.
---
= Complete the Cisco Nexus 9332D-GX2B cabling worksheet
:icons: font
:imagesdir: ../media/

[.lead]
If you want to document the supported platforms, download a PDF of this page and complete the cabling worksheet. 

The sample cabling worksheet provides examples of recommended port assignments from the switches to the controllers. The blank worksheet provides a template that you can use in setting up your cluster.

* <<9332D-GX2B sample cabling worksheet>>
* <<9332D-GX2B blank cabling worksheet>>

== 9332D-GX2B sample cabling worksheet

The sample port definition on each pair of switches is as follows:

[options="header", cols="1, 1, 1, 1"]
|===
2+|Switch A
2+|Switch B
| Switch port| Node and port usage| Switch port| Node and port usage
a|
1
a|
100GbE Intra-Cluster/HA/Storage port node 1
a|
1
a|
100GbE Intra-Cluster/HA/Storage port node 1
a|
2
a|
100GbE Intra-Cluster/HA/Storage port node 2
a|
2
a|
100GbE Intra-Cluster/HA/Storage port node 2
a|
3
a|
100GbE Intra-Cluster/HA/Storage port node 3
a|
3
a|
100GbE Intra-Cluster/HA/Storage port node 3
a|
4
a|
100GbE Intra-Cluster/HA/Storage port node 4
a|
4
a|
100GbE Intra-Cluster/HA/Storage port node 4
a|
5
a|
100GbE Intra-Cluster/HA/Storage port node 5
a|
5
a|
100GbE Intra-Cluster/HA/Storage port node 5
a|
6
a|
100GbE Intra-Cluster/HA/Storage port node 6
a|
6
a|
100GbE Intra-Cluster/HA/Storage port node 6
a|
7
a|
100GbE Intra-Cluster/HA/Storage port node 7
a|
7
a|
100GbE Intra-Cluster/HA/Storage port node 7
a|
8
a|
100GbE Intra-Cluster/HA/Storage port node 8
a|
8
a|
100GbE Intra-Cluster/HA/Storage port node 8
a|
9
a|
100GbE Intra-Cluster/HA/Storage port node 9
a|
9
a|
100GbE Intra-Cluster/HA/Storage port node 9
a|
10
a|
100GbE Intra-Cluster/HA/Storage port node 10
a|
10
a|
100GbE Intra-Cluster/HA/Storage port node 10
a|
11
a|
100GbE Intra-Cluster/HA/Storage port node 11
a|
11 
a|
100GbE Intra-Cluster/HA/Storage port node 11
a|
12
a|
100GbE Intra-Cluster/HA/Storage port node 12
a|
12
a|
100GbE Intra-Cluster/HA/Storage port node 12
a|
13
a|
100GbE Intra-Cluster/HA/Storage port node 13
a|
13
a|
100GbE Intra-Cluster/HA/Storage port node 13
a|
14
a|
100GbE Intra-Cluster/HA/Storage port node 14
a|
14
a|
100GbE Intra-Cluster/HA/Storage port node 14
a|
15
a|
100GbE Intra-Cluster/HA/Storage port node 15
a|
15
a|
100GbE Intra-Cluster/HA/Storage port node 15
a|
16
a|
100GbE Intra-Cluster/HA/Storage port node 16
a|
16
a|
100GbE Intra-Cluster/HA/Storage port node 16
a|
17
a|
100GbE Intra-Cluster/HA/Storage port node 17
a|
17
a|
100GbE Intra-Cluster/HA/Storage port node 17
a|
18
a|
100GbE Intra-Cluster/HA/Storage port node 18
a|
18
a|
100GbE Intra-Cluster/HA/Storage port node 18
a|
19
a|
100GbE Intra-Cluster/HA/Storage port node 19
a|
19
a|
100GbE Intra-Cluster/HA/Storage port node 19
a|
20
a|
100GbE Intra-Cluster/HA/Storage port node 20
a|
20
a|
100GbE Intra-Cluster/HA/Storage port node 20
a|
21
a|
100GbE Intra-Cluster/HA/Storage port node 21
a|
21
a|
100GbE Intra-Cluster/HA/Storage port node 21
a|
22
a|
100GbE Intra-Cluster/HA/Storage port node 22
a|
22
a|
100GbE Intra-Cluster/HA/Storage port node 22
a|
23
a|
100GbE Intra-Cluster/HA/Storage port node 23
a|
23
a|
100GbE Intra-Cluster/HA/Storage port node 23
a|
24
a|
100GbE Intra-Cluster/HA/Storage port node 24
a|
24
a|
100GbE Intra-Cluster/HA/Storage port node 24
a|
25
a|
100GbE Intra-Cluster/HA/Storage port node 25
a|
25
a|
100GbE Intra-Cluster/HA/Storage port node 25
a|
26
a|
100GbE Intra-Cluster/HA/Storage port node 26
a|
26
a|
100GbE Intra-Cluster/HA/Storage port node 26
a|
27
a|
100GbE Intra-Cluster/HA/Storage port node 27
a|
27
a|
100GbE Intra-Cluster/HA/Storage port node 27
a|
28
a|
100GbE Intra-Cluster/HA/Storage port node 28
a|
28
a|
100GbE Intra-Cluster/HA/Storage port node 28
a|
29
a|
100GbE Intra-Cluster/HA/Storage port node 29
a|
29
a|
100GbE Intra-Cluster/HA/Storage port node 29
a|
30
a|
100GbE Intra-Cluster/HA/Storage port node 30
a|
30
a|
100GbE Intra-Cluster/HA/Storage port node 30
a|
31
a|
Intra-Cluster ISL port 31
a|
31
a|
Intra-Cluster ISL port 31
a|
32
a|
Intra-Cluster ISL port 32
a|
32
a|
Intra-Cluster ISL port 32
|===

== 9332D-GX2B blank cabling worksheet

You can use the blank cabling worksheet to document the platforms that are supported as nodes in a cluster. The _Supported Cluster Connections_ section of the https://hwu.netapp.com[Hardware Universe^] defines the cluster ports used by the platform.

[options="header", cols="1, 1, 1, 1"]
|===
2+|Cluster switch A
2+|Cluster switch B
a|
1
a|

a|
1
a|

a|
2
a|

a|
2
a|

a|
3
a|

a|
3
a|

a|
4
a|

a|
4
a|

a|
5
a|

a|
5
a|

a|
6
a|

a|
6
a|

a|
7
a|

a|
7
a|

a|
8
a|

a|
8
a|

a|
9
a|

a|
9
a|

a|
10
a|

a|
10
a|

a|
11
a|

a|
11
a|

a|
12
a|

a|
12
a|

a|
13
a|

a|
13
a|

a|
14
a|

a|
14
a|

a|
15
a|

a|
15
a|

a|
16
a|

a|
16
a|

a|
17
a|

a|
17
a|

a|
18
a|

a|
18
a|

a|
19
a|

a|
19
a|

a|
20
a|

a|
20
a|

a|
21
a|

a|
21
a|

a|
22
a|

a|
22
a|

a|
23
a|

a|
23
a|

a|
24
a|

a|
24
a|

a|
25
a|

a|
25 
a|

a|
26
a|

a|
26
a|

a|
27
a|

a|
27
a|

a|
28
a|

a|
28
a|

a|
29
a|

a|
29
a|

a|
30
a|

a|
30
a|

a|
31
a|

a|
31
a|

a|
32
a|

a|
32
a|
|===

See the link:https://hwu.netapp.com/Switch/Index[Hardware Universe^] for more information on switch ports.

// New content for OAM project, AFFFASDOC-331, 2025-MAY-08