---
permalink: switch-cisco-9332d-gx2b/setup-switch-9332d-cluster.html
sidebar: sidebar
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9332d-gx2b
summary: After you power on Cisco Nexus 9332D-GX2B switch(es) as part of a new AFX system installation or a switch replacement, or after you reset a switch to its factory default settings, you are prompted to complete the initial setup for the switch(es) using configuration wizard. You can reference the following configuration wizard questions and recommended responses to help you complete the initial setup of the switch(es).
---
= Complete initial switch setup - Cisco Nexus 9332D-GX2B
:icons: font
:imagesdir: ../media/

[.lead]
After you power on Cisco Nexus 9332D-GX2B switch(es) as part of a new AFX system installation or a switch replacement, or after you reset a switch to its factory default settings, you are prompted to complete the initial setup for the switch(es) using configuration wizard. You can reference the following configuration wizard questions and recommended responses to help you complete the initial setup of the switch(es).

.Before you begin

* If you are installing switches as part of a new AFX system installation, make sure you have completed the https://docs.netapp.com/us-en/ontap-afx/install-setup/power-on-configure-switch.html[Power on and configure the switch^] procedure for each switch in your AFX system.
+
Lisa: note that the above topic in the AFX repo links back to my Configure sw and RCF workflow topic, which has users complete switch config, sw, RCF, SSH, health monitor and SCH, THEN links back to AFX repo to pwr on the system. Hey, in what switch topic does it link back to the AFX repo? BUT must change the AFX doc link to go to my switch setup topic instead.

* If you are replacing a switch in an existing AFX system, make sure you have completed the link:replace-9332d-cluster-test.html[Replace a switch] procedure.

* If you are resetting a switch to its factory default settings, make sure you have completed the link:reset-switch-9332d.html[Reset a switch to factory default settings] procedure.

* Make sure you have the following network information for each switch to complete the initial switch setup:
** The switch name.
** The IP address for Out-of-band (mgmt0) management configuration.
** The default gateway to enable remote management from a different network/VLAN than the management interface (mgmt0).
//for the switch management interface (mgmt0). 

** The number of key bits from 1014 to 2048 for SSH key generation.

//* Make sure you have the applicable licenses, network and configuration information, and cables.


.About this task
* When you power on the switch(es), they begin to boot and you are prompted to provide answers to the following series of questions to complete the initial switch startup.
+
You must complete the initial setup on each switch.

* If needed, you can access the applicable link:required-documentation-9332d-cluster.html[Cisco switch and ONTAP reference documentation]. 

.Steps

. Complete the initial switch setup by providing responses to the following questions.
+
NOTE: Your site's security policy defines the responses and services to enable.
+
[options="header" cols="1,2"]
|===
| Prompt| Response
a|
Abort Auto Provisioning and continue with normal setup? (yes/no)
a|
Respond with *yes*. The default is no.
a|
Do you want to enforce secure password standard? (yes/no)
a|
Respond with *yes*. The default is yes.
a|
Enter the password for admin.
a|
The default password is "`admin`"; you must create a new, strong password. A weak password can be rejected.
a|
Would you like to enter the basic configuration dialog? (yes/no)
a|
Respond with *yes* at the initial configuration of the switch.
a|
Create another login account? (yes/no)
a|
Your answer depends on your site's policies on alternate administrators. The default is *no*.
a|
Configure read-only SNMP community string? (yes/no)
a|
Respond with *no*. The default is no.
a|
Configure read-write SNMP community string? (yes/no)
a|
Respond with *no*. The default is no.
a|
Enter the switch name.
a|
Enter the switch name, which is limited to 63 alphanumeric characters.
a|
Continue with Out-of-band (mgmt0) management configuration? (yes/no)
a|
Respond with *yes* (the default) at that prompt. At the mgmt0 IPv4 address: prompt, enter your IP address: ip_address.
a|
Configure the default-gateway? (yes/no)
a|
Respond with *yes*. At the IPv4 address of the default-gateway: prompt, enter your default_gateway.
a|
Configure advanced IP options? (yes/no)
a|
Respond with *no*. The default is no.
a|
Enable the telnet service? (yes/no)
a|
Respond with *no*. The default is no.
a|
Enabled SSH service? (yes/no)
a|
Respond with *yes*. The default is yes.

NOTE: SSH is recommended when using Ethernet Switch Health Monitor (CSHM) for its log collection features. SSHv2 is also recommended for enhanced security.
a|
Enter the type of SSH key you want to generate (dsa/rsa/rsa1).
a|
The default is *rsa*.
a|
Enter the number of key bits (1024-2048).
a|
Enter the number of key bits from 1024 to 2048.
a|
Configure the NTP server? (yes/no)
a|
Respond with *no*. The default is no.
a|
Configure default interface layer (L3/L2)
a|
Respond with *L2*. The default is L2.
a|
Configure default switch port interface state (shut/noshut)
a|
Respond with *noshut*. The default is noshut.
a|
Configure CoPP system profile (strict/moderate/lenient/dense)
a|
Respond with *strict*. The default is strict.
a|
Would you like to edit the configuration? (yes/no)
a|
You should see the new configuration at this point. Review and make any necessary changes to the configuration you just entered. Respond with *no* at the prompt if you are satisfied with the configuration. Respond with *yes* if you want to edit your configuration settings.
a|
Use this configuration and save it? (yes/no)
a|
Respond with *yes* to save the configuration. This automatically updates the kickstart and system images.

NOTE: If you do not save the configuration at this stage, none of the changes will be in effect the next time you reboot the switch.
|===

. Verify the configuration choices you made in the display that appears at the end of the setup, and make sure that you save the configuration.

//. Check the version of software on the switch(es), and if necessary, download the 
//NetApp-supported version of the software to the switches from the https://software.cisco.com/download/home[Cisco software download^] page.

.What's next?

After you've completed the initial switch setup, you link:configure-software-overview-9332d-cluster.html[install the NX-OS software and RCF].

// New content for OAM project, AFFFASDOC-331, 2025-MAY-08
// Refactored content project, GH#423 2026-APR-MAY