---
permalink: switch-cisco-9336c-fx2/9336-overview.html
sidebar: sidebar
keywords: cisco nexus 9336c-fx2
summary: If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.
---
= Cisco 9336C-FX2 switch overview
:icons: font
:imagesdir: ../media/

[.lead]
If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.

You can install the Cisco Nexus 9336C-FX2 switch (X190200/X190210) in a NetApp system cabinet or third-party cabinet with the standard brackets that are included with the switch.

The following table lists the part number and description for the 9336C-FX2 switch, fans, and power supplies:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
X190200-CS-PE
a|
N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28
a|
X190200-CS-PI
a|
N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28
a|
X190210-FE-PE
a|
N9K-9336C, FTE, PTSX, 36PT10/25/40/100GQSFP28
a|
X190210-FE-PI
a|
N9K-9336C, FTE, PSIN, 36PT10/25/40/100GQSFP28
a|
X190002
a|
Accessory Kit X190001/X190003
a|
X-NXA-PAC-1100W-PE2
a|
N9K-9336C AC 1100W PSU - Port side exhaust airflow
a|
X-NXA-PAC-1100W-PI2
a|
N9K-9336C AC 1100W PSU - Port side Intake airflow
a|
X-NXA-FAN-65CFM-PE
a|
N9K-9336C 65CFM, Port side exhaust airflow
a|
X-NXA-FAN-65CFM-PI
a|
N9K-9336C 65CFM, Port side intake airflow
|===

== Other supported switches

* Nexus 3232C
+
You can install the Cisco Nexus 3232C switch (X190100) NetApp system cabinet with the custom brackets that come with the switch, or you can install it in a rack with the standard brackets that are also included with the switch.

* Nexus 3132Q-V
+
You can install the Cisco Nexus 3132Q-V switch (X190001) in a NetApp system cabinet or third-party cabinet with the standard brackets that are included with the switch.

The following cluster switches are no longer available from NetApp, but will be supported by Cisco for a limited time:

* Nexus 5596UP/5596T
+
You can install the Cisco Nexus 5596UP switch (X1967-R6) or 5596T (X1989-R6) in a NetApp system cabinet with the custom brackets that come with the switch, or you can install it in a rack with the standard brackets that are also included with the switch.
+
The Nexus 5596UP switch also supports one or two 16-port expansion modules (X1988-R6).
+
The Nexus 5596T switch is only supported as a cluster interconnect switch for the FAS2520 and is intended to be used for performing nondisruptive hardware upgrades.
+
http://support.netapp.com/info/communications/ECMP12454150.html[End of Availability] details.
