---
sidebar: sidebar
permalink: switch-cisco-9336c-fx2/components-9336c-cluster.html
keywords: shared storage cluster switch
summary: From ONTAP 9.9.1, you can use Cisco Nexus 9336C-FX2 switches to combine storage and cluster functionality into a shared switch scenario.
---
= Components and part numbers for Cisco Nexus 9336C-FX2 and 9336C-FX2-T cluster switches
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
For Cisco Nexus 9336C-FX2 and 9336C-FX2-T switch installation and maintenance, be sure to review the list of components and part numbers.
 
== Part number details
The following table lists the part number and description for the 9336C-FX2 and 9336C-FX2-T switches, fans, and power supplies:

[options="header" cols="1,2"]
|===
| Part number| Description

a|
X190200-CS-PE
a| 	
Cluster Switch, N9336C 36Pt PTSX 10/25/40/100G
a|
X190200-CS-PI
a|
Cluster Switch, N9336C 36Pt PSIN 10/25/40/100G
a|
X190212-CS-PE
a|
Cluster Switch, N9336C 12Pt (9336C-FX2-T) PTSX 10/25/40/100G
a|
X190212-CS-PI
a|
Cluster Switch, N9336C 12Pt (9336C-FX2-T) PSIN 10/25/40/100G
a|
NetApp SW-N9K-FX2-24P-UPG

Cisco N9K-FX2-24P-UPG
a|
SW, Cisco 9336CFX2 24-Port POD License
a|
X190210-FE-PE
a|
N9K-9336C, FTE, PTSX, 36PT 10/25/40/100GQSFP28
a|
X190210-FE-PI
a|
N9K-9336C, FTE, PSIN, 36PT 10/25/40/100GQSFP28
a|
X190002
a|
Accessory Kit X190001/X190003
a|
X-NXA-PAC-1100W-PE2
a|
N9K-9336C AC 1100W PSU - Port side exhaust airflow
a|
X-NXA-PAC-1100W-PI2
a|
N9K-9336C AC 1100W PSU - Port side Intake airflow
a|
X-NXA-FAN-65CFM-PE
a|
N9K-9336C 65CFM, Port side exhaust airflow
a|
X-NXA-FAN-65CFM-PI
a|
N9K-9336C 65CFM, Port side intake airflow
|===


== Cisco Smart licenses

In order to activate more than 12 ports, you must purchase a Cisco smart license. Cisco smart licenses are managed through Cisco smart accounts.

. Create a new Smart account, if required. See https://id.cisco.com/signin/register[Create a new Smart account^] for details.
. Request access to an existing Smart account. See https://id.cisco.com/oauth2/default/v1/authorize?response_type=code&scope=openid%20profile%20address%20offline_access%20cci_coimemberOf%20email&client_id=cae-okta-web-gslb-01&state=s2wvKDiBja__7ylXonWrq8w-FAA&redirect_uri=https%3A%2F%2Frpfa.cloudapps.cisco.com%2Fcb%2Fsso&nonce=qO6s3cZE5ZdhC8UKMEfgE6fbu3mvDJ8PTw5jYOp6z30[Request access to an existing Smart account^] for details. 
. Buy your Smart license. See https://www.cisco.com/c/en/us/buy.html[How to buy a Smart license^] for details.

Applicable part numbers for Cisco Nexus 9336C-FX2-T are:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
Cisco: N9K-FX2-24P-UPG
a|
SW, Cisco 9336CFX2 24-Port POD License
a|
NetApp: SW-N9K-FX2-24P-UPG
a|
SW, Cisco 9336CFX2 24-Port POD License
|===

NOTE: Once you have purchased your Smart license, install the appropriate RCF file to configure and load all 36 available ports for use.






// Updates for MF AFFFASDOC-234, JUL-2024