---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html
sidebar: sidebar
keywords: switches, initial installation, configure switch-cisco-9336c-fx2 switch
summary: 'Overview of software configuration for Cisco Nexus 9336C-FX2 cluster switches'
---
= Software install workflow for Cisco Nexus 9336C-FX2 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
To install and configure the software for a Cisco Nexus 9336C-FX2 switch and to install or upgrade the Reference Configuration File (RCF), follow these steps:

. link:install-nxos-overview-9336c-cluster.html[Prepare to install the NX-OS software and RCF]. 
+
The Cisco NX-OS software and reference configuration files (RCFs) must be installed on Cisco Nexus 9336C-FX2 cluster switches.

. link:install-nxos-software-9336c-cluster.html[Install or upgrade the NX-OS software]. 
+
Download and install or upgrade the NX-OS software on the Cisco Nexus 9336C-FX2 cluster switch.

. link:install-upgrade-rcf-overview-cluster.html[Install or upgrade the RCF]. 
+
Install or upgrade the RCF after setting up the Cisco Nexus 9336C-FX2 switch for the first time. You can also use this procedure to upgrade your RCF version.

. link:configure-ssh-keys.html[Verify SSH configuration on the Nexus 9336C-FX2 cluster switches]. 
+
If you use the Ethernet Switch Health Monitor (CSHM) and log collection features, verify SSH is enabled on the switches.

// Updates for the Batik release ONTAPDOC-1340, 2023-SEPT-25
// Updates for upgrade RCF details, 2024-APR-30
// Updates for GH issue #204, 2024-SEP-10
// Updates for GH issue #214, 2024-OCT-24
// Link fix, 2025-FEB-14