---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html
sidebar: sidebar
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch
summary: 'Overview of software configuration for Cisco Nexus 9336C-FX2 cluster switches'
---
= Software install workflow for Cisco Nexus 9336C-FX2 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
To install and configure the software for a Cisco Nexus 9336C-FX2 switch and to install or upgrade the Reference Configuration File (RCF), follow these steps:

. link:install-nxos-overview-9336c-cluster.html[Prepare to install NX-OS software and RCF]. 
. link:install-nxos-software-9336c-cluster.html[Install the NX-OS software]. 
. link:install-nxos-rcf-9336c-cluster.html[Install or upgrade the Reference Configuration File (RCF)]. 
+
Install the RCF after setting up the Nexus 9336C-FX2 switch for the first time. You can also use this procedure to upgrade your RCF version.
+
.Available RCF configurations
+
The following table describes the RCFs available for different configurations. Choose the RCF applicable to your configuration.
+
For specific port and VLAN usage details, refer to the banner and important notes section in your RCF.
+ 
[options="header" cols="1,2"]
|===
| RCF name | Description
a|
12P-1-Cluster-HA-Breakout
a|
Ports are configured for 4x10GbE breakout, 4x25GbE breakout (RCF 1.6+ on 100GbE switches), and 40/100GbE. Supports systems that use shared cluster/HA Ethernet ports. See the link:https://hwu.netapp.com[Hardware Universe^] for specific model information. Additionally, all ports can be used as dedicated cluster ports.
a|
12P-1-Cluster-HA
a|
A total of 12 ports are configured for 40/100GbE (10 for cluster traffic and 2 ISL ports). Supports systems that use shared cluster/HA Ethernet ports. See the link:https://hwu.netapp.com[Hardware Universe^] for specific model information. Additionally, 10 ports can be used as dedicated cluster ports.
a|
2-Cluster-HA-Breakout
a|
Supports two ONTAP clusters with at least eight nodes, including nodes that use shared Cluster+HA ports.
a|
4-Cluster-HA-Breakout
a|
Supports four ONTAP clusters with at least four nodes, including nodes that use shared Cluster+HA ports.
a|
1-Cluster-HA
a|
All ports are configured for 40/100GbE. Supports systems that use shared cluster/HA Ethernet ports. See the link:https://hwu.netapp.com[Hardware Universe^] for specific model information. Additionally, all ports can be used as dedicated cluster ports.
a|
1-Cluster-HA-Breakout
a|
Ports are configured for 4x10GbE breakout, 4x25GbE breakout (RCF 1.6+ on 100GbE switches), and 40/100GbE. Supports systems that use shared cluster/HA Ethernet ports. See the link:https://hwu.netapp.com[Hardware Universe^] for specific model information. Additionally, all ports can be used as dedicated cluster ports.
a|
Cluster-HA-Storage
a|
Ports are configured for 40/100GbE for Cluster+HA, 4x10GbE Breakout for Cluster and 4x25GbE Breakout for Cluster+HA, and 100GbE for each Storage HA Pair.
a|
Cluster
a|
Two flavors of RCF with different allocations of 4x10GbE ports (breakout) and 40/100GbE ports. All FAS/AFF nodes are supported, except for systems that use shared cluster/HA ports.
a|
Storage
a|
All ports are configured for 100GbE NVMe storage connections.
|===

// Updates for the Batik release ONTAPDOC-1340, 2023-SEPT-25
// Updates for upgrade RCF details, 2024-APR-30
// Updates for MicroFleece (AFFFASDOC-234), 2024-JUL-15