---
permalink: switch-cisco-9336c-fx2/configure-switch-overview-9336c-cluster.html
sidebar: sidebar
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch
summary: 'Before configuring switch-cisco-9336c-fx2 switches, review an overview of the process and the nomenclature.'
---
= Overview of configuration process for Cisco Nexus 9336C-FX2 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
Before configuring Cisco Nexus 9336C-FX2 switches, review the requirements and the procedural overview.

To initially configure a Cisco Nexus 9336C-FX2 switch on systems running ONTAP, follow these steps:

. link:install-nxos-overview-9336c-cluster.html[Prepare to install NX-OS and RCF]. Follow preliminary procedures in preparation for installing the Cisco NX-OS software and reference configuration files (RCFs).
. link:install-nxos-software-9336c-cluster.html[Install the NX-OS software]. Install the NX-OS software on the Nexus 9336C-FX2 cluster switch.
. link:install-nxos-rcf-9336c-cluster.html[Install the RCF config file]. Install the RCF after setting up the Nexus 9336C-FX2 switch for the first time. You can also use this procedure to upgrade your RCF version.

