---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html
sidebar: sidebar
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch
summary: 'Overview of software configuration for Cisco Nexus 9336C-FX2 cluster switches'
---
= Software install workflow for Cisco Nexus 9336C-FX2 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
To install and configure the software for a Cisco Nexus 9336C-FX2 switch, follow these steps:

. link:install-nxos-overview-9336c-cluster.html[Prepare to install NX-OS software and RCF]. 
. link:install-nxos-software-9336c-cluster.html[Install the NX-OS software]. 
. link:install-nxos-rcf-9336c-cluster.html[Install the Reference Configuration File (RCF)]. 
+
Install the RCF after setting up the Nexus 9336C-FX2 switch for the first time. You can also use this procedure to upgrade your RCF version.
+
.Available RCF configurations
+
The following table describes the RCFs available for different configurations. Choose the RCF applicable to your configuration.
+
For specific port and VLAN usage details, refer to the banner and important notes section in your RCF.
+ 
[options="header" cols="1,2"]
|===
| RCF name | Description
a|
2C-MultiCluster-HA
a|
Supports two ONTAP clusters with at least eight nodes, including nodes that use shared Cluster+HA ports.
a|
4C-MultiCluster-HA
a|
Supports four ONTAP clusters with at least four nodes, including nodes that use shared Cluster+HA ports.
a|
Cluster-HA
a|
All ports are configured for 40/100GbE. Supports shared cluster/HA traffic on ports. Required for AFF A320, AFF A250, and FAS500f systems. Additionally, all ports can be used as dedicated cluster ports.
a|
Cluster-HA-Breakout
a|
Ports are configured for 4x10GbE breakout, 4x25GbE breakout (RCF 1.6+ on 100GbE switches), and 40/100GbE. Supports shared cluster/HA traffic on ports for nodes that use shared cluster/HA ports: AFF A320, AFF A250, and FAS500f. Additionally, all ports can be used as dedicated cluster ports.
a|
Cluster-HA-Storage
a|
Ports are configured for 40/100GbE for Cluster+HA, 4x10GbE Breakout for Cluster and 4x25GbE Breakout for Cluster+HA, and 100GbE for each Storage HA Pair.
a|
Cluster
a|
Two flavors of RCF with different allocations of 4x10GbE ports (breakout) and 40/100GbE ports. All FAS/AFF nodes are supported, except for AFF A320, AFF A250, and FAS500f.
a|
Storage
a|
All ports are configured for 100GbE NVMe storage connections.
|===

// Updates for the Batik release ONTAPDOC-1340, 2023-SEPT-25