---
permalink: switch-cisco-9336c-fx2/install-nxos-rcf-9336c-cluster.html
sidebar: sidebar
keywords: install rcf, cisco switches
summary: 'You can install the RCF after setting up the Nexus 9336C-FX2 switch for the first time.You can also use this procedure to upgrade your RCF version.'
---
= Install or upgrade the Reference Configuration File (RCF)
:icons: font
:imagesdir: ../media/

[.lead]
You install the Reference Configuration File (RCF) after setting up the Nexus 9336C-FX2 switch for the first time. You upgrade your RCF version when you have an existing version of the RCF file installed on your switch. 

.Suggested documentation
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches (NSS)^]
+
Consult the switch compatibility table for the supported ONTAP and RCF versions on the NetApp Support Site. Note that there can be command dependencies between the command syntax in the RCF and the syntax found in specific versions of NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html[Cisco Nexus 3000 Series Switches^]
+
Refer to the appropriate software and upgrade guides available on the Cisco web site for complete documentation on the Cisco switch upgrade and downgrade procedures.

.About the examples
The examples in this procedure use the following switch and node nomenclature:

* The names of the two Cisco switches are cs1 and cs2.
* The node names are cluster1-01, cluster1-02, cluster1-03, and cluster1-04.
* The cluster LIF names are cluster1-01_clus1, cluster1-01_clus2, cluster1-02_clus1, cluster1-02_clus2 , cluster1-03_clus1, cluster1-03_clus2, cluster1-04_clus1, and cluster1-04_clus2.
* The `cluster1::*>` prompt indicates the name of the cluster.

The examples in this procedure use four nodes. These nodes use two 10GbE cluster interconnect ports e0a and e0b. See the https://hwu.netapp.com/SWITCH/INDEX[Hardware Universe] to verify the correct cluster ports on your platforms.

NOTE: The command outputs might vary depending on different releases of ONTAP.

For details of the available RCF configurations, see link:configure-software-overview-9336c-cluster.html[Software install workflow].

.Commands used
The procedure requires the use of both ONTAP commands and Cisco Nexus 9000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

== Option 1: Install RCF file on a new switch
You install the Reference Configuration File (RCF) after setting up the Nexus 9336C-FX2 switch for the first time.

include::../_include/install-rcf-software-9336c-cluster.adoc[]

== Option 2: Upgrade existing switches with a new RCF version
You upgrade your RCF version when you have an existing version of the RCF file installed on your operational switches. 

.Before you begin
Make sure you have the following:

* A current backup of the switch configuration.
* A fully functioning cluster (no errors in the logs or similar issues).
* The current RCF file.
* If you are updating your RCF version, you need a boot configuration in the RCF that reflects the desired boot images. 
+
If you need to change the boot configuration to reflect the current boot images, you must do so before reapplying the RCF so that the correct version is instantiated on future reboots.

NOTE: No operational inter-switch link (ISL) is needed during this procedure. This is by design because RCF version changes can affect ISL connectivity temporarily. To ensure non-disruptive cluster operations, the following procedure migrates all of the cluster LIFs to the operational partner switch while performing the steps on the target switch.

CAUTION: Before installing a new switch software version and RCFs, you must erase the switch settings and perform basic configuration. You must be connected to the switch using the serial console or have preserved basic configuration information prior to erasing the switch settings.

include::../_include/upgrade-rcf-software-9336c-cluster.adoc[]

// Updates for AFFFASDOC-199, 2024-APR-14