---
permalink: switch-cisco-9336c-fx2/migrate_requirements.html
sidebar: sidebar
keywords: Cisco Nexus cluster switches,replacing older Cisco switches,9336C-FX2 cluster switches,migrate to newer cisco cluster switch
summary: 'You must be aware of certain configuration information, port connections and cabling requirements when you are replacing some older Cisco Nexus cluster switches with Cisco Nexus 9336C-FX2 cluster switches.'
---
= Migrate requirements
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain configuration information, port connections and cabling requirements when you are replacing some older Cisco Nexus cluster switches with Cisco Nexus 9336C-FX2 cluster switches.

== Older Cisco switch to a Cisco Nexus 9336C-FX2 cluster switch
* The following cluster switches are supported:
 ** Nexus 9336C-FX2
 ** Nexus 5596UP
 ** Nexus 3232C
 ** Nexus 3132Q-V
* See the https://hwu.netapp.com/[Hardware Universe^] for full details of supported ports and their configurations.
* You have configured some of the ports on Nexus 9336C-FX2 switches to run at 10 GbE or 40 GbE.
* You have planned, migrated, and documented 10 GbE and 40 GbE connectivity from nodes to Nexus 9336C-FX2 cluster switches.

* The ONTAP and NX-OS versions supported in this procedure are on the https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches^] page.

== Two-nodes
You must be aware of certain configuration information, port connections, and cabling requirements when you migrate a two-node switchless cluster, non-disruptively, to a cluster with Cisco Nexus 9336C-FX2 cluster switches.

The procedure you use depends on whether you have two dedicated cluster-network ports on each controller or a single cluster port on each controller. The process documented works for all nodes using optical or Twinax ports but is not supported on this switch if nodes are using onboard 10Gb BASE-T RJ45 ports for the cluster-network ports.

Most systems require two dedicated cluster-network ports on each controller. See https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet switches^]
