---
permalink: switch-cisco-9336c-fx2/smart-call-9336c-cluster.html
sidebar: sidebar
keywords: cisco smart call,small call home
summary: 'Smart Call Home monitors the hardware and software components on your network, to generate an email-based notification of critical system conditions. When an event occurs on your device, Smart Call Home raises an alert to all the recipients that are configured in your destination profile.'
---
= Smart Call Home requirements
:icons: font
:imagesdir: ../media/

[.lead]
To use the Smart Call Home feature, review the following guidelines.

Smart Call Home monitors the hardware and software components on your network. When a critical system configuration occurs, it generates an email-based notification and raises an alert to all the recipients that are configured in your destination profile. To use Smart Call Home, you must configure a cluster network switch to communicate using email with the Smart Call Home system. In addition, you can optionally set up your cluster network switch to take advantage of Cisco's embedded Smart Call Home support feature.

Before you can use Smart Call Home, be aware of the following considerations:

* An email server must be in place.
* The switch must have IP connectivity to the email server.
* The contact name (SNMP server contact), phone number, and street address information must be configured. This is required to determine the origin of messages received.
* A CCO ID must be associated with an appropriate Cisco SMARTnet Service contract for your company.
* Cisco SMARTnet Service must be in place for the device to be registered.

The http://www.cisco.com/c/en/us/products/switches/index.html[Cisco support site^] contains information about the commands to configure Smart Call Home.

