---
permalink: switch-bes-53248/components-bes53248.html
sidebar: sidebar
keywords: cluster-mode,supported versions,switches supported,cluster network,efos
summary: 'For BES-53248 switch installation and maintenance, be sure to review the list of components and part numbers.'
---
= Components and part numbers for BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
For BES-53248 switch installation and maintenance, be sure to review the list of components and part numbers.

The following table lists the part number and description for the newly available BES-53248 cluster switch components, including Power Supply Units (PSU) and rack-mount rail kit details.

[options="header" cols="1,2,3"]
|===
| Part number| Description | Minimum EFOS version 
a|
BES-53248A2-G1-16E1-R or is it BES-53248-B?
a|
FSP-based
a|
3.10.0.3
a|
BES-53248A2-G1-16E1-F
a|
FSP-based
a|
3.10.0.3
a|
BES-53248A3-G1-16E1-R
a|
Greatwall-based
a|
3.10.0.3
a|
BES-53248A3-G1-16E1-F
a|
Greatwall-based
a|
3.10.0.3
a|
BES-53248A2-PSU-R
a|
FSP-based
a|
3.10.0.3
a|
BES-53248A2-PSU-F
a|
FSP-based
a|
3.10.0.3
a|
BES-53248A3-PSU-R
a|
Greatwall-based
a|
3.10.0.3
a|
BES-53248A3-PSU-F
a|
Greatwall-based
a|
3.10.0.3
a|
X-RAIL-4POST-190005
a|
Rack mount rail kit Ozeki 4 post 19"
a|
N/A
|===

NOTE: A minimum EFOS version of *3.10.0.3* is required for the components listed in the table above. 


The following table lists the part number and description for existing BES-53248 cluster switch components, including rack-mount rail kit details.

[options="header" cols="1,2"]
|===
| Part number| Description
a|
X190005
a|
BES-53248, CLSW, 16Pt10/25GB, PTSX, BRDCM SUPP (PTSX = Port Side Exhaust)
a|
X190005R
a|
BES-53248, CLSW, 16Pt10/25GB, PSIN, BRDCM SUPP (PSIN = Port Side Intake)
a|
X-RAIL-4POST-190005
a|
Rack mount rail kit Ozeki 4 post 19"
|===

//
//X-FAN-190005-R
//Fan, port side intake X190005
//X-FAN-190005-F
//Fan, port side exhaust X190005
//X-PSU-190005-R
//Power supply, port side intake X190005
//Port-side intake airflow (reverse air): Cool air enters the chassis through the port end in the cold aisle and exhausts through the fan and power supply modules in the hot aisle.
//X-PSU-190005-F
//Power supply, port side exhaust X190005
//Port-side exhaust airflow (standard air): Cool air enters the chassis through the fan and power supply modules in the cold aisle and exhausts through the port end of the chassis in the hot aisle. Blue coloring indicates port-side exhaust airflow. This is the most common option.
|===

// Updates for the new PSU for Jute, 2023-APR


