---
permalink: switch-bes-53248/complete-upgrade.html
sidebar: sidebar
keywords: BES-53248 switches, upgrade completion, upgrade bes-53248 switch
summary: 'Before configuring BES-53248 cluster switches, review an overview of the process and the nomenclature.'
---
= Complete the upgrade of your BES-53248 cluster switch
:icons: font
:imagesdir: ../media/

[.lead]
//Before upgrading your BES-53248 cluster switches, review the configuration overview.
Follow these steps to complete the upgrade of your BES-54328 cluster switches, as applicable.

//. link:upgrade-efos-software.html[Upgrade your EFOS version]. 

//Download and install the Ethernet Fabric OS (EFOS) software on the BES-53248 cluster switch.

//. link:upgrade-rcf.html[Upgrade your RCF version]. 

//Upgrade the RCF on the BES-53248 cluster switch, and then verify the ports for any additional licenses after the RCF is applied.

. link:configure-ssh.html[Enable SSH on BES-53248 cluster switches]. 
+
If you use the Cluster Switch Health Monitor (CSHM) and log collection features, enable SSH on the switches.
+
. link:configure-log-collection.html[Enable the log collection feature]. 
+
Use this feature to collect switch-related log files in ONTAP.
+
. link:CSHM_snmpv3.html[Configure SNMPv3 for monitoring].
+
If you use the Cluster Switch Health Monitor (CSHM) feature, configure SNMPv3, which supports Ethernet switch health monitoring (CSHM).


// New content for GH issues #72, 109, 124, AFFFASDOC-212, 2024-APR-02