---
permalink: switch-bes-53248/configure-install-initial.html
sidebar: sidebar
keywords: switches initial setup,initial setup,efos download
summary: 'You can use this procedure to perform the initial installation of the BES-53248 cluster switch.'
---
= Configure the BES-53248 cluster switch
:icons: font
:imagesdir: ../media/

[.lead]
Follow these steps to perform an initial setup of the BES-53248 cluster switch.

.Before you begin

* Hardware is installed, as described in link:install-hardware-bes53248.html[Install the hardware].
* You have reviewed the following:

** link:configure-reqs-bes53248.html[Configuration requirements]
** link:components-bes53248.html[Components and part numbers]
** link:required-documentation-bes53248.html[Documentation requirements]

.About the examples

The examples in the configuration procedures use the following switch and node nomenclature:

* The NetApp switch names are `cs1` and `cs2`. The upgrade starts on the second switch, _cs2._
* The cluster LIF names are `node1_clus1` and `node1_clus2` for node1, and `node2_clus1` and `node2_clus2` for node2.
* The IPspace name is Cluster.
* The `cluster1::>` prompt indicates the name of the cluster.
* The cluster ports on each node are named `e0a` and `e0b`. See the https://hwu.netapp.com/Home/Index[NetApp Hardware Universe^] for the actual cluster ports supported on your platform.
* The Inter-Switch Links (ISLs) supported for the NetApp switches are ports 0/55 and 0/56.
* The node connections supported for the NetApp switches are ports 0/1 through 0/16 with default licensing.
* The examples use two nodes, but you can have up to 24 nodes in a cluster.


.Steps

. Connect the serial port to a host or serial port.
. Connect the management port (the RJ-45 wrench port on the left side of the switch) to the same network where your TFTP server is located.
. At the console, set the host-side serial settings:
 ** 115200 baud
 ** 8 data bits
 ** 1 stop bit
 ** parity: none
 ** flow control: none
. Log in to the switch as `admin` and press *Enter* when prompted for a password.
The default switch name is *routing*. At the prompt, enter `enable`. This gives you access to Privileged EXEC mode for switch configuration.
+
[subs=+quotes]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----

. Change the switch name to *cs2*.
+
[subs=+quotes]
----
(Routing)# *hostname cs2*
(cs2)#
----

. To set a static IP address, use the `serviceport protocol`, `network protocol`, and `serviceport ip` commands as shown in the example.
+
The serviceport is set to use DHCP by default. The IP address, subnet mask, and default gateway address are assigned automatically.
+
[subs=+quotes]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip ipaddr netmask gateway*
----

. Verify the results using the command:
+
`show serviceport`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
====

. Configure the domain and name server:
+
`ip domain name <domain_name>`
+
`ip name server <server_name>`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
====

. Configure the NTP server.

// start of tabbed content 
[role="tabbed-block"] 

==== 
.EFOS 3.9.0.2 and earlier
--
Configure the time zone and time synchronization (SNTP):

`sntp client mode <client_mode>`

`sntp server <server_name>`

`clock`

[subs=+quotes]
----
(cs2)# configure
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--

.EFOS 3.10.0.3 and later
--
Configure the time zone and time synchronization (NTP):

[subs=+quotes]
----
(cs2)configure 
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
==== 
// end of tabbed content

[start=10]
. [[step10]]Configure the time manually if you did not configure an NTP server in the previous step.

// start of tabbed content 
[role="tabbed-block"] 

==== 
.EFOS 3.9.0.2 and earlier
--
`clock`

[subs=+quotes]
----

(cs2)# *config*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2020*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2020
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--

.EFOS 3.10.0.3 and later
--
`clock`

[subs=+quotes]
----

(cs2)# *config*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2020*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2020
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
==== 
// end of tabbed content

[start=11]
. [[step11]]Save the running configuration to the startup configuration:
+
`write memory`
+
[subs=+quotes]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----

.What's next?

link:configure-efos-software.html[Install the EFOS software]

// Added note for ntp usage, as per GH issue #94, 2023-MAY-16
// Updated with details for ntp for EFOS 3.10, as per AFFFASDOC-141, 2023-OCT-12
// Minor update for Sunil, added in ntp server 10.99.99.5, 2023-OCT-17
// Updates for GH issues #72, 109, 12, AFFFASDOC-212, 2024-MAY-02