---
permalink: switch-bes-53248/configure-log-collection.html
sidebar: sidebar
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation
summary: 'The cluster switch health monitor log collection feature is used to collect switch-related log files in ONTAP. You must make sure that you have set up your environment using the BES-53248 cluster switch CLI as detailed here.'
---
= Enable the log collection feature
:icons: font
:imagesdir: ../media/

[.lead]
You can use the log collection feature to collect switch-related log files in ONTAP. 

IMPORTANT: To enable the log collection feature, you must be running ONTAP version 9.12.1 and later and EFOS 3.8.0.2 and later.

Verify that you have set up your environment using the BES-53248 cluster switch *CLI*.

// start of tabbed content 

//[role="tabbed-block"] 

//==== 

//.For ONTAP 9.8 and later

.Steps

. Create a password for the Ethernet switch health monitor log collection feature.
+
`system switch ethernet log setup-password`

+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====

. Enable the Ethernet switch health monitor log collection feature.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Wait for 10 minutes and then check that the log collection was successful using the command:
`system switch ethernet log show`
+
CAUTION: If any of these commands return an error, contact NetApp support.


//.For ONTAP 9.5P15, 9.6P11, 9.7P8 and later patch releases
//--

//Enable the log collection feature using the commands:

//`system cluster-switch log setup-password` and `system cluster-switch log enable-collection`

//Enter: `system cluster-switch log setup-password`

//[subs=+quotes]
//----
//cluster1::*> *system cluster-switch log setup-password*
//Enter the switch name: <return>
//The switch name entered is not recognized.
//Choose from the following list:
//*cs1*
//*cs2*

//cluster1::*> *system cluster-switch log setup-password*

//Enter the switch name: *cs1*
//RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
//Do you want to continue? {y|n}::[n] *y*

//Enter the password: <enter switch password>
//Enter the password again: <enter switch password>

//cluster1::*> *system cluster-switch log setup-password*

//Enter the switch name: *cs2*
//RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
//Do you want to continue? {y|n}:: [n] *y*

//Enter the password: <enter switch password>
//Enter the password again: <enter switch password>
//----

//Enter: `system cluster-switch log enable-collection`

//[subs=+quotes]
//----
//cluster1::*> *system cluster-switch log enable-collection*

//Do you want to enable cluster log collection for all nodes in the cluster?
//{y|n}: [n] *y*

//Enabling cluster switch log collection.
//----
//--
//==== 

// end of tabbed content 

//NOTE: The log collect command is not available at this time. See link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1225042[Bug 1225042^] for further details.

.What's next?
If you are upgrading the switch, go to link:replace-verify.html[Verify upgrade configuration].

//. Begin an initial data collection from each switch:

//* `cluster1::*> system cluster-switch log collect -device <cs1>`
//* `cluster1::*> system cluster-switch log collect -device <cs2>`

//Updates for GH issues #72 & 79, 2023-APR-04

// Updates made for AFFFASDOC-72 apply here too, 2023-JUL-12