---
permalink: switch-bes-53248/configure-reqs-bes53248.html
sidebar: sidebar
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches
summary: You can use the BES-53248 cluster switch port assignment table as a guide to configure your cluster.
---
= Configuration requirements for BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
For BES-53248 switch installation and maintenance, be sure to review EFOS and ONTAP support and configuration requirements.

== EFOS and ONTAP support

See the https://hwu.netapp.com/Switch/Index[NetApp Hardware Universe^] and https://mysupport.netapp.com/site/info/broadcom-cluster-switch[Broadcom switches compatibility matrix^] for EFOS and ONTAP compatibility information with BES-53248 switches. EFOS and ONTAP support can vary by the specific machine type of the BES-53248 switch. For details of all BES-52348 switch machine types, see link:components-bes53248.html[Components and part numbers for BES-53248 cluster switches]. See link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU[What additional information do I need to install my equipment that is not in HWU?]^ for more information about switch installation requirements.

//The BES-53248 switch supports the following:

//* *EFOS firmware 3.4.4.6 and later*. The BES-53248 switch runs on a Broadcom-embedded OS known as Ethernet Fabric OS (EFOS). Support for 40/100 GbE cluster ports starts with EFOS firmware version 3.4.4.6 and later.

//* *ONTAP 9.5P8 and later*. The Broadcom-supported  BES-53248 cluster switches are designed to work in clusters ranging in size from two to 24 nodes in ONTAP 9.5P8 and later.

== Configuration requirements
To configure a cluster, you need the appropriate number and type of cables and cable connectors for the cluster switches. Depending on the type of cluster switch you are initially configuring, you need to connect to the switch console port with the included console cable.

=== Cluster switch port assignments
You can use the Broadcom-supported BES-53248 cluster switch port assignments table as a guide to configuring your cluster.

[options="header" cols="1,2"]
|===
| Switch ports| Ports usage
a|
01-16
a|
10/25GbE cluster port nodes, base configuration
a|
17-48
a|
10/25GbE cluster port nodes, with licenses
a|
49-54
a|
40/100GbE cluster port nodes, with licenses, added right to left
a|
55-56
a|
100GbE cluster Inter-Switch Link (ISL) ports, base configuration
|===

See the https://hwu.netapp.com/Switch/Index[Hardware Universe] for more information on switch ports. See link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU[What additional information do I need to install my equipment that is not in HWU?^] for more information about switch installation requirements.

=== Port group speed constraint
* On BES-53248 cluster switches, the 48 10/25GbE (SFP28/SFP+) ports are combined into 12 x 4-port groups as follows: Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44, and 45-48.

* The SFP28/SFP+ port speed must be the same (10GbE or 25GbE) across all ports in the 4-port group.

=== Additional requirements
* If you purchase additional licenses, see link:configure-licenses.html[Activate newly licenses ports] for details on how to activate them.

* If SSH is active, you must re-enable it manually after running the command `erase startup-config` and rebooting the switch.

.What's next
After you've reviewed the configuration requirements, you can confirm your link:components-bes53248.html[components and part numbers].

// Updates for the new PSU for Jute, 2023-APR-18
// Updates for AFFFASDOC-370, 2025-JUL-29
// AFFFASDOC-411, 2025-OCT-30