---
permalink: switch-bes-53248/configure-log-collection.html
sidebar: sidebar
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation
summary: 'The cluster switch health monitor log collection feature is used to collect switch-related log files in ONTAP. You must make sure that you have set up your environment using the BES-53248 cluster switch CLI as detailed here.'
---
= Enable the log collection feature
:icons: font
:imagesdir: ../media/

[.lead]
Follow these steps to enable the cluster switch health monitor log collection feature, which is used to collect switch-related log files in ONTAP. You must make sure that you have set up your environment using the BES-53248 cluster switch CLI as detailed here.

== For ONTAP 9.8 and later

Enable the cluster switch health monitor log collection feature for collecting switch-related log files, using the commands:

`system switch ethernet log setup-password` and `system switch ethernet log enable-collection`

.Steps

. Enter: `system switch ethernet log setup-password`
+
.Example of system switch ethernet log setup-password command
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====

. Enter: `system switch ethernet log enable-collection`
+
.Example of system switch ethernet log enable-collection command
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
==== 


== For ONTAP 9.5P15, 9.6P11, 9.7P8 and later patch releases



Enable the cluster switch health monitor log collection feature for collecting switch-related log files, using the commands:

`system cluster-switch log setup-password` and `system cluster-switch log enable-collection`

.Steps

. Enter: `system cluster-switch log setup-password`
+
.Example of system cluster-switch log setup-password command
[%collapsible]
====
[subs=+quotes]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====

. Enter: `system cluster-switch log enable-collection`
+
.Example of system cluster-switch log enable-collection command
[%collapsible]
====
[subs=+quotes]
----
cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----
====

NOTE: The log collect command is not available at this time. See link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1225042[Bug 1225042^] for further details.

CAUTION: If any of these commands return an error, contact NetApp support.

.What's next?
If you are upgrading the switch, go to link:replace-verify.html[Verify upgrade configuration].




//. Begin an initial data collection from each switch:

//* `cluster1::*> system cluster-switch log collect -device <cs1>`
//* `cluster1::*> system cluster-switch log collect -device <cs2>`
