---
permalink: switch-bes-53248/configure-licenses.html
sidebar: sidebar
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches
summary: The BES-53248 cluster switch base model is licensed for 16 10GbE or 25GbE ports and two 100GbE ports. New ports can be added by purchasing more licenses.
---
= Install licenses for BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
The BES-53248 cluster switch base model is licensed for 16 10GbE or 25GbE ports and two 100GbE ports. New ports can be added by purchasing more licenses.

== Available licenses
The following licenses are available for use on the BES-53248 cluster switch:

[options="header" cols="1,2"]
|===
| License type| License details| Supported firmware version
a|
SW-BES-53248A1-G1-8P-LIC
a|
Broadcom 8P 10-25,2P40-100 License Key, X190005/R
a|
EFOS 3.4.3.3 and later
a|
SW-BES-53248A1-G1-16P-LIC
a|
Broadcom 16P 10-25,4P40-100 License Key, X190005/R
a|
EFOS 3.4.3.3 and later
a|
SW-BES-53248A1-G1-24P-LIC
a|
Broadcom 24P 10-25,6P40-100 License Key, X190005/R
a|
EFOS 3.4.3.3 and later
a|
SW-BES54248-40-100G-LIC
a|
Broadcom 6Port 40G100G License Key, X190005/R
a|
EFOS 3.4.4.6 and later
a|
SW-BES53248-8P-10G25G-LIC
a|
Broadcom 8Port 10G25G License Key, X190005/R
a|
EFOS 3.4.4.6 and later
a|
SW-BES53248-16P-1025G-LIC
a|
Broadcom 16Port 10G25G License Key, X190005/R
a|
EFOS 3.4.4.6 and later
a|
SW-BES53248-24P-1025G-LIC
a|
Broadcom 24Port 10G25G License Key, X190005/R
a|
EFOS 3.4.4.6 and later
|===

== Install licences
Learn how to install licenses for BES-53248 cluster switches.

.Steps

. Connect the cluster switch to the management network.
. Use the `ping` command to verify connectivity to the server hosting EFOS, licenses, and the RCF file.
+
This example verifies that the switch is connected to the server at IP address 172.19.2.1:
+
[subs=+quotes]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----

. Check the current license usage on switch cs2:
+
`show license`
+
[subs=+quotes]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----

. Install the license file. The following example uses SFTP to copy a license file to a key index 1.
+
Repeat this step to load more licenses and to use different key index numbers.
+
[subs=+quotes]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----

. Display all current license information and note the license status before switch cs2 is rebooted:
+
`show license`
+
[subs=+quotes]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----

. Display all licensed ports:
+
`show port all | exclude Detach`
+
The ports from the additional license files are not displayed until after the switch is rebooted.
+
[subs=+quotes]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----

. Reboot the switch:
+
`reload`
+
[subs=+quotes]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----

. Check that the new license is active and note that the license has been applied:
+
`show license`
+
[subs=+quotes]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----

. Check that all new ports are available:
+
`show port all | exclude Detach`
+
[subs=+quotes]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----

CAUTION: When installing additional licenses, you must configure the new interfaces manually. Re-applying an RCF to an existing working production switch is not advisable.

== Debug commands
Where problems arise when installing a license, the following debug commands should be run before running the `copy` command again to install the license.

Debug commands to use: `debug transfer` and `debug license`

[subs=+quotes]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----

When you run the `copy` command with the `debug transfer` and `debug license` options enabled, the following log output is returned:

----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----

Check for the following in the debug output:

* Check that the Serial number matches: `Serial number QTFCU38290012 matched.`
* Check that the switch Model matches: `Model BES-53248 matched.`
* Check that the specified license index was not used previously. Where a license index is already used, the following error is returned: `License file /mnt/download//license.dat.1 already exists.`
* A port license is not a feature license. Therefore, the following statement is expected: `Feature not found in license file with index = 1.`

Use the `copy` command to backup port licenses to the server:
[subs=+quotes]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

See link:configure-licenses.html[Installing licenses for BES-53248 cluster switches] for details of the firmware versions supported for available licenses.

CAUTION: If you need to downgrade the switch software from version 3.4.4.6, the licenses are removed. This is expected behavior.

You must install an appropriate older license before reverting to an older version of the software.
