---
permalink: switch-bes-53248/configure-ssh.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, bes, enable ssh on bes-53248 cluster switches - bes-53248 switches
summary: SSH is a requirement when using the Cluster Switch Health Monitor \(CSHM\) and log collection features. To enable SSH on BES-53248 cluster switches, you generate the SSH keys first and then enable SSH.
---
= Enable SSH on BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
If you are using the Ethernet Switch Health Monitor (CSHM) and log collection features, you must generate the SSH keys and then enable SSH on the cluster switches.

.Steps

. Verify that SSH is disabled:
+
`show ip ssh`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Disabled
SCP server Administrative Mode: ............... Disabled
----
====
+ 
If SSH is not disabled, disable it as follows:
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
(switch)# *ip ssh server disable*
(switch)# *ip scp server disable*
----
====
+
WARNING: Make sure that you disable SSH before you modify the keys, otherwise, a warning is reported on the switch.

. Within config mode, generate the SSH keys:
+
`crypto key generate`
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*
----
====

. Within config mode, set AAA authorization for ONTAP log collection:
+
`aaa authorization commands "noCmdAuthList" none`
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
----
====

. Re-enable SSH/SCP.
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(switch)# *ip ssh server enable*
(switch)# *ip scp server enable*
(switch)# *ip ssh pubkey-auth*
----
====

. Save these changes to the startup-config:
+
`write memory`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====

. Encrypt the SSH keys (for *FIPS-mode only*):

+
CAUTION: In FIPS mode, the keys are required to be encrypted with a passphrase for security. In the absence of an encrypted key, the application fails to start. The keys are created and encrypted using the following commands:

+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(switch) *configure*
(switch) (Config)# *crypto key encrypt write rsa passphrase _<passphase>_*
 
The key will be encrypted and saved on NVRAM. 
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*
 
Config file 'startup-config' created successfully.
 
(switch) (Config)# *crypto key encrypt write dsa passphrase _<passphase>_*
 
The key will be encrypted and saved on NVRAM. 
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*
 
Config file 'startup-config' created successfully.
 
(switch)(Config)# *crypto key encrypt write ecdsa passphrase _<passphase>_*
 
The key will be encrypted and saved on NVRAM. 
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*
 
Config file 'startup-config' created successfully.
 
(switch) (Config)# *end*
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*
 
Config file 'startup-config' created successfully.
 
Configuration Saved!
----               
====

. Reboot the switch:
+
`reload`

. Verify that SSH is enabled:
+
`show ip ssh`
+

.Show example
[%collapsible]
====

[subs=+quotes]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Enabled
SCP server Administrative Mode: ............... Enabled
----
====

.What's next?

link:../switch-cshm/config-overview.html[Configure switch health monitoring].


// Update for GH issue #153, 2024-JAN-17
// Update for GH issue #168, 2024-MAR-19
// Update for AFFFASDOC-216/217, 2024-JUL-08
// Update for AFFFASDOC-266, 2024-SEP-17
// Updates for AFFFASDOC-319, 2025-JUN-25
// Updates for AFFFASDOC-379, 2025-AUG-27