---
permalink: switch-bes-53248/configure-new-switch.html
sidebar: sidebar
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch
summary: 'You can configure a new BES-53248 cluster switch by completing the steps detailed in this chapter.'
---
= Configure a new BES-53248 cluster switch
:icons: font
:imagesdir: ../media/

[.lead]
You can configure a new BES-53248 cluster switch by completing the steps detailed in this chapter.

.About this task

Installing the BES-53248 cluster switch on systems running ONTAP starts with setting up an IP address and configuration to allow the switch to communicate through the management interface. Then you can install the Ethernet Fabric OS (EFOS) software, reference configuration file (RCF), and other licenses as needed. This procedure is intended for preparing the BES-53248 switch before controllers are added. In addition, you might need to install the required configuration file to support the Cluster Switch Health Monitor (CSHM) for the BES-53248 cluster switches. See link:configure-health-monitor.html[Installing the Cluster Switch Health Monitor (CSHM) configuration file] for more details.

The examples in this procedure use the following switch and node nomenclature:

* The NetApp switch names are `cs1` and `cs2`.
* The example used in this procedure starts the upgrade on the second switch, _cs2._
* The cluster LIF names are `node1_clus1` and `node1_clus2` for node1, and `node2_clus1` and `node2_clus2` for node2.
* The IPspace name is Cluster.
* The `cluster1::>` prompt indicates the name of the cluster.
* The cluster ports on each node are named e0a and e0b.
+
See the https://hwu.netapp.com/Home/Index[NetApp Hardware Universe] for the actual cluster ports supported on your platform.

* The Inter-Switch Links (ISLs) supported for the NetApp switches are ports 0/55 and 0/56.
* The node connections supported for the NetApp switches are ports 0/1 through 0/16 with default licensing.
* The examples in this procedure use two nodes, but you can have up to 24 nodes in a cluster.
