---
permalink: switch-bes-53248/configure-efos-software.html
sidebar: sidebar
keywords: BES-53248 cluster switches,installing EFOS software
summary: 'Follow these steps to install the Ethernet Fabric OS (EFOS) software on the BES-53248 cluster switch.'
---
= Install the EFOS software
:icons: font
:imagesdir: ../media/

[.lead]
Follow these steps to install the Ethernet Fabric OS (EFOS) software on the BES-53248 cluster switch.

EFOS software includes a set of advanced networking features and protocols for developing Ethernet and IP infrastructure systems. This software architecture is suitable for any network organizational device using applications that require thorough packet inspection or separation. 

== Prepare for installation

.Before you begin
* Download the applicable Broadcom EFOS software for your cluster switches from the https://www.broadcom.com/support/bes-switch[Broadcom Ethernet Switch Support^] site.

== Install the software
Use one of the following methods to install the EFOS software :

* <<Method 1: Install EFOS>>. Use for most cases.
* <<Method 2: Install EFOS in ONIE mode>>. Use if one EFOS version is FIPS compliant and the other EFOS version is non-FIPS compliant.

IMPORTANT: Install EFOS on one switch at a time to ensure continued cluster network operation.

=== Method 1: Install EFOS
Perform the following steps to install the EFOS software.

.Steps

. Connect the BES-53248 cluster switch to the management network.
. Use the `ping` command to verify connectivity to the server hosting EFOS, licenses, and the RCF file.
+
.Show example
[%collapsible]
====
This example verifies that the switch is connected to the server at IP address 172.19.2.1:

[subs=+quotes]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====

. Download the image file to the switch.
+
Copying the image file to the active image means that when you reboot, that image establishes the running EFOS version. The previous image remains available as a backup.
+
.Show example
[%collapsible]
==== 

[subs=+quotes]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====

. Display the boot images for the active and backup configuration:
+
`show bootvar`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====

. Reboot the switch:
+
`reload`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====

. Log in again and verify the new version of the EFOS software:
+
`show version`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.7.0.4, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.7.0.4
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====

. Repeat steps 3 through to 6 on the partner switch.
. Enable auto-revert on the cluster LIFs.
+
[subs=+quotes]
----
cluster1::*> **network interface modify -vserver Cluster -lif * -auto-revert True**
----

. Verify that the cluster LIFs have reverted to their home port:
+
`network interface show -role cluster`

For details see link:../ontap/networking/revert-a-lif-to-its-home-port.html[Revert a LIF to its home port].

.What's next?

link:configure-licenses.html[Install licenses for BES-53248 cluster switches]. 

=== Method 2: Install EFOS in ONIE mode
You can perform the following steps if one EFOS version is FIPS compliant and the other EFOS version is non-FIPS compliant. These steps can be used to install the non-FIPS or FIPS compliant EFOS 3.7.x.x image from ONIE if the switch fails to boot.

.Steps
. Boot the switch into ONIE installation mode.
+
During boot, select ONIE when you see the prompt.
+
.Show example
[%collapsible]
====
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
After you select *ONIE*, the switch loads and presents you with several choices. Select *Install OS*.
+
.Show example
[%collapsible]
====
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
The switch boots into ONIE installation mode.

. Stop the ONIE discovery and configure the Ethernet interface.
+
When the following message appears, press *Enter* to invoke the ONIE console:
+
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
NOTE: The ONIE discovery continues and messages are printed to the console.
+
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----

. Configure the Ethernet interface and add the route using `ifconfig eth0 <ipAddress> netmask <netmask> up` and `route add default gw <gatewayAddress>`
+
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----

. Verify that the server hosting the ONIE installation file is reachable:
+
`ping`
+
.Show example
[%collapsible]
====
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
+
. Install the new switch software:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`
+
.Show example
[%collapsible]
====
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
The software installs and then reboots the switch. Let the switch reboot normally into the new EFOS version.
+
. Login and verify that the new switch software is installed: 
+
`show bootvar`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====

. Complete the installation.
The switch reboots with no configuration applied and resets to factory defaults. Follow these four steps to reconfigure the switch:
.. link:configure-install-initial.html[Configure switch]
.. link:configure-licenses.html[Install licenses] 
.. link:configure-install-rcf.html[Install the RCF file]
.. link:configure-ssh.html[Enable SSH]
.. link:CSHM_log_collection.html[Enable log collection]
.. link:CSHM_snmpv3.html[Configure SNMPv3 for monitoring]
. Repeat steps 1 through to 7 on the partner switch.
. Enable auto-revert on the cluster LIFs.
+
[subs=+quotes]
----
cluster1::*> **network interface modify -vserver Cluster -lif * -auto-revert True**
----

. Verify that the cluster LIFs have reverted to their home port:
+
`network interface show -role cluster`

For details see link:../ontap/networking/revert-a-lif-to-its-home-port.html[Revert a LIF to its home port].

.What's next?

link:configure-licenses.html[Install licenses for BES-53248 cluster switches]. 

// 2023 FEB 16, ontap-systems-switches-issues-76
// added details for BES-53248A1 under show version commands, 2023-APR-05
// Updates for AFFFASDOC-41, 2023-MAY-10
// 2024-03-01, GitHub issue 159
