---
permalink: switch-bes-53248/index.html
sidebar: sidebar
keywords: broadcom, support, bes, cluster, switch, broadcam-supported bes-53248 cluster switches
summary: Broadcom-supported BES-53248 Cluster Switches
---
= Broadcom-supported BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
BES-53248 is a switch running on a Broadcom-embedded OS known as Ethernet Fabric OS (EFOS).

Broadcom-supported BES-53248 cluster switches are designed to work in clusters ranging in size from two to 24 nodes in ONTAP 9.5P8 and later. Support for 40/100 GbE cluster ports starts with EFOS firmware version 3.4.4.6 and later.


== Switch components
The following table lists the part number and description for the BES-53248 cluster switch, rack mount rail kit, fans, and power supplies:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
X190005
a|
BES-53248, CLSW, 16Pt10/25GB, PTSX, BRDCM SUPP (PTSX = Port Side Exhaust)
a|
X190005R
a|
BES-53248, CLSW, 16Pt10/25GB, PSIN, BRDCM SUPP (PSIN = Port Side Intake)
a|
X-RAIL-4POST-190005
a|
Rack mount rail kit Ozeki 4 post 19"
a|
X-FAN-190005-R
a|
Fan, port side intake X190005
a|
X-FAN-190005-F
a|
Fan, port side exhaust X190005
a|
X-PSU-190005-R
a|
Power supply, port side intake X190005
Port-side intake airflow (reverse air): Cool air enters the chassis through the port end in the cold aisle and exhausts through the fan and power supply modules in the hot aisle.
a|
X-PSU-190005-F
a|
Power supply, port side exhaust X190005
Port-side exhaust airflow (standard air): Cool air enters the chassis through the fan and power supply modules in the cold aisle and exhausts through the port end of the chassis in the hot aisle. Blue coloring indicates port-side exhaust airflow. This is the most common option.
|===

See the https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch[NetApp KB article: How to add additional port licensing for the Broadcom-supported BES-53248 switch^] for details on adding additional port licenses.

For information on the relevant connectors and cable options to use along with their part numbers, see the https://hwu.netapp.com/Home/Index[NetApp Hardware Universe^].

For more information, see the _Cluster Network and Management Network Compatibility Matrix_ available from the BES-53248 switch download site https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab[Broadcom cluster switches^].

== Configuration requirements
To configure your cluster, you need the appropriate number and type of cables and cable connectors for your cluster switches. Depending on the type of cluster switch you are initially configuring, you need to connect to the switch console port with the included console cable and you need specific network information.

.Cluster switch port assignments
You can use the Broadcom-supported BES-53248 cluster switch port assignments table as a guide to configuring your cluster.

[options="header" cols="1,2"]
|===
| Switch ports| Ports usage
a|
01-16
a|
10/25GbE cluster port nodes, base configuration
a|
17-48
a|
10/25GbE cluster port nodes, with licenses
a|
49-54
a|
100GbE cluster port nodes, with licenses, added right to left
a|
55-56
a|
100GbE cluster Inter-Switch Link (ISL) ports, base configuration
|===

.Port group speed constraint
On BES-53248 cluster switches, the 48 10/25GbE (SFP28/SFP+) ports are combined into 12 x 4-port groups as follows:

* Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44, and 45-48.

The SFP28/SFP+ port speed must be the same (10GbE or 25GbE) across all ports in the 4-port group.

[.lead]
You need specific switch and controller documentation to set up your Cluster-Mode configuration.

== Required documentation
To set up the BES-53248 cluster switch, you need the following documents available from the Broadcom Support Site: https://www.broadcom.com/support/bes-switch[Broadcom Ethernet Switch Product Line^]

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_EFOS Administrator's Guide v3.4.3_
a|
Provides examples of how to use the BES-53248 switch in a typical network.
a|
_EFOS CLI Command Reference v3.4.3_
a|
Describes the command-line interface (CLI) commands you use to view and configure the BES-53248 software.
a|
_EFOS Getting Started Guide v3.4.3_
a|
Provides detailed information about for the BES-53248 switch.
a|
_EFOS SNMP Reference Guide v3.4.3_
a|
Provides examples of how to use the BES-53248 switch in a typical network.
a|
_EFOS Scaling Parameters and Values v3.4.3_
a|
Describes the default scaling parameters with which EFOS software is delivered and validated on the supported platforms.
a|
_EFOS Functional Specifications v3.4.3_
a|
Describes the specifications for the EFOS software on the supported platforms.
a|
_EFOS Release Notes v3.4.3_
a|
Provides release-specific information about BES-53248 software.
|===

=== Required documentation for supported ONTAP systems
To set up an ONTAP system, you need the following documents from the NetApp Support Site at http://mysupport.netapp.com/[mysupport.netapp.com^]

[options="header" cols="1,2"]
|===
| Name| Description
a|
https://hwu.netapp.com/Home/Index[NetApp Hardware Universe^]
a|
Describes the power and site requirements for all NetApp hardware, including system cabinets.
a|
Controller-specific _Installation and Setup Instructions_
a|
Describes how to install NetApp hardware.
a|
ONTAP 9
a|
Provides detailed information about all aspects of the ONTAP 9 release.
|===
