---
permalink: switch-bes-53248/migrate-to-2n-switched.html
sidebar: sidebar
keywords: two-node switchless clusters,migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches,migrating two-node switched clusters,2-node
summary: 'If you have a two-node switchless cluster, you can migrate, non-disruptively, to a two-node switched cluster that includes Broadcom-supported BES-53248 cluster switches. The documented process works for all cluster node ports using optical or Twinax ports but is not supported on this switch if nodes are using onboard 10GBASE-T RJ45 ports for the cluster network ports.'
---
= Migrate to a two-node switched cluster with Broadcom-supported BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
If you have a two-node switchless cluster, you can migrate, non-disruptively, to a two-node switched cluster that includes Broadcom-supported BES-53248 cluster switches. The documented process works for all cluster node ports using optical or Twinax ports but is not supported on this switch if nodes are using onboard 10GBASE-T RJ45 ports for the cluster network ports.

.About this task

Most systems require two dedicated cluster-network ports on each controller.

Ensure that the BES-53248 cluster switch is set up as described in link:replace-requirements.html[Broadcom-supported BES-53248 switches setup and configuration^] before starting this migration process.

NOTE: After your migration completes, you might need to install the required configuration file to support the Cluster Switch Health Monitor (CSHM) for BES-53248 cluster switches.

See link:configure-health-monitor.html[Install the Cluster Switch Health Monitor (CSHM) configuration file] and link:configure-log-collection.html[Configure the cluster switch log collection feature] for the steps required to enable cluster health switch log collection used for collecting switch-related log files.
