---
permalink: switch-bes-53248/migrate-to-2n-switched.html
sidebar: sidebar
keywords: two-node switchless clusters,migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches,migrating two-node switched clusters,2-node
summary: 'If you have a two-node switchless cluster, you can migrate, non-disruptively, to a two-node switched cluster that includes Broadcom-supported BES-53248 cluster switches. The documented process works for all cluster node ports using optical or Twinax ports but is not supported on this switch if nodes are using onboard 10GBASE-T RJ45 ports for the cluster network ports.'
---
= Migrate to a two-node switched cluster with Broadcom-supported BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
If you have a two-node switchless cluster, you can migrate, non-disruptively, to a two-node switched cluster that includes Broadcom-supported BES-53248 cluster switches. The documented process works for all cluster node ports using optical or Twinax ports but is not supported on this switch if nodes are using onboard 10GBASE-T RJ45 ports for the cluster network ports.

.About this task

Most systems require two dedicated cluster-network ports on each controller.

Ensure that the BES-53248 cluster switch is set up as described in the http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/home.html[Switch Setup and Configuration Guide for Broadcom-supported BES-53248 switches] guide before starting this migration process.

NOTE: After your migration completes, you might need to install the required configuration file to support the Cluster Switch Health Monitor (CSHM) for BES-53248 cluster switches.

See http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/GUID-211616A4-C962-464A-A70E-5E057D7B13E1.html[Installing the Cluster Switch Health Monitor (CSHM) configuration file] in the _Switch Setup and Configuration Guide for Broadcom-supported BES-53248 switches_ guide.

Also, see _Configuring the cluster switch log collection feature_ in the http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/home.html[Switch Setup and Configuration Guide for Broadcom-supported BES-53248 switches] for the steps required to enable cluster health switch log collection used for collecting switch-related log files.
