---
permalink: switch-bes-53248/replace-requirements.html
sidebar: sidebar
keywords: requirements, bes-53428 switches
summary: To configure your cluster, you need the appropriate number and type of cables and cable connectors for your cluster switches. Depending on the type of cluster switch you are initially configuring, you need to connect to the switch console port with the included console cable and you need specific network information.
---
= BES-53248 cluster switch configuration requirements
:icons: font
:imagesdir: ../media/

[.lead]
To configure your cluster, you need the appropriate number and type of cables and cable connectors for your cluster switches. Depending on the type of cluster switch you are initially configuring, you need to connect to the switch console port with the included console cable and you need specific network information.

== BES-53248 cluster switch port assignments
You can use the Broadcom-supported BES-53248 cluster switch port assignments table as a guide to configuring your cluster.

[options="header" cols="1,2"]
|===
| Switch ports| Ports usage
a|
01-16
a|
10/25GbE cluster port nodes, base configuration
a|
17-48
a|
10/25GbE cluster port nodes, with licenses
a|
49-54
a|
100GbE cluster port nodes, with licenses, added right to left
a|
55-56
a|
100GbE cluster Inter-Switch Link (ISL) ports, base configuration
|===

.Port group speed constraint

On BES-53248 cluster switches, the 48 10/25GbE (SFP28/SFP+) ports are combined into 12 x 4-port groups as follows:

* Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44, and 45-48.

The SFP28/SFP+ port speed must be the same (10GbE or 25GbE) across all ports in the 4-port group.
