---
permalink: switch-bes-53248/replace-upgrade.html
sidebar: sidebar
keywords: BES-53248 switches,upgrading,BES-53248 switches
summary: 'Upgrading BES-53248 cluster switches starts with preparing the controller for upgrade, installing the EFOS software, licenses, and reference configuration file \(RCF\). After the installation, you can restore the controller configuration in a nondisruptive upgrade \(NDU\) and nondisruptive operation \(NDO\) environment.'
---
= Upgrade a BES-53248 cluster switch in an NDO/NDU environment
:icons: font
:imagesdir: ../media/

[.lead]
Upgrading BES-53248 cluster switches starts with preparing the controller for upgrade, installing the EFOS software, licenses, and reference configuration file (RCF). After the installation, you can restore the controller configuration in a nondisruptive upgrade (NDU) and nondisruptive operation (NDO) environment.

.What you'll need

The following conditions must exist before you install the EFOS software, licenses, and the RCF file on an existing NetApp BES-53248 cluster switch:

* The cluster must be a fully functioning cluster (no error log messages or other issues).
* The cluster must not contain any defective cluster network interface cards (NICs).
* All connected ports on both cluster switches must be functional.
* All cluster ports must be up.
* All cluster LIFs must be administratively and operationally up and on their home ports.
* The ONTAP `cluster ping-cluster -node node1` advanced privilege command must indicate that `larger than PMTU communication` is successful on all paths.
* There might be command dependencies between command syntax in the RCF and EFOS versions.

.About this task

You must consult the switch compatibility table on the NetApp BES-53248 switches page for the supported EFOS, RCF, and ONTAP versions at: http://mysupport.netapp.com/site[NetApp BES-53248 switches].

This procedure applies to a functioning cluster and allows for NDU and NDO. The examples in this procedure use the following switch and node nomenclature:

* The NetApp switch names are `cs1` and `cs2`.
* The example used in this procedure starts the upgrade on the second switch, _cs2._
* The cluster LIF names are `node1_clus1` and `node1_clus2` for node1, and `node2_clus1` and `node2_clus2` for node2 .
* The IPspace name is Cluster.
* The `cluster1::>` prompt indicates the name of the cluster.
* The cluster ports on each node are named `e0a` and `e0b`.
+
See the __Hardware Universe__for the actual cluster ports supported on your platform.
+
https://hwu.netapp.com/Home/Index[NetApp Hardware Universe]

* The Inter-Switch Links (ISLs) supported for the NetApp cluster switches are ports 0/55 and 0/56.
* The node connections supported for the NetApp cluster switches are ports 0/1 through 0/16 with default licensing.
* The examples in this procedure use two nodes, but you can have up to 24 nodes in a cluster.
* Repeat all procedures in this section to upgrade the EFOS software and RCF file on the other switch, *cs1*.
