---
permalink: switch-bes-53248/replace-verify.html
sidebar: sidebar
keywords: command, verify, operational, bes, cluster, switch, upgrade, verify the configuration after a cluster switch upgrade - bes-53428 switches
summary: You can use the commands provided here to verify that all is operational after a BES-53248 cluster switch upgrade.
---
= Verify the ONTAP cluster network after an EFOS software or RCF upgrade BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
You can use the following commands to verify the health of the ONTAP cluster network after an upgrade of the EFOS software or RCF for BES-53248 cluster switches.

.Steps

. Display information about the network ports on the cluster using the command:
+
[source,cli]
----
network port show -ipspace Cluster
----
+
`Link` must have the value `up` and `Health Status` must be `healthy`.
+
.Show example
[%collapsible]
====

The following example shows the output from the command:

[subs=+quotes]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====

. For each LIF, verify that `Is Home` is `true` and `Status Admin/Oper` is `up` on both nodes, using the command:
+
[source,cli]
----
network interface show -vserver Cluster
----
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.217.125/16 node1         e0a     true
            node1_clus2  up/up    169.254.205.88/16  node1         e0b     true
            node2_clus1  up/up    169.254.252.125/16 node2         e0a     true
            node2_clus2  up/up    169.254.110.131/16 node2         e0b     true
----
====

. Verify that the `Health Status` of each node is `true` using the command: 
+
`cluster show`
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
cluster1::> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====

// Updates for for GH issues #72, 109, 12, AFFFASDOC-212, 2024-MAY-02