---
permalink: switch-bes-53248/replace-install-rcf.html
sidebar: sidebar
keywords: rcf,install rcf,bes-53248 switch
summary: 'You can install the RCF after setting up the BES-53248 cluster switch for the first time and after the new license or licenses have been applied. If you are upgrading an RCF from an older version, the files are effectively merged together and you complete the steps as detailed here.'
---
= Install the Reference Configuration File (RCF)
:icons: font
:imagesdir: ../media/

[.lead]
You can install the RCF after setting up the BES-53248 cluster switch for the first time and after the new license or licenses have been applied. If you are upgrading an RCF from an older version, the files are effectively merged together and you complete the steps as detailed here.

.Steps
. Connect the cluster switch to the management network.
. Use the ping command to verify connectivity to the server hosting EFOS, licenses, and the RCF.
+
If connectivity is an issue, use a nonrouted network and configure the service port using IP address 192.168.x or 172.19.x. You can reconfigure the service port to the production management IP address later.
+
This example verifies that the switch is connected to the server at IP address 172.19.2.1:
+
----
(cs2) # **ping 172.19.2.1**
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----

. Install the RCF on the BES-53248 cluster switch using the copy command.
+
----
(cs2) # **copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr**

Remote Password ********

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) **y
**
File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+
NOTE: Depending on your environment, you might need to use a double slash in the copy command, for example: `+copy http://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr+`.
+
NOTE: The `.scr` extension must be set as part of the file name before invoking the script. This extension is the extension for the EFOS operating system. The switch validates the script automatically when it is downloaded to the switch, and the output goes to the console. Also, you can change the name of the `.scr` to fit your console screen for easier readability, for example: `+copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script RCF_v1.6-Cluster-HA.scr+`.

. Verify that the script was downloaded and saved to the file name you gave it:
+
`script list`
+
----
(cs2) # **script list**

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----

. Apply the script to the switch.
+
`script apply`
+
----
(cs2) # **script apply BES-53248_RCF_v1.6-Cluster-HA.scr**

Are you sure you want to apply the configuration script? (y/n) **y**

The system has unsaved changes.
Would you like to save them now? (y/n) **y**
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----

. Verify the ports for an additional license after the RCF is applied:
+
`show port all | exclude Detach`
+
----
(cs2) # **show port all \| exclude Detach**

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----

. Verify on the switch that your changes have been made:
+
`show running-config`
+
----
(cs2) # **show running-config**
----

. Save the running configuration so that it becomes the startup configuration when you reboot the switch:
+
`write memory`
+
----
(cs2) # **write memory**
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) **y**

Config file 'startup-config' created successfully.

Configuration Saved!
----

. Reboot the switch and verify that the running configuration is correct:
+
`reload`
+
----
(cs2) # **reload**

Are you sure you would like to reset the system? (y/n)**y**

System will now restart!
----
