---
permalink: switch-bes-53248/replace-restrictions.html
sidebar: sidebar
keywords: problem, install, license, debug, command, restriction, limitation, switch, restrictions and limitations - bes-53428 switches
summary: Where problems arise when installing a license, the following debug commands should be run before running the copy command again to install the license.
---
= Restrictions and limitations - BES-53248 switches
:icons: font
:imagesdir: ../media/

[.lead]
Where problems arise when installing a license, the following debug commands should be run before running the `copy` command again to install the license.

Debug commands to use:

`debug transferdebug license`

----
(cs2) # debug transfer
Debug transfer output is enabled.
(cs2) # debug license
Enabled capability licensing debugging.
----

When you run the `copy` command with the `debug transfer` and `debug license` options enabled, the following log output is returned:

----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----

Check for the following in the debug output:

* Check that the Serial number matches: `Serial number QTFCU38290012 matched.`
* Check that the switch Model matches: `Model BES-53248 matched.`
* Check that the specified license index was not used previously. Where a license index is already used, the following error is returned: `License file /mnt/download//license.dat.1 already exists.`
* A port license is not a feature license. Therefore, the following statement is expected: `Feature not found in license file with index = 1.`

Use the `copy` command to backup port licenses to the server:

----
(cs2) # copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat
----

See link:configure-licenses.html[Installing licenses for BES-53248 cluster switches] for details of the firmware versions supported for available licenses.

WARNING: If you need to downgrade the switch software from version 3.4.4.6, the licenses are removed. This is expected behavior.

You must install an appropriate older license before reverting to an older version of the software.
