---
permalink: switch-bes-53248/replace-upgrade.html
sidebar: sidebar
keywords: BES-53248 switches,upgrading,BES-53248 switches
summary: 'Upgrading BES-53248 cluster switches starts with preparing the controller for upgrade, installing the EFOS software, licenses, and reference configuration file \(RCF\). After the installation, you can restore the controller configuration in a nondisruptive upgrade \(NDU\) and nondisruptive operation \(NDO\) environment.'
---
= Prepare the BES-53248 cluster switch for upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Follow these steps to upgrade the BES-53248 cluster switch.

This procedure applies to a functioning cluster and allows for a nondisruptive upgrade (NDU) and nondisruptive operation (NDO) environment.

== Requirements for upgrade

The following conditions must exist before you install the EFOS software, licenses, and the RCF file on an existing NetApp BES-53248 cluster switch:

* The cluster must be a fully functioning cluster (no error log messages or other issues).
* The cluster must not contain any defective cluster network interface cards (NICs).
* All connected ports on both cluster switches must be functional.
* All cluster ports must be up.
* All cluster LIFs must be administratively and operationally up and on their home ports.
* The ONTAP `cluster ping-cluster -node node1` advanced privilege command must indicate that `larger than PMTU communication` is successful on all paths.
* There might be command dependencies between command syntax in the RCF and EFOS versions.

NOTE: For switch compatibility, consult the compatibility table on the http://mysupport.netapp.com/site[NetApp BES-53248 switches^] page for the supported EFOS, RCF, and ONTAP versions.

== Prepare the controller

Follow this procedure to prepare the controller for a BES-53248 cluster switch upgrade.

.Steps

. Connect the cluster switch to the management network.
. Use the ping command to verify connectivity to the server hosting EFOS, licenses, and the RCF.
+
If this is an issue, use a nonrouted network and configure the service port using IP address 192.168.x or 172.19.x. You can reconfigure the service port to the production management IP address later.
+
.Example of ping command
[%collapsible]
====
This example verifies that the switch is connected to the server at IP address 172.19.2.1:

[subs=+quotes]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====

. Verify that the cluster ports are healthy and have a link using the command:
+
`network port show -ipspace Cluster`
+
.Example of network port show -ipspace Cluster command
[%collapsible]
====
The following example shows the type of output with all ports having a `Link` value of up and a `Health Status` of healthy:

[subs=+quotes]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====

. Verify that the cluster LIFs are administratively and operationally up and reside on their home ports, using the command:
+
`network interface show -vserver Cluster`
+
.Example of network interface show -vserver Cluster command
[%collapsible]
====
In this example, the `-vserver` parameter displays information about the LIFs that are associated with cluster ports. `Status Admin/Oper` must be up and `Is Home` must be true:

[subs=+quotes]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----
====

.What's next?

link:configure-efos-software.html[Install the EFOS software].