---
permalink: switch-bes-53248/replace-install-rcf.html
sidebar: sidebar
keywords: rcf,install rcf,bes-53248 switch
summary: 'You can install the RCF after setting up the BES-53248 cluster switch for the first time and after the new license or licenses have been applied. If you are upgrading an RCF from an older version, the files are effectively merged together and you complete the steps as detailed here.'
---
= Install the Reference Configuration File (RCF)
:icons: font
:imagesdir: ../media/

[.lead]
You can install the RCF after setting up the BES-53248 cluster switch for the first time and after the new license or licenses have been applied. If you are upgrading an RCF from an older version, you must reset the Broadcom switch settings and perform basic configuration to re-apply the RCF. You must perform this operation every time you want to upgrade or change an RCF. See the following https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/Error!_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF[KB article^] for details.

== Reset the Broadcom IP switch to factory defaults

Before installing a new switch software version and RCFs, you must erase the Broadcom switch settings and perform basic configuration.

.About this task

* You must repeat these steps on each of the cluster switches.
* You must be connected to the switch using the serial console.
* This task resets the configuration of the management network.

.Steps


. Change to the elevated command prompt (`#`): `enable`
+
----
(cs2)> enable
(cs2) #
----

. Erase the startup configuration and remove the banner
.. Erase the startup configuration:
+

*`erase startup-config`*
+
-----
(cs2) #erase startup-config
Are you sure you want to clear the configuration? (y/n) y
(cs2) #
-----
+

This command does not erase the banner.
+
..	Remove the banner:
+

*`no set clibanner`*
+
-----
(cs2) #configure
(cs2)(Config) # no set clibanner
(cs2)(Config) #
-----

. Reboot the switch:
*`(cs2) #reload*`
+
----
Are you sure you would like to reset the system? (y/n) y
----
+
NOTE: If the system asks whether to save the unsaved or changed configuration before reloading the switch, select *No*.

. Wait for the switch to reload, and then log in to the switch.
+
The default user is "`admin`", and no password is set. A prompt similar to the following is displayed:
+
----
(Routing)>
----

. Change to the elevated command prompt:
+
`enable`
+
----
Routing)> enable
(Routing) #
----

. Set the service port protocol to `none`:
+
`serviceport protocol none`
+
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----

. Assign the IP address to the service port:
+
`serviceport ip _ip-address_ _netmask_ _gateway_`
+
The following example shows a service port assigned IP address "10.10.10.10" with subnet "255.255.255.0" and gateway "10.10.10.1":
+
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----

. Verify that the service port is correctly configured:
+
`show serviceport`
+
The following example shows that the port is up and the correct addresses have been assigned:
+
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----

. If desired, configure the SSH server.
+
NOTE: The RCF file disables the Telnet protocol. If you do not configure the SSH server, you can only access the bridge using the serial port connection.

 .. Generate RSA keys.
+
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----

 .. Generate DSA keys (optional)
+
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----

.. If you are using the FIPS compliant version of EFOS, generate the ECDSA keys. The following example creates the keys with a length of 256. Valid values are 256, 384 or 521.
+
-----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256
-----
+

 .. Enable the SSH server.
+
If necessary, exit the configuration context.
+
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+
NOTE: If keys already exist, then you might be asked to overwrite them.

. If desired, configure the domain and name server:
+
`configure`
+
The following example shows the `ip domain` and `ip name server` commands:
+
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----

. If desired, configure the time zone and time synchronization (SNTP).
+
The following example shows the `sntp` commands, specifying the IP address of the SNTP server and the relative time zone.
+
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----

. Configure the switch name:
+
`hostname cs2`
+
The switch prompt will display the new name:
+
----
(Routing) # hostname cs2

(cs2) #
----

. Save the configuration:
+
`write memory`
+
You receive prompts and output similar to the following example:
+
----
(cs2) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(cs2) #
----

. Repeat the previous steps on the other cluster switch.

== Install the Reference Configuration File (RCF)

.Steps
. Connect the cluster switch to the management network.
. Use the ping command to verify connectivity to the server hosting EFOS, licenses, and the RCF.
+
If connectivity is an issue, use a nonrouted network and configure the service port using IP address 192.168.x or 172.19.x. You can reconfigure the service port to the production management IP address later.
+
This example verifies that the switch is connected to the server at IP address 172.19.2.1:
+
----
(cs2) # ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----

. Install the RCF on the BES-53248 cluster switch using the copy command.
+
----
(cs2) # copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr

Remote Password ********

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+
NOTE: Depending on your environment, you might need to use a double slash in the copy command, for example: `+copy http://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr+`.
+
NOTE: The `.scr` extension must be set as part of the file name before invoking the script. This extension is the extension for the EFOS operating system. The switch validates the script automatically when it is downloaded to the switch, and the output goes to the console. Also, you can change the name of the `.scr` to fit your console screen for easier readability, for example: `+copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script RCF_v1.6-Cluster-HA.scr+`.

. Verify that the script was downloaded and saved to the file name you gave it:
+
`script list`
+
----
(cs2) # script list

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----

. Apply the script to the switch.
+
`script apply`
+
----
(cs2) # script apply BES-53248_RCF_v1.6-Cluster-HA.scr

Are you sure you want to apply the configuration script? (y/n) y

The system has unsaved changes.
Would you like to save them now? (y/n) y
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----

. Verify the ports for an additional license after the RCF is applied:
+
`show port all | exclude Detach`
+
----
(cs2) # show port all \| exclude Detach

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----

. Verify on the switch that your changes have been made:
+
`show running-config`
+
----
(cs2) # show running-config
----

. Save the running configuration so that it becomes the startup configuration when you reboot the switch:
+
`write memory`
+
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----

. Reboot the switch and verify that the running configuration is correct:
+
`reload`
+
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n) y

System will now restart!
----

// 2022-01-10, BURT 1445096
// 2022-01-20, BURT 1445096
