---
permalink: switch-bes-53248/required-documentation-bes53248.html
sidebar: sidebar
keywords: documentation requirements, BES-53248 switches,cluster switches
summary: 'You need specific switch and controller documentation to set up your Cluster-Mode configuration.'
---
= Documentation requirements for BES-53248 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
For BES-53248 switch installation and maintenance, be sure to review the specific switch and controller documentation.

== Broadcom documentation
To set up the BES-53248 cluster switch, you need the following documents available from the Broadcom Support Site: https://www.broadcom.com/support/bes-switch[Broadcom Ethernet Switch Product Line^]

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_EFOS Administrator's Guide v3.4.3_
a|
Provides examples of how to use the BES-53248 switch in a typical network.
a|
_EFOS CLI Command Reference v3.4.3_
a|
Describes the command-line interface (CLI) commands you use to view and configure the BES-53248 software.
a|
_EFOS Getting Started Guide v3.4.3_
a|
Provides detailed information about for the BES-53248 switch.
a|
_EFOS SNMP Reference Guide v3.4.3_
a|
Provides examples of how to use the BES-53248 switch in a typical network.
a|
_EFOS Scaling Parameters and Values v3.4.3_
a|
Describes the default scaling parameters with which EFOS software is delivered and validated on the supported platforms.
a|
_EFOS Functional Specifications v3.4.3_
a|
Describes the specifications for the EFOS software on the supported platforms.
a|
_EFOS Release Notes v3.4.3_
a|
Provides release-specific information about BES-53248 software.
a|
_Cluster Network and Management Network Compatibility Matrix_
a|
Provides information on network compatibility. The matrix is available from the BES-53248 switch download site at https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab[Broadcom cluster switches^].
|===

== ONTAP systems documentation and KB articles
To set up an ONTAP system, you need the following documents from the NetApp Support Site at http://mysupport.netapp.com/[mysupport.netapp.com^] or the Knowledgebase (KB) site at https://kb.netapp.com/[kb.netapp.com^].

[options="header" cols="1,2"]
|===
| Name| Description
a|
https://hwu.netapp.com/Home/Index[NetApp Hardware Universe^]
a|
Describes the power and site requirements for all NetApp hardware, including system cabinets, and provides information on the relevant connectors and cable options to use along with their part numbers.
a|
Controller-specific _Installation and Setup Instructions_
a|
Describes how to install NetApp hardware.
a|
ONTAP 9
a|
Provides detailed information about all aspects of the ONTAP 9 release.
a|
_How to add additional port licensing for the Broadcom-supported BES-53248 switch_
a|
Provides detailed information on adding port licenses. Go to the https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch[KB article^].
|===
