---
permalink: switch-bes-53248/upgrade-efos-software.html
sidebar: sidebar
keywords: BES-53248 cluster switches,upgrading EFOS software
summary: 'Follow these steps to upgrade the Ethernet Fabric OS (EFOS) software on the BES-53248 cluster switch.'
---
= Upgrade the EFOS software
:icons: font
:imagesdir: ../media/

[.lead]
Follow these steps to upgrade the EFOS software on the BES-53248 cluster switch.

EFOS software includes a set of advanced networking features and protocols for developing Ethernet and IP infrastructure systems. This software architecture is suitable for any network organizational device using applications that require thorough packet inspection or separation. 

== Prepare for upgrade

.Before you begin
* Download the applicable Broadcom EFOS software for your cluster switches from the https://www.broadcom.com/support/bes-switch[Broadcom Ethernet Switch Support^] site.
* Review the following notes regarding EFOS versions.

====
*Note the following:*

* When upgrading from EFOS 3.4.x.x to EFOS 3.7.x.x or later, the switch must be running EFOS 3.4.4.6 (or later 3.4.x.x release). If you are running a release prior to that, then upgrade the switch to EFOS 3.4.4.6 (or later 3.4.x.x release) first, then upgrade the switch to EFOS 3.7.x.x or later.

* The configuration for EFOS 3.4.x.x and 3.7.x.x or later are different. Changing the EFOS version from 3.4.x.x to 3.7.x.x or later, or vice versa, requires the switch to be reset to factory defaults and the RCF files for the corresponding EFOS version to be (re)applied. This procedure requires access through the serial console port.

* Beginning with EFOS version 3.7.x.x or later, a non-FIPS compliant and a FIPS compliant version is available. Different steps apply when moving from a non-FIPS compliant to a FIPS compliant version or vice versa. Changing EFOS from a non-FIPS compliant to a FIPS compliant version or vice versa will reset the switch to factory defaults. This procedure requires access through the serial console port.
====
// BURT-1392530

|===

h| *Procedure* h| *Current EFOS version* h| *New EFOS version* h| *High level steps*

.5+a|Steps to upgrade EFOS between two (non) FIPS compliant versions
a| 3.4.x.x
a| 3.4.x.x
a| Upgrade the new EFOS image using <<Method 1: Upgrade EFOS>>.
The configuration and license information is retained.
a| 3.4.4.6 (or later 3.4.x.x)
a| 3.7.x.x or later non-FIPS compliant
a|Upgrade EFOS using <<Method 1: Upgrade EFOS>>.
Reset the switch to factory defaults and apply the RCF file for EFOS 3.7.x.x or later.
.2+|3.7.x.x or later non-FIPS compliant
a|3.4.4.6 (or later 3.4.x.x)
a|Downgrade EFOS using <<Method 1: Upgrade EFOS>>.
Reset the switch to factory defaults and apply the RCF file for EFOS 3.4.x.x
a|3.7.x.x or later non-FIPS compliant
a|Upgrade the new EFOS image using <<Method 1: Upgrade EFOS>>. The configuration and license information is retained.
a|3.7.x.x or later FIPS compliant
a|3.7.x.x or later FIPS compliant
a|Upgrade the new EFOS image using <<Method 1: Upgrade EFOS>>.
The configuration and license information is retained.
.2+a|Steps to upgrade to/from a FIPS compliant EFOS version
a|Non-FIPS compliant
a|FIPS compliant
.2+a|Upgrade of the EFOS image using <<Method 2: Upgrade EFOS using the ONIE OS installation>>. The switch configuration and license information will be lost.
a|FIPS compliant
a|Non-FIPS compliant
|===

[IMPORTANT]
====
To check if your version of EFOS is FIPS compliant or non-FIPS compliant, use the `show fips status` command. In the following examples, *IP_switch_a1* is using FIPS compliant EFOS and *IP_switch_a2* is using non-FIPS compliant EFOS. 

* On switch IP_switch_a1 (FIPS compliant EFOS):
+
[subs=+quotes]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----

* On switch IP_switch_a2 (non-FIPS compliant EFOS):
+
[subs=+quotes]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----
====

== Upgrade the software
Use one of the following methods:

* <<Method 1: Upgrade EFOS>>. Use for most cases (see the table above).
* <<Method 2: Upgrade EFOS using the ONIE OS installation>>. Use if one EFOS version is FIPS compliant and the other EFOS version is non-FIPS compliant.

NOTE: Upgrade EFOS on one switch at a time to ensure continued cluster network operation.

=== Method 1: Upgrade EFOS
Perform the following steps to upgrade the EFOS software.

IMPORTANT: Note that after upgrading BES-53248 cluster switches from EFOS 3.3.x.x or 3.4.x.x to EFOS 3.7.0.4 or 3.8.0.2, Inter-Switch Links (ISLs) and port channel are marked in the *Down* state. See this KB article: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later[BES-53248 Cluster Switch NDU failed upgrade to EFOS 3.7.0.4 and later^] for further details.

.Steps

. Connect the BES-53248 cluster switch to the management network.
. Use the `ping` command to verify connectivity to the server hosting EFOS, licenses, and the RCF file.
+
This example verifies that the switch is connected to the server at IP address 172.19.2.1:
+
[subs=+quotes]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----

. Disable auto-revert on the cluster LIFs.
+
[source,cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----

. Display the boot images for the active and backup configuration:
+
[source,cli]
----
show bootvar
----
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6       3.7.0.4           3.7.0.4

----
====

. Back up the current active image on cs2:
+
[source,cli]
----
copy active backup
----
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
(cs2)# *copy active backup*
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :
 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------   
    1      3.7.0.4     3.4.4.6       3.7.0.4           3.7.0.4
(cs2)#
----
====

. Verify the running version of the EFOS software:
+
[source,cli]
----
show version
----
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.7.0.4, Linux 4.4.117-ceeeb99d, 2016.05.00.05
Machine Type................................... BES-53248A1
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.7.0.4
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
+
NOTE: If you installed any licences, please review their status.

. Download the image file to the switch.
+
Copying the image file to the active image means that when you reboot, that image establishes the running EFOS version. The previous image remains available as a backup.
+
[subs=+quotes]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----

. Display the boot images for the active and backup configuration:
+
[source,cli]
----
show bootvar
----
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====

. Reboot the switch:
+
[source,cli]
----
reload
----
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====

. Log in again and verify the new version of the EFOS software:
+
[source,cli]
----
show version
----
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====

. Repeat steps 5 through to 10 on the switch cs1.

. Enable auto-revert on the cluster LIFs.
+
[source,cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----

. Verify that the cluster LIFs have reverted to their home port:
+
[source,cli]
----
network interface show -role Cluster
----
+
For further details, see link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html[Revert a LIF to its home port].

//.What's next?

//link:configure-licenses.html[Install licenses for BES-53248 cluster switches]. 

=== Method 2: Upgrade EFOS using the ONIE OS installation
You can perform the following steps if one EFOS version is FIPS compliant and the other EFOS version is non-FIPS compliant. These steps can be used to upgrade the non-FIPS or FIPS compliant EFOS 3.7.x.x image from ONIE if the switch fails to boot.

NOTE: This functionality is only available for EFOS 3.7.x.x or later non-FIPS compliant.

CAUTION: If you upgrade EFOS using the ONIE OS installation, the configuration is reset to factory defaults and licenses are deleted. You must set up the switch and install licenses and a supported RCF to return the switch to normal operation.

.Steps
. Disable auto-revert on the cluster LIFs.
+
[source,cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----

. Boot the switch into ONIE installation mode.
+
During boot, select ONIE when you see the prompt:
+
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----

+
After you select *ONIE*, the switch loads and presents you with several choices. Select *Install OS*.
+
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
The switch boots into ONIE installation mode.

. Stop the ONIE discovery and configure the Ethernet interface.
+
When the following message appears, press *Enter* to invoke the ONIE console:
+
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
NOTE: The ONIE discovery continues and messages are printed to the console.
+
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----

. Configure the Ethernet interface and add the route using `ifconfig eth0 <ipAddress> netmask <netmask> up` and `route add default gw <gatewayAddress>`
+
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----

. Verify that the server hosting the ONIE installation file is reachable:
+
[source,cli]
----
ping
----
+
.Show example
[%collapsible]
====
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
+
. Install the new switch software:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`
+
.Show example
[%collapsible]
====
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
The software installs and then reboots the switch. Let the switch reboot normally into the new EFOS version.
+
. Verify that the new switch software is installed: 
+
[source,cli]
----
show bootvar
----
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====

. Complete the installation. The switch reboots with no configuration applied and resets to factory defaults. Complete the following steps to reconfigure the switch:
.. link:configure-licenses.html[Install licenses] 
.. link:configure-install-rcf.html[Install the RCF]
.. link:configure-ssh.html[Enable SSH]
.. link:CSHM_log_collection.html[Enable log collection]
.. link:CSHM_snmpv3.html[Configure SNMPv3 for monitoring]

. Repeat steps 2 through to 8 on the switch cs1.
. Enable auto-revert on the cluster LIFs.
+
[source,cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----

. Verify that the cluster LIFs have reverted to their home port:
+
[source,cli]
----
network interface show -role Cluster
----
+
For further details, see link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html[Revert a LIF to its home port].

//.What's next?

//link:configure-licenses.html[Install licenses for BES-53248 cluster switches.]. 

// New content for GH issues #72, 109, 12, AFFFASDOC-212, 2024-APR-02