---
permalink: switch-cisco-3132q-v/cn1610-migrate-requirements.html
sidebar: sidebar
keywords: install, cisco nexus 3132q-v switch,
summary: 'Before configuring Cisco Nexus 3132q-v switches, review an overview of the process and the nomenclature.'
---
= Migration requirements
:imagesdir: ../media/

[.lead]
Cisco Nexus 3132Q-V switches can be used as cluster switches in your AFF or FAS cluster. Cluster switches allow you to build ONTAP clusters with more than two nodes. 

[NOTE]
====
The procedure requires the use of both ONTAP commands and Cisco Nexus 3000 Series Switches commands; ONTAP commands are used unless otherwise indicated.
====

For more information, see:

* http://support.netapp.com/NOW/download/software/cm_switches_ntap/[NetApp CN1601 and CN1610 description page^]

* http://support.netapp.com/NOW/download/software/cm_switches/[Cisco Ethernet Switch description page^]

* http://hwu.netapp.com[Hardware Universe^]

== CN1610 requirements

The following cluster switches are supported:

* NetApp CN1610
* Cisco Nexus 3132Q-V

The cluster switches support the following node connections:

* NetApp CN1610: ports 0/1 through 0/12 (10 GbE)
* Cisco Nexus 3132Q-V: ports e1/1-30 (40/100 GbE)

The cluster switches use the following inter-switch link (ISL) ports:

* NetApp CN1610: ports 0/13 through 0/16 (10 GbE)
* Cisco Nexus 3132Q-V: ports e1/31-32 (40/100 GbE)
+
The link:https://hwu.netapp.com/[Hardware Universe^] contains information about supported cabling to Nexus 3132Q-V switches:
* Nodes with 10 GbE cluster connections require QSFP to SFP+ optical fiber breakout cables or QSFP to SFP+ copper breakout cables
* Nodes with 40/100 GbE cluster connections require supported QSFP/QSFP28 optical modules with optical fiber cables or QSFP/QSFP28 copper direct-attach cables

The appropriate ISL cabling is as follows:

* Beginning: For CN1610 to CN1610 (SFP+ to SFP+), four SFP+ optical fiber or copper direct-attach cables
* Interim: For CN1610 to Nexus 3132Q-V (QSFP to four SFP+ breakout), one QSFP to SFP+ optical fiber or copper breakout cable
* Final: For Nexus 3132Q-V to Nexus 3132Q-V (QSFP28 to QSFP28), two QSFP28 optical fiber or copper direct-attach cables

NetApp twinax cables are not compatible with Cisco Nexus 3132Q-V switches.

If your current CN1610 configuration uses NetApp twinax cables for cluster-node-to-switch connections or ISL connections and you want to continue using twinax in your environment, you need to procure Cisco twinax cables. Alternatively, you can use optical fiber cables for both the ISL connections and the cluster-node-to-switch connections.


.About the examples used

The examples in this procedure describe replacing CN1610 switches with Cisco Nexus 3132Q-V switches. You can use these steps (with modifications) for other older Cisco switches.

The procedure also uses the following switch and node nomenclature:

* The command outputs might vary depending on different releases of ONTAP.
* The CN1610 switches to be replaced are *CL1* and *CL2*.
* The Nexus 3132Q-V switches to replace the CN1610 switches are *C1* and *C2*.
* *n1_clus1* is the first cluster logical interface (LIF) connected to cluster switch 1 (CL1 or C1) for node *n1*.
* *n1_clus2* is the first cluster LIF connected to cluster switch 2 (CL2 or C2) for node *n1*.
* *n1_clus3* is the second LIF connected to cluster switch 2 (CL2 or C2) for node *n1*.
* *n1_clus4* is the second LIF connected to cluster switch 1 (CL1 or C1) for node *n1*.
* The number of 10 GbE and 40/100 GbE ports are defined in the reference configuration files (RCFs) available on the https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml[Cisco® Cluster Network Switch Reference Configuration File Download^] page.
* The nodes are *n1*, *n2*, *n3*, and *n4*.

The examples in this procedure use four nodes:

* Two nodes use four 10 GbE cluster interconnect ports: *e0a*, *e0b*, *e0c*, and *e0d*.
* The other two nodes use two 40 GbE cluster interconnect ports: *e4a* and *e4e*.
+
The link:https://hwu.netapp.com/[Hardware Universe^] lists the actual cluster ports on your platforms.


.What's next?
link:cn5596-prepare-to-migrate.html[Prepare for migration].

//Updates for internal GH issue #262, 2024-11-19