---
permalink: switch-cisco-3132q-v/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html
sidebar: sidebar
keywords: replace, cn1610 cluster switches, cisco nexus 3132q-v
summary: "You must be aware of certain configuration information, port connections, and cabling requirements when you replace CN1610 cluster switches with Cisco Nexus 3132Q-V cluster switches."
---
= Replace CN1610 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
Make sure you understand the configuration requirements, port connections, and cabling requirements when you replace CN1610 cluster switches with Cisco Nexus 3132Q-V cluster switches.

* The following cluster switches are supported:
 ** NetApp CN1610
 ** Cisco Nexus 3132Q-V
* The cluster switches support the following node connections:
 ** NetApp CN1610: ports 0/1 through 0/12 (10 GbE)
 ** Cisco Nexus 3132Q-V: ports e1/1-30 (40/100 GbE)
* The cluster switches use the following inter-switch link (ISL) ports:
 ** NetApp CN1610: ports 0/13 through 0/16 (10 GbE)
 ** Cisco Nexus 3132Q-V: ports e1/31-32 (40/100 GbE)
* The link:https://hwu.netapp.com/[Hardware Universe^] contains information about supported cabling to Nexus 3132Q-V switches:
 ** Nodes with 10 GbE cluster connections require QSFP to SFP+ optical fiber breakout cables or QSFP to SFP+ copper breakout cables
 ** Nodes with 40/100 GbE cluster connections require supported QSFP/QSFP28 optical modules with optical fiber cables or QSFP/QSFP28 copper direct-attach cables
* The appropriate ISL cabling is as follows:
 ** Beginning: For CN1610 to CN1610 (SFP+ to SFP+), four SFP+ optical fiber or copper direct-attach cables
 ** Interim: For CN1610 to Nexus 3132Q-V (QSFP to four SFP+ breakout), one QSFP to SFP+ optical fiber or copper breakout cable
 ** Final: For Nexus 3132Q-V to Nexus 3132Q-V (QSFP28 to QSFP28), two QSFP28 optical fiber or copper direct-attach cables
* NetApp twinax cables are not compatible with Cisco Nexus 3132Q-V switches.
+
If your current CN1610 configuration uses NetApp twinax cables for cluster-node-to-switch connections or ISL connections and you want to continue using twinax in your environment, you need to procure Cisco twinax cables. Alternatively, you can use optical fiber cables for both the ISL connections and the cluster-node-to-switch connections.

* On Nexus 3132Q-V switches, you can operate QSFP/QSFP28 ports as either 40/100 Gb Ethernet or 4x 10 Gb Ethernet modes.
+
By default, there are 32 ports in the 40/100 Gb Ethernet mode. These 40 Gb Ethernet ports are numbered in a 2-tuple naming convention. For example, the second 40 Gb Ethernet port is numbered as 1/2. The process of changing the configuration from 40 Gb Ethernet to 10 Gb Ethernet is called _breakout_ and the process of changing the configuration from 10 Gb Ethernet to 40 Gb Ethernet is called _breakin_. When you break out a 40/100 Gb Ethernet port into 10 Gb Ethernet ports, the resulting ports are numbered using a 3-tuple naming convention. For example, the breakout ports of the second 40 Gb Ethernet port are numbered as 1/2/1, 1/2/2, 1/2/3, and 1/2/4.

* On the left side of Nexus 3132Q-V switches is a set of four SFP+ ports multiplexed to the first QSFP port.
+
By default, the reference configuration file (RCF) is structured to use the first QSFP port.
+
You can make four SFP+ ports active instead of a QSFP port for Nexus 3132Q-V switches by using the `hardware profile front portmode sfp-plus` command. Similarly, you can reset Nexus 3132Q-V switches to use a QSFP port instead of four SFP+ ports by using the `hardware profile front portmode qsfp` command.
+
NOTE: When you use the first four SFP+ ports, it will disable the first 40GbE QSFP port.

* You must have configured some of the ports on Nexus 3132Q-V switches to run at 10 GbE or 40/100 GbE.
+
You can break out the first six ports into 4x 10 GbE mode by using the `interface breakout module 1 port 1-6 map 10g-4x` command. Similarly, you can regroup the first six QSFP+ ports from _breakout_ configuration by using the `no interface breakout module 1 port 1-6 map 10g-4x` command.

* You must have done the planning, migration, and read the required documentation on 10 GbE and 40/100 GbE connectivity from nodes to Nexus 3132Q-V cluster switches.
* The ONTAP and NX-OS versions that are supported in this procedure are listed on the link:http://support.netapp.com/NOW/download/software/cm_switches/[Cisco Ethernet Switches^] page.


* The ONTAP and FASTPATH versions that are supported in this procedure are listed on the link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/[NetApp CN1601 and CN1610 Switches^] page.

// QA clean-up, 2022-03-04
