---
permalink: switch-cisco-3132q-v/index.html
sidebar: sidebar
keywords: Cisco, 3132Q-V
summary: "Migrating to a Two-Node Switched Cluster"
---
= Overview of Cisco Nexus 3132Q-V switches
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Cisco Nexus 3132Q-V switches as cluster switches in your AFF or FAS cluster.

* You can install NX-OS and reference configuration files (RCFs) on the Cisco Nexus 3132Q-V cluster switch.

* You can migrate from a two-node switchless cluster environment to a two-node switched environment using Cisco Nexus 3132Q-V cluster switches.

* You can replace a defective Cisco Nexus 3132Q-V switch in a cluster and download the switch operating system and reference configuration file.

* You can replace Cisco Nexus 5596, Nexus 5020, or Nexus 5010 cluster switches with Cisco Nexus 3132Q-V switches.

* You can replace NetApp CN1610 switches with Cisco Nexus 3132Q-V cluster switches.

.Available documentation
The following table lists the documentation available for the Cisco Nexus 3132Q-V switches.
["options="header"]
|===
| Title| Description
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/task-install-a-cisco-nexus-3232c-cluster-switch-and-pass-through-panel-in-a-netapp-cabinet.html[_Install a Cisco® Nexus 3132Q-V cluster switch and pass-through panel in a NetApp® cabinet_^]
a|
Describes how to install the pass-through panel in system cabinets where power connectors are at the front of the chassis and power distribution units are located in the rear of the chassis.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/setup-switches.html[_Setup the Cisco® Nexus 3132Q-V cluster switches_^]
a| Describes how to setup and configure your Cisco Nexus 3132Q-V cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/task-install-nx-os-software-and-rcfs-on-cisco-nexus-3132q-v-cluster-switches.html[_Install NX-OS and Reference Configuration Files (RCFs)_^]
a|
Describes how to install NX-OS and reference configuration files (RCFs) on Nexus 3132Q-V cluster switch.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/concept-migrate-from-a-cisco-5596-switch-to-a-cisco-nexus-3232c.html[_Replace Cisco Nexus 5596 cluster switches with Cisco Nexus 3132Q-V cluster switches_^]
a|
Describes how to migrate from environments that use older Cisco switches to environments that use Cisco 3132Q-V switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html[_Replace CN1610 cluster switches with Cisco Nexus 3132Q-V cluster switches_^]
a|
Describes the procedure to replace a CN1610 switch with a Cisco Nexus 3132Q-V cluster switch.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/concept-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3232c-cluster-switches.html[_Migrate from a two-node Switchless Cluster_^]
a|
Describes how to migrate from a two-node switchless cluster environment to a two-node switched environment using Cisco Nexus 3132Q-V cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/concept-replace-cisco-nexus-3132q-v-cluster-switches.html[_Replace a Cisco Nexus 3132Q-V Cluster Switch_^]
a|
Describes the procedure to replace a defective Cisco Nexus 3132Q-V switch in a cluster and download the switch operating system and reference configuration file.
//a|
//https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-replace-a-cisco-nexus-3232c-storage-switch.html[_Replacing a Cisco Nexus 3232C Storage Switch_^]
//a|
//Describes the procedure to replace a defective Cisco Nexus 3232C storage switch and download the switch operating system and reference configuration file.
|===

// QA clean-up, 2022-03-03
