---
permalink: switch-cisco-3132q-v/index.html
sidebar: sidebar
keywords: Cisco, 3132Q-V
summary: "Migrating to a Two-Node Switched Cluster"
---
= Overview and requirements
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Cisco Nexus 3132Q-V switches as cluster switches in your AFF or FAS cluster.

* You can install NX-OS and reference configuration files (RCFs) on the Cisco Nexus 3132Q-V cluster switch.

* You can migrate from a two-node switchless cluster environment to a two-node switched environment using Cisco Nexus 3132Q-V cluster switches.

* You can replace a defective Cisco Nexus 3132Q-V switch in a cluster and download the switch operating system and reference configuration file.

* You can replace Cisco Nexus 5596, Nexus 5020, or Nexus 5010 cluster switches with Cisco Nexus 3132Q-V switches.

* You can replace NetApp CN1610 switches with Cisco Nexus 3132Q-V cluster switches.

== Configuration requirements
[.lead]
To configure your cluster, you need the appropriate number and type of cables and cable connectors for your switches. Depending on the type of switch you are initially configuring, you need to connect to the switch console port with the included console cable; you also need to provide specific network information.

== Network requirements

You need the following network information for all switch configurations:

* IP subnet for management network traffic
* Host names and IP addresses for each of the storage system controllers and all applicable switches
* Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon). On AFF A800 and AFF A700 systems, the e0M interface uses a dedicated Ethernet port.

Refer to the https://hwu.netapp.com[Hardware Universe^] for latest information.

== Smart Call Home requirements
[.lead]
Smart Call Home monitors the hardware and software components on your network, to generate an email-based notification of critical system conditions. When an event occurs on your device, Smart Call Home raises an alert to all the recipients that are configured in your destination profile.

You must configure a cluster network switch to communicate using email with the Smart Call Home system. You can optionally set up your cluster network switch to take advantage of Cisco's embedded Smart Call Home support feature.

Before you can use Smart Call Home feature, you need to be aware of the following considerations:

* An email server must be in place.
* The switch must have IP connectivity to the email server.
* The contact name (SNMP server contact), phone number, and street address information must be configured.
* This is required to determine the origin of messages received.
* A CCO ID must be associated with an appropriate Cisco SMARTnet Service contract for your company.
* Cisco SMARTnet Service must be in place for the device to be registered.

The Cisco support site contains information about the commands to configure Smart Call Home.

http://www.cisco.com/c/en/us/products/switches/index.html[Cisco support site^]


== Documentation requirements
[.lead]
You need specific switch and controller documentation to set up your ONTAP cluster.

=== Cluster network switches documentation
To set up the Cisco Nexus 9336C-FX2 and 92300YC switches, you need the following documentation from the https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html[Cisco Nexus 9000 Series Switches Support^] page:

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_Nexus 9000 Series Hardware Installation Guide_
a|
Provides detailed information about site requirements, switch hardware details, and installation options.
a|
_Cisco Nexus 9000 Series Switch Software Configuration Guides_ (choose the guide for the NX-OS release installed on your switches)
a|
Provides initial switch configuration information that you need before you can configure the switch for ONTAP operation.
a|
_Cisco Nexus 9000 Series NX-OS Software Upgrade and Downgrade Guide_ (choose the guide for the NX-OS release installed on your switches)
a|
Provides information on how to downgrade the switch to ONTAP supported switch software, if necessary.
a|
_Cisco Nexus 9000 Series NX-OS Command Reference Master Index_
a|
Provides links to the various command references provided by Cisco.
a|
_Cisco Nexus 9000 MIBs Reference_
a|
Describes the Management Information Base (MIB) files for the Nexus 9000 switches.
a|
_Nexus 9000 Series NX-OS System Message Reference_
a|
Describes the system messages for Cisco Nexus 9000 series switches, those that are informational, and others that might help diagnose problems with links, internal hardware, or the system software.
a|
_Cisco Nexus 9000 Series NX-OS Release Notes (choose the notes for the NX-OS release installed on your switches)_
a|
Describes the features, bugs, and limitations for the Cisco Nexus 9000 Series.
a|
Regulatory Compliance and Safety Information for Cisco Nexus 9000 Series
a|
Provides international agency compliance, safety, and statutory information for the Nexus 9000 series switches.
|===
To set up the Cisco Nexus 3232C and 3132Q-V switches, you need the following documentation from the https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html[Cisco Nexus 3000 Series Switches Support^] page:

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_Nexus 3000 Series Hardware Installation Guide_
a|
Provides detailed information about site requirements, switch hardware details, and installation options.
a|
_Cisco Nexus 3000 Series Switch Software Configuration Guides_ (choose the guide for the NX-OS release installed on your switches)
a|
Provides initial switch configuration information that you need before you can configure the switch for ONTAP operation.
a|
_Cisco Nexus 3000 Series NX-OS Software Upgrade and Downgrade Guide_ (choose the guide for the NX-OS release installed on your switches)
a|
Provides information on how to downgrade the switch to ONTAP supported switch software, if necessary.
a|
_Cisco Nexus 3000 Series NX-OS Command Reference Master Index_
a|
Provides links to the various command references provided by Cisco.
a|
_Cisco Nexus 3000 MIBs Reference_
a|
Describes the Management Information Base (MIB) files for the Nexus 3000 switches.
a|
_Nexus 3000 Series NX-OS System Message Reference_
a|
Describes the system messages for Cisco Nexus 3000 series switches, those that are informational, and others that might help diagnose problems with links, internal hardware, or the system software.
a|
_Cisco Nexus 3000 Series NX-OS Release Notes (choose the notes for the NX-OS release installed on your switches)_
a|
Describes the features, bugs, and limitations for the Cisco Nexus 3000 Series.
a|
Regulatory, Compliance, and Safety Information for the Cisco Nexus 6000, Cisco Nexus 5000 Series, Cisco Nexus 3000 Series, and Cisco Nexus 2000 Series
a|
Provides international agency compliance, safety, and statutory information for the Nexus 3000 series switches.
|===
To set up the Cisco Nexus 5596 switch, you need the following documents from https://www.cisco.com/c/en/us/support/switches/nexus-5000-series-switches/series.html[Cisco Nexus 5000 Series Switches Support^] page:

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_Nexus 5000 Series Hardware Installation Guide_
a|
Provides detailed information about site requirements, switch hardware details, and installation options.
a|
_Cisco Nexus 5000 Series Switch Software Configuration Guide_ (choose the guide for the software you are using)
a|
Provides initial switch configuration information that you need before you can configure the switch for ONTAP operation.
a|
_Cisco Nexus 5000 Series NX-OS Software Upgrade and Downgrade Guide_
a|
Provides information about how to downgrade the switch to the supported ONTAP switch software, if necessary.
a|
_Cisco Nexus 5000 Series NX-OS Command Reference Master Index_
a|
Provides an alphabetical list of all the commands supported for a specific NX-OS release.
a|
_Cisco Nexus 5000 and Nexus 2000 MIBs Reference_
a|
Describes the Management Information Base (MIB) files for the Nexus 5000 switches.
a|
_Nexus 5000 Series NX-OS System Message Reference_
a|
Describes troubleshooting information.
a|
_Regulatory, Compliance, and Safety Information for the Cisco Nexus 6000 Series, Cisco Nexus 5000 Series, Cisco Nexus 3000 Series, and Cisco Nexus 2000 Series_
a|
Provides international agency compliance, safety, and statutory information for the Nexus 5000 series switches.
|===

=== ONTAP systems documentation

To set up an ONTAP system, you need the following documents for your version of the operating system from the https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center^].

[options="header" cols="1,2"]
|===
| Name| Description
a|
Controller-specific _Installation and Setup Instructions_
a|
Describes how to install NetApp hardware.
a|
ONTAP documentation
a|
Provides detailed information about all aspects of the ONTAP releases.
a|
https://hwu.netapp.com[Hardware Universe^]
a|
Provides NetApp hardware configuration and compatibility information.
|===

.Rail kit and cabinet documentation

To install a Cisco switch in a NetApp cabinet, see the following hardware documentation:

[options="header" cols="1,2"]
|===
| Name| Description
a|
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394[42U System Cabinet, Deep Guide^]
a|
Describes the FRUs associated with the 42U system cabinet, and provides maintenance and FRU replacement instructions.
a|
https://library.netapp.com/ecm/ecm_get_file/ECMLP2843148[Installing a Cisco Nexus 3232C cluster switch and pass-through panel in a NetApp cabinet^]
a|
Describes how to install a Cisco Nexus 3232C switch in a four-post NetApp cabinet.
a|
https://library.netapp.com/ecm/ecm_download_file/ECMLP2518305[Installing a Cisco Nexus 3132Q-V switch and pass-through panel in a NetApp Cabinet^]
a|
Describes how to install a Cisco Nexus 3132Q-V switch in a four-post NetApp cabinet.
a|
https://library.netapp.com/ecm/ecm_download_file/ECMP1141864[Installing a Cisco Nexus 5596 switch and pass-through panel in a NetApp Cabinet^]
a|
Describes how to install a Cisco Nexus 5596 switch in a NetApp cabinet.
|===
