---
permalink: switch-cisco-3132q-v/index.html
sidebar: sidebar
keywords: Cisco, 3132Q-V
summary: "Migrating to a Two-Node Switched Cluster"
---
= Cisco Nexus 3132Q-V switches Overview
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Cisco 3132Q-V switches as cluster switches in your AFF or FAS cluster. You can use these procedures to install the switch, migrate from an existing switch, replace a switch, and update the RCF files on the switch.

* You can install NX-OS and reference configuration files (RCFs) on the Nexus 3132Q-V cluster switch.

* You can migrate from a two-node switchless cluster environment to a two-node switched environment using Cisco Nexus 3132Q-V cluster switches.

* You can replace a defective Cisco Nexus 3132Q-V switch in a cluster and download the switch operating system and reference configuration file.

* You can replace Cisco Nexus 5596, Nexus 5020, or Nexus 5010 cluster switches with Cisco Nexus 3132Q-V switches.

* You can replace CN1610 switches with Cisco Nexus 3132Q-V cluster switches.

// QA clean-up, 2022-03-03
