---
permalink: switch-cisco-3132q-v/install-nx-os-software-3132q-v.html
sidebar: sidebar
keywords: install, nx-os software
summary: "You can use this procedure to install the NX-OS software on the Nexus 3132Q-V cluster switch."
---
= Install the NX-OS software
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to install the NX-OS software on the Nexus 3132Q-V cluster switch.

== Requirements for this procedure

.What you'll need

* A fully functioning cluster (no errors in the logs or similar issues).
* The current Reference Configuration File (RCF).
* A boot configuration in the RCF that reflects the desired boot images, required if you are installing only NX-OS and keeping your current RCF version. If you need to change the boot configuration to reflect the current boot images, you must do so before reapplying the RCF so that the correct version is instantiated on future reboots.
* A console connection to the switch, required when installing the RCF.

.Suggested documentation

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet switch^] page. Consult the switch compatibility table on the  for the supported ONTAP, NX-OS, and RCF versions. Note that there can be command dependencies between the command syntax in the RCF and that found in versions of NX-OS.
* https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html[Cisco Nexus 3000 Series Switches^]. Consult the appropriate software and upgrade guides available on the Cisco web site for complete documentation on the Cisco switch upgrade and downgrade procedures.

== Install the software

.About this task
Be sure to complete the procedure in link:setup-switch.html[Prepare to install NX-OS and RCF], and then follow the steps below.

.Steps

. Connect the cluster switch to the management network.
. Use the `ping` command to verify connectivity to the server hosting the NX-OS software and the RCF.
+
.Example verifying the switch can reach the server at IP address 172.19.2.1
[%collapsible]
====


[subs=+quotes]
----
cs2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====

. Copy the NX-OS software to the Nexus 3132Q-V switch using one of the following transfer protocols: FTP, TFTP, SFTP, or SCP. For more information on Cisco commands, see the appropriate guide in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html[Cisco Nexus 3000 Series NX-OS Command Reference guides^].
+
.Example showing SFTP being used to copy the NX-OS software to the Nexus 3132Q-V switch
[%collapsible]
====

[subs=+quotes]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.4.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password: *xxxxxxxx*
sftp> *progress*
Progress meter enabled
sftp> *get   /code/nxos.9.3.4.bin  /bootflash/nxos.9.3.4.bin*
/code/nxos.9.3.4.bin  100% 1261MB   9.3MB/s   02:15
sftp> *exit*
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
+
// BURT 1412345 8-Mar-2022 removed reference to EPLD image

. Verify the running version of the NX-OS software:
`show version`
+
.Example showing the version
[%collapsible]
====
[subs=+quotes]
----
cs2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 04.25
NXOS: version 9.3(3)
  BIOS compile time:  01/28/2020
  NXOS image file is: bootflash:///nxos.9.3.3.bin
                  NXOS compile time: 12/22/2019 2:00:00 [12/22/2019 14:00:37]

Hardware
  cisco Nexus 3132QV Chassis (Nexus 9000 Series)
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16399900 kB of memory.
  Processor Board ID FOxxxxxxx23

  Device name: cs2
  bootflash:   15137792 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 79 day(s), 10 hour(s), 23 minute(s), 53 second(s)

Last reset at 663500 usecs after Mon Nov  2 10:50:33 2020
  Reason: Reset Requested by CLI command reload
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
cs2#
----
====

. Install the NX-OS image.
+
Installing the image file causes it to be loaded every time the switch is rebooted.
+
.Example showing install command
[%collapsible]
====
[subs=+quotes]
----
cs2# *install all nxos bootflash:nxos.9.3.4.bin*
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact              Install-type  Reason
------- ----------------- ------------------- ------------- ------
     1     yes            disruptive          reset         default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image       Running-Version(pri:alt)                New-Version          Upg-Required
------------ ----------- --------------------------------------- -------------------- ------------
     1       nxos        9.3(3)                                  9.3(4)               yes
     1       bios        v04.25(01/28/2020):v04.25(10/18/2016)   v04.25(01/28/2020)   no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
cs2#
----
====

. Verify the new version of NX-OS software after the switch has rebooted:
+
`show version`
+
.Example showing the version
[%collapsible]
====
[subs=+quotes]
----
cs2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 04.25
NXOS: version 9.3(4)
  BIOS compile time:  05/22/2019
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 06:28:31]


Hardware
  cisco Nexus 3132QV Chassis (Nexus 9000 Series)
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16399900 kB of memory.
  Processor Board ID FOxxxxxxx23

  Device name: cs2
  bootflash:   15137792 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 79 day(s), 10 hour(s), 23 minute(s), 53 second(s)

Last reset at 663500 usecs after Mon Nov  2 10:50:33 2020
  Reason: Reset Requested by CLI command reload
  System version: 9.3(4)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

cs2#
----
====


.What's next?

link:install-rcf-3132q-v.html[Install RCF config file]

// QA clean-up, 2022-03-03

// BURT 1412345 8-Mar-2022 removed EPLD upgrade steps 7 to 9
