---
permalink: switch-cisco-3132q-v/install-overview-cisco-3132qv.html
sidebar: sidebar
keywords: install, cisco nexus 3132q-v cluster switch,
summary: 'Before configuring BES-53248 cluster switches, review an overview of the process and the nomenclature.'
---
= Overview of configuration process for Cisco Nexus 3132Q-V switches
:icons: font
:imagesdir: ../media/

[.lead]
Before configuring Cisco Nexus 3132Q-V switches, review the requirements and the procedure overview.

== Requirements
Be sure to review the link:index.html[Overview and requirements].

== Procedure overview

To initially configure a Cisco Nexus 3132Q-V switch on systems running ONTAP, follow these steps:

. link:switch-cisco-3132q-v/setup_worksheet_3132q.html[Complete cabling worksheet].
.link:install-cisco-nexus-3232c.html[Install a Cisco Nexus 3132Q-V cluster switch in a NetApp cabinet].
. link:setup-switch.html[Configure the Cisco Nexus 3132Q-V switch].
. link:prepare-install-cisco-nexus-3132q.html[Prepare to install NX-OS software and Reference Configuration file].
. link:install-nx-os-software-3132q-v.html[Install the NX-OS software].
. link:install-rcf-3132q-v.html[Install the Reference Configuration File (RCF)].
