---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html
sidebar: sidebar
keywords: install, cisco nexus 3132q-v switch,
summary: 'Before configuring Cisco Nexus 3132q-v switches, review an overview of the process and the nomenclature.'
---
= Migration requirements
:imagesdir: ../media/

[.lead]
If you have a two-node switchless cluster, review this procedure for the applicable requirements to migrate to a two-node switched cluster. 

[NOTE]
====
The procedure requires the use of both ONTAP commands and Cisco Nexus 3000 Series Switches commands; ONTAP commands are used unless otherwise indicated.
====

For more information, see:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab[NetApp CN1601 and CN1610^]

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switch^]

* link:http://hwu.netapp.com[Hardware Universe^]

.Port and node connections
Make sure you understand the port and node connections and cabling requirements when you migrate to a two-node switched cluster with Cisco Nexus 3132Q-V cluster switches.

* The cluster switches use the Inter-Switch Link (ISL) ports e1/31-32.
* The link:https://hwu.netapp.com/[Hardware Universe^] contains information about supported cabling to Nexus 3132Q-V switches:

 ** The nodes with 10 GbE cluster connections require QSFP optical modules with breakout fiber cables or QSFP to SFP+ copper break-out cables.
 ** The nodes with 40 GbE cluster connections require supported QSFP/QSFP28 optical modules with fiber cables or QSFP/QSFP28 copper direct-attach cables.
 ** The cluster switches use the appropriate ISL cabling: 2x QSFP28 fiber or copper direct-attach cables.
* On Nexus 3132Q-V, you can operate QSFP ports as either 40 Gb Ethernet or 4x10 Gb Ethernet modes.
+
By default, there are 32 ports in the 40 Gb Ethernet mode. These 40 Gb Ethernet ports are numbered in a 2-tuple naming convention. For example, the second 40 Gb Ethernet port is numbered as 1/2. The process of changing the configuration from 40 Gb Ethernet to 10 Gb Ethernet is called _breakout_ and the process of changing the configuration from 10 Gb Ethernet to 40 Gb Ethernet is called _breakin_. When you break out a 40 Gb Ethernet port into 10 Gb Ethernet ports, the resulting ports are numbered using a 3-tuple naming convention. For example, the breakout ports of the second 40 Gb Ethernet port are numbered as 1/2/1, 1/2/2, 1/2/3, and 1/2/4.

* On the left side of Nexus 3132Q-V is a set of four SFP+ ports multiplexed to the first QSFP port.
+
By default, the RCF is structured to use the first QSFP port.
+
You can make four SFP+ ports active instead of a QSFP port for Nexus 3132Q-V by using the `hardware profile front portmode sfp-plus` command. Similarly, you can reset Nexus 3132Q-V to use a QSFP port instead of four SFP+ ports by using the `hardware profile front portmode qsfp` command.

* Make sure you configured some of the ports on Nexus 3132Q-V to run at 10 GbE or 40 GbE.
+
You can break-out the first six ports into 4x10 GbE mode by using the `interface breakout module 1 port 1-6 map 10g-4x` command. Similarly, you can regroup the first six QSFP+ ports from breakout configuration by using the `no interface breakout module 1 port 1-6 map 10g-4x` command.

* The number of 10 GbE and 40 GbE ports are defined in the reference configuration files (RCFs) available at link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab[Cisco ® Cluster Network Switch Reference Configuration File Download^].

.Before you begin

* Configurations properly set up and functioning.
* Nodes running ONTAP 9.4 or later.
* All cluster ports in the `up` state.
* The Cisco Nexus 3132Q-V cluster switch is supported.
* The existing cluster network configuration has:

 ** The Nexus 3132 cluster infrastructure that is redundant and fully functional on both switches.
 ** The latest RCF and NX-OS versions on your switches.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch[Cisco Ethernet Switches^] has information about the ONTAP and NX-OS versions supported in this procedure.

 ** Management connectivity on both switches.
 ** Console access to both switches.
 ** All cluster logical interfaces (LIFs) in the `up` state without being migrated.
 ** Initial customization of the switch.
 ** All the ISL ports enabled and cabled.

In addition, you must plan, migrate, and read the required documentation on 10 GbE and 40 GbE connectivity from nodes to Nexus 3132Q-V cluster switches.

.About the examples used

The examples in this procedure use the following switch and node nomenclature:

* Nexus 3132Q-V cluster switches, C1 and C2.
* The nodes are n1 and n2.

[NOTE]
====
The examples in this procedure use two nodes, each using two 40 GbE cluster interconnect ports *e4a* and *e4e*. The link:https://hwu.netapp.com/[Hardware Universe^] has details about the cluster ports on your platforms.
====

This procedure covers the following scenarios:

* *n1_clus1* is the first cluster logical interface (LIF) to be connected to cluster switch C1 for node *n1*.
* *n1_clus2* is the first cluster LIF to be connected to cluster switch C2 for node *n1*.
* *n2_clus1* is the first cluster LIF to be connected to cluster switch C1 for node *n2*.
* *n2_clus2* is the second cluster LIF to be connected to cluster switch C2 for node *n2*.
* The number of 10 GbE and 40 GbE ports are defined in the reference configuration files (RCFs) available at link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab[Cisco ® Cluster Network Switch Reference Configuration File Download^].

[NOTE]
====
The procedure requires the use of both ONTAP commands and Cisco Nexus 3000 Series Switches commands; ONTAP commands are used unless otherwise indicated.
====

* The cluster starts with two nodes connected and functioning in a two-node switchless cluster setting.
* The first cluster port is moved to C1.
* The second cluster port is moved to C2.
* The two-node switchless cluster option is disabled.


.What's next?
After you've reviewed the migration requirements, you can
link:migrate-switchless-prepare-to-migrate.html[prepare to migrate your switches].

//Updates for internal GH issue #262, 2024-DEC-09