---
permalink: switch-cisco-3132q-v/switch-requirements.html
sidebar: sidebar
keywords: replace, cisco nexus 3132q-v cluster switches
summary: "You must be aware of certain configuration information, port connections and cabling requirements when you replace Cisco Nexus 3132Q-V cluster switches."
---
= Requirements for replacing Cisco Nexus 3132Q-V cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
Make sure you understand the configuration requirements, port connections, and cabling requirements when you replace cluster switches.

== Cisco Nexus 3132Q-V requirements
* The Cisco Nexus 3132Q-V cluster switch is supported.
* The number of 10 GbE and 40/100 GbE ports are defined in the reference configuration files (RCFs) available on the link:https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml[Cisco® Cluster Network Switch Reference Configuration File Download^] page.
* The cluster switches use the Inter-Switch Link (ISL) ports e1/31-32.
* The link:https://hwu.netapp.com[Hardware Universe^] contains information about supported cabling to Nexus 3132Q-V switches:
 ** The nodes with 10 GbE cluster connections require QSFP optical modules with breakout fiber cables or QSFP to SFP+ copper break-out cables.
 ** The nodes with 40/100 GbE cluster connections require supported QSFP/QSFP28 optical modules with fiber cables or QSFP/QSFP28 copper direct-attach cables.
 ** The cluster switches use the appropriate ISL cabling: 2x QSFP28 fiber or copper direct-attach cables.
* On Nexus 3132Q-V, you can operate QSFP ports as either 40/100 Gb Ethernet or 4 x10 Gb Ethernet modes.
+
By default, there are 32 ports in the 40/100 Gb Ethernet mode. These 40 Gb Ethernet ports are numbered in a 2-tuple naming convention. For example, the second 40 Gb Ethernet port is numbered as 1/2. The process of changing the configuration from 40 Gb Ethernet to 10 Gb Ethernet is called _breakout_ and the process of changing the configuration from 10 Gb Ethernet to 40 Gb Ethernet is called _breakin_. When you break out a 40/100 Gb Ethernet port into 10 Gb Ethernet ports, the resulting ports are numbered using a 3-tuple naming convention. For example, the breakout ports of the second 40/100 Gb Ethernet port are numbered as 1/2/1, 1/2/2, 1/2/3, 1/2/4.

* On the left side of Nexus 3132Q-V is a set of four SFP+ ports multiplexed to the first QSFP port.
+
By default, the RCF is structured to use the first QSFP port.
+
You can make four SFP+ ports active instead of a QSFP port for Nexus 3132Q-V by using the `hardware profile front portmode sfp-plus` command. Similarly, you can reset Nexus 3132Q-V to use a QSFP port instead of four SFP+ ports by using the `hardware profile front portmode qsfp` command.

* You must have configured some of the ports on Nexus 3132Q-V to run at 10 GbE or 40/100 GbE.
+
You can break-out the first six ports into 4x10 GbE mode by using the `interface breakout module 1 port 1-6 map 10g-4x` command. Similarly, you can regroup the first six QSFP+ ports from breakout configuration by using the `no interface breakout module 1 port 1-6 map 10g-4x` command.

* You must have done the planning, migration, and read the required documentation on 10 GbE and 40/100 GbE connectivity from nodes to Nexus 3132Q-V cluster switches.
+
The link:http://mysupport.netapp.com/NOW/download/software/cm_switches/[Cisco Ethernet Switches^] page has information about the ONTAP and NX-OS versions supported in this procedure.

// QA clean-up, 2022-03-04

== Cisco Nexus 5596 requirements
* The following cluster switches are supported:
 ** Nexus 5596
 ** Nexus 3132Q-V
* The number of 10 GbE and 40/100 GbE ports are defined in the reference configuration files (RCFs) available on the https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml[Cisco® Cluster Network Switch Reference Configuration File Download^] page.
* The cluster switches use the following ports for connections to nodes:
 ** Ports e1/1-40 (10 GbE): Nexus 5596
 ** Ports e1/1-30 (40/100 GbE): Nexus 3132Q-V
* The cluster switches use the following Inter-Switch Link (ISL) ports:
 ** Ports e1/41-48 (10 GbE): Nexus 5596
 ** Ports e1/31-32 (40/100 GbE): Nexus 3132Q-V
* The link:https://hwu.netapp.com/[Hardware Universe^] contains information about supported cabling to Nexus 3132Q-V switches:
 ** Nodes with 10 GbE cluster connections require QSFP to SFP+ optical fiber breakout cables or QSFP to SFP+ copper breakout cables.
 ** Nodes with 40/100 GbE cluster connections require supported QSFP/QSFP28optical modules with fiber cables or QSFP/QSFP28 copper direct-attach cables.
* The cluster switches use the appropriate ISL cabling:
 ** Beginning: Nexus 5596 to Nexus 5596 (SFP+ to SFP+)
  *** 8x SFP+ fiber or copper direct-attach cables
 ** Interim: Nexus 5596 to Nexus 3132Q-V (QSFP to 4xSFP+ break-out)
  *** 1x QSFP to SFP+ fiber break-out or copper break-out cables
 ** Final: Nexus 3132Q-V to Nexus 3132Q-V (QSFP28 to QSFP28)
  *** 2x QSFP28 fiber or copper direct-attach cables
* On Nexus 3132Q-V switches, you can operate QSFP/QSFP28 ports as either 40/100 Gigabit Ethernet or 4 x10 Gigabit Ethernet modes.
+
By default, there are 32 ports in the 40/100 Gigabit Ethernet mode. These 40 Gigabit Ethernet ports are numbered in a 2-tuple naming convention. For example, the second 40 Gigabit Ethernet port is numbered as 1/2. The process of changing the configuration from 40 Gigabit Ethernet to 10 Gigabit Ethernet is called _breakout_ and the process of changing the configuration from 10 Gigabit Ethernet to 40 Gigabit Ethernet is called _breakin_. When you break out a 40/100 Gigabit Ethernet port into 10 Gigabit Ethernet ports, the resulting ports are numbered using a 3-tuple naming convention. For example, the break-out ports of the second 40 Gigabit Ethernet port are numbered as 1/2/1, 1/2/2, 1/2/3, and 1/2/4.

* On the left side of Nexus 3132Q-V switches is a set of 4 SFP+ ports multiplexed to that QSFP28 port.
+
By default, the RCF is structured to use the QSFP28 port.
+
NOTE: You can make 4x SFP+ ports active instead of a QSFP port for Nexus 3132Q-V switches by using the `hardware profile front portmode sfp-plus` command. Similarly, you can reset Nexus 3132Q-V switches to use a QSFP port instead of 4x SFP+ ports by using the `hardware profile front portmode qsfp` command.

* You have configured some of the ports on Nexus 3132Q-V switches to run at 10 GbE or 40/100 GbE.
+
NOTE: You can break out the first six ports into 4x10 GbE mode by using the `interface breakout module 1 port 1-6 map 10g-4x` command. Similarly, you can regroup the first six QSFP+ ports from breakout configuration by using the `no interface breakout module 1 port 1-6 map 10g-4x` command.

* You have done the planning, migration, and read the required documentation on 10 GbE and 40/100 GbE connectivity from nodes to Nexus 3132Q-V cluster switches.
* The ONTAP and NX-OS versions supported in this procedure are on the link:http://support.netapp.com/NOW/download/software/cm_switches/[Cisco Ethernet Switches^] page.

// QA clean-up, 2022-03-03

== NetApp CN1610 requirements
* The following cluster switches are supported:
 ** NetApp CN1610
 ** Cisco Nexus 3132Q-V
* The cluster switches support the following node connections:
 ** NetApp CN1610: ports 0/1 through 0/12 (10 GbE)
 ** Cisco Nexus 3132Q-V: ports e1/1-30 (40/100 GbE)
* The cluster switches use the following inter-switch link (ISL) ports:
 ** NetApp CN1610: ports 0/13 through 0/16 (10 GbE)
 ** Cisco Nexus 3132Q-V: ports e1/31-32 (40/100 GbE)
* The link:https://hwu.netapp.com/[Hardware Universe^] contains information about supported cabling to Nexus 3132Q-V switches:
 ** Nodes with 10 GbE cluster connections require QSFP to SFP+ optical fiber breakout cables or QSFP to SFP+ copper breakout cables
 ** Nodes with 40/100 GbE cluster connections require supported QSFP/QSFP28 optical modules with optical fiber cables or QSFP/QSFP28 copper direct-attach cables
* The appropriate ISL cabling is as follows:
 ** Beginning: For CN1610 to CN1610 (SFP+ to SFP+), four SFP+ optical fiber or copper direct-attach cables
 ** Interim: For CN1610 to Nexus 3132Q-V (QSFP to four SFP+ breakout), one QSFP to SFP+ optical fiber or copper breakout cable
 ** Final: For Nexus 3132Q-V to Nexus 3132Q-V (QSFP28 to QSFP28), two QSFP28 optical fiber or copper direct-attach cables
* NetApp twinax cables are not compatible with Cisco Nexus 3132Q-V switches.
+
If your current CN1610 configuration uses NetApp twinax cables for cluster-node-to-switch connections or ISL connections and you want to continue using twinax in your environment, you need to procure Cisco twinax cables. Alternatively, you can use optical fiber cables for both the ISL connections and the cluster-node-to-switch connections.

* On Nexus 3132Q-V switches, you can operate QSFP/QSFP28 ports as either 40/100 Gb Ethernet or 4x 10 Gb Ethernet modes.
+
By default, there are 32 ports in the 40/100 Gb Ethernet mode. These 40 Gb Ethernet ports are numbered in a 2-tuple naming convention. For example, the second 40 Gb Ethernet port is numbered as 1/2. The process of changing the configuration from 40 Gb Ethernet to 10 Gb Ethernet is called _breakout_ and the process of changing the configuration from 10 Gb Ethernet to 40 Gb Ethernet is called _breakin_. When you break out a 40/100 Gb Ethernet port into 10 Gb Ethernet ports, the resulting ports are numbered using a 3-tuple naming convention. For example, the breakout ports of the second 40 Gb Ethernet port are numbered as 1/2/1, 1/2/2, 1/2/3, and 1/2/4.

* On the left side of Nexus 3132Q-V switches is a set of four SFP+ ports multiplexed to the first QSFP port.
+
By default, the reference configuration file (RCF) is structured to use the first QSFP port.
+
You can make four SFP+ ports active instead of a QSFP port for Nexus 3132Q-V switches by using the `hardware profile front portmode sfp-plus` command. Similarly, you can reset Nexus 3132Q-V switches to use a QSFP port instead of four SFP+ ports by using the `hardware profile front portmode qsfp` command.
+
NOTE: When you use the first four SFP+ ports, it will disable the first 40GbE QSFP port.

* You must have configured some of the ports on Nexus 3132Q-V switches to run at 10 GbE or 40/100 GbE.
+
You can break out the first six ports into 4x 10 GbE mode by using the `interface breakout module 1 port 1-6 map 10g-4x` command. Similarly, you can regroup the first six QSFP+ ports from _breakout_ configuration by using the `no interface breakout module 1 port 1-6 map 10g-4x` command.

* You must have done the planning, migration, and read the required documentation on 10 GbE and 40/100 GbE connectivity from nodes to Nexus 3132Q-V cluster switches.
* The ONTAP and NX-OS versions that are supported in this procedure are listed on the link:http://support.netapp.com/NOW/download/software/cm_switches/[Cisco Ethernet Switches^] page.


* The ONTAP and FASTPATH versions that are supported in this procedure are listed on the link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/[NetApp CN1601 and CN1610 Switches^] page.

// QA clean-up, 2022-03-04
