---
sidebar: sidebar
permalink: switch-cisco-3232c-storage/configure-reqs-3232c-storage.html
keywords: shared storage cluster switch
summary: From ONTAP 9.9.1, you can use Cisco Nexus 3232C switches to combine storage and cluster functionality into a shared switch scenario.
---
= Configuration requirements for Cisco Nexus 3232C storage switches
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
For Cisco Nexus 3232C switch installation and maintenance, be sure to review configuration and network requirements. 

== Configuration requirements

You need the appropriate number and type of cables and cable connectors for your switches. Depending on the type of switch you are initially configuring, you need to connect to the switch console port with the included console cable; you also need to provide specific network information.

== Network requirements

You need the following network information for all switch configurations:

* IP subnet for management network traffic
* Host names and IP addresses for each of the storage system controllers and all applicable switches
* Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon). On AFF A800 and AFF A700 systems, the e0M interface uses a dedicated Ethernet port.

Refer to the https://hwu.netapp.com[Hardware Universe^] for latest information. See link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU[What additional information do I need to install my equipment that is not in HWU?^] for more information about switch installation requirements.

.What's next

After you've confirmed your configuration requirements, you can review the link:required-documentation-3232c-storage.html[required documentation].

// New content for 3232C storage switches, 2026-JAN-07