---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html
sidebar: sidebar
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c
summary: SSH is a requirement when using the Cluster Switch Health Monitor \(CSHM\) and log collection features. To enable SSH on Cisco 3232c cluster switches, you generate the SSH keys first and then enable SSH.
---
= Install the Reference Configuration File (RCF)
:icons: font
:imagesdir: ../media/

[.lead]
You install the Reference Configuration File (RCF) after setting up the Nexus 3232C switches for the first time.

.Before you begin
Verify the following installations and connections:

* A current backup of the switch configuration.
* A fully functioning cluster (no errors in the logs or similar issues).
* The current RCF.
* A console connection to the switch, this is required when installing the RCF.

.About this task
The procedure requires the use of both ONTAP commands and Cisco Nexus 3000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

Complete the procedure in link:prepare-install-cisco-nexus-3232c-storage.html[Prepare to install NX-OS and RCF], and then follow the steps below.

== Step 1: Install the RCF on the switches
. Login to switch s2 using SSH or by using a serial console.

. Copy the RCF to the bootflash of switch s2 using one of the following transfer protocols: FTP, TFTP, SFTP, or SCP. For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html[Cisco Nexus 3000 Series NX-OS Command Reference^].
+
.Show example 
[%collapsible]
====
This example shows TFTP being used to copy an RCF to the bootflash on switch s2:
[subs=+quotes]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9336C-FX2-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====

. Apply the RCF previously downloaded to the bootflash.
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html[Cisco Nexus 3000 Series NX-OS Command Reference^].
+
.Show example 
[%collapsible]
====
This example shows the RCF file `NX9336C-FX2-RCF-v1.13-1-Storage.txt` being installed on switch s2:
[subs=+quotes]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
=================
Make sure to read thoroughly the *Installation notes*, *Important Notes*, and *banner* sections of your RCF. You must read and follow these instructions to verify the proper configuration and operation of the switch.
=================

. Examine the banner output from the `show banner motd` command. You must read and follow the instructions under *Important Notes* to make sure the proper configuration and operation of the switch.

. Verify that the RCF is the correct newer version:
+
`show running-config`
+
When you check the output to verify you have the correct RCF, make sure that the following information is correct:

* The RCF banner
* The node and port settings
* Customizations
+
The output varies according to your site configuration. Check the port settings and refer to the release notes for any changes specific to the RCF that you have installed.

. Reapply any previous customizations to the switch configuration. 

. After you verify that the RCF versions and switch settings are correct, copy the `running-config` file to the `startup-config` file.
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. Reboot switch s2:
+
`s2# *reload*`
+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repeat Steps 1 to 8 on switch s1.

. Connect the node storage ports and storage shelf of all nodes in the ONTAP cluster to switches s1 and s2.

== Step: 2: Verify the switch connections

. Verify that the switch ports are *up*.
+
`show interface brief`

. Verify that the node storage ports and storage shelf ports are in their correct VLANs using the following commands:
+
`show vlan brief`
+
`show interface trunk`

== Step 3: Set up your ONTAP cluster
NetApp recommends that you use System Manager to set up new clusters.

System Manager provides a simple and easy workflow for cluster set up and configuration including assigning a node management IP address, initializing the cluster, creating a local tier, configuring protocols, and provisioning initial storage.

Refer to https://docs.netapp.com/us-en/ontap/task_configure_ontap.html[Configure ONTAP on a new cluster with System Manager] for setup instructions.

.What's next?
After you've installed the RCF, you can link:configure-ssh-keys.html[verify the SSH configuration].

// New content for 3232C storage switches, 2026-JAN-13
// AFFFASDOC-458, 2026-FEB-03