---
permalink: switch-cisco-3232c-storage/prepare-install-cisco-nexus-3232c-storage.html
sidebar: sidebar
keywords: nx-os software, install, cisco nexus storage switches, 3232c, rcfs
summary: "The Cisco NX-OS software and reference configuration files (RCFs) must be installed on Cisco Nexus 3232C storage switches."
---
= Prepare to install NX-OS software and Reference Configuration File (RCF)
:icons: font
:imagesdir: ../media/

[.lead]
Before you install the NX-OS software and the Reference Configuration File (RCF), follow this procedure.

.About the examples

The examples in this procedure use the following switch and node nomenclature:

* The names of the two Cisco switches are s1 and s2.

* The node names are cluster1-01 and cluster1-02.

See the link:https://hwu.netapp.com/SWITCH/INDEX[Hardware Universe^] to verify the correct cluster ports on your platforms. See link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU[What additional information do I need to install my equipment that is not in HWU?^] for more information about switch installation requirements.

.About this task
The procedure requires the use of both ONTAP commands and Cisco Nexus 3000 Series Switches commands; ONTAP commands are used unless otherwise indicated.

.Steps

. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message:
`system node autosupport invoke -node * -type all -message MAINT=x h`
+
where _x_ is the duration of the maintenance window in hours.
+
[NOTE]
====
The AutoSupport message notifies technical support of this maintenance task so that automatic case creation is suppressed during the maintenance window.
====

. Change the privilege level to advanced, entering *y* when prompted to continue:
+
`set -privilege advanced`
+
The advanced prompt (`*>`) appears.

. Display how many cluster interconnect interfaces are configured in each node for each cluster interconnect switch:
+
`network device-discovery show -protocol cdp`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e0a    s1                        Eth1/2            N3K-C3232C
            e0b    s2                        Eth1/2            N3K-C3232C
cluster1-01/cdp
            e0a    s1                        Eth1/1            N3K-C3232C
            e0b    s2                        Eth1/1            N3K-C3232C
4 entries were displayed.
----
====

. Check the administrative or operational status of each node storage port and storage shelf port.

 .. Display the node storage port attributes:
+
`storage port show`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e0a  ENET  storage    100 enabled  online      -
               e0b  ENET  storage    100 enabled  online      -
cluster1-02

               e0a  ENET  storage    100 enabled  online      -
               e0b  ENET  storage    100 enabled  online      -
4 entries were displayed.
----
====

 .. Display the storage shelf port attributes:
`storage shelf port show`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
4 entries were displayed.
----
====

. Verify that switch health monitoring (CSHM) is enabled for the switches so that they are monitored:
`system switch ethernet show`
+
.Show example
[%collapsible]
====

[subs=+quotes]
----
cluster1::> *system switch ethernet show*
  Switch               Type               Address          Model
  -------------------- ------------------ ---------------- ---------------
 s1                    cluster-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
s2                    cluster-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP  false
4 entries were displayed.
----
====

.What's next?

After you've prepared to install the NX-OS software and RCF, you can  link:install-nx-os-software-3232c-storage.html[install the NX-OS software].

// New content for 3232C storage switches, 2026-JAN-13
// AFFFASDOC-458, 2026-FEB-03