---
permalink: switch-cisco-3232c-storage/upgrade-rcf-software-3232c-storage.html
sidebar: sidebar
keywords: install rcf, cisco switches
summary: 'You can use this procedure to upgrade your RCF version.'
---
= Upgrade your Reference Configuration File (RCF)
:icons: font
:imagesdir: ../media/

[.lead]
You upgrade your RCF version when you have an existing version of the RCF file installed on your operational switches. 

.Before you begin
Make sure you have the following:

* A current backup of the switch configuration.
* A fully functioning cluster (no errors in the logs or similar issues).
* The current RCF.
* If you are updating your RCF version, you need a boot configuration in the RCF that reflects the desired boot images. 
+
If you need to change the boot configuration to reflect the current boot images, you must do so before reapplying the RCF so that the correct version is instantiated on future reboots.

CAUTION: Before installing a new switch software version and RCFs, you must erase the switch settings and perform basic configuration. You must be connected to the switch using the serial console or have preserved basic configuration information before erasing the switch settings.

== Step 1: Prepare for the upgrade

. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message: 
+
`system node autosupport invoke -node * -type all -message MAINT=xh`
+
Where _x_ is the duration of the maintenance window in hours.

. Change the privilege level to advanced, entering *y* when prompted to continue: 
+
`set -privilege advanced`
+
The advanced prompt (*>) appears.

. Display the ports on each node that are connected to the switches: 
+
[source,cli]
----
network device-discovery show
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
cluster1-01/cdp 
            e3a    s1                       Ethernet1/7     N3K-C3232C
            e3b    s2                       Ethernet1/7     N3K-C3232C
cluster1-02/cdp
            e3a    s1                       Ethernet1/8     N3K-C3232C
            e3b    s2                       Ethernet1/8     N3K-C3232C
.
.
----
====

. Verify that all the node storage ports are up with a healthy status: 
+
[source,cli]
----
storage port show -port-type ENET
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e0a ENET  -         100   enabled  online
                   e0b ENET  -         100   enabled  online
cluster1-02
                   e0a ENET  -         100   enabled  online
                   e0b ENET  -         100   enabled  online
.
.
----
====

. Verify that all the storage shelf ports are up with a healthy status: 
+
[source,cli]
----
storage shelf port show
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
4 entries were displayed.
----
====

. Verify that the switches are being monitored.  
+
[source,cli]
----
system switch ethernet show
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *system switch ethernet show*
  Switch               Type               Address          Model
  -------------------- ------------------ ---------------- ---------------
  s1                   cluster-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
s2                   cluster-network      2.3.4.5           N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====

== Step 2: Upgrade the RCF

. On switch s1, shut down the ports connected to all the ports of the nodes.
+

[subs=+quotes]
----
s1> *enable*
s1# *configure*
s1(config)# *interface eth1/1/1-12*
s1(config-if-range)# *shutdown*
s1(config-if-range)# *exit*
s1(config)# *exit*
----
+
CAUTION: Make sure to shutdown *all* connected ports to avoid any network connection issues.
See the Knowledge Base article https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade[Node out of quorum when migrating cluster LIF during switch OS upgrade^] for further details. 

. Log in to the switch using SSH or by using a serial console.

. If you have not already done so, save a copy of the current switch configuration by copying the output of the following command to a text file:
+

`show running-config`

.. Record any custom additions between the current `running-config` and the RCF file in use (such as an SNMP configuration for your organization).  
+
.. For NX-OS 10.2 and later, use the `show diff running-config` command to compare with the saved RCF file in the bootflash.  Otherwise, use a third-party diff or compare tool.

. Save basic configuration details to the `write_erase.cfg` file on the bootflash.
+
[NOTE]
====================================
Make sure to configure the following:

* Username and password
* Management IP address
* Default gateway
* Switch name
====================================
+
`s1# show run | section "switchname" > bootflash:write_erase.cfg`
+
`s1# show run | section "hostname" >> bootflash:write_erase.cfg`
+
`s1# show run | i "username admin password" >> bootflash:write_erase.cfg`
+
`s1# show run | section "vrf context management" >> bootflash:write_erase.cfg`
+
`s1# show run | section "interface mgmt0" >> bootflash:write_erase`
. When upgrading to RCF version 1.12 and later, run the following commands:
+
`s1# echo "hardware access-list tcam region racl-lite 512" >> bootflash:write_erase.cfg`
+
`s1# echo "hardware access-list tcam region qos 256" >> bootflash:write_erase.cfg`
+ 
See the Knowledge Base article link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity[How to clear configuration on a Cisco interconnect switch while retaining remote connectivity^] for further details.

. Verify that the `write_erase.cfg` file is populated as expected:
+
`*show file bootflash:write_erase.cfg*`

. Issue the `write erase` command to erase the current saved configuration:
+
`s1# *write erase*`
+
`Warning: This command will erase the startup-configuration.`
+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copy the previously saved basic configuration into the startup configuration.
+
`s1# *copy bootflash:write_erase.cfg startup-config*`

. Reboot the switch:
+
`s1# *reload*`
+
`This command will reboot the system. (y/n)?  [n] *y*`

. After the management IP address is reachable again, log in to the switch through SSH.
+
You might need to update host file entries related to the SSH keys.

. Copy the RCF to the bootflash of switch s1 using one of the following transfer protocols: FTP, TFTP, SFTP, or SCP. 
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.
+
.Show example 
[%collapsible]
====
This example shows TFTP being used to copy an RCF to the bootflash on switch s1:

[subs=+quotes]
----
s1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9336C-FX2-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====

. Apply the RCF previously downloaded to the bootflash.
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.

+
This example shows the RCF file `NX9336C-FX2-RCF-v1.13-1-Storage.txt` being installed on switch s1:
+

[subs=+quotes]
----
s1# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----

+
[CAUTION]
=======
Make sure to thoroughly read the *Installation notes*, *Important Notes*, and *banner* sections of your RCF. You must read and follow these instructions to ensure the proper configuration and operation of the switch.
=======

. Verify that the RCF file is the correct newer version: 
+
`show running-config`
+
When you check the output to verify you have the correct RCF, make sure that the following information is correct:

 ** The RCF banner
 ** The node and port settings
 ** Customizations
+
The output varies according to your site configuration. Check the port settings and refer to the release notes for any changes specific to the RCF that you have installed.

. Reapply any previous customizations to the switch configuration.

. After you verify the RCF versions, custom additions, and switch settings are correct, copy the `running-config` file to the `startup-config` file.
+
For more information on Cisco commands, see the appropriate guide in the https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences[Cisco Nexus 9000 Series NX-OS Command Reference^] guides.
+

`s1# *copy running-config startup-config*` 
+
`[########################################] 100% Copy complete` 

. Reboot switch s1. You can ignore the "`cluster switch health monitor`" alerts and "`cluster ports down`" events reported on the nodes while the switch reboots.
+

`s1# *reload*` 
+
`This command will reboot the system. (y/n)?  [n] *y*` 

. Verify that all the storage ports are up with a healthy status: 
+
[source,cli]
----
storage port show -port-type ENET
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e0a  ENET  -          100 enabled  online
                   e0b  ENET  -          100 enabled  online
cluster1-02
                   e0a  ENET  -          100 enabled  online
                   e0b  ENET  -          100 enabled  online
.
.
----
====

. Verify that all the storage shelf ports are up with a healthy status:
+
[source,cli]
----
storage shelf port show 
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
4 entries were displayed.
----
====

. Verify that the switches are being monitored:
+
[source,cli]
----
system switch ethernet show
----
+
.Show example 
[%collapsible]
====

[subs=+quotes]
----
cluster1::> *system switch ethernet show*
  Switch              Type               Address          Model
  ------------------- ------------------ ---------------- ---------------
s1                    cluster-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
s2                    cluster-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====

. Repeat steps 1 to 19 on switch s2.

== Step 3: Verify the storage network

. Verify that the switch ports connected to the cluster ports are *up*.
+
[source,cli]
----
show interface brief
----

. Verify that the expected node storage ports are still connected:
+
[source,cli]
----
show cdp neighbors
----

. Verify that the expected storage shelf ports are still connected:
+
[source,cli]
----
show lldp neighbors
----

. Verify that the node storage ports and storage shelf ports are in their correct VLANs using the following commands:
+
[source,cli]
----
show vlan brief
----
+
[source,cli]
----
show interface trunk
----

.What's next?

After you've upgraded your RCF, you can link:configure-ssh-keys.html[verify the SSH configuration].

// AFFFASDOC-289, 2025-NOV-05
// AFFFASDOC-458, 2026-FEB-03