---
permalink: switch-netapp-cn1610/migrate-overview.html
sidebar: sidebar
keywords: migrate, two-node switched cluster, netapp cn1610
summary: "Review the migration options for moving from a two-node switchless cluster to a switched cluster using NetApp CN1610 cluster switches."
---
= Review migration options for NetApp CN1610 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
Review the migration options for moving from a two-node switchless cluster to a switched cluster using NetApp CN1610 cluster switches. The procedure depends on whether you have two dedicated cluster-network ports or a single cluster port on each controller.

Most systems require two dedicated cluster-network ports on each controller.

FAS22xx nodes allow a single cluster port on each controller.

There are two migration options available:

* link:migrate-switched-netapp-cn1610.html[Migrate from a switchless cluster to a switched NetApp CN1610 cluster environment]
* link:migrate-fas22xx-systems.html[Migrate from a switchless cluster (FAS22xx systems with a single cluster-network connection)]
