---
permalink: switch-netapp-cn1610/migrate-overview.html
sidebar: sidebar
keywords: migrate, two-node switched cluster, netapp cn1610
summary: "If you have a two-node switchless cluster, you can migrate, non-disruptively, to a two-node switched cluster that includes NetApp CN1610 cluster-network switches. The procedure you use depends on whether you have two dedicated cluster-network ports on each controller or a single cluster port on each controller."
---
= Migration options for a two-node switched cluster with NetApp CN1610 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
If you have a two-node switchless cluster, you can migrate, non-disruptively, to a two-node switched cluster that includes NetApp CN1610 cluster-network switches. The procedure you use depends on whether you have two dedicated cluster-network ports on each controller or a single cluster port on each controller.

Most systems require two dedicated cluster-network ports on each controller.

FAS22xx nodes allow a single cluster port on each controller.

There are two migration options available:

* link:migrate-switched-netapp-cn1610.html[Migrate from a switchless cluster to a switched NetApp CN1610 cluster environment]
* link:migrate-fas22xx-systems.html[Migrate from a switchless cluster (FAS22xx systems with a single cluster-network connection)]
