---
permalink: switch-netapp-cn1610/prepare-install-fastpath-rcfs.html
sidebar: sidebar
keywords: install, fastpath, software, rcfs, netapp cluster switch
summary: "You must install the FASTPATH software and reference configuration files (RCFs) on a NetApp CN1610 cluster switch."
---
= Prepare to install FASTPATH software and RCFs on a NetApp cluster switch
:icons: font
:imagesdir: ../media/

[.lead]
You must install the FASTPATH software and reference configuration files (RCFs) on a NetApp CN1610 cluster switch.

.Before you begin

* The cluster must be a fully functioning cluster.
* There must be no defective cluster network interface cards (NICs), and all connected ports on the cluster switch must be functional.
* All cluster ports must be up.
* All cluster logical interfaces (LIFs) must be up and must not have been migrated.
* The ONTAP (privilege: advanced) `cluster ping-cluster -node node1` command must indicate that `larger than PMTU communication` is successful on all paths.

* You must consult the switch compatibility table on the http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/[NetApp CN1601 and CN1610 Switches^] page for the supported FASTPATH, RCF, and ONTAP versions.
+
There can be command dependencies between command syntax in the RCF and FASTPATH versions.

NOTE: In RCF version 1.2, support for Telnet has been explicitly disabled because of security concerns. To avoid connectivity issues while installing RCF 1.2, you must verify that Secure Shell (SSH) is enabled. The https://library.netapp.com/ecm/ecm_get_file/ECMP1117874[NetApp® CN1610 Switch Administrator's Guide^] has more information about SSH.


.About this task
The examples in this procedure use the following switch and node nomenclature:

* The procedures in this document use the clustered Data ONTAP 8.2 syntax. As a result, the cluster Vserver, LIF names, and CLI output will be different than those in Data ONTAP 8.3.
* The two NetApp switches are cs1 and cs2.
* The two cluster LIFs are clus1 and clus2.
* The Vservers are vs1 and vs2.
* The `cluster::*>` prompt indicates the name of the cluster.
* The cluster ports on each node are named e1a and e2a.
+

The https://hwu.netapp.com/[Hardware Universe^] has more information about the actual cluster ports that are supported on your platform.

* The Inter-Switch Links (ISLs) that are supported for the NetApp cluster switch are ports 0/13 through 0/16.
* The node connections that are supported for the NetApp cluster switch are ports 0/1 through 0/12.

This procedure has two parts:

* link:install-fastpath-software.html[Install FASTPATH software] describes how to install the FASTPATH software.
* link:install-rcf-file.html[Install an RCF on a CN1610 switch] describes how to install RCFs.

// GH issue #340 internal repo, 2025-SEPT-18
