---
permalink: switch-netapp-cn1610/required-documentation-cn1610.html
sidebar: sidebar
keywords: cn1610, switch, netapp
summary: For NetApp CN1610 switch installation and maintenance, be sure to review all the recommended documentation. 
---
= Documentation requirements for NetApp CN1610 switches 
:icons: font
:imagesdir: ../media/

[.lead]
For NetApp CN1610 switch installation and maintenance, be sure to review all the recommended documentation. 

[options="header" cols="1,2"]
|===
| Document title| Description
a|
_https://library.netapp.com/ecm/ecm_download_file/ECMP1117853[1G Installation Guide^]_
a|
An overview of the CN1601 switch hardware and software features and installation process.
a|
https://library.netapp.com/ecm/ecm_download_file/ECMP1117824[10G Installation Guide^]
a|
An overview of the CN1610 switch hardware and software features and describes the features to install the switch and access the CLI.
a|
https://library.netapp.com/ecm/ecm_download_file/ECMP1118645[CN1601 and CN1610 Switch Setup and Configuration Guide^]
a|
Details how to configure the switch hardware and software for your cluster environment.
a|
_CN1601 Switch Administrator's Guide_ 
a|
Provides examples of how to use the CN1601 switch in a typical network.

* https://library.netapp.com/ecm/ecm_download_file/ECMP1117844[Administrator's Guide^]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2811865[Administrator's Guide, Version 1.1.x.x^]
* https://library.netapp.com/ecm/ecm_download_file/ECMP1117874[Administrator's Guide, Version 1.2.x.x^]
a|
_CN1610 Network Switch CLI Command Reference_ 
a|
Provides detailed information about the command-line interface (CLI) commands you use to configure the CN1601 software.

* https://library.netapp.com/ecm/ecm_download_file/ECMP1117834[Command Reference^]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2811863[Command Reference, Version 1.1.x.x^]
* https://library.netapp.com/ecm/ecm_download_file/ECMP1117863[Command Reference, Version 1.2.x.x^]
|===

