---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html
sidebar: sidebar
keywords: install, fastpath, software, rcfs
summary: Before configuring NetApp CN1610 switches, review the procedure overview.
---
= Overview of installation and configuration for NetApp CN1610 switches
:icons: font
:imagesdir: ../media/

[.lead]
The CN1610 is a high bandwidth, managed Layer 2 switch that provides 16 10-Gigabit Small Form-Factor Pluggable Plus (SFP+) ports. 

The switch includes redundant power supplies and fan trays that support hot swapping for high availability. This 1U switch can be installed in a standard 19-inch NetApp 42U system cabinet or third-party cabinet.

The switch supports local management through the console port or remote management by using Telnet or SSH through a network connection. The CN1610 includes a dedicated 1-Gigabit Ethernet RJ45 management port for out-of-band switch management. You can manage the switch by entering commands into the command-line interface (CLI) or by using an SNMP-based network management system (NMS).
