---
permalink: switch-netapp-cn1610/task-migrate-to-a-two-node-switched-cluster-with-netapp-cn1610-cluster-switches.html
sidebar: sidebar
keywords: migrate, two-node switched cluster, netapp cn1610
summary: "If you have a two-node switchless cluster, you can migrate, non-disruptively, to a two-node switched cluster that includes NetApp CN1610 cluster-network switches. The procedure you use depends on whether you have two dedicated cluster-network ports on each controller or a single cluster port on each controller."
---
= Migrate to a two-node switched cluster with NetApp CN1610 cluster switches
:icons: font
:imagesdir: ../media/

[.lead]
If you have a two-node switchless cluster, you can migrate, non-disruptively, to a two-node switched cluster that includes NetApp CN1610 cluster-network switches. The procedure you use depends on whether you have two dedicated cluster-network ports on each controller or a single cluster port on each controller.

.About this task

Most systems require two dedicated cluster-network ports on each controller.

FAS22xx nodes allow a single cluster port on each controller.

There are two migration options available:

* link:task-migrate-from-a-switchless-cluster-to-a-switched-netapp-cn1610-cluster-environment.html[Migrate from a switchless cluster to a switched NetApp CN1610 cluster environment]
* xref:task-migrate-from-a-switchless-cluster-fas22xx-systems-with-a-single-cluster-network-connection.adoc[Migrate from a switchless cluster (FAS22xx systems with a single cluster-network connection)]
