---
permalink: switch-netapp-cn1610/task-migrate-from-a-switchless-cluster-to-a-switched-netapp-cn1610-cluster-environment.html
sidebar: sidebar
keywords: migrate, switchless cluster environment, switched netapp cn1610
summary: "If you have an existing two-node switchless cluster environment, you can migrate to a two-node switched cluster environment using CN1610 cluster network switches that enables you to scale beyond two nodes."
---
= Migrate from a switchless cluster environment to a switched NetApp CN1610 cluster environment
:icons: font
:imagesdir: ../media/

[.lead]
If you have an existing two-node switchless cluster environment, you can migrate to a two-node switched cluster environment using CN1610 cluster network switches that enables you to scale beyond two nodes.

== What you'll need

Two-node switchless configuration:

* The two-node switchless configuration must be properly set up and functioning.
* The nodes must be running ONTAP 8.2 or later.
* All cluster ports must be in the `up` state.
* All cluster logical interfaces (LIFs) must be in the `up` state and on their home ports.

CN1610 cluster switch configuration:

* The CN1610 cluster switch infrastructure must be and fully functional on both switches.
* Both switches must have management network connectivity.
* There must be console access to the cluster switches.
* CN1610 node-to-node switch and switch-to-switch connections must use twinax or fiber cables.
+
The link:https://hwu.netapp.com/Switch/Index[Hardware Universe^] contains more information about cabling.

* Inter-Switch Link (ISL) cables must be connected to ports 13 through 16 on both CN1610 switches.
* Initial customization of both the CN1610 switches must be completed.
+
Any previous site customization, such as SMTP, SNMP, and SSH should be copied to the new switches.

== About this task

The examples in this procedure use the following cluster switch and node nomenclature:

* The names of the CN1610 switches are cs1 and cs2.
* The names of the LIFs are clus1 and clus2.
* The names of the nodes are node1 and node2.
* The `cluster::*>` prompt indicates the name of the cluster.
* The cluster ports used in this procedure are e1a and e2a.
+
The link:https://hwu.netapp.com/[Hardware Universe^] contains the latest information about the actual cluster ports for your platforms.

== Steps

. Change the privilege level to advanced, entering `y` when prompted to continue: `set -privilege advanced`
+
The advanced prompt (*>) appears.

. If AutoSupport is enabled on this cluster, suppress automatic case creation by invoking an AutoSupport message: `system node autosupport invoke -node * -type all -message MAINT=xh`
+
_x_ is the duration of the maintenance window in hours.
+
[NOTE]
====
The AutoSupport message notifies technical support of this maintenance task so that automatic case creation is suppressed during the maintenance window.
====
+
The following command suppresses automatic case creation for two hours:
+
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----

. Disable all of the node-facing ports (not ISL ports) on both the new cluster switches cs1 and cs2.
+
You must not disable the ISL ports.
+
The following example shows that node-facing ports 1 through 12 are disabled on switch cs1:
+
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
+
The following example shows that node-facing ports 1 through 12 are disabled on switch cs2:
+
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----

. Verify that the ISL and the physical ports on the ISL between the two CN1610 cluster switches cs1 and cs2 are `up`: `show port-channel`
+
The following example shows that the ISL ports are `up` on switch cs1:
+
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
+
The following example shows that the ISL ports are `up` on switch cs2:
+
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----

. Display the list of neighboring devices: `show isdp neighbors`
+
This command provides information about the devices that are connected to the system.
+
The following example lists the neighboring devices on switch cs1:
+
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
+
The following example lists the neighboring devices on switch cs2:
+
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----

. Display the list of cluster ports: `network port show`
+
The following example shows the available cluster ports:
+
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----

. Verify that each cluster port is connected to the corresponding port on its partner cluster node: `run * cdpd show-neighbors`
+
The following example shows that cluster ports e1a and e2a are connected to the same port on their cluster partner node:
+
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----

. Verify that all of the cluster LIFs are `up` and operational: `network interface show -vserver Cluster`
+
Each cluster LIF should display `true` in the "`Is Home`" column.
+
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
+
[NOTE]
====
The following modification and migration commands in steps 10 through 13 must be done from the local node.
====

. Verify that all cluster ports are `up`: `network port show -ipspace Cluster`
+
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----

. Set the `-auto-revert` parameter to `false` on cluster LIFs clus1 and clus2 on both nodes: `network interface modify`
+
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
+
[NOTE]
====
For release 8.3 and later, use the following command: `network interface modify -vserver Cluster -lif * -auto-revert false`
====

. Ping the cluster ports to verify the cluster connectivity: `cluster ping-cluster local`
+
The command output shows connectivity between all of the cluster ports.

. Migrate clus1 to port e2a on the console of each node: `network interface migrate`
+
The following example shows the process for migrating clus1 to port e2a on node1 and node2:
+
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
+
[NOTE]
====
For release 8.3 and later, use the following command: `network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a`
====

. Verify that the migration took place: `network interface show -vserver Cluster`
+
The following example verifies that clus1 is migrated to port e2a on node1 and node2:
+
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----

. Shut down cluster port e1a on both nodes: `network port modify`
+
The following example shows how to shut down the port e1a on node1 and node2:
+
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----

. Verify the port status: `network port show`
+
The following example shows that port e1a is `down` on node1 and node2:
+
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----

. Disconnect the cable from cluster port e1a on node1, and then connect e1a to port 1 on cluster switch cs1, using the appropriate cabling supported by the CN1610 switches.
+
The link:https://hwu.netapp.com/Switch/Index[Hardware Universe^] contains more information about cabling.

. Disconnect the cable from cluster port e1a on node2, and then connect e1a to port 2 on cluster switch cs1, using the appropriate cabling supported by the CN1610 switches.
. Enable all of the node-facing ports on cluster switch cs1.
+
The following example shows that ports 1 through 12 are enabled on switch cs1:
+
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----

. Enable the first cluster port e1a on each node: `network port modify`
+
The following example shows how to enable the port e1a on node1 and node2:
+
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----

. Verify that all of the cluster ports are `up`: `network port show -ipspace Cluster`
+
The following example shows that all of the cluster ports are `up` on node1 and node2:
+
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----

. Revert clus1 (which was previously migrated) to e1a on both nodes: `network interface revert`
+
The following example shows how to revert clus1 to the port e1a on node1 and node2:
+
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
+
[NOTE]
====
For release 8.3 and later, use the following command: `network interface revert -vserver Cluster -lif <nodename_clus<N>>`
====

. Verify that all of the cluster LIFs are `up`, operational, and display as `true` in the "Is Home" column: `network interface show -vserver Cluster`
+
The following example shows that all of the LIFs are `up` on node1 and node2 and that the "Is Home" column results are `true`:
+
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----

. Display information about the status of the nodes in the cluster: `cluster show`
+
The following example displays information about the health and eligibility of the nodes in the cluster:
+
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----

. Migrate clus2 to port e1a on the console of each node: `network interface migrate`
+
The following example shows the process for migrating clus2 to port e1a on node1 and node2:
+
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
+
[NOTE]
====
For release 8.3 and later, use the following command: `network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a`
====

. Verify that the migration took place: `network interface show -vserver Cluster`
+
The following example verifies that clus2 is migrated to port e1a on node1 and node2:
+
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----

. Shut down cluster port e2a on both nodes: `network port modify`
+
The following example shows how to shut down the port e2a on node1 and node2:
+
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----

. Verify the port status: `network port show`
+
The following example shows that port e2a is `down` on node1 and node2:
+
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----

. Disconnect the cable from cluster port e2a on node1, and then connect e2a to port 1 on cluster switch cs2, using the appropriate cabling supported by the CN1610 switches.
. Disconnect the cable from cluster port e2a on node2, and then connect e2a to port 2 on cluster switch cs2, using the appropriate cabling supported by the CN1610 switches.
. Enable all of the node-facing ports on cluster switch cs2.
+
The following example shows that ports 1 through 12 are enabled on switch cs2:
+
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----

. Enable the second cluster port e2a on each node:
+
The following example shows how to enable the port e2a on node1 and node2:
+
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----

. Verify that all of the cluster ports are `up`: `network port show -ipspace Cluster`
+
The following example shows that all of the cluster ports are `up` on node1 and node2:
+
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----

. Revert clus2 (which was previously migrated) to e2a on both nodes: `network interface revert`
+
The following example shows how to revert clus2 to the port e2a on node1 and node2:
+
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
+
[NOTE]
====
For release 8.3 and later, the commands are:

 cluster::*> network interface revert -vserver Cluster -lif node1_clus2
 cluster::*> network interface revert -vserver Cluster -lif node2_clus2

====

. Verify that all of the interfaces display `true` in the "Is Home" column: `network interface show -vserver Cluster`
+
The following example shows that all of the LIFs are `up` on node1 and node2 and that the "Is Home" column results are `true`:
+
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----

. Ping the cluster ports to verify the cluster connectivity: `cluster ping-cluster local`
+
The command output shows connectivity between all of the cluster ports.

. Verify that both nodes have two connections to each switch: `show isdp neighbors`
+
The following example shows the appropriate results for both switches:
+
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----

. Display information about the devices in your configuration: `network device discovery show`
. Disable the two-node switchless configuration settings on both nodes using the advanced privilege command: `network options detect-switchless modify`
+
The following example shows how to disable the switchless configuration settings:
+
----

cluster::*> network options detect-switchless modify -enabled false
----
+
[NOTE]
====
For release 9.2 and later, skip this step since the configuration is automatically converted.
====

. Verify that the settings are disabled: `network options detect-switchless-cluster show`
+
The `false` output in the following example shows that the configuration settings are disabled:
+
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
+
[NOTE]
====
For release 9.2 and later, wait until 'Enable Switchless Cluster' is set to false. This can take up to three minutes.
====

. Configure clusters clus1 and clus2 to auto revert on each node and confirm:
+
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
+
[NOTE]
====
For release 8.3 and later, use the following command: `network interface modify -vserver Cluster -lif * -auto-revert true` to enable auto-revert on all nodes in the cluster.
====

. Verify the status of the node members in the cluster: `cluster show`
+
The following example shows information about the health and eligibility of the nodes in the cluster:
+
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----

. If you suppressed automatic case creation, reenable it by invoking an AutoSupport message:
+
`system node autosupport invoke -node * -type all -message MAINT=END`
+
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----

. Change the privilege level back to admin: `set -privilege admin`

*Related information*

http://hwu.netapp.com[Hardware Universe^]

http://support.netapp.com/NOW/download/software/cm_switches_ntap/[NetApp CN1601 and CN1610 description page^]

https://library.netapp.com/ecm/ecm_download_file/ECMP1118645[CN1601 and CN1610 Switch Setup and Configuration Guide^]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows[NetApp KB Article 1010449: How to suppress automatic case creation during scheduled maintenance windows^]
