---
permalink: getting-started/learn-switch-concept.html
sidebar: sidebar
keywords:
summary: Learn about cluster, storage, and shared switches.
---
= Learn about Cluster, Storage, and Shared switches
:icons: font
:imagesdir: ../media/

[.lead]
NetApp offers "front-end" switches that provide connectivity to host storage and "back-end" cluster switches. 

These switches provide connections between two or more NetApp FAS/AFF controllers to deliver internal communications and the ability to non-disruptively move data and network interfaces across the cluster.

== Cluster switches
Cluster switches allow you to build ONTAP clusters with more than two nodes. NetApp-supported cluster switches include:

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2
* Cisco Nexus 92300YC
* Cisco Nexus 3132Q-V
* Cisco Nexus 3232C
* NetApp CN1610
* NVIDIA SN2100

== Storage switches
Storage switches allow you to route data between servers and storage arrays in a Storage Area Network (SAN). NetApp-supported cluster switches include:

* Cisco Nexus 9336C-FX2
* NVIDIA SN2100

== Shared switches
Shared switches allow you to combine cluster and storage functionality into a shared switch configuration, by supporting the use of shared cluster and storage RCFs. The NetApp-supported shared switch is:

* Cisco Nexus 9336C-FX2