---
permalink: get-started/learn-switch-concept.html
sidebar: sidebar
keywords:
summary: Learn about cluster, storage, and shared switches.
---
= Learn about Cluster, Storage, and Shared switches
:icons: font
:imagesdir: ../media/

[.lead]
NetApp offers cluster, storage, and shared switches that deliver internal communications with the ability to non-disruptively move data and network interfaces across the cluster.

The “front-end” switches provide connectivity to host storage, while the “back-end” cluster switches provide connections between two or more NetApp controllers. 

NOTE: Only NetApp-validated back-end switches (ordered from NetApp) are supported.


== Cluster switches
Cluster switches allow you to build ONTAP clusters with more than two nodes. NetApp-supported cluster switches include:

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2
* NVIDIA SN2100

== Storage switches
Storage switches allow you to route data between servers and storage arrays in a Storage Area Network (SAN). NetApp-supported storage switches include:

* Cisco Nexus 9336C-FX2
* NVIDIA SN2100

== Shared switches
Shared switches allow you to combine cluster and storage functionality into a shared switch configuration, by supporting the use of shared cluster and storage RCFs. The NetApp-supported shared switch is:

* Cisco Nexus 9336C-FX2

== End-of-availability
The following storage switches are no longer available for purchase, but are still supported:

*	Cisco Nexus 3232C
*	Cisco Nexus 3132Q-V
*	Cisco Nexus 92300YC
*	NetApp CN1610


// Corrected cluster -> storage line 33 as per PR on external repo (203), 2024-AUG-20