---
permalink: other-procedures/transition-to-two-node-switchless-cluster-index.html
sidebar: sidebar
keywords: transition, switchless, cluster, two, node
summary: You can transition to a two-node cluster that uses cluster interconnect switches to one where two nodes are directly connected.
---

= Overview
:icons: font
:imagesdir: ../media/

If you have an existing two-node cluster that uses cluster interconnect switches and is running ONTAP 9.3 or later, you can replace the switches with direct, back-to-back connections between the nodes.

.About this task

You cannot use the switchless cluster interconnect feature with more than two nodes.

Transitioning to a two-node switchless cluster configuration is a nondisruptive operation. Most systems have two dedicated cluster interconnect ports on each node, but you can also use this procedure for systems with a larger number of dedicated cluster interconnect ports on each node, such as four, six or eight.

This procedure describes transitioning a cluster with a switched cluster network to one where two nodes are directly connected for ONTAP 9.3 and later.
