---
permalink: switch-cisco-92300/92300-overview.html
sidebar: sidebar
keywords: cisco nexus 92300YC
summary: If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.
---
= Cisco Nexus 92300YC switch overview
:icons: font
:imagesdir: ../media/

[.lead]
If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.

You can install the Cisco Nexus 92300YC switch (X190003/R) in a NetApp system cabinet or third-party cabinet with the standard brackets that are included with the switch.

The following table lists the part number and description for the 92300YC switch, fans, and power supplies:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
190003
a|
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = Port Side Exhaust)
a|
190003R
a|
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = Port Side Intake)
a|
X-NXA-FAN-35CFM-B
a|
Fan, Cisco N9K port side intake airflow
a|
X-NXA-FAN-35CFM-F
a|
Fan, Cisco N9K port side exhaust airflow
a|
X-NXA-PAC-650W-B
a|
Power supply, Cisco 650W - port side intake
a|
X-NXA-PAC-650W-F
a|
Power supply, Cisco 650W - port side exhaust
|===

Cisco Nexus 92300YC switch airflow details:

 ** Port-side exhaust airflow (standard air) --Cool air enters the chassis through the fan and power supply modules in the cold aisle and exhausts through the port end of the chassis in the hot aisle. Port-side exhaust airflow with blue coloring.
 ** Port-side intake airflow (reverse air) --Cool air enters the chassis through the port end in the cold aisle and exhausts through the fan and power supply modules in the hot aisle. Port-side intake airflow with burgundy coloring.

.Available documentation
The following table lists the documentation available for the Cisco Nexus 92300YC switches.
["options="header"]
|===
| Title| Description
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html[_Setup the Cisco® Nexus 92300YC cluster switches_^]
a| Describes how to setup and configure your Cisco Nexus 92300YC cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html[_Install NX-OS and Reference Configuration Files (RCFs)_^]
a|
Describes how to install NX-OS and reference configuration files (RCFs) on Nexus 92300YC cluster switch.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html[_Configure a new Cisco Nexus 92300YC Switch_^]
a|
Describes how to migrate from environments that use older Cisco switches to environments that use Cisco 92300YC switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc-overview.html[_Migrate from an older Cisco Switch to a Cisco Nexus 92300YC Switch_^]
a|
Describes the procedure to replace an older Cisco switch with a Cisco Nexus 92300YC cluster switch.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html[_Migrate from a two-node Switchless Cluster_^]
a|
Describes how to migrate from a two-node switchless cluster environment to a two-node switched environment using Cisco Nexus 92300YC cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html[_Replace a Cisco Nexus 92300YC Cluster Switch_^]
a|
Describes the procedure to replace a defective Cisco Nexus 92300YC switch in a cluster and download the switch operating system and reference configuration file.
|===
