---
permalink: switch-cisco-92300/components-92300.html
sidebar: sidebar
keywords: cisco nexus 92300YC
summary: If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.
---
= Components and part numbers for Cisco Nexus 92300YC switches
:icons: font
:imagesdir: ../media/

[.lead]
For Cisco Nexus 92300YC switch installation and maintenance, be sure to review all switch components and part numbers. See the https://hwu.netapp.com/SWITCH/INDEX[Hardware Universe^] for details.

The following table lists the part number and description for the 92300YC switch, fans, and power supplies:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
190003
a|
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = Port Side Exhaust)
a|
190003R
a|
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = Port Side Intake)
a|
X-NXA-FAN-35CFM-B
a|
Fan, Cisco N9K port side intake airflow
a|
X-NXA-FAN-35CFM-F
a|
Fan, Cisco N9K port side exhaust airflow
a|
X-NXA-PAC-650W-B
a|
Power supply, Cisco 650W - port side intake
a|
X-NXA-PAC-650W-F
a|
Power supply, Cisco 650W - port side exhaust
|===

Cisco Nexus 92300YC switch airflow details:

 ** Port-side exhaust airflow (standard air) -- Cool air enters the chassis through the fan and power supply modules in the cold aisle and exhausts through the port end of the chassis in the hot aisle. Port-side exhaust airflow with blue coloring.
 ** Port-side intake airflow (reverse air) -- Cool air enters the chassis through the port end in the cold aisle and exhausts through the fan and power supply modules in the hot aisle. Port-side intake airflow with burgundy coloring.

.What's next
After you've confirmed your components and part numbers, you can review the link:required-documentation-92300.html[required documentation].

// Updates for AFFFASDOC-370, 2025-JUL-29
