---
permalink: switch-cisco-92300/configure-reqs-92300.html
sidebar: sidebar
keywords: cisco nexus 92300YC
summary: If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.
---
= Configuration requirements for Cisco Nexus 92300YC switches
:icons: font
:imagesdir: ../media/

[.lead]
For Cisco Nexus 92300YC switch installation and maintenance, be sure to review all configuration and network requirements. 

If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.

== Configuration requirements

To configure your cluster, you need the appropriate number and type of cables and cable connectors for your switches. Depending on the type of switch you are initially configuring, you need to connect to the switch console port with the included console cable; you also need to provide specific network information.

== Network requirements

You need the following network information for all switch configurations:

* IP subnet for management network traffic
* Host names and IP addresses for each of the storage system controllers and all applicable switches
* Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon). On AFF A800 and AFF A700 systems, the e0M interface uses a dedicated Ethernet port.

Refer to the https://hwu.netapp.com[Hardware Universe^] for latest information.

.What's next

link:components-92300.html[Components and part numbers].

// Updates for AFFFASDOC-370, 2025-JUL-29