---
permalink: switch-cisco-92300/install-overview-cisco-92300.html
sidebar: sidebar
keywords: install, cisco nexus 92300 switch,
summary: 'Before configuring Cisco Nexus 92300 switches, review an overview of the process and the nomenclature.'
---
= Overview of configuration process for Cisco Nexus 92300 switches
:icons: font
:imagesdir: ../media/

[.lead]
Before configuring Cisco Nexus 92300 switches, review the requirements and the procedure overview.

== Requirements
Be sure to review the link:index.html[Overview and requirements].

== Procedure overview

To initially configure a Cisco Nexus 92300 switch on systems running ONTAP, follow these steps:

. link:setup_worksheet_92300yc[Complete cabling worksheet].
. link:configure-install-initial.html[Configure the switch].
. link:install-nxos-overview.html[Prepare to install NX-OS software and Reference Configuration file].
. link:install-nxos-software.html[Install the NX-OS software].
. link:install-the-rcf-file.html[Install the Reference Configuration File (RCF)].
. link:setup-install-cshm-file.html[Install the Cluster Switch Health Monitor (CSHM) configuration file ].
