---
permalink: switch-cshm/config-snmpv3.html
sidebar: sidebar
keywords: cshm, configure, snmpv3, switch logs, debugging, collection
summary: "Configure SNMPv3 on your network switches to enable secure communication with the Ethernet switch health monitor (CSHM)."
---
= Configure SNMPv3 for Ethernet switch health monitoring
:icons: font
:imagesdir: ../media/

[.lead]
Configure SNMPv3 on your network switches to enable secure, authenticated communication with the Ethernet switch health monitor (CSHM). SNMPv3 provides encrypted polling of switch status for health monitoring in ONTAP. 

The Ethernet Switch Health Monitor (CSHM) utilizes SNMP to monitor the health and performance of network switches. By default, SNMPv2c is configured automatically through the Reference Configuration File (RCF). SNMPv3 is more secure than SNMPv2 because it introduces robust security features such as authentication, encryption, and message integrity, which protect against unauthorized access and ensure data confidentiality and integrity during transmission.

include::../_include/configure-snmpv3-switches.adoc[]

// AFFFASDOC-476, 2026-MAR-30