---
permalink: switch-cshm/config-log-collection.html
sidebar: sidebar
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation
summary: "Configure log collection to enable CSHM to gather switch logs and diagnostic data from cluster and storage network switches."
---
= Configure CSHM log collection 
:icons: font
:imagesdir: ../media/

[.lead]
Configure log collection on your Ethernet switches to enable the Ethernet switch health monitor (CSHM) to gather switch logs for debugging and AutoSupport reporting. This procedure sets up both on-demand support log collection and hourly periodic data collection in ONTAP.

include::../_include/configure-log-collection.adoc[]

CAUTION: If any error statuses are reported by the log collection feature (visible in the output of `system switch ethernet log show`), refer to link:log-collection-troubleshoot.html[Troubleshoot log collection] for further details.

.What's next?
link:config-snmpv3.html[Configure SNMPv3 (Optional)].

// Link to KBs for log collection (need to update)
// Update from AClose (see Teams), 2024-SEP-17
// Updates for GH issue #228, 2024-DEC-04
// Updates for AFFFASDOC-295, 2025-FEB-12
// Updates for GH issue #254, 2025-APR-10
// Updates for GH issue #269, 2025-MAY-28
// AFFFASDOC-473, 2026-MAR-18