---
permalink: switch-nvidia-sn2100-storage/components-sn2100-storage.html
sidebar: sidebar
keywords: nvidia SN2100 switches
summary: For NVIDIA SN2100 switch installation and maintenance, be sure to review the list of components and part numbers for the cabinet and rail kit. 
---
= Components and part numbers for NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
For NVIDIA SN2100 switch installation and maintenance, be sure to review the list of components and part numbers for the cabinet and rail kit. 

== Cabinet details
You install the NVIDIA SN2100 switch (X190006/X190106) in the NVIDIA dual/single switch cabinet with the standard brackets that are included with the switch.

== Rail kit details

The following table lists the part number and description for the MSN2100 switches and rail kits:

[options="header" cols="1,2"]
|===
| Part number| Description
a|
X190006-PE
a|
Cluster Switch, NVIDIA SN2100, 16PT 100G, PTSX
a|
X190006-PI
a|
Cluster Switch, NVIDIA SN2100, 16PT 100G, PSIN
a|
X190106-FE-PE
a|
Switch, NVIDIA SN2100, 16PT 100G, PTSX, Front End
a|
X190106-FE-PI
a|
Switch, NVIDIA SN2100, 16PT 100G, PSIN, Front End
a|
X-MTEF-KIT-D
a|
Rail Kit, NVIDIA Dual switch side by side
a|
X-MTEF-KIT-E
a|
Rail Kit, NVIDIA Single switch short depth
|===

NOTE: See NVIDIA documentation for details on https://docs.nvidia.com/networking/display/sn2000pub/Installation[installing your SN2100 switch and rail kit^].

.What's next
link:required-documentation-sn2100-storage.html[Required documentation]
