---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-storage.html
sidebar: sidebar
keywords: nvidia SN2100 switches
summary: For NVIDIA SN2100 switch installation and maintenance, be sure to review all requirements. 
---
= Configuration requirements for NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
For NVIDIA SN2100 switch installation and maintenance, be sure to review all requirements. 

== Installation requirements

If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.

You install the NVIDIA SN2100 switch (X190006/X190106) in the NVIDIA dual/single switch cabinet with the standard brackets that are included with the switch. 

For cabling guidelines, see link:cabling-considerations-sn2100-cluster.html[Cabling and configuration considerations].

== ONTAP and Linux support

The NVIDIA SN2100 switch is a 10/25/40/100 Gb Ethernet switch running Cumulus Linux. The switch supports the following:

* ONTAP 9.10.1P3. The SN2100 switch serves Cluster and Storage applications in ONTAP 9.10.1P3 over different switch-pairs. From ONTAP 9.10.1P3, you can use NVIDIA SN2100 switches to combine storage and cluster functionality into a shared switch configuration.

* Cumulus Linux (CL) OS version 4.4.2. Cumulus Linux can be installed either when the switch is running Cumulus Linux or ONIE.
