---
permalink: switch-nvidia-sn2100/install-onie-mode-sn2100-storage.html
sidebar: sidebar
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode
summary: 'Cumulus Linux (CL) OS can be installed either when the switch is running Cumulus Linux or ONIE.'
---
= Install Cumulus Linux in ONIE mode
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to install Cumulus Linux (CL) OS when the switch is running in ONIE mode.  

NOTE: Cumulus Linux (CL) OS can be installed either when the switch is running Cumulus Linux or ONIE (see link:install-cumulus-mode-sn2100-storage.html[Install in Cumulus mode]).

.About this task
You can install the Cumulus Linux using Open Network Install Environment (ONIE) that allows for automatic discovery of a network installer image. This facilitates the system model of securing switches with an operating system choice, such as Cumulus Linux. The easiest way to install Cumulus Linux with ONIE is with local HTTP discovery.

NOTE: If your host is IPv6-enabled, make sure it is running a web server. If your host is IPv4-enabled, make sure it is running DHCP in addition to a web server.

This procedure demonstrates how to upgrade Cumulus Linux after the admin has booted in ONIE.

//NOTE: Example command output uses switch management IP address 10.233.204.71, netmask 255.255.254.0 and default gateway 10.233.204.1.

.Steps
. Download the Cumulus Linux installation file to the root directory of the web server. Rename this file `onie-installer`.
. Connect your host to the management Ethernet port of the switch using an Ethernet cable.
. Power on the switch. The switch downloads the ONIE image installer and boots. After the installation completes, the Cumulus Linux login prompt appears in the terminal window.
+
NOTE: Each time Cumulus Linux is installed, the entire file system structure is erased and rebuilt.

. Reboot the SN2100 switch:
+
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Press the *Esc* key at the GNU GRUB screen to interrupt the normal boot process, select *ONIE* and press *Enter*.
. On the next screen displayed, select *ONIE: Install OS*.
. The ONIE installer discovery process runs searching for the automatic installation.  Press *Enter* to temporarily stop the process.
. When the discovery process has stopped:
+
[subs=+quotes]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. If the DHCP service is running on your network, verify that the IP address, subnet mask, and the default gateway are correctly assigned:
+
`ifconfig eth0`
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====

. If the IP addressing scheme is manually defined, do the following:
+
[subs=+quotes]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. Repeat step 9 to verify that the static information is correctly entered.
. Install Cumulus Linux:
+
[subs=+quotes]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Once the installation has completed, log in to the switch:
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *netapp1!*
Retype new password: *netapp1!*
----
====

. Verify the Cumulus Linux version:
+
`net show version`
+
.Show example
[%collapsible]
====
[subs=+quotes]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
====

.What's next?
link:install-rcf-sn2100-storage.html[Install RCF script].

// GH issue #77 replacing 4.4.2with 4.4.3, 2023-FEB-22