---
permalink: switch-nvidia-sn2100/install-sn2100-overview.html
sidebar: sidebar
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux
summary: 'The NVIDIA SN2100 switch is a 10/25/40/100 GbE Ethernet switch running Cumulus Linux. The SN2100 switch serves Cluster and Storage applications in ONTAP 9.10.1 over different switch-pairs.'
---
= Overview of configuration process for NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
Before configuring NVIDIA SN2100 switches, review the requirements and the procedure overview.

== Requirements
Be sure to review the link:sn2100-overview.html[Overview and requirements].

IMPORTANT: When using breakout cables for 10G and 25G, make sure that auto-negotiation is off and hard set the port speed on the switch. See link:cabling-considerations-sn2100.html[Cabling and configuration considerations^] for further details.

== Procedure overview

To configure a NVIDIA SN2100 switch on systems running ONTAP, follow these steps:

* link:install-cumulus-linux-cumulus-mode.html[Install in Cumulus mode] or link:install-cumulus-linux-onie-mode.html[install in ONIE mode]. Cumulus Linux (CL) OS can be installed either when the switch is running Cumulus Linux or ONIE.
* link:install-sn2100-rcf.html[Install the RCF script]. There are two RCF scripts available for Clustering and Storage applications. 
* link:install-snmpv3.html[ Configure SNMPv3 for switch log collection]. This release includes support for SNMPv3 for switch log collection and for Switch Health Monitoring (SHM).


NOTE: The procedures use Network Command Line Utility (NCLU), which is a command line interface that ensures Cumulus Linux is fully accessible to all. The net command is the wrapper utility you use to execute actions from a terminal.

