---
permalink: switch-nvidia-sn2100-storage/required-documentation-sn2100-storage.html
sidebar: sidebar
keywords: nvidia SN2100 switches
summary: For NVIDIA SN2100 switch installation and maintenance, be sure to review all the recommended documentation. 
---
= Documentation requirements for NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
For NVIDIA SN2100 switch installation, be sure to review all the recommended documentation. 

The following table lists the documentation available for the NVIDIA SN2100 switches.

[options="header" cols="1,2"]
|===
| Title | Description
a|
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html[Setup and configure your NVIDIA SN2100 switches^]
a|
Describes how to setup and configure your NVIDIA SN2100 switches, including installing Cumulus Linux and applicable RCFs.
a|
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html[Migrate from a Cisco storage switch to a NVIDIA SN2100 storage switch^]
a|
Describes how to migrate from environments that use Cisco storage switches to environments that use NVIDIA SN2100 storage switches.
a|
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html[Migrate to a two-node switched cluster^]
a|
Describes how to migrate to a two-node switched environment using NVIDIA SN2100 switches.
a|
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html[Replace a NVIDIA SN2100 storage switch^]
a|
Describes the procedure to replace a defective NVIDIA SN2100 storage switch and download Cumulus Linux and reference configuration file.
|===

== ONTAP systems documentation

To set up an ONTAP system, you need the following documents for your version of the operating system.

[options="header" cols="1,2"]
|===
| Name| Description
a|
Controller-specific _Installation and Setup Instructions_
a|
Describes how to install NetApp hardware.
a|
link:https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9^]
a|
Provides detailed information about all aspects of the ONTAP releases.
a|
link:https://hwu.netapp.com/[Hardware Universe^]
a|
Allows you to confirm supported hardware, such as storage switches and cables, for your platform model.
|===

// GH issue #340 internal repo, 2025-SEPT-18
// AFFFASDOC-473, 2026-MAR-18