---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-storage
.html
sidebar: sidebar
keywords: nvidia SN2100 switches
summary: If you want to build ONTAP clusters with more than two nodes, you need two supported cluster network switches. You can use additional management switches, which are optional.
---
= Documentation requirements for NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
For NVIDIA SN2100 switch installation and maintenance, be sure to review all the recommended documentation. 

The following table lists the documentation available for the NVIDIA SN2100 switches.

[options="header" cols="1,2"]
|===
| Title | Description
a|
link:install_setup_sn2100_switches_overview.html[_Setup and configure your NVIDIA SN2100 switches_^]
a|
Describes how to setup and configure your NVIDIA SN2100 switches, including installing Cumulus Linux and applicable RCFs.
a|
link:migrate_cisco_sn2100_cluster_switch.html[_Migrate from a Cisco cluster switch to a NVIDIA SN2100 cluster switch_^]
a|
Describes how to migrate from environments that use Cisco cluster switches to environments that use NVIDIA SN2100 cluster switches.
a|
link:migrate_cisco_sn2100_storage_switch.html[_Migrate from a Cisco storage switch to a NVIDIA storage switch_^]
a|
Describes how to migrate from environments that use Cisco storage switches to environments that use NVIDIA SN2100 storage switches.
a|
link:migrate_2n_switched_sn2100_switches.html[_Migrate to a two-node switched cluster with NVIDIA SN2100 cluster switches_^]
a|
Describes how to migrate to a two-node switched environment using NVIDIA SN2100 cluster switches.
a|
link:replace_sn2100_switch_cluster.html[_Replace a NVIDIA SN2100 cluster switch_^]
a|
Describes the procedure to replace a defective NVIDIA SN2100 switch in a cluster and download Cumulus Linux and reference configuration file.
a|
link:replace_sn2100_switch_storage.html[_Replace a NVIDIA SN2100 storage switch_^]
a|
Describes the procedure to replace a defective NVIDIA SN2100 storage switch and download Cumulus Linux and reference configuration file.
|===
