---
permalink: switch-nvidia-sn2100-storage/required-documentation-sn2100-storage.html
sidebar: sidebar
keywords: nvidia SN2100 switches
summary: For NVIDIA SN2100 switch installation and maintenance, be sure to review all the recommended documentation. 
---
= Documentation requirements for NVIDIA SN2100 switches
:icons: font
:imagesdir: ../media/

[.lead]
For NVIDIA SN2100 switch installation and maintenance, be sure to review all the recommended documentation. 

The following table lists the documentation available for the NVIDIA SN2100 switches.

[options="header" cols="1,2"]
|===
| Title | Description
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html[_Setup and configure your NVIDIA SN2100 switches_^]
a|
Describes how to setup and configure your NVIDIA SN2100 switches, including installing Cumulus Linux and applicable RCFs.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-sn2100-cluster-switch.html[_Migrate from a Cisco cluster switch to a NVIDIA SN2100 cluster switch_^]
a|
Describes how to migrate from environments that use Cisco cluster switches to environments that use NVIDIA SN2100 cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html[_Migrate to a two-node switched cluster with NVIDIA SN2100 cluster switches_^]
a|
Describes how to migrate to a two-node switched environment using NVIDIA SN2100 cluster switches.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-cluster.html[_Replace a NVIDIA SN2100 cluster switch_^]
a|
Describes the procedure to replace a defective NVIDIA SN2100 switch in a cluster and download Cumulus Linux and reference configuration file.
a|
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-storage.html[_Replace a NVIDIA SN2100 storage switch_^]
a|
Describes the procedure to replace a defective NVIDIA SN2100 storage switch and download Cumulus Linux and reference configuration file.
|===


// GH issue #340 internal repo, 2025-SEPT-18